part of 'daily_choice_seed_data.dart';

final List<DailyChoiceOption> _eatOptions = <DailyChoiceOption>[
  _choice(
    id: 'eat_breakfast_microwave_egg',
    moduleId: 'eat',
    categoryId: 'breakfast',
    titleZh: '微波炉版鸡蛋羹',
    titleEn: 'Microwave steamed egg',
    subtitleZh: '柔软、快手，适合早上低负担开局。',
    subtitleEn: 'Soft, fast, and gentle for breakfast.',
    detailsZh: '用鸡蛋和温水做一个轻量热食，适合不想开火但想吃点暖的早晨。',
    detailsEn:
        'A warm egg dish for mornings when you want comfort without turning on a stove.',
    materialsZh: <String>['鸡蛋', '温水', '盐', '葱花可选'],
    materialsEn: <String>['Egg', 'Warm water', 'Salt', 'Optional scallion'],
    stepsZh: <String>[
      '鸡蛋打散，加约 1.5 倍温水。',
      '过筛或撇泡，盖盘留缝。',
      '微波中火分段加热，凝固后静置 1 分钟。',
    ],
    stepsEn: <String>[
      'Beat egg with about 1.5x warm water.',
      'Skim bubbles and cover loosely.',
      'Microwave in short bursts, then rest for one minute.',
    ],
    tagsZh: <String>['早饭', '微波炉', '简单'],
    tagsEn: <String>['Breakfast', 'Microwave', 'Easy'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_breakfast_oatmeal',
    moduleId: 'eat',
    categoryId: 'breakfast',
    titleZh: '微波炉版燕麦粥',
    titleEn: 'Microwave oatmeal',
    subtitleZh: '主食感稳定，能量释放慢。',
    subtitleEn: 'A steady bowl with slow energy.',
    detailsZh: '适合早上胃口一般、又不想空腹出门的时候。',
    detailsEn: 'Good when appetite is low but you still need something steady.',
    materialsZh: <String>['燕麦或米', '牛奶或水', '坚果/水果可选'],
    materialsEn: <String>[
      'Oats or rice',
      'Milk or water',
      'Optional nuts or fruit',
    ],
    stepsZh: <String>['燕麦加液体没过一指。', '微波加热 1-2 分钟后搅拌。', '按稠度补水，再加热到顺滑。'],
    stepsEn: <String>[
      'Cover oats with liquid.',
      'Microwave 1-2 minutes and stir.',
      'Add liquid if needed and heat until smooth.',
    ],
    tagsZh: <String>['早饭', '主食', '微波炉'],
    tagsEn: <String>['Breakfast', 'Starch', 'Microwave'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_breakfast_air_fryer_pancake',
    moduleId: 'eat',
    categoryId: 'breakfast',
    titleZh: '空气炸锅早餐饼',
    titleEn: 'Air-fryer breakfast patty',
    subtitleZh: '鸡蛋和蔬菜合体，方便带走。',
    subtitleEn: 'Egg and vegetables in a grab-and-go patty.',
    detailsZh: '适合想吃咸口、又希望早饭带一点蔬菜的时候。',
    detailsEn: 'A savory breakfast when you want vegetables included.',
    materialsZh: <String>['鸡蛋', '西葫芦', '胡萝卜', '少量面粉'],
    materialsEn: <String>['Egg', 'Zucchini', 'Carrot', 'A little flour'],
    stepsZh: <String>['蔬菜擦丝挤水。', '加鸡蛋、面粉和盐拌成糊。', '空气炸锅铺纸，分成小饼烤到定型。'],
    stepsEn: <String>[
      'Shred vegetables and squeeze dry.',
      'Mix with egg, flour, and salt.',
      'Shape small patties and air-fry until set.',
    ],
    tagsZh: <String>['早餐', '空气炸锅', '蔬菜'],
    tagsEn: <String>['Breakfast', 'Air fryer', 'Vegetables'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_lunch_sausage_rice',
    moduleId: 'eat',
    categoryId: 'lunch',
    titleZh: '电饭煲版广式腊肠煲饭',
    titleEn: 'Rice-cooker sausage rice',
    subtitleZh: '一锅出，适合午餐省心。',
    subtitleEn: 'One-pot rice for a low-effort lunch.',
    detailsZh: '腊肠和米饭一起熟，香味足，适合搭配一份青菜。',
    detailsEn:
        'Sausage steams with rice, giving a fragrant bowl that pairs well with greens.',
    materialsZh: <String>['腊肠', '米', '青菜可选', '生抽'],
    materialsEn: <String>[
      'Chinese sausage',
      'Rice',
      'Optional greens',
      'Soy sauce',
    ],
    stepsZh: <String>['米洗净按平时水量入锅。', '腊肠切片铺在米上。', '煮熟后焖 5 分钟，拌入少量生抽。'],
    stepsEn: <String>[
      'Wash rice and add usual water.',
      'Layer sliced sausage on top.',
      'Cook, rest five minutes, and season lightly.',
    ],
    tagsZh: <String>['午餐', '电饭煲', '主食'],
    tagsEn: <String>['Lunch', 'Rice cooker', 'Starch'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_lunch_tomato_beef_rice',
    moduleId: 'eat',
    categoryId: 'lunch',
    titleZh: '番茄牛腩焖饭',
    titleEn: 'Tomato beef rice',
    subtitleZh: '酸甜开胃，主菜主食一起解决。',
    subtitleEn: 'Bright tomato beef with rice in one pot.',
    detailsZh: '番茄提供汁水和酸味，牛肉负责满足感。时间紧可用熟牛肉或预制牛腩。',
    detailsEn:
        'Tomato gives liquid and acidity; beef adds satisfaction. Use cooked beef when time is short.',
    materialsZh: <String>['牛肉', '番茄', '米', '洋葱可选'],
    materialsEn: <String>['Beef', 'Tomato', 'Rice', 'Optional onion'],
    stepsZh: <String>['牛肉先焯或煎到表面变色。', '番茄切块和米一起入锅。', '煮熟后把番茄压散，调盐和黑胡椒。'],
    stepsEn: <String>[
      'Blanch or sear beef briefly.',
      'Add tomato chunks and rice to the cooker.',
      'After cooking, crush tomato and season.',
    ],
    tagsZh: <String>['午餐', '懒人', '电饭煲'],
    tagsEn: <String>['Lunch', 'Lazy', 'Rice cooker'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_lunch_mushroom_chicken_rice',
    moduleId: 'eat',
    categoryId: 'lunch',
    titleZh: '菌菇鸡肉焖饭',
    titleEn: 'Mushroom chicken rice',
    subtitleZh: '蛋白质和菌菇都在一碗里。',
    subtitleEn: 'Protein and mushrooms in one bowl.',
    detailsZh: '适合工作日午餐，香气稳，复热也不太出错。',
    detailsEn: 'A weekday lunch that reheats reliably.',
    materialsZh: <String>['鸡肉', '菌菇', '胡萝卜', '米'],
    materialsEn: <String>['Chicken', 'Mushrooms', 'Carrot', 'Rice'],
    stepsZh: <String>['鸡肉切块用盐和生抽抓匀。', '菌菇切片，胡萝卜切丁。', '全部与米同煮，熟后拌匀。'],
    stepsEn: <String>[
      'Season chicken with salt and soy.',
      'Slice mushrooms and dice carrot.',
      'Cook with rice and mix well.',
    ],
    tagsZh: <String>['午餐', '微波炉', '减脂餐'],
    tagsEn: <String>['Lunch', 'Microwave', 'Balanced'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_dinner_coke_wings',
    moduleId: 'eat',
    categoryId: 'dinner',
    titleZh: '可乐鸡翅',
    titleEn: 'Cola chicken wings',
    subtitleZh: '甜咸下饭，适合晚餐奖励感。',
    subtitleEn: 'Sweet-savory comfort for dinner.',
    detailsZh: '经典下饭菜，注意收汁别太久，避免过甜过咸。',
    detailsEn:
        'A classic comfort dish. Reduce sauce gently to avoid excess sweetness or saltiness.',
    materialsZh: <String>['鸡翅', '可乐', '生抽', '姜片'],
    materialsEn: <String>['Chicken wings', 'Cola', 'Soy sauce', 'Ginger'],
    stepsZh: <String>['鸡翅划口焯水或煎到微黄。', '加可乐、生抽和姜片小火煮。', '汤汁变稠后翻匀出锅。'],
    stepsEn: <String>[
      'Score wings and blanch or sear.',
      'Simmer with cola, soy, and ginger.',
      'Reduce until glossy and coat well.',
    ],
    tagsZh: <String>['晚餐', '下饭', '一口大锅'],
    tagsEn: <String>['Dinner', 'Comfort', 'Pot'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_dinner_borscht',
    moduleId: 'eat',
    categoryId: 'dinner',
    titleZh: '电饭煲版罗宋汤',
    titleEn: 'Rice-cooker borscht',
    subtitleZh: '蔬菜多，适合想吃暖汤的晚上。',
    subtitleEn: 'Vegetable-rich warm soup for dinner.',
    detailsZh: '番茄、牛肉和根茎蔬菜一起炖，适合搭配面包或米饭。',
    detailsEn: 'Tomato, beef, and root vegetables simmer into a filling soup.',
    materialsZh: <String>['牛肉', '番茄', '洋葱', '土豆', '胡萝卜', '包菜'],
    materialsEn: <String>[
      'Beef',
      'Tomato',
      'Onion',
      'Potato',
      'Carrot',
      'Cabbage',
    ],
    stepsZh: <String>['牛肉焯水，蔬菜切块。', '番茄先压出汁，再加入其他材料。', '电饭煲煮到土豆软，最后调盐。'],
    stepsEn: <String>[
      'Blanch beef and cut vegetables.',
      'Crush tomato first, then add the rest.',
      'Cook until potato softens and season.',
    ],
    tagsZh: <String>['晚餐', '汤', '电饭煲'],
    tagsEn: <String>['Dinner', 'Soup', 'Rice cooker'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_dinner_tomato_egg_soup',
    moduleId: 'eat',
    categoryId: 'dinner',
    titleZh: '番茄鸡蛋汤',
    titleEn: 'Tomato egg soup',
    subtitleZh: '轻晚餐万能补位。',
    subtitleEn: 'A light dinner fallback.',
    detailsZh: '当主菜已经有油脂时，用它补一个热汤和蛋白质。',
    detailsEn: 'A warm soup that adds protein without making dinner too heavy.',
    materialsZh: <String>['番茄', '鸡蛋', '盐', '葱花'],
    materialsEn: <String>['Tomato', 'Egg', 'Salt', 'Scallion'],
    stepsZh: <String>['番茄炒软出汁。', '加水煮开后转小火。', '蛋液绕圈倒入，凝固后调味。'],
    stepsEn: <String>[
      'Cook tomato until juicy.',
      'Add water and simmer.',
      'Pour in beaten egg and season.',
    ],
    tagsZh: <String>['晚餐', '汤', '快手'],
    tagsEn: <String>['Dinner', 'Soup', 'Fast'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_tea_air_fryer_cake',
    moduleId: 'eat',
    categoryId: 'tea',
    titleZh: '空气炸锅酸奶蛋糕',
    titleEn: 'Air-fryer yogurt cake',
    subtitleZh: '下午茶想吃甜口时的轻量选择。',
    subtitleEn: 'A lighter sweet snack for afternoon tea.',
    detailsZh: '口感介于蛋糕和布丁之间，适合少量做。',
    detailsEn:
        'Somewhere between cake and pudding, best made in a small portion.',
    materialsZh: <String>['鸡蛋', '酸奶', '少量面粉', '糖可选'],
    materialsEn: <String>['Egg', 'Yogurt', 'A little flour', 'Optional sugar'],
    stepsZh: <String>['鸡蛋、酸奶和面粉拌匀。', '倒入小模具，震掉大气泡。', '空气炸锅低温烤到中心凝固。'],
    stepsEn: <String>[
      'Mix egg, yogurt, and flour.',
      'Pour into a small mold.',
      'Air-fry gently until the center sets.',
    ],
    tagsZh: <String>['下午茶', '甜口', '空气炸锅'],
    tagsEn: <String>['Tea', 'Sweet', 'Air fryer'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_tea_potato_chips',
    moduleId: 'eat',
    categoryId: 'tea',
    titleZh: '气泡小土豆',
    titleEn: 'Bubble potatoes',
    subtitleZh: '咸口小食，适合配茶或咖啡。',
    subtitleEn: 'A savory snack for tea or coffee.',
    detailsZh: '土豆类小食容易过量，建议做小份并搭配水。',
    detailsEn: 'Potato snacks are easy to overeat, so keep the portion small.',
    materialsZh: <String>['土豆', '盐', '黑胡椒', '少量油'],
    materialsEn: <String>['Potato', 'Salt', 'Black pepper', 'A little oil'],
    stepsZh: <String>['土豆切片或小块，擦干水分。', '拌少量油和盐。', '烤到边缘起泡酥脆。'],
    stepsEn: <String>[
      'Cut potato and dry well.',
      'Toss with a little oil and salt.',
      'Bake or air-fry until crisp.',
    ],
    tagsZh: <String>['下午茶', '零食', '烤箱'],
    tagsEn: <String>['Tea', 'Snack', 'Oven'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_night_noodle_egg',
    moduleId: 'eat',
    categoryId: 'night',
    titleZh: '微波炉版荷包蛋方便面',
    titleEn: 'Microwave egg noodles',
    subtitleZh: '宵夜救急，但别做太咸。',
    subtitleEn: 'Emergency late snack, kept less salty.',
    detailsZh: '适合真的饿了时救急。调料包少放一半，给胃留点余地。',
    detailsEn:
        'For real hunger at night. Use half the seasoning packet to keep it lighter.',
    materialsZh: <String>['方便面', '鸡蛋', '香肠可选', '青菜可选'],
    materialsEn: <String>[
      'Instant noodles',
      'Egg',
      'Optional sausage',
      'Optional greens',
    ],
    stepsZh: <String>['面饼加水没过，先微波到散开。', '打入鸡蛋并戳破蛋黄。', '继续分段加热，少放调料。'],
    stepsEn: <String>[
      'Cover noodles with water and microwave until loose.',
      'Add egg and pierce yolk.',
      'Microwave in bursts and season lightly.',
    ],
    tagsZh: <String>['宵夜', '速食', '微波炉'],
    tagsEn: <String>['Late snack', 'Instant', 'Microwave'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
  _choice(
    id: 'eat_night_potato_soup',
    moduleId: 'eat',
    categoryId: 'night',
    titleZh: '微波炉版土豆浓汤',
    titleEn: 'Microwave potato soup',
    subtitleZh: '比炸物温和的夜间选择。',
    subtitleEn: 'Gentler than fried snacks at night.',
    detailsZh: '土豆和胡萝卜做成温热浓汤，饱腹但不刺激。',
    detailsEn:
        'Potato and carrot become a warm soup that is filling but gentle.',
    materialsZh: <String>['土豆', '胡萝卜', '水或牛奶', '盐'],
    materialsEn: <String>['Potato', 'Carrot', 'Water or milk', 'Salt'],
    stepsZh: <String>['土豆胡萝卜切小块微波到软。', '压碎后加水或牛奶搅开。', '再加热到温热，少量调味。'],
    stepsEn: <String>[
      'Microwave diced potato and carrot until soft.',
      'Mash and loosen with liquid.',
      'Heat again and season lightly.',
    ],
    tagsZh: <String>['宵夜', '热汤', '微波炉'],
    tagsEn: <String>['Late snack', 'Soup', 'Microwave'],
    sourceLabel: cookRecipeSourceLabel,
    sourceUrl: cookRecipeSourceUrl,
  ),
];
