part of 'daily_choice_seed_data.dart';

final List<DailyChoiceOption> _placeOptions =
    List<DailyChoiceOption>.unmodifiable(_buildPlaceOptions());

List<DailyChoiceOption> _buildPlaceOptions() {
  final options = <DailyChoiceOption>[];
  for (final scene in _placeSceneSeeds) {
    for (final distance in _placeDistanceProfiles) {
      for (final archetype in scene.archetypes) {
        options.add(_buildPlaceOption(scene, distance, archetype));
      }
    }
  }
  assert(
    _placeSceneSeeds.every((scene) => scene.archetypes.length == 8),
    'Each place scene should expose 8 archetypes.',
  );
  assert(
    options.length >= 300 && options.length <= 500,
    'Place options should stay between 300 and 500 items.',
  );
  return options;
}

DailyChoiceOption _buildPlaceOption(
  _PlaceSceneSeed scene,
  _PlaceDistanceProfile distance,
  _PlaceArchetype archetype,
) {
  final queryZh = archetype.searchQueryZh;
  final queryEn = archetype.searchQueryEn;
  final sceneLabelZh = _placeSceneTitleZh(scene.id);
  final sceneLabelEn = _placeSceneTitleEn(scene.id);
  final titleZh = '${_placeTitlePrefixZh(distance.id)}${archetype.titleZh}';
  final titleEn = '${_placeTitlePrefixEn(distance.id)}${archetype.titleEn}';
  return _choice(
    id: 'go_${distance.id}_${scene.id}_${archetype.slug}',
    moduleId: 'go',
    categoryId: distance.id,
    contextId: scene.id,
    contextIds: <String>[scene.id, ...archetype.secondarySceneIds],
    titleZh: titleZh,
    titleEn: titleEn,
    subtitleZh: '${archetype.subtitleZh}，${distance.rhythmZh}。',
    subtitleEn: '${archetype.subtitleEn}, ${distance.rhythmEn}.',
    detailsZh:
        '当你想${scene.intentZh}时，$titleZh通常是稳妥起点。${archetype.subtitleZh}。这类地点更适合${distance.durationZh}的节奏，出发前优先确认${scene.checkpointZh}。当前版本先提供结构化筛选与地图搜索词，后续仍可继续接入粗略定位、开放地理数据和系统地图拉起。',
    detailsEn:
        'When you want to ${scene.intentEn}, $titleEn is a solid starting point. ${archetype.subtitleEn}. It fits a ${distance.durationEn} rhythm, and you should confirm ${scene.checkpointEn} before leaving. This version focuses on structured filtering and map queries, while leaving room for coarse location, open geo data, and system-map launch later.',
    materialsZh: <String>[
      '建议时长：${distance.durationZh}',
      '预算预期：${scene.budgetZh(distance.id)}',
      '同行建议：${scene.companionZh}',
      '地图搜索词：$queryZh',
    ],
    materialsEn: <String>[
      'Suggested duration: ${distance.durationEn}',
      'Budget: ${scene.budgetEn(distance.id)}',
      'Good with: ${scene.companionEn}',
      'Map query: $queryEn',
    ],
    stepsZh: <String>[
      '先确认今天愿意给这次外出 ${distance.durationZh}，不要把临时起意拖成负担。',
      '用“$queryZh”在地图里先看一组候选，再比营业时间、通勤时间和现场拥挤度。',
      '出发前确认${distance.checklistZh}，并准备一个同区域替代点。',
    ],
    stepsEn: <String>[
      'Decide whether you want to spend ${distance.durationEn} on this outing and keep the scope honest.',
      'Search “$queryEn” on a map first, then compare opening hours, travel time, and crowd level.',
      'Before leaving, confirm ${distance.checklistEn} and keep a backup in the same area.',
    ],
    notesZh: <String>[
      '适合状态：${scene.intentZh}。',
      archetype.indoor
          ? '天气提醒：下雨也能执行，但先看营业时间、排队和临时闭馆信息。'
          : '天气提醒：户外点优先看气温、降水和风，天气突变时准备室内替代点。',
      _placeDistanceNoteZh(distance.id),
      '扩展边界：详情页先提供地图搜索词复制；后续可在同一数据结构上接入粗略定位、开放地图 POI 和系统地图。',
    ],
    notesEn: <String>[
      'Best for: ${scene.intentEn}.',
      archetype.indoor
          ? 'Weather note: indoor places still need opening-hour and queue checks, especially in rain.'
          : 'Weather note: outdoor spots should be checked against temperature, rain, and wind, with an indoor fallback ready.',
      _placeDistanceNoteEn(distance.id),
      'Expansion path: this release starts with map-query copying, while leaving room for coarse location, open-map POIs, and system-map launch later.',
    ],
    tagsZh: <String>[
      placeCategories.firstWhere((item) => item.id == distance.id).titleZh,
      sceneLabelZh,
      ...archetype.tagsZh,
      archetype.indoor ? '室内' : '户外',
    ],
    tagsEn: <String>[
      placeCategories.firstWhere((item) => item.id == distance.id).titleEn,
      sceneLabelEn,
      ...archetype.tagsEn,
      archetype.indoor ? 'Indoor' : 'Outdoor',
    ],
    references: _buildPlaceReferences(queryZh, queryEn),
  );
}

List<DailyChoiceReferenceLink> _buildPlaceReferences(
  String queryZh,
  String queryEn,
) {
  return <DailyChoiceReferenceLink>[
    DailyChoiceReferenceLink(
      labelZh: 'OpenStreetMap 搜索建议',
      labelEn: 'OpenStreetMap search',
      url:
          'https://www.openstreetmap.org/search?query=${Uri.encodeComponent(queryZh)}',
    ),
    DailyChoiceReferenceLink(
      labelZh: '英文检索建议',
      labelEn: 'English search query',
      url:
          'https://www.openstreetmap.org/search?query=${Uri.encodeComponent(queryEn)}',
    ),
  ];
}

String _placeTitlePrefixZh(String distanceId) {
  return switch (distanceId) {
    'outside' => '附近',
    'nearby' => '同城',
    'travel' => '远一点的',
    _ => '',
  };
}

String _placeTitlePrefixEn(String distanceId) {
  return switch (distanceId) {
    'outside' => 'Nearby ',
    'nearby' => 'In-town ',
    'travel' => 'Further-out ',
    _ => '',
  };
}

String _placeDistanceNoteZh(String distanceId) {
  return switch (distanceId) {
    'outside' => '出门层级优先选步行或短交通能往返的点，主要目标是快速换个环境。',
    'nearby' => '周边层级更适合同城半日安排，最好把餐饮、休息位和返程一起考虑。',
    'travel' => '远行层级请提前看预约、票务、返程和补给，把“回得来”一起算进去。',
    _ => '',
  };
}

String _placeDistanceNoteEn(String distanceId) {
  return switch (distanceId) {
    'outside' =>
      'Step-out options work best when they are walkable or only need a very short ride and can close cleanly.',
    'nearby' =>
      'Nearby options fit a local half-day rhythm, so it helps to think about food, rest, and return timing together.',
    'travel' =>
      'Travel options should be checked for booking, tickets, return timing, and supplies before you commit.',
    _ => '',
  };
}

String _placeSceneTitleZh(String id) {
  return placeSceneCategories
      .firstWhere(
        (item) => item.id == id,
        orElse: () => placeSceneCategories.first,
      )
      .titleZh;
}

String _placeSceneTitleEn(String id) {
  return placeSceneCategories
      .firstWhere(
        (item) => item.id == id,
        orElse: () => placeSceneCategories.first,
      )
      .titleEn;
}

const List<_PlaceDistanceProfile> _placeDistanceProfiles =
    <_PlaceDistanceProfile>[
      _PlaceDistanceProfile(
        id: 'outside',
        rhythmZh: '适合说走就走的小切换',
        rhythmEn: 'good for a low-friction switch',
        durationZh: '30 分钟到 1 小时',
        durationEn: '30 to 60 minutes',
        checklistZh: '天气、电量和步行或短途通勤',
        checklistEn: 'weather, battery, and a short walking or transit route',
      ),
      _PlaceDistanceProfile(
        id: 'nearby',
        rhythmZh: '适合同城半日安排',
        rhythmEn: 'good for a local half-day outing',
        durationZh: '半天左右',
        durationEn: 'around half a day',
        checklistZh: '营业时间、通勤方式和返程窗口',
        checklistEn: 'opening hours, transit choice, and return timing',
      ),
      _PlaceDistanceProfile(
        id: 'travel',
        rhythmZh: '适合专门留出一段行程',
        rhythmEn: 'good for a more intentional trip',
        durationZh: '半天到一天',
        durationEn: 'half a day to a full day',
        checklistZh: '预约、票务、返程和补给',
        checklistEn: 'booking, tickets, return timing, and supplies',
      ),
    ];

final List<_PlaceSceneSeed> _placeSceneSeeds = <_PlaceSceneSeed>[
  _scene(
    id: 'food',
    intentZh: '补一顿饭、换个口味，或者找个能坐下来的点',
    intentEn: 'land a meal, switch flavors, or find somewhere to sit',
    companionZh: '一个人也能去，两三个人更容易顺手延长行程',
    companionEn: 'solo-friendly, with small groups making it easier to extend',
    checkpointZh: '营业时间、排队情况和是否容易收尾',
    checkpointEn:
        'opening hours, queue length, and how easy it is to close out',
    outsideBudgetZh: '人均 20-60 元',
    outsideBudgetEn: 'roughly 20-60 CNY per person',
    nearbyBudgetZh: '人均 40-120 元',
    nearbyBudgetEn: 'roughly 40-120 CNY per person',
    travelBudgetZh: '餐饮 + 路费，预留 100-300 元起',
    travelBudgetEn: 'meal plus transit, often 100-300 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'breakfast_shop',
        titleZh: '早餐铺',
        titleEn: 'breakfast shop',
        subtitleZh: '适合先把一餐吃稳，几乎不用做准备',
        subtitleEn: 'a reliable way to settle one meal with almost no setup',
        searchQueryZh: '早餐铺',
        searchQueryEn: 'breakfast shop',
        tagsZh: <String>['热食', '快决策'],
        tagsEn: <String>['Hot food', 'Fast choice'],
        secondarySceneIds: <String>['study'],
        indoor: true,
      ),
      _archetype(
        slug: 'noodle_house',
        titleZh: '面馆',
        titleEn: 'noodle house',
        subtitleZh: '热食稳定，独自去也自然',
        subtitleEn: 'warm, steady, and very natural for solo outings',
        searchQueryZh: '面馆',
        searchQueryEn: 'noodle house',
        tagsZh: <String>['正餐', '独自可去'],
        tagsEn: <String>['Main meal', 'Solo-friendly'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'local_restaurant',
        titleZh: '本地馆子',
        titleEn: 'local restaurant',
        subtitleZh: '想吃得像当地人一点时很好用',
        subtitleEn: 'great when you want a more local everyday meal',
        searchQueryZh: '本地餐馆',
        searchQueryEn: 'local restaurant',
        tagsZh: <String>['本地口味', '正餐'],
        tagsEn: <String>['Local flavor', 'Main meal'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'cafe_dessert',
        titleZh: '咖啡甜品店',
        titleEn: 'cafe and dessert shop',
        subtitleZh: '适合坐一会儿、聊天或缓冲节奏',
        subtitleEn: 'good for sitting down, talking, or slowing the pace',
        searchQueryZh: '咖啡甜品店',
        searchQueryEn: 'cafe and dessert shop',
        tagsZh: <String>['可久坐', '轻甜'],
        tagsEn: <String>['Sit-down', 'Dessert'],
        secondarySceneIds: <String>['study', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'food_hall',
        titleZh: '美食城',
        titleEn: 'food hall',
        subtitleZh: '多人同行时更容易各吃各的',
        subtitleEn: 'works well when a group wants different things',
        searchQueryZh: '美食城',
        searchQueryEn: 'food hall',
        tagsZh: <String>['多人友好', '选择多'],
        tagsEn: <String>['Group-friendly', 'Many choices'],
        secondarySceneIds: <String>['shopping', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'snack_street',
        titleZh: '小吃街',
        titleEn: 'snack street',
        subtitleZh: '适合边走边吃，顺手逛一圈',
        subtitleEn: 'good for walking, eating, and browsing at the same time',
        searchQueryZh: '小吃街',
        searchQueryEn: 'snack street',
        tagsZh: <String>['边走边吃', '烟火气'],
        tagsEn: <String>['Walking food', 'Street vibe'],
        secondarySceneIds: <String>['photo', 'social'],
        indoor: false,
      ),
      _archetype(
        slug: 'late_night_bbq',
        titleZh: '夜宵烧烤街',
        titleEn: 'late-night barbecue strip',
        subtitleZh: '适合晚上还想续摊或补一顿',
        subtitleEn: 'good when the evening still needs one more meal stop',
        searchQueryZh: '夜宵烧烤街',
        searchQueryEn: 'late-night barbecue street',
        tagsZh: <String>['夜宵', '续摊'],
        tagsEn: <String>['Late-night food', 'After-hours'],
        secondarySceneIds: <String>['nightlife', 'social'],
        indoor: false,
      ),
      _archetype(
        slug: 'view_restaurant',
        titleZh: '景观餐厅',
        titleEn: 'scenic restaurant',
        subtitleZh: '把吃饭和看风景合在一起',
        subtitleEn: 'combines the meal with a view in one stop',
        searchQueryZh: '景观餐厅',
        searchQueryEn: 'scenic restaurant',
        tagsZh: <String>['景观', '约会'],
        tagsEn: <String>['View', 'Date-friendly'],
        secondarySceneIds: <String>['photo', 'social'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'entertainment',
    intentZh: '找一点新鲜感、玩一会儿，或者给社交找个载体',
    intentEn:
        'get some novelty, play for a while, or give social time a shared activity',
    companionZh: '一个人优先低沟通成本，多人更适合互动型场地',
    companionEn:
        'solo works best with low-friction fun, while groups suit interactive venues',
    checkpointZh: '营业时段、预约规则和是否容易临时改计划',
    checkpointEn: 'opening time, booking rules, and how easy it is to pivot',
    outsideBudgetZh: '人均 30-80 元',
    outsideBudgetEn: 'roughly 30-80 CNY per person',
    nearbyBudgetZh: '人均 50-150 元',
    nearbyBudgetEn: 'roughly 50-150 CNY per person',
    travelBudgetZh: '门票 + 路费，预留 100-300 元起',
    travelBudgetEn: 'tickets plus transit, often 100-300 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'cinema',
        titleZh: '影院',
        titleEn: 'cinema',
        subtitleZh: '低沟通成本，最适合快速进入另一个叙事',
        subtitleEn: 'low-friction and perfect for stepping into another story',
        searchQueryZh: '影院',
        searchQueryEn: 'cinema',
        tagsZh: <String>['低沟通', '室内'],
        tagsEn: <String>['Low-communication', 'Indoor'],
        secondarySceneIds: <String>['social', 'relax'],
        indoor: true,
      ),
      _archetype(
        slug: 'arcade',
        titleZh: '电玩厅',
        titleEn: 'arcade',
        subtitleZh: '规则直给，上手快，能迅速把气氛提起来',
        subtitleEn: 'simple to enter and fast at lifting the group energy',
        searchQueryZh: '电玩厅',
        searchQueryEn: 'arcade',
        tagsZh: <String>['互动', '上手快'],
        tagsEn: <String>['Interactive', 'Easy start'],
        secondarySceneIds: <String>['social', 'nightlife'],
        indoor: true,
      ),
      _archetype(
        slug: 'board_game_cafe',
        titleZh: '桌游店',
        titleEn: 'board game cafe',
        subtitleZh: '有事可做，不容易尴尬',
        subtitleEn:
            'gives the group something to do, which lowers social awkwardness',
        searchQueryZh: '桌游店',
        searchQueryEn: 'board game cafe',
        tagsZh: <String>['桌游', '慢社交'],
        tagsEn: <String>['Board games', 'Slow social'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'escape_room',
        titleZh: '密室',
        titleEn: 'escape room',
        subtitleZh: '适合想要明显互动和团队感的时候',
        subtitleEn: 'great when you want obvious teamwork and shared momentum',
        searchQueryZh: '密室',
        searchQueryEn: 'escape room',
        tagsZh: <String>['团队', '沉浸'],
        tagsEn: <String>['Team', 'Immersive'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'ktv',
        titleZh: 'KTV',
        titleEn: 'KTV',
        subtitleZh: '适合想把聚会做得热一点的时候',
        subtitleEn:
            'works well when the group wants a louder, warmer gathering',
        searchQueryZh: 'KTV',
        searchQueryEn: 'KTV',
        tagsZh: <String>['合唱', '聚会'],
        tagsEn: <String>['Sing-along', 'Group outing'],
        secondarySceneIds: <String>['social', 'nightlife'],
        indoor: true,
      ),
      _archetype(
        slug: 'livehouse',
        titleZh: 'Livehouse',
        titleEn: 'livehouse',
        subtitleZh: '现场感强，适合用一场演出来切换状态',
        subtitleEn: 'strongly live and good for shifting the whole mood',
        searchQueryZh: 'Livehouse',
        searchQueryEn: 'livehouse',
        tagsZh: <String>['现场', '氛围'],
        tagsEn: <String>['Live', 'Atmosphere'],
        secondarySceneIds: <String>['nightlife', 'photo'],
        indoor: true,
      ),
      _archetype(
        slug: 'esports_hall',
        titleZh: '电竞馆 / 网吧',
        titleEn: 'esports hall / internet cafe',
        subtitleZh: '适合打两局、开黑，或者把注意力沉进一个游戏里',
        subtitleEn: 'good for a few matches or sinking attention into one game',
        searchQueryZh: '电竞馆 网吧',
        searchQueryEn: 'esports hall internet cafe',
        tagsZh: <String>['电竞', '网吧'],
        tagsEn: <String>['Esports', 'Internet cafe'],
        secondarySceneIds: <String>['nightlife', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'comedy_club',
        titleZh: '脱口秀小剧场',
        titleEn: 'comedy club',
        subtitleZh: '适合晚上想看点轻演出，但又不想把节奏拉太重',
        subtitleEn:
            'good for a light performance without turning the whole night heavy',
        searchQueryZh: '脱口秀 小剧场',
        searchQueryEn: 'comedy club',
        tagsZh: <String>['轻演出', '夜间'],
        tagsEn: <String>['Light performance', 'Evening'],
        secondarySceneIds: <String>['social', 'nightlife'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'sports',
    intentZh: '让身体动起来、出点汗，或者把注意力从脑子拉回身体',
    intentEn:
        'wake up the body, sweat a bit, or bring attention back into physical effort',
    companionZh: '一个人适合低门槛训练，两三个人更适合球类和互动场地',
    companionEn:
        'solo works for low-friction training, while pairs or groups suit shared sports',
    checkpointZh: '场地预约、更衣淋浴和开放时段',
    checkpointEn: 'booking, changing facilities, and opening hours',
    outsideBudgetZh: '人均 0-50 元',
    outsideBudgetEn: 'roughly 0-50 CNY per person',
    nearbyBudgetZh: '人均 30-120 元',
    nearbyBudgetEn: 'roughly 30-120 CNY per person',
    travelBudgetZh: '场地/门票 + 路费，预留 80-260 元起',
    travelBudgetEn: 'venue or ticket plus transit, often 80-260 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'sports_center',
        titleZh: '体育中心',
        titleEn: 'sports center',
        subtitleZh: '综合场地多，适合先去再决定具体玩什么',
        subtitleEn: 'gives you multiple venue types so you can decide on site',
        searchQueryZh: '体育中心',
        searchQueryEn: 'sports center',
        tagsZh: <String>['综合场馆', '可预约'],
        tagsEn: <String>['Multi-sport', 'Bookable'],
        secondarySceneIds: <String>['family'],
        indoor: true,
      ),
      _archetype(
        slug: 'gym',
        titleZh: '健身房',
        titleEn: 'gym',
        subtitleZh: '适合明确想练一次，不想再做额外选择',
        subtitleEn:
            'good when you want one clear training session without extra decisions',
        searchQueryZh: '健身房',
        searchQueryEn: 'gym',
        tagsZh: <String>['力量/有氧', '个人也可'],
        tagsEn: <String>['Strength/cardio', 'Solo-friendly'],
        secondarySceneIds: <String>['relax'],
        indoor: true,
      ),
      _archetype(
        slug: 'swimming_pool',
        titleZh: '游泳馆',
        titleEn: 'swimming pool',
        subtitleZh: '全身运动，夏天尤其容易成立',
        subtitleEn:
            'full-body movement and especially easy to justify in hot weather',
        searchQueryZh: '游泳馆',
        searchQueryEn: 'swimming pool',
        tagsZh: <String>['全身运动', '降温'],
        tagsEn: <String>['Full body', 'Cooling'],
        secondarySceneIds: <String>['family', 'relax'],
        indoor: true,
      ),
      _archetype(
        slug: 'badminton_hall',
        titleZh: '羽毛球馆',
        titleEn: 'badminton hall',
        subtitleZh: '双打友好，容易约到人一起消耗体力',
        subtitleEn:
            'friendly for doubles and easy to turn into a shared session',
        searchQueryZh: '羽毛球馆',
        searchQueryEn: 'badminton hall',
        tagsZh: <String>['双打友好', '高频'],
        tagsEn: <String>['Doubles', 'Fast-paced'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'basketball_court',
        titleZh: '篮球场',
        titleEn: 'basketball court',
        subtitleZh: '适合想打对抗或想在开阔空间里活动',
        subtitleEn: 'good for competition or for moving in a more open space',
        searchQueryZh: '篮球场',
        searchQueryEn: 'basketball court',
        tagsZh: <String>['对抗', '开阔'],
        tagsEn: <String>['Competitive', 'Open space'],
        secondarySceneIds: <String>['social', 'nature'],
        indoor: false,
      ),
      _archetype(
        slug: 'climbing_gym',
        titleZh: '攀岩馆',
        titleEn: 'climbing gym',
        subtitleZh: '体验感强，适合想让身体和注意力同时进入状态',
        subtitleEn: 'strongly experiential and great for full-body focus',
        searchQueryZh: '攀岩馆',
        searchQueryEn: 'climbing gym',
        tagsZh: <String>['体验感', '技巧'],
        tagsEn: <String>['Experiential', 'Technical'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'skating_arena',
        titleZh: '滑冰 / 轮滑场',
        titleEn: 'skating arena',
        subtitleZh: '有一点娱乐性，也能把运动做得更有玩心',
        subtitleEn:
            'adds a playful layer to the movement instead of pure exercise',
        searchQueryZh: '滑冰场 轮滑场',
        searchQueryEn: 'skating arena roller rink',
        tagsZh: <String>['新鲜感', '节奏'],
        tagsEn: <String>['Novelty', 'Rhythm'],
        secondarySceneIds: <String>['entertainment', 'family'],
        indoor: true,
      ),
      _archetype(
        slug: 'cycling_route',
        titleZh: '骑行绿道',
        titleEn: 'cycling greenway',
        subtitleZh: '适合需要线性路线和节奏感的户外运动',
        subtitleEn:
            'good when you want a linear outdoor route with clear rhythm',
        searchQueryZh: '骑行绿道',
        searchQueryEn: 'cycling greenway',
        tagsZh: <String>['户外', '线性路线'],
        tagsEn: <String>['Outdoor', 'Linear route'],
        secondarySceneIds: <String>['nature', 'photo'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'culture',
    intentZh: '看展、看演出，或者让注意力换一种输入',
    intentEn:
        'see an exhibition, watch a performance, or switch your input mode',
    companionZh: '独自看展最自由，结伴更适合剧场和演出',
    companionEn:
        'solo is ideal for exhibitions, while groups suit theater and performance',
    checkpointZh: '展期、开闭馆时间和是否需要预约',
    checkpointEn:
        'exhibition dates, opening hours, and whether booking is required',
    outsideBudgetZh: '人均 0-80 元',
    outsideBudgetEn: 'roughly 0-80 CNY per person',
    nearbyBudgetZh: '人均 30-180 元',
    nearbyBudgetEn: 'roughly 30-180 CNY per person',
    travelBudgetZh: '门票 + 路费，预留 80-300 元起',
    travelBudgetEn: 'ticket plus transit, often 80-300 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'museum',
        titleZh: '综合博物馆',
        titleEn: 'museum',
        subtitleZh: '信息量稳定，是最稳妥的文化输入点',
        subtitleEn: 'consistently rich and one of the safest culture inputs',
        searchQueryZh: '综合博物馆',
        searchQueryEn: 'museum',
        tagsZh: <String>['常设展', '稳妥'],
        tagsEn: <String>['Permanent collection', 'Reliable'],
        secondarySceneIds: <String>['history'],
        indoor: true,
      ),
      _archetype(
        slug: 'art_gallery',
        titleZh: '美术馆',
        titleEn: 'art gallery',
        subtitleZh: '适合慢看，能把节奏拉得更轻一点',
        subtitleEn: 'good for slow looking and easing the pace down',
        searchQueryZh: '美术馆',
        searchQueryEn: 'art gallery',
        tagsZh: <String>['审美输入', '适合慢看'],
        tagsEn: <String>['Aesthetic input', 'Slow pace'],
        secondarySceneIds: <String>['photo'],
        indoor: true,
      ),
      _archetype(
        slug: 'science_center',
        titleZh: '科技馆',
        titleEn: 'science center',
        subtitleZh: '互动展多，适合想让大脑换一种兴奋方式',
        subtitleEn: 'interactive and good for a more playful kind of attention',
        searchQueryZh: '科技馆',
        searchQueryEn: 'science center',
        tagsZh: <String>['互动展', '科普'],
        tagsEn: <String>['Interactive', 'Science'],
        secondarySceneIds: <String>['family'],
        indoor: true,
      ),
      _archetype(
        slug: 'theater',
        titleZh: '剧院',
        titleEn: 'theater',
        subtitleZh: '适合把时间盒交给一场完整演出',
        subtitleEn:
            'good when you want to hand the time box to a full performance',
        searchQueryZh: '剧院',
        searchQueryEn: 'theater',
        tagsZh: <String>['现场表演', '时间盒明确'],
        tagsEn: <String>['Live performance', 'Clear time box'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'independent_exhibit',
        titleZh: '独立展馆',
        titleEn: 'independent gallery',
        subtitleZh: '小而新鲜，适合想看一些不那么常规的内容',
        subtitleEn: 'small and fresh, good for less conventional inputs',
        searchQueryZh: '独立展馆',
        searchQueryEn: 'independent gallery',
        tagsZh: <String>['小型策展', '新鲜'],
        tagsEn: <String>['Curated', 'Fresh'],
        secondarySceneIds: <String>['photo', 'specialty'],
        indoor: true,
      ),
      _archetype(
        slug: 'intangible_heritage_hall',
        titleZh: '非遗馆',
        titleEn: 'intangible heritage hall',
        subtitleZh: '适合看地方手艺和文化技法如何被保存',
        subtitleEn:
            'good for seeing how local craft and traditions are preserved',
        searchQueryZh: '非遗馆',
        searchQueryEn: 'intangible heritage hall',
        tagsZh: <String>['地方文化', '手艺'],
        tagsEn: <String>['Local culture', 'Craft'],
        secondarySceneIds: <String>['history', 'specialty'],
        indoor: true,
      ),
      _archetype(
        slug: 'concert_hall',
        titleZh: '音乐厅',
        titleEn: 'concert hall',
        subtitleZh: '适合想把听觉和氛围当成主体验的时候',
        subtitleEn: 'works when listening and atmosphere are the main event',
        searchQueryZh: '音乐厅',
        searchQueryEn: 'concert hall',
        tagsZh: <String>['音乐会', '氛围'],
        tagsEn: <String>['Concert', 'Atmosphere'],
        secondarySceneIds: <String>['nightlife', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'planetarium',
        titleZh: '天文馆',
        titleEn: 'planetarium',
        subtitleZh: '沉浸黑盒感强，适合安静但不无聊的输入',
        subtitleEn: 'immersive and dark in a calming way without being boring',
        searchQueryZh: '天文馆',
        searchQueryEn: 'planetarium',
        tagsZh: <String>['沉浸黑盒', '低刺激'],
        tagsEn: <String>['Immersive', 'Low stimulation'],
        secondarySceneIds: <String>['family', 'relax'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'history',
    intentZh: '看看老城区、旧建筑和时间留下来的痕迹',
    intentEn: 'walk through old districts, relics, and visible traces of time',
    companionZh: '适合慢走慢看，和愿意边逛边聊的人一起更好',
    companionEn:
        'best with people who enjoy slow walking and talking along the way',
    checkpointZh: '开放区域、讲解时段和步行强度',
    checkpointEn: 'accessible zones, guided-tour timing, and walking intensity',
    outsideBudgetZh: '人均 0-40 元',
    outsideBudgetEn: 'roughly 0-40 CNY per person',
    nearbyBudgetZh: '人均 20-100 元',
    nearbyBudgetEn: 'roughly 20-100 CNY per person',
    travelBudgetZh: '门票 + 路费，预留 80-260 元起',
    travelBudgetEn: 'ticket plus transit, often 80-260 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'old_street',
        titleZh: '老街区',
        titleEn: 'old street',
        subtitleZh: '适合边走边看，慢慢把城市的旧层理翻出来',
        subtitleEn:
            'good for walking and slowly uncovering the city’s older layers',
        searchQueryZh: '老街区',
        searchQueryEn: 'old street',
        tagsZh: <String>['老城肌理', '适合散步'],
        tagsEn: <String>['Old urban texture', 'Walkable'],
        secondarySceneIds: <String>['photo', 'food'],
        indoor: false,
      ),
      _archetype(
        slug: 'former_residence',
        titleZh: '故居',
        titleEn: 'former residence',
        subtitleZh: '适合从一个人物切入一段更具体的时代线索',
        subtitleEn: 'lets one person become the entry point to a specific era',
        searchQueryZh: '故居',
        searchQueryEn: 'former residence',
        tagsZh: <String>['人物故事', '慢看'],
        tagsEn: <String>['人物线索', 'Slow look'],
        secondarySceneIds: <String>['culture', 'memorial'],
        indoor: true,
      ),
      _archetype(
        slug: 'ancient_town',
        titleZh: '古镇',
        titleEn: 'ancient town',
        subtitleZh: '吃饭、走路、拍照能自然串成一条线',
        subtitleEn: 'food, walking, and photos naturally chain together here',
        searchQueryZh: '古镇',
        searchQueryEn: 'ancient town',
        tagsZh: <String>['一站式', '可吃可逛'],
        tagsEn: <String>['All-in-one', 'Food and stroll'],
        secondarySceneIds: <String>['food', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'city_wall_site',
        titleZh: '城墙遗址',
        titleEn: 'city wall site',
        subtitleZh: '适合看城市如何把防御和扩张写进空间',
        subtitleEn:
            'good for reading how the city wrote defense and growth into space',
        searchQueryZh: '城墙遗址',
        searchQueryEn: 'city wall site',
        tagsZh: <String>['城建痕迹', '开阔'],
        tagsEn: <String>['Urban trace', 'Open'],
        secondarySceneIds: <String>['photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'industrial_heritage_park',
        titleZh: '工业遗址园',
        titleEn: 'industrial heritage park',
        subtitleZh: '适合看旧工业空间如何被重新使用',
        subtitleEn: 'good for seeing how old industrial space gets re-used',
        searchQueryZh: '工业遗址园',
        searchQueryEn: 'industrial heritage park',
        tagsZh: <String>['工业感', '空间大'],
        tagsEn: <String>['Industrial', 'Spacious'],
        secondarySceneIds: <String>['photo', 'specialty'],
        indoor: false,
      ),
      _archetype(
        slug: 'temple_hall',
        titleZh: '古寺 / 祠堂',
        titleEn: 'historic temple hall',
        subtitleZh: '适合看木构、院落和秩序感如何落在空间里',
        subtitleEn:
            'good for observing timber structures, courtyards, and spatial order',
        searchQueryZh: '古寺 祠堂',
        searchQueryEn: 'historic temple hall',
        tagsZh: <String>['古建', '秩序感'],
        tagsEn: <String>['Historic architecture', 'Order'],
        secondarySceneIds: <String>['culture', 'memorial'],
        indoor: false,
      ),
      _archetype(
        slug: 'archaeology_site_park',
        titleZh: '考古遗址公园',
        titleEn: 'archaeology site park',
        subtitleZh: '适合把“遗址”从抽象词变成可漫步的现实空间',
        subtitleEn:
            'turns the idea of an archaeological site into a walkable reality',
        searchQueryZh: '考古遗址公园',
        searchQueryEn: 'archaeology site park',
        tagsZh: <String>['遗址', '信息量'],
        tagsEn: <String>['Archaeology', 'Informative'],
        secondarySceneIds: <String>['culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'historic_village',
        titleZh: '古村落',
        titleEn: 'historic village',
        subtitleZh: '适合把步行速度降下来，换一种更慢的生活感',
        subtitleEn:
            'good for slowing walking speed and shifting into a quieter life rhythm',
        searchQueryZh: '古村落',
        searchQueryEn: 'historic village',
        tagsZh: <String>['村落漫游', '节奏慢'],
        tagsEn: <String>['Village walk', 'Slow pace'],
        secondarySceneIds: <String>['nature', 'photo'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'nature',
    intentZh: '透气、晒太阳、看树看水，或者把身体带到户外',
    intentEn:
        'breathe, get light, look at trees and water, or move the body outdoors',
    companionZh: '一个人也能成行，拍照和轻运动同行体验更好',
    companionEn:
        'solo is easy here, though photos and light exercise pair especially well',
    checkpointZh: '天气、步行强度和返程便利性',
    checkpointEn: 'weather, walking intensity, and how easy the return is',
    outsideBudgetZh: '人均 0-30 元',
    outsideBudgetEn: 'roughly 0-30 CNY per person',
    nearbyBudgetZh: '人均 0-80 元',
    nearbyBudgetEn: 'roughly 0-80 CNY per person',
    travelBudgetZh: '门票 + 路费，预留 80-260 元起',
    travelBudgetEn: 'ticket plus transit, often 80-260 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'city_park',
        titleZh: '公园',
        titleEn: 'park',
        subtitleZh: '低门槛透气，几乎总有一条能走的路径',
        subtitleEn: 'easy to enter and almost always gives you a path to walk',
        searchQueryZh: '公园',
        searchQueryEn: 'park',
        tagsZh: <String>['低门槛', '透气'],
        tagsEn: <String>['Low friction', 'Fresh air'],
        secondarySceneIds: <String>['family', 'relax'],
        indoor: false,
      ),
      _archetype(
        slug: 'riverside_greenway',
        titleZh: '滨河绿道',
        titleEn: 'riverside greenway',
        subtitleZh: '线性路线明确，适合少做选择地往前走',
        subtitleEn:
            'a clear linear route that lowers decision-making while you move',
        searchQueryZh: '滨河绿道',
        searchQueryEn: 'riverside greenway',
        tagsZh: <String>['线性路线', '适合散步'],
        tagsEn: <String>['Linear route', 'Walkable'],
        secondarySceneIds: <String>['photo', 'sports'],
        indoor: false,
      ),
      _archetype(
        slug: 'lakeside_walk',
        titleZh: '湖边步道',
        titleEn: 'lakeside walk',
        subtitleZh: '看水面能明显把节奏放慢下来',
        subtitleEn: 'water views help the pace drop almost immediately',
        searchQueryZh: '湖边步道',
        searchQueryEn: 'lakeside walk',
        tagsZh: <String>['看水', '节奏慢'],
        tagsEn: <String>['Water view', 'Slow pace'],
        secondarySceneIds: <String>['relax', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'wetland_park',
        titleZh: '湿地公园',
        titleEn: 'wetland park',
        subtitleZh: '空间大，适合把身体和视野一起打开',
        subtitleEn:
            'spacious enough to open up both the body and the visual field',
        searchQueryZh: '湿地公园',
        searchQueryEn: 'wetland park',
        tagsZh: <String>['自然观察', '空间大'],
        tagsEn: <String>['Nature watching', 'Spacious'],
        secondarySceneIds: <String>['family', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'hill_trail',
        titleZh: '山林步道',
        titleEn: 'hill trail',
        subtitleZh: '适合想稍微出点汗，又不想做正式登山',
        subtitleEn:
            'good when you want some effort without making it a serious hike',
        searchQueryZh: '山林步道',
        searchQueryEn: 'hill trail',
        tagsZh: <String>['轻徒步', '出汗'],
        tagsEn: <String>['Light hiking', 'Sweat'],
        secondarySceneIds: <String>['sports', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'botanical_garden',
        titleZh: '植物园',
        titleEn: 'botanical garden',
        subtitleZh: '适合看植物密度和季节变化如何影响心情',
        subtitleEn:
            'good for noticing how plant density and seasonality change your mood',
        searchQueryZh: '植物园',
        searchQueryEn: 'botanical garden',
        tagsZh: <String>['植物密度高', '四季可看'],
        tagsEn: <String>['Plant-dense', 'Seasonal'],
        secondarySceneIds: <String>['relax', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'camping_lawn',
        titleZh: '露营草地',
        titleEn: 'camping lawn',
        subtitleZh: '铺个垫子就能待一会儿，社交和放空都成立',
        subtitleEn:
            'a mat is often enough to make the spot work for chatting or idling',
        searchQueryZh: '露营草地',
        searchQueryEn: 'camping lawn',
        tagsZh: <String>['可坐下', '弹性大'],
        tagsEn: <String>['Sit down', 'Flexible'],
        secondarySceneIds: <String>['social', 'family'],
        indoor: false,
      ),
      _archetype(
        slug: 'scenic_viewpoint',
        titleZh: '观景平台',
        titleEn: 'viewpoint',
        subtitleZh: '适合把“看风景”作为明确的收尾动作',
        subtitleEn:
            'good when seeing the view itself is the clean final action',
        searchQueryZh: '观景平台',
        searchQueryEn: 'viewpoint',
        tagsZh: <String>['看风景', '收尾'],
        tagsEn: <String>['View', 'Closure'],
        secondarySceneIds: <String>['photo', 'nightlife'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'study',
    intentZh: '找个安静地方看书、自习、办公或整理思路',
    intentEn:
        'find somewhere quiet to read, study, work, or sort out your thoughts',
    companionZh: '一个人最稳，结伴更适合低声共处的空间',
    companionEn:
        'solo is the most stable mode, while company works in low-voice shared spaces',
    checkpointZh: '安静程度、插座网络和停留规则',
    checkpointEn: 'noise level, sockets and Wi-Fi, and staying rules',
    outsideBudgetZh: '人均 0-40 元',
    outsideBudgetEn: 'roughly 0-40 CNY per person',
    nearbyBudgetZh: '人均 20-90 元',
    nearbyBudgetEn: 'roughly 20-90 CNY per person',
    travelBudgetZh: '场地 / 路费，预留 80-220 元起',
    travelBudgetEn: 'space plus transit, often 80-220 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'public_library',
        titleZh: '公共图书馆',
        titleEn: 'public library',
        subtitleZh: '免费稳妥，是最典型的专注环境',
        subtitleEn: 'free and reliable, the classic focus environment',
        searchQueryZh: '公共图书馆',
        searchQueryEn: 'public library',
        tagsZh: <String>['免费', '稳'],
        tagsEn: <String>['Free', 'Reliable'],
        secondarySceneIds: <String>['culture'],
        indoor: true,
      ),
      _archetype(
        slug: 'independent_bookstore',
        titleZh: '独立书店',
        titleEn: 'independent bookstore',
        subtitleZh: '适合选书、翻看，顺手进入更轻的专注状态',
        subtitleEn:
            'good for browsing and slipping into a lighter kind of focus',
        searchQueryZh: '独立书店',
        searchQueryEn: 'independent bookstore',
        tagsZh: <String>['选书', '安静'],
        tagsEn: <String>['Book browsing', 'Quiet'],
        secondarySceneIds: <String>['culture', 'relax'],
        indoor: true,
      ),
      _archetype(
        slug: 'study_room',
        titleZh: '自习室',
        titleEn: 'study room',
        subtitleZh: '适合短时冲刺，不需要再为氛围做筛选',
        subtitleEn: 'ideal for a short focused sprint without further setup',
        searchQueryZh: '自习室',
        searchQueryEn: 'study room',
        tagsZh: <String>['专注', '短时冲刺'],
        tagsEn: <String>['Focus', 'Sprint'],
        secondarySceneIds: <String>[],
        indoor: true,
      ),
      _archetype(
        slug: 'coworking_space',
        titleZh: '联合办公空间',
        titleEn: 'coworking space',
        subtitleZh: '适合带电脑完整坐一段时间',
        subtitleEn:
            'works when you want to sit with a laptop for a real block of time',
        searchQueryZh: '联合办公空间',
        searchQueryEn: 'coworking space',
        tagsZh: <String>['办公', '插座网络'],
        tagsEn: <String>['Work setup', 'Sockets and Wi-Fi'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'archive_reading_room',
        titleZh: '档案 / 地方文献阅览室',
        titleEn: 'archive reading room',
        subtitleZh: '适合带着明确问题去查资料',
        subtitleEn:
            'good when you already have a concrete question to investigate',
        searchQueryZh: '档案馆 阅览室',
        searchQueryEn: 'archive reading room',
        tagsZh: <String>['资料感', '深度输入'],
        tagsEn: <String>['Reference-heavy', 'Deep input'],
        secondarySceneIds: <String>['history', 'culture'],
        indoor: true,
      ),
      _archetype(
        slug: 'campus_study_corner',
        titleZh: '大学开放自习角',
        titleEn: 'campus study corner',
        subtitleZh: '学生氛围明显，适合短时借用一种学习气场',
        subtitleEn:
            'gives you a student-like atmosphere for a short burst of work',
        searchQueryZh: '大学 自习',
        searchQueryEn: 'campus study space',
        tagsZh: <String>['开放自习', '学生氛围'],
        tagsEn: <String>['Study corner', 'Campus vibe'],
        secondarySceneIds: <String>['food'],
        indoor: true,
      ),
      _archetype(
        slug: 'quiet_cafe',
        titleZh: '安静咖啡店',
        titleEn: 'quiet cafe',
        subtitleZh: '适合轻办公、看书或与人低声共处',
        subtitleEn:
            'good for light work, reading, or sitting quietly with someone',
        searchQueryZh: '安静咖啡店',
        searchQueryEn: 'quiet cafe',
        tagsZh: <String>['可久坐', '轻社交'],
        tagsEn: <String>['Sit-down', 'Light social'],
        secondarySceneIds: <String>['food', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'magazine_reading_space',
        titleZh: '杂志阅读空间',
        titleEn: 'magazine reading space',
        subtitleZh: '适合轻阅读，不会像重度自习那样压迫',
        subtitleEn:
            'supports softer reading without the pressure of formal study',
        searchQueryZh: '杂志 阅读 空间',
        searchQueryEn: 'magazine reading space',
        tagsZh: <String>['轻阅读', '不压迫'],
        tagsEn: <String>['Light reading', 'Low pressure'],
        secondarySceneIds: <String>['relax', 'culture'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'shopping',
    intentZh: '补给、逛街、比价，或顺手买点想要的东西',
    intentEn: 'restock, browse, compare, or buy something you actually need',
    companionZh: '一个人效率更高，结伴更适合慢逛和互相参谋',
    companionEn:
        'solo is more efficient, while company works for browsing and mutual advice',
    checkpointZh: '营业时间、人流密度和拎东西是否方便',
    checkpointEn:
        'opening hours, crowd density, and how manageable carrying items will be',
    outsideBudgetZh: '人均 20-120 元',
    outsideBudgetEn: 'roughly 20-120 CNY per person',
    nearbyBudgetZh: '人均 50-300 元',
    nearbyBudgetEn: 'roughly 50-300 CNY per person',
    travelBudgetZh: '购物 + 路费，预算波动较大',
    travelBudgetEn: 'shopping plus transit, with a wide budget range',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'neighborhood_market',
        titleZh: '生活市集',
        titleEn: 'neighborhood market',
        subtitleZh: '日常补给效率高，也容易顺手解决几件小事',
        subtitleEn:
            'efficient for everyday supplies and easy to bundle with errands',
        searchQueryZh: '生活市集',
        searchQueryEn: 'neighborhood market',
        tagsZh: <String>['日常补给', '效率'],
        tagsEn: <String>['Restock', 'Efficient'],
        secondarySceneIds: <String>['food'],
        indoor: false,
      ),
      _archetype(
        slug: 'mall',
        titleZh: '商场',
        titleEn: 'mall',
        subtitleZh: '一站式，天气不好时也更稳',
        subtitleEn: 'one-stop and especially steady in bad weather',
        searchQueryZh: '商场',
        searchQueryEn: 'mall',
        tagsZh: <String>['一站式', '天气友好'],
        tagsEn: <String>['One-stop', 'Weather-safe'],
        secondarySceneIds: <String>['food', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'pedestrian_street',
        titleZh: '步行街',
        titleEn: 'pedestrian street',
        subtitleZh: '逛走结合，适合边看边决定买不买',
        subtitleEn: 'good for moving and deciding in real time as you browse',
        searchQueryZh: '步行街',
        searchQueryEn: 'pedestrian street',
        tagsZh: <String>['逛走结合', '密度高'],
        tagsEn: <String>['Browse and walk', 'Dense'],
        secondarySceneIds: <String>['food', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'design_market',
        titleZh: '设计市集',
        titleEn: 'design market',
        subtitleZh: '适合想看更有审美取向的东西',
        subtitleEn:
            'good when you want objects with a stronger visual point of view',
        searchQueryZh: '设计市集',
        searchQueryEn: 'design market',
        tagsZh: <String>['审美', '手作'],
        tagsEn: <String>['Aesthetic', 'Handmade'],
        secondarySceneIds: <String>['specialty', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'vintage_store_block',
        titleZh: '复古买手店区',
        titleEn: 'vintage store block',
        subtitleZh: '适合淘风格明确、带点意外性的单品',
        subtitleEn: 'good for style-heavy finds with some surprise built in',
        searchQueryZh: '复古 买手店',
        searchQueryEn: 'vintage store block',
        tagsZh: <String>['淘货', '风格化'],
        tagsEn: <String>['Treasure hunt', 'Stylish'],
        secondarySceneIds: <String>['photo', 'specialty'],
        indoor: true,
      ),
      _archetype(
        slug: 'wholesale_market',
        titleZh: '批发市场',
        titleEn: 'wholesale market',
        subtitleZh: '目标明确时很好用，适合比价和集中补货',
        subtitleEn:
            'useful when your target is clear and price comparison matters',
        searchQueryZh: '批发市场',
        searchQueryEn: 'wholesale market',
        tagsZh: <String>['比价', '目标明确'],
        tagsEn: <String>['Compare prices', 'Targeted'],
        secondarySceneIds: <String>['specialty'],
        indoor: true,
      ),
      _archetype(
        slug: 'night_market',
        titleZh: '夜市',
        titleEn: 'night market',
        subtitleZh: '烟火气强，买和吃都能一起解决',
        subtitleEn: 'lively and practical, with shopping and food combined',
        searchQueryZh: '夜市',
        searchQueryEn: 'night market',
        tagsZh: <String>['烟火气', '夜间'],
        tagsEn: <String>['Night vibe', 'Evening'],
        secondarySceneIds: <String>['food', 'nightlife'],
        indoor: false,
      ),
      _archetype(
        slug: 'specialty_shopping_street',
        titleZh: '特产商店街',
        titleEn: 'specialty shopping street',
        subtitleZh: '适合带着一点目的性去买地方风味或伴手礼',
        subtitleEn: 'good for purposeful buying of local specialties or gifts',
        searchQueryZh: '特产商店街',
        searchQueryEn: 'specialty shopping street',
        tagsZh: <String>['伴手礼', '目的性'],
        tagsEn: <String>['Gifts', 'Purposeful'],
        secondarySceneIds: <String>['food', 'specialty'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'social',
    intentZh: '见人、聊天、轻聚会，或者让关系往前挪一点',
    intentEn:
        'meet someone, talk, gather lightly, or move a relationship a bit forward',
    companionZh: '两三个人最好，多人聚会要优先看等待和位置',
    companionEn:
        'best for two or three people, while larger groups need seating and timing',
    checkpointZh: '座位、噪音、预约和换场便利',
    checkpointEn:
        'seating, noise level, booking, and how easy it is to move on',
    outsideBudgetZh: '人均 20-80 元',
    outsideBudgetEn: 'roughly 20-80 CNY per person',
    nearbyBudgetZh: '人均 40-160 元',
    nearbyBudgetEn: 'roughly 40-160 CNY per person',
    travelBudgetZh: '餐饮 / 活动 + 路费，预留 100-320 元起',
    travelBudgetEn: 'food or activity plus transit, often 100-320 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'teahouse',
        titleZh: '茶馆',
        titleEn: 'teahouse',
        subtitleZh: '适合长聊，不需要一直靠新话题撑着',
        subtitleEn:
            'supports long conversation without needing constant stimulation',
        searchQueryZh: '茶馆',
        searchQueryEn: 'teahouse',
        tagsZh: <String>['适合长聊', '不吵'],
        tagsEn: <String>['Long talk', 'Not loud'],
        secondarySceneIds: <String>['relax', 'food'],
        indoor: true,
      ),
      _archetype(
        slug: 'chat_cafe',
        titleZh: '聊天咖啡馆',
        titleEn: 'chat cafe',
        subtitleZh: '低压力见面最稳妥的经典场景',
        subtitleEn: 'a classic low-pressure setting for meeting up',
        searchQueryZh: '聊天 咖啡馆',
        searchQueryEn: 'chat cafe',
        tagsZh: <String>['低压力', '经典'],
        tagsEn: <String>['Low pressure', 'Classic'],
        secondarySceneIds: <String>['food', 'study'],
        indoor: true,
      ),
      _archetype(
        slug: 'riverside_square',
        titleZh: '河岸广场',
        titleEn: 'riverside square',
        subtitleZh: '边走边聊，几乎没有门槛成本',
        subtitleEn:
            'lets conversation happen while moving with almost zero entry cost',
        searchQueryZh: '河岸广场',
        searchQueryEn: 'riverside square',
        tagsZh: <String>['边走边聊', '零门票'],
        tagsEn: <String>['Walk and talk', 'No ticket'],
        secondarySceneIds: <String>['nature', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'boardgame_club',
        titleZh: '桌游社交馆',
        titleEn: 'board game club',
        subtitleZh: '有共同规则时，关系推进往往更自然',
        subtitleEn: 'shared rules often make connection feel more natural',
        searchQueryZh: '桌游 社交馆',
        searchQueryEn: 'board game club',
        tagsZh: <String>['有事做', '不尴尬'],
        tagsEn: <String>['Shared activity', 'Less awkward'],
        secondarySceneIds: <String>['entertainment'],
        indoor: true,
      ),
      _archetype(
        slug: 'shared_kitchen_studio',
        titleZh: '共享手作厨房',
        titleEn: 'shared kitchen studio',
        subtitleZh: '适合一起做点什么，而不是只靠聊天推进气氛',
        subtitleEn:
            'useful when making something together is easier than just talking',
        searchQueryZh: '共享 手作 厨房',
        searchQueryEn: 'shared kitchen studio',
        tagsZh: <String>['一起做事', '体验型'],
        tagsEn: <String>['Make together', 'Experiential'],
        secondarySceneIds: <String>['food', 'specialty'],
        indoor: true,
      ),
      _archetype(
        slug: 'community_center',
        titleZh: '社区活动中心',
        titleEn: 'community center',
        subtitleZh: '低门槛，适合邻里和轻量见面',
        subtitleEn: 'low-barrier and well-suited to neighborhood-scale meetups',
        searchQueryZh: '社区活动中心',
        searchQueryEn: 'community center',
        tagsZh: <String>['低门槛', '邻里感'],
        tagsEn: <String>['Low barrier', 'Neighborhood'],
        secondarySceneIds: <String>['family'],
        indoor: true,
      ),
      _archetype(
        slug: 'pet_friendly_park',
        titleZh: '宠物友好公园',
        titleEn: 'pet-friendly park',
        subtitleZh: '有宠物时尤其好用，没宠物也适合轻松散步见面',
        subtitleEn:
            'especially useful with pets, but still good for easy walk-and-talk meetups',
        searchQueryZh: '宠物友好 公园',
        searchQueryEn: 'pet-friendly park',
        tagsZh: <String>['带宠友好', '节奏轻'],
        tagsEn: <String>['Pet-friendly', 'Easy pace'],
        secondarySceneIds: <String>['nature', 'family'],
        indoor: false,
      ),
      _archetype(
        slug: 'rooftop_lounge',
        titleZh: '露台休闲吧',
        titleEn: 'rooftop lounge',
        subtitleZh: '适合夜间聊天，有氛围但不一定要很闹',
        subtitleEn:
            'good for evening conversation with atmosphere but not too much chaos',
        searchQueryZh: '露台 休闲吧',
        searchQueryEn: 'rooftop lounge',
        tagsZh: <String>['夜间聊天', '有氛围'],
        tagsEn: <String>['Evening talk', 'Atmospheric'],
        secondarySceneIds: <String>['nightlife', 'photo'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'family',
    intentZh: '带孩子、陪长辈，或者安排多年龄都能接受的外出',
    intentEn:
        'take kids out, accompany elders, or plan for multiple age groups at once',
    companionZh: '优先考虑厕所、座位、无障碍和吃饭衔接',
    companionEn:
        'prioritize restrooms, seating, accessibility, and meal continuity',
    checkpointZh: '安全性、步行负担和多人移动效率',
    checkpointEn:
        'safety, walking burden, and how smoothly a group can move together',
    outsideBudgetZh: '人均 20-100 元',
    outsideBudgetEn: 'roughly 20-100 CNY per person',
    nearbyBudgetZh: '人均 60-240 元',
    nearbyBudgetEn: 'roughly 60-240 CNY per person',
    travelBudgetZh: '门票 / 餐饮 + 路费，预留 120-400 元起',
    travelBudgetEn: 'ticket or meal plus transit, often 120-400 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'children_play_center',
        titleZh: '儿童乐园',
        titleEn: 'children play center',
        subtitleZh: '放电直接，雨天也能成立',
        subtitleEn: 'a direct way to let kids burn energy, even on rainy days',
        searchQueryZh: '儿童乐园',
        searchQueryEn: 'children play center',
        tagsZh: <String>['放电', '雨天可去'],
        tagsEn: <String>['Energy release', 'Rain-safe'],
        secondarySceneIds: <String>['entertainment'],
        indoor: true,
      ),
      _archetype(
        slug: 'family_restaurant',
        titleZh: '亲子餐厅',
        titleEn: 'family restaurant',
        subtitleZh: '适合把吃饭和看护压力一起降下来',
        subtitleEn:
            'good for lowering both mealtime friction and caregiving pressure',
        searchQueryZh: '亲子餐厅',
        searchQueryEn: 'family restaurant',
        tagsZh: <String>['吃饭省心', '儿童友好'],
        tagsEn: <String>['Easy meal', 'Kid-friendly'],
        secondarySceneIds: <String>['food'],
        indoor: true,
      ),
      _archetype(
        slug: 'zoo_aquarium',
        titleZh: '动物园 / 水族馆',
        titleEn: 'zoo or aquarium',
        subtitleZh: '适合停留更久，也能自然拉开交流内容',
        subtitleEn:
            'supports longer stays and gives everyone things to talk about',
        searchQueryZh: '动物园 水族馆',
        searchQueryEn: 'zoo aquarium',
        tagsZh: <String>['观察类', '停留久'],
        tagsEn: <String>['Observation', 'Long stay'],
        secondarySceneIds: <String>['nature', 'culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'kids_science_hall',
        titleZh: '儿童科学馆',
        titleEn: 'kids science hall',
        subtitleZh: '适合边玩边学，家长也不容易无聊',
        subtitleEn:
            'lets kids play and learn while adults still have something to engage with',
        searchQueryZh: '儿童 科学馆',
        searchQueryEn: 'kids science hall',
        tagsZh: <String>['互动学习', '亲子共玩'],
        tagsEn: <String>['Interactive learning', 'Co-play'],
        secondarySceneIds: <String>['culture', 'study'],
        indoor: true,
      ),
      _archetype(
        slug: 'family_park',
        titleZh: '大草坪公园',
        titleEn: 'family park lawn',
        subtitleZh: '弹性大，推车、休息和跑动都更容易兼顾',
        subtitleEn: 'flexible enough to balance strollers, rest, and movement',
        searchQueryZh: '大草坪 公园',
        searchQueryEn: 'family park lawn',
        tagsZh: <String>['弹性大', '可休息'],
        tagsEn: <String>['Flexible', 'Rest-friendly'],
        secondarySceneIds: <String>['nature', 'relax'],
        indoor: false,
      ),
      _archetype(
        slug: 'picking_farm',
        titleZh: '采摘农场',
        titleEn: 'picking farm',
        subtitleZh: '有参与感，也能让孩子和长辈都找到自己的节奏',
        subtitleEn: 'participatory and often works for both kids and elders',
        searchQueryZh: '采摘农场',
        searchQueryEn: 'picking farm',
        tagsZh: <String>['可参与', '季节性'],
        tagsEn: <String>['Participatory', 'Seasonal'],
        secondarySceneIds: <String>['nature', 'food'],
        indoor: false,
      ),
      _archetype(
        slug: 'indoor_playground',
        titleZh: '室内游乐中心',
        titleEn: 'indoor playground',
        subtitleZh: '适合需要明确控温和更低天气风险的时候',
        subtitleEn:
            'useful when weather control and predictability matter more',
        searchQueryZh: '室内 游乐中心',
        searchQueryEn: 'indoor playground',
        tagsZh: <String>['室内放电', '低天气风险'],
        tagsEn: <String>['Indoor energy release', 'Weather-safe'],
        secondarySceneIds: <String>['entertainment'],
        indoor: true,
      ),
      _archetype(
        slug: 'easy_outing_lakeside',
        titleZh: '低门槛湖滨点',
        titleEn: 'easy lakeside outing spot',
        subtitleZh: '适合推车、慢走和多年龄一起看风景',
        subtitleEn:
            'good for strollers, slow walking, and shared scenery across ages',
        searchQueryZh: '湖滨 公园',
        searchQueryEn: 'lakeside park',
        tagsZh: <String>['推车友好', '慢走'],
        tagsEn: <String>['Stroller-friendly', 'Slow walk'],
        secondarySceneIds: <String>['nature', 'relax'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'nightlife',
    intentZh: '晚上继续玩、看夜景，或者给一天加一段有氛围的收尾',
    intentEn:
        'keep the evening going, see night views, or end the day with some atmosphere',
    companionZh: '两三个人最佳，夜间独行要优先看返程安全',
    companionEn:
        'best with a small group, and solo outings should prioritize safe return options',
    checkpointZh: '营业到几点、返程方式和夜间安全',
    checkpointEn: 'closing time, return transport, and night safety',
    outsideBudgetZh: '人均 30-120 元',
    outsideBudgetEn: 'roughly 30-120 CNY per person',
    nearbyBudgetZh: '人均 60-220 元',
    nearbyBudgetEn: 'roughly 60-220 CNY per person',
    travelBudgetZh: '活动 / 餐饮 + 路费，预留 120-400 元起',
    travelBudgetEn: 'activity or food plus transit, often 120-400 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'cocktail_bar',
        titleZh: '鸡尾酒吧',
        titleEn: 'cocktail bar',
        subtitleZh: '有一点仪式感，适合把聊天做得更完整',
        subtitleEn: 'adds some ritual and supports fuller conversation',
        searchQueryZh: '鸡尾酒吧',
        searchQueryEn: 'cocktail bar',
        tagsZh: <String>['仪式感', '聊天'],
        tagsEn: <String>['Ritual', 'Conversation'],
        secondarySceneIds: <String>['social'],
        indoor: true,
      ),
      _archetype(
        slug: 'craft_beer_bar',
        titleZh: '精酿吧',
        titleEn: 'craft beer bar',
        subtitleZh: '轻松一点，不必太正式，也适合续上社交',
        subtitleEn:
            'more relaxed and less formal, making it easy to extend a meetup',
        searchQueryZh: '精酿吧',
        searchQueryEn: 'craft beer bar',
        tagsZh: <String>['轻松', '不必正式'],
        tagsEn: <String>['Relaxed', 'Casual'],
        secondarySceneIds: <String>['social', 'food'],
        indoor: true,
      ),
      _archetype(
        slug: 'jazz_lounge',
        titleZh: 'Jazz Lounge',
        titleEn: 'jazz lounge',
        subtitleZh: '适合想要现场音乐，但又不想太吵的时候',
        subtitleEn: 'works when you want live music without a fully loud night',
        searchQueryZh: 'Jazz Lounge',
        searchQueryEn: 'jazz lounge',
        tagsZh: <String>['现场乐', '低照度'],
        tagsEn: <String>['Live music', 'Low light'],
        secondarySceneIds: <String>['culture', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'late_night_cafe',
        titleZh: '深夜咖啡馆',
        titleEn: 'late-night cafe',
        subtitleZh: '适合想延长清醒，但不想进入高刺激场景',
        subtitleEn:
            'good when you want to stay awake a bit longer without going high-stimulation',
        searchQueryZh: '深夜咖啡馆',
        searchQueryEn: 'late-night cafe',
        tagsZh: <String>['不太吵', '夜间出口'],
        tagsEn: <String>['Not too loud', 'Night option'],
        secondarySceneIds: <String>['study', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'night_show_stage',
        titleZh: '晚场演出点',
        titleEn: 'night show venue',
        subtitleZh: '适合把晚上做成一段明确体验，而不是只是耗时间',
        subtitleEn:
            'turns the evening into a clear experience instead of just idle time',
        searchQueryZh: '晚场 演出',
        searchQueryEn: 'night show venue',
        tagsZh: <String>['晚场', '明确体验'],
        tagsEn: <String>['Late show', 'Defined experience'],
        secondarySceneIds: <String>['entertainment'],
        indoor: true,
      ),
      _archetype(
        slug: 'night_view_spot',
        titleZh: '夜景观景点',
        titleEn: 'night view spot',
        subtitleZh: '低成本但很有收尾感，尤其适合一整天之后',
        subtitleEn: 'low-cost but great at giving the day a sense of closure',
        searchQueryZh: '夜景 观景点',
        searchQueryEn: 'night view spot',
        tagsZh: <String>['看城市灯光', '低成本'],
        tagsEn: <String>['City lights', 'Low cost'],
        secondarySceneIds: <String>['photo', 'nature'],
        indoor: false,
      ),
      _archetype(
        slug: 'all_night_esports_hall',
        titleZh: '24 小时电竞馆 / 网吧',
        titleEn: '24-hour esports hall',
        subtitleZh: '适合夜里还想和朋友打两局，或一个人继续沉浸',
        subtitleEn:
            'good when the night still wants a few more games with friends or alone',
        searchQueryZh: '24小时 电竞馆 网吧',
        searchQueryEn: '24 hour esports hall internet cafe',
        tagsZh: <String>['24h', '电竞'],
        tagsEn: <String>['24h', 'Esports'],
        secondarySceneIds: <String>['entertainment', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'late_night_food_block',
        titleZh: '夜间美食区',
        titleEn: 'late-night food block',
        subtitleZh: '适合用“再吃点什么”把夜晚自然收住',
        subtitleEn:
            'lets the night close itself through one more easy meal stop',
        searchQueryZh: '夜间 美食区',
        searchQueryEn: 'late-night food block',
        tagsZh: <String>['夜间收尾', '边吃边聊'],
        tagsEn: <String>['Night closure', 'Eat and talk'],
        secondarySceneIds: <String>['food', 'social'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'relax',
    intentZh: '降噪、恢复、慢下来，或者给自己一个明显的缓冲',
    intentEn:
        'decompress, recover, slow down, or give yourself a clearer buffer',
    companionZh: '独自去最容易放松，同行更适合轻声相处的人',
    companionEn:
        'solo is usually easiest for relaxing, with company working best when everyone stays gentle',
    checkpointZh: '是否需要预约、停留时长和安静程度',
    checkpointEn:
        'whether booking is needed, how long to stay, and how quiet it really is',
    outsideBudgetZh: '人均 0-80 元',
    outsideBudgetEn: 'roughly 0-80 CNY per person',
    nearbyBudgetZh: '人均 50-200 元',
    nearbyBudgetEn: 'roughly 50-200 CNY per person',
    travelBudgetZh: '放松项目 + 路费，预留 120-500 元起',
    travelBudgetEn: 'relaxation cost plus transit, often 120-500 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'hot_spring',
        titleZh: '温泉',
        titleEn: 'hot spring',
        subtitleZh: '恢复感明确，适合想把疲惫真正卸下来',
        subtitleEn:
            'clear in its restorative effect when you want real physical release',
        searchQueryZh: '温泉',
        searchQueryEn: 'hot spring',
        tagsZh: <String>['浸泡', '恢复'],
        tagsEn: <String>['Soak', 'Recovery'],
        secondarySceneIds: <String>['nature'],
        indoor: true,
      ),
      _archetype(
        slug: 'spa_massage',
        titleZh: '按摩 SPA',
        titleEn: 'spa or massage',
        subtitleZh: '适合把“我很累”直接翻译成一个明确动作',
        subtitleEn: 'turns “I am tired” into one direct restorative action',
        searchQueryZh: '按摩 SPA',
        searchQueryEn: 'spa massage',
        tagsZh: <String>['身体恢复', '明确放松'],
        tagsEn: <String>['Body recovery', 'Direct relax'],
        secondarySceneIds: <String>[],
        indoor: true,
      ),
      _archetype(
        slug: 'teahouse_retreat',
        titleZh: '静一点的茶室',
        titleEn: 'quiet tea room',
        subtitleZh: '适合把节奏压低，不靠高刺激转移注意力',
        subtitleEn: 'good for lowering the pace without leaning on stimulation',
        searchQueryZh: '茶室',
        searchQueryEn: 'tea room',
        tagsZh: <String>['慢坐', '降噪'],
        tagsEn: <String>['Slow sit', 'Quiet'],
        secondarySceneIds: <String>['food', 'social'],
        indoor: true,
      ),
      _archetype(
        slug: 'yoga_meditation_studio',
        titleZh: '瑜伽 / 冥想馆',
        titleEn: 'yoga or meditation studio',
        subtitleZh: '适合想让身体和注意力一起慢下来',
        subtitleEn:
            'useful when both the body and attention need to slow down together',
        searchQueryZh: '瑜伽 冥想馆',
        searchQueryEn: 'yoga meditation studio',
        tagsZh: <String>['轻运动', '静下来'],
        tagsEn: <String>['Light movement', 'Calm'],
        secondarySceneIds: <String>['sports'],
        indoor: true,
      ),
      _archetype(
        slug: 'lakeside_quiet_spot',
        titleZh: '湖边静坐点',
        titleEn: 'lakeside quiet spot',
        subtitleZh: '适合看水放空，不必额外消费也能成立',
        subtitleEn:
            'good for sitting by water and spacing out without needing to spend',
        searchQueryZh: '湖边 静坐',
        searchQueryEn: 'lakeside quiet spot',
        tagsZh: <String>['看水放空', '零门票'],
        tagsEn: <String>['Water view', 'No ticket'],
        secondarySceneIds: <String>['nature', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'healing_bookshop',
        titleZh: '疗愈书店',
        titleEn: 'healing bookstore',
        subtitleZh: '适合轻阅读和低刺激停留，不容易把人压满',
        subtitleEn:
            'supports gentle reading and low-stimulation staying without overloading you',
        searchQueryZh: '疗愈 书店',
        searchQueryEn: 'healing bookstore',
        tagsZh: <String>['安静', '可轻阅读'],
        tagsEn: <String>['Quiet', 'Light reading'],
        secondarySceneIds: <String>['study', 'culture'],
        indoor: true,
      ),
      _archetype(
        slug: 'staycation_courtyard',
        titleZh: '慢节奏小院 / 度假点',
        titleEn: 'slow staycation courtyard',
        subtitleZh: '适合换个环境，但又不想把旅程弄得太重',
        subtitleEn:
            'good when you want a change of scene without making the trip too heavy',
        searchQueryZh: '小院 度假',
        searchQueryEn: 'staycation courtyard',
        tagsZh: <String>['换环境', '不太折腾'],
        tagsEn: <String>['Scene change', 'Low hassle'],
        secondarySceneIds: <String>['family', 'food'],
        indoor: true,
      ),
      _archetype(
        slug: 'greenhouse_garden',
        titleZh: '温室花园',
        titleEn: 'greenhouse garden',
        subtitleZh: '适合想看绿色，但又想降低天气变量',
        subtitleEn: 'good when you want greenery with less weather uncertainty',
        searchQueryZh: '温室 花园',
        searchQueryEn: 'greenhouse garden',
        tagsZh: <String>['天气友好', '绿色感'],
        tagsEn: <String>['Weather-friendly', 'Greenery'],
        secondarySceneIds: <String>['nature', 'photo'],
        indoor: true,
      ),
    ],
  ),
  _scene(
    id: 'photo',
    intentZh: '找街景、机位、建筑和自然光，让拍照更容易出片',
    intentEn:
        'find street scenes, camera angles, architecture, and light that make photos easier',
    companionZh: '一个人适合扫街，有同伴时更适合互拍和等光',
    companionEn:
        'solo works for street wandering, while company is better for mutual shooting and waiting for light',
    checkpointZh: '光线、天气、人流和机位可替代性',
    checkpointEn:
        'light, weather, crowd level, and how replaceable the angle is',
    outsideBudgetZh: '人均 0-40 元',
    outsideBudgetEn: 'roughly 0-40 CNY per person',
    nearbyBudgetZh: '人均 20-120 元',
    nearbyBudgetEn: 'roughly 20-120 CNY per person',
    travelBudgetZh: '门票 / 路费，预留 80-300 元起',
    travelBudgetEn: 'ticket or transit, often 80-300 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'street_scene_block',
        titleZh: '街景街区',
        titleEn: 'street-scene block',
        subtitleZh: '适合扫街，容易靠细节和行人关系出片',
        subtitleEn:
            'good for street shooting where details and passersby do a lot of the work',
        searchQueryZh: '街景 街区',
        searchQueryEn: 'street scene block',
        tagsZh: <String>['扫街', '细节密度高'],
        tagsEn: <String>['Street shooting', 'Detail-rich'],
        secondarySceneIds: <String>['specialty', 'history'],
        indoor: false,
      ),
      _archetype(
        slug: 'rooftop_viewpoint',
        titleZh: '高处观景台',
        titleEn: 'rooftop viewpoint',
        subtitleZh: '适合看天际线和等光线变化',
        subtitleEn: 'great for skylines and waiting through changing light',
        searchQueryZh: '观景台',
        searchQueryEn: 'rooftop viewpoint',
        tagsZh: <String>['看天际线', '适合等光'],
        tagsEn: <String>['Skyline', 'Wait for light'],
        secondarySceneIds: <String>['nightlife', 'nature'],
        indoor: false,
      ),
      _archetype(
        slug: 'industrial_photo_zone',
        titleZh: '工业风园区',
        titleEn: 'industrial photo zone',
        subtitleZh: '结构感强，适合线条、材质和人物关系',
        subtitleEn:
            'strong on structure, lines, textures, and figure placement',
        searchQueryZh: '工业风 园区',
        searchQueryEn: 'industrial photo zone',
        tagsZh: <String>['结构感', '工业风'],
        tagsEn: <String>['Structured', 'Industrial'],
        secondarySceneIds: <String>['specialty', 'culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'installation_square',
        titleZh: '装置广场',
        titleEn: 'installation square',
        subtitleZh: '适合前景、留白和互动感比较强的画面',
        subtitleEn:
            'good for frames with foreground, negative space, and interaction',
        searchQueryZh: '装置 广场',
        searchQueryEn: 'installation square',
        tagsZh: <String>['装置', '前景丰富'],
        tagsEn: <String>['Installation', 'Foreground'],
        secondarySceneIds: <String>['culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'riverside_sunset_spot',
        titleZh: '江边日落点',
        titleEn: 'riverside sunset spot',
        subtitleZh: '适合把光线当主角，尤其在傍晚',
        subtitleEn:
            'lets light be the main character, especially toward evening',
        searchQueryZh: '江边 日落',
        searchQueryEn: 'riverside sunset spot',
        tagsZh: <String>['日落', '光线柔'],
        tagsEn: <String>['Sunset', 'Soft light'],
        secondarySceneIds: <String>['nature'],
        indoor: false,
      ),
      _archetype(
        slug: 'old_alley',
        titleZh: '老巷子',
        titleEn: 'old alley',
        subtitleZh: '故事感强，适合拍一些更靠近时间痕迹的内容',
        subtitleEn: 'rich in story and suited to images shaped by time traces',
        searchQueryZh: '老巷子',
        searchQueryEn: 'old alley',
        tagsZh: <String>['故事感', '时间痕迹'],
        tagsEn: <String>['Story-rich', 'Time traces'],
        secondarySceneIds: <String>['history', 'specialty'],
        indoor: false,
      ),
      _archetype(
        slug: 'landmark_architecture',
        titleZh: '地标建筑群',
        titleEn: 'landmark architecture cluster',
        subtitleZh: '适合拍线条清楚、尺度感明显的画面',
        subtitleEn: 'works well for strong lines and images with obvious scale',
        searchQueryZh: '地标 建筑',
        searchQueryEn: 'landmark architecture',
        tagsZh: <String>['建筑线条', '尺度感'],
        tagsEn: <String>['Architecture', 'Sense of scale'],
        secondarySceneIds: <String>['culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'seasonal_flower_field',
        titleZh: '季节花田 / 花园',
        titleEn: 'seasonal flower field',
        subtitleZh: '适合花期驱动的明确出片目标',
        subtitleEn:
            'good when the outing is driven by a clear seasonal bloom target',
        searchQueryZh: '花田 花园',
        searchQueryEn: 'seasonal flower field',
        tagsZh: <String>['花期驱动', '强视觉'],
        tagsEn: <String>['Seasonal bloom', 'Visual impact'],
        secondarySceneIds: <String>['nature', 'family'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'specialty',
    intentZh: '找有地方性气质的区域，不只是到一个单点',
    intentEn:
        'find areas with local character instead of going only to one isolated spot',
    companionZh: '更适合愿意边走边看、愿意临时拐弯的人',
    companionEn: 'best with people willing to wander, browse, and improvise',
    checkpointZh: '开放时间、区域密度和步行串联性',
    checkpointEn: 'opening time, area density, and how walkable the cluster is',
    outsideBudgetZh: '人均 20-100 元',
    outsideBudgetEn: 'roughly 20-100 CNY per person',
    nearbyBudgetZh: '人均 50-220 元',
    nearbyBudgetEn: 'roughly 50-220 CNY per person',
    travelBudgetZh: '消费 + 路费，预留 120-420 元起',
    travelBudgetEn: 'spending plus transit, often 120-420 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'creative_park',
        titleZh: '创意园区',
        titleEn: 'creative park',
        subtitleZh: '复合业态多，适合把逛、吃、拍合在一起',
        subtitleEn:
            'mixed-use and easy to combine browsing, eating, and shooting',
        searchQueryZh: '创意园区',
        searchQueryEn: 'creative park',
        tagsZh: <String>['复合业态', '能逛很久'],
        tagsEn: <String>['Mixed-use', 'Long browse'],
        secondarySceneIds: <String>['shopping', 'photo'],
        indoor: false,
      ),
      _archetype(
        slug: 'craft_street',
        titleZh: '手作街区',
        titleEn: 'craft street',
        subtitleZh: '适合看小店密度和手作质感',
        subtitleEn: 'good for browsing dense small shops and handmade textures',
        searchQueryZh: '手作 街区',
        searchQueryEn: 'craft street',
        tagsZh: <String>['手作', '慢逛'],
        tagsEn: <String>['Handmade', 'Slow browse'],
        secondarySceneIds: <String>['shopping', 'culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'specialty_food_zone',
        titleZh: '特色风味区',
        titleEn: 'specialty food zone',
        subtitleZh: '适合集中尝一种地方味道，而不是散点式找店',
        subtitleEn: 'good for tasting one local style in a concentrated area',
        searchQueryZh: '特色 风味区',
        searchQueryEn: 'specialty food zone',
        tagsZh: <String>['地方味道', '集中'],
        tagsEn: <String>['Local flavor', 'Concentrated'],
        secondarySceneIds: <String>['food'],
        indoor: false,
      ),
      _archetype(
        slug: 'antique_market',
        titleZh: '古玩旧物区',
        titleEn: 'antique market',
        subtitleZh: '适合看旧物如何构成一种地方审美',
        subtitleEn: 'good for seeing how old objects build a local aesthetic',
        searchQueryZh: '古玩 旧物 市场',
        searchQueryEn: 'antique market',
        tagsZh: <String>['旧物气质', '能淘'],
        tagsEn: <String>['Vintage objects', 'Treasure hunt'],
        secondarySceneIds: <String>['shopping', 'photo'],
        indoor: true,
      ),
      _archetype(
        slug: 'cultural_market',
        titleZh: '文创市集',
        titleEn: 'cultural market',
        subtitleZh: '适合把逛展和买点小东西合在同一条线里',
        subtitleEn:
            'lets exhibitions and small purchases live on the same outing line',
        searchQueryZh: '文创 市集',
        searchQueryEn: 'cultural market',
        tagsZh: <String>['文创', '展售混合'],
        tagsEn: <String>['Cultural goods', 'Show and shop'],
        secondarySceneIds: <String>['shopping', 'culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'converted_factory_district',
        titleZh: '改造厂区',
        titleEn: 'converted factory district',
        subtitleZh: '适合看旧工业空间如何被改写成当代生活场景',
        subtitleEn:
            'good for watching industrial space get rewritten into present-day life',
        searchQueryZh: '改造 厂区',
        searchQueryEn: 'converted factory district',
        tagsZh: <String>['改造空间', '层次感'],
        tagsEn: <String>['Adaptive reuse', 'Layered'],
        secondarySceneIds: <String>['photo', 'history'],
        indoor: false,
      ),
      _archetype(
        slug: 'folk_custom_neighborhood',
        titleZh: '民俗风情区',
        titleEn: 'folk-custom neighborhood',
        subtitleZh: '适合集中体验某种地方生活方式的外观与节奏',
        subtitleEn:
            'good for sensing the visual style and rhythm of a local way of life',
        searchQueryZh: '民俗 风情区',
        searchQueryEn: 'folk custom neighborhood',
        tagsZh: <String>['地域风情', '体验型'],
        tagsEn: <String>['Regional style', 'Experiential'],
        secondarySceneIds: <String>['history', 'food'],
        indoor: false,
      ),
      _archetype(
        slug: 'themed_fair',
        titleZh: '主题市集',
        titleEn: 'themed fair',
        subtitleZh: '短期活动感强，适合想要明显新鲜感的时候',
        subtitleEn:
            'strong on temporary-event energy when you want obvious novelty',
        searchQueryZh: '主题 市集',
        searchQueryEn: 'themed fair',
        tagsZh: <String>['短期活动', '新鲜感强'],
        tagsEn: <String>['Limited-time', 'High novelty'],
        secondarySceneIds: <String>['entertainment', 'shopping'],
        indoor: false,
      ),
    ],
  ),
  _scene(
    id: 'memorial',
    intentZh: '做一次纪念、缅怀，或认真看一个城市如何保存记忆',
    intentEn:
        'remember, commemorate, or look closely at how a city preserves memory',
    companionZh: '更适合慢速行走和低声交流，也可以独自去',
    companionEn:
        'best for slow walking and low-voice exchange, though solo works very well too',
    checkpointZh: '开放规则、讲解安排和礼仪要求',
    checkpointEn:
        'access rules, guided interpretation, and etiquette expectations',
    outsideBudgetZh: '人均 0-30 元',
    outsideBudgetEn: 'roughly 0-30 CNY per person',
    nearbyBudgetZh: '人均 0-80 元',
    nearbyBudgetEn: 'roughly 0-80 CNY per person',
    travelBudgetZh: '门票 / 路费，预留 60-220 元起',
    travelBudgetEn: 'ticket or transit, often 60-220 CNY and up',
    archetypes: <_PlaceArchetype>[
      _archetype(
        slug: 'memorial_hall',
        titleZh: '纪念馆',
        titleEn: 'memorial hall',
        subtitleZh: '主题明确，是最标准的公共记忆入口',
        subtitleEn:
            'the clearest public-memory entry point thanks to its focused theme',
        searchQueryZh: '纪念馆',
        searchQueryEn: 'memorial hall',
        tagsZh: <String>['主题明确', '信息完整'],
        tagsEn: <String>['Focused theme', 'Informative'],
        secondarySceneIds: <String>['history', 'culture'],
        indoor: true,
      ),
      _archetype(
        slug: 'martyrs_park',
        titleZh: '烈士纪念园',
        titleEn: 'martyrs memorial park',
        subtitleZh: '适合短暂停留，也适合更安静地走一段路',
        subtitleEn: 'works for both a short stop and a quieter reflective walk',
        searchQueryZh: '烈士 纪念园',
        searchQueryEn: 'martyrs memorial park',
        tagsZh: <String>['肃穆', '短暂停留'],
        tagsEn: <String>['Solemn', 'Short stop'],
        secondarySceneIds: <String>['history'],
        indoor: false,
      ),
      _archetype(
        slug: 'disaster_memorial_park',
        titleZh: '灾害纪念公园',
        titleEn: 'disaster memorial park',
        subtitleZh: '适合认真理解一段集体经验如何被留下来',
        subtitleEn:
            'good for understanding how a collective experience gets preserved',
        searchQueryZh: '灾害 纪念公园',
        searchQueryEn: 'disaster memorial park',
        tagsZh: <String>['公共记忆', '认真看'],
        tagsEn: <String>['Public memory', 'Reflective'],
        secondarySceneIds: <String>['history', 'culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'city_memory_museum',
        titleZh: '城市记忆馆',
        titleEn: 'city memory museum',
        subtitleZh: '适合理解一座城市如何讲述自己的过去',
        subtitleEn: 'helps you see how a city narrates its own past',
        searchQueryZh: '城市记忆馆',
        searchQueryEn: 'city memory museum',
        tagsZh: <String>['城市叙事', '记忆保存'],
        tagsEn: <String>['City narrative', 'Memory'],
        secondarySceneIds: <String>['history', 'culture'],
        indoor: true,
      ),
      _archetype(
        slug: 'school_history_museum',
        titleZh: '校史馆',
        titleEn: 'school history museum',
        subtitleZh: '对校友、家长和对教育史有兴趣的人都很友好',
        subtitleEn:
            'friendly for alumni, families, and people curious about education history',
        searchQueryZh: '校史馆',
        searchQueryEn: 'school history museum',
        tagsZh: <String>['校友友好', '教育史'],
        tagsEn: <String>['Alumni-friendly', 'Education history'],
        secondarySceneIds: <String>['study', 'history'],
        indoor: true,
      ),
      _archetype(
        slug: 'figure_memorial_residence',
        titleZh: '人物故居纪念馆',
        titleEn: 'figure memorial residence',
        subtitleZh: '适合沿着一个人物去看时代与生活切面',
        subtitleEn:
            'lets one historical figure open up a wider era and way of life',
        searchQueryZh: '人物 故居 纪念馆',
        searchQueryEn: 'figure memorial residence',
        tagsZh: <String>['人物线索', '生活切面'],
        tagsEn: <String>['Figure-led', 'Life slice'],
        secondarySceneIds: <String>['history', 'culture'],
        indoor: true,
      ),
      _archetype(
        slug: 'war_site_memorial',
        titleZh: '战役遗址纪念地',
        titleEn: 'war-site memorial',
        subtitleZh: '适合把历史事件与真实空间感重新对齐',
        subtitleEn: 'reconnects historical events with real physical space',
        searchQueryZh: '战役 遗址 纪念地',
        searchQueryEn: 'war site memorial',
        tagsZh: <String>['遗址感', '完整看'],
        tagsEn: <String>['Site feeling', 'Full look'],
        secondarySceneIds: <String>['history', 'culture'],
        indoor: false,
      ),
      _archetype(
        slug: 'remembrance_square',
        titleZh: '公共纪念广场',
        titleEn: 'remembrance square',
        subtitleZh: '仪式性明确，适合短时驻足和集中注意力',
        subtitleEn:
            'clear in ritual character and good for a focused short stop',
        searchQueryZh: '纪念 广场',
        searchQueryEn: 'remembrance square',
        tagsZh: <String>['仪式性', '驻足'],
        tagsEn: <String>['Ritual', 'Pause'],
        secondarySceneIds: <String>['history'],
        indoor: false,
      ),
    ],
  ),
];

_PlaceSceneSeed _scene({
  required String id,
  required String intentZh,
  required String intentEn,
  required String companionZh,
  required String companionEn,
  required String checkpointZh,
  required String checkpointEn,
  required String outsideBudgetZh,
  required String outsideBudgetEn,
  required String nearbyBudgetZh,
  required String nearbyBudgetEn,
  required String travelBudgetZh,
  required String travelBudgetEn,
  required List<_PlaceArchetype> archetypes,
}) {
  return _PlaceSceneSeed(
    id: id,
    intentZh: intentZh,
    intentEn: intentEn,
    companionZh: companionZh,
    companionEn: companionEn,
    checkpointZh: checkpointZh,
    checkpointEn: checkpointEn,
    outsideBudgetZh: outsideBudgetZh,
    outsideBudgetEn: outsideBudgetEn,
    nearbyBudgetZh: nearbyBudgetZh,
    nearbyBudgetEn: nearbyBudgetEn,
    travelBudgetZh: travelBudgetZh,
    travelBudgetEn: travelBudgetEn,
    archetypes: archetypes,
  );
}

_PlaceArchetype _archetype({
  required String slug,
  required String titleZh,
  required String titleEn,
  required String subtitleZh,
  required String subtitleEn,
  required String searchQueryZh,
  required String searchQueryEn,
  List<String> tagsZh = const <String>[],
  List<String> tagsEn = const <String>[],
  List<String> secondarySceneIds = const <String>[],
  bool indoor = false,
}) {
  return _PlaceArchetype(
    slug: slug,
    titleZh: titleZh,
    titleEn: titleEn,
    subtitleZh: subtitleZh,
    subtitleEn: subtitleEn,
    searchQueryZh: searchQueryZh,
    searchQueryEn: searchQueryEn,
    tagsZh: tagsZh,
    tagsEn: tagsEn,
    secondarySceneIds: secondarySceneIds,
    indoor: indoor,
  );
}

class _PlaceDistanceProfile {
  const _PlaceDistanceProfile({
    required this.id,
    required this.rhythmZh,
    required this.rhythmEn,
    required this.durationZh,
    required this.durationEn,
    required this.checklistZh,
    required this.checklistEn,
  });

  final String id;
  final String rhythmZh;
  final String rhythmEn;
  final String durationZh;
  final String durationEn;
  final String checklistZh;
  final String checklistEn;
}

class _PlaceSceneSeed {
  const _PlaceSceneSeed({
    required this.id,
    required this.intentZh,
    required this.intentEn,
    required this.companionZh,
    required this.companionEn,
    required this.checkpointZh,
    required this.checkpointEn,
    required this.outsideBudgetZh,
    required this.outsideBudgetEn,
    required this.nearbyBudgetZh,
    required this.nearbyBudgetEn,
    required this.travelBudgetZh,
    required this.travelBudgetEn,
    required this.archetypes,
  });

  final String id;
  final String intentZh;
  final String intentEn;
  final String companionZh;
  final String companionEn;
  final String checkpointZh;
  final String checkpointEn;
  final String outsideBudgetZh;
  final String outsideBudgetEn;
  final String nearbyBudgetZh;
  final String nearbyBudgetEn;
  final String travelBudgetZh;
  final String travelBudgetEn;
  final List<_PlaceArchetype> archetypes;

  String budgetZh(String distanceId) {
    return switch (distanceId) {
      'outside' => outsideBudgetZh,
      'nearby' => nearbyBudgetZh,
      'travel' => travelBudgetZh,
      _ => nearbyBudgetZh,
    };
  }

  String budgetEn(String distanceId) {
    return switch (distanceId) {
      'outside' => outsideBudgetEn,
      'nearby' => nearbyBudgetEn,
      'travel' => travelBudgetEn,
      _ => nearbyBudgetEn,
    };
  }
}

class _PlaceArchetype {
  const _PlaceArchetype({
    required this.slug,
    required this.titleZh,
    required this.titleEn,
    required this.subtitleZh,
    required this.subtitleEn,
    required this.searchQueryZh,
    required this.searchQueryEn,
    this.tagsZh = const <String>[],
    this.tagsEn = const <String>[],
    this.secondarySceneIds = const <String>[],
    this.indoor = false,
  });

  final String slug;
  final String titleZh;
  final String titleEn;
  final String subtitleZh;
  final String subtitleEn;
  final String searchQueryZh;
  final String searchQueryEn;
  final List<String> tagsZh;
  final List<String> tagsEn;
  final List<String> secondarySceneIds;
  final bool indoor;
}
