part of 'daily_choice_seed_data.dart';

final List<DailyChoiceOption> _activityOptions = <DailyChoiceOption>[
  _activity(
    'do_move_walk',
    'move',
    '快走 12 分钟',
    '12-minute brisk walk',
    '不用换装备，只要出门一圈。',
    'No gear change, just one loop.',
  ),
  _activity(
    'do_move_stretch',
    'move',
    '肩颈拉伸一轮',
    'One neck-shoulder stretch round',
    '适合久坐后重启身体。',
    'Good after long sitting.',
  ),
  _activity(
    'do_move_squat',
    'move',
    '深蹲 3 组',
    'Three sets of squats',
    '用最少空间激活下肢。',
    'Activate legs in minimal space.',
  ),
  _activity(
    'do_learn_words',
    'learn',
    '复习 10 个单词',
    'Review 10 words',
    '和主应用目标保持连贯。',
    'Aligned with the main learning goal.',
  ),
  _activity(
    'do_learn_article',
    'learn',
    '读一页文章并摘一句',
    'Read one page and extract one line',
    '小输入也算学习闭环。',
    'A small input still completes a learning loop.',
  ),
  _activity(
    'do_learn_video',
    'learn',
    '看 8 分钟教程',
    'Watch an 8-minute tutorial',
    '只记一个可执行动作。',
    'Record one actionable idea only.',
  ),
  _activity(
    'do_outdoor_photo',
    'outdoor',
    '出门拍 3 张照片',
    'Take three photos outside',
    '用观察代替刷屏。',
    'Use observation instead of scrolling.',
  ),
  _activity(
    'do_outdoor_errand',
    'outdoor',
    '完成一个顺路小事',
    'Finish one small errand',
    '让出门有一个明确收口。',
    'Give the outing a clear endpoint.',
  ),
  _activity(
    'do_home_desk',
    'home',
    '桌面清空 5 分钟',
    'Clear desk for five minutes',
    '只处理可见表面，不挖深坑。',
    'Only visible surfaces, no deep excavation.',
  ),
  _activity(
    'do_home_laundry',
    'home',
    '衣物归位一篮',
    'Put away one laundry basket',
    '一个篮子就是边界。',
    'One basket is the boundary.',
  ),
  _activity(
    'do_home_kitchen',
    'home',
    '厨房水槽归零',
    'Reset kitchen sink',
    '完成后下一顿饭阻力会小很多。',
    'Makes the next meal much easier.',
  ),
  _activity(
    'do_relax_breathing',
    'relax',
    '呼吸训练 3 分钟',
    'Three-minute breathing practice',
    '低刺激重置。',
    'A low-stimulation reset.',
  ),
  _activity(
    'do_relax_music',
    'relax',
    '听一首完整音乐',
    'Listen to one full track',
    '不切歌，给注意力一个完整段落。',
    'No skipping; give attention one full segment.',
  ),
  _activity(
    'do_relax_tea',
    'relax',
    '泡一杯热饮',
    'Make a warm drink',
    '用一个慢动作结束焦躁。',
    'Use one slow action to close agitation.',
  ),
  _activity(
    'do_create_note',
    'create',
    '写 100 字碎片',
    'Write a 100-word fragment',
    '不求完整，只留下痕迹。',
    'Not complete, just leave a trace.',
  ),
  _activity(
    'do_create_sketch',
    'create',
    '画一个 5 分钟草图',
    'Draw a five-minute sketch',
    '手先动起来。',
    'Let the hand move first.',
  ),
  _activity(
    'do_create_playlist',
    'create',
    '整理 5 首歌歌单',
    'Curate a five-song playlist',
    '小型审美整理。',
    'A small aesthetic edit.',
  ),
  _activity(
    'do_social_message',
    'social',
    '给一个人发近况',
    'Send one update message',
    '轻量连接，不必展开长聊。',
    'Light contact, no need for a long chat.',
  ),
  _activity(
    'do_social_thanks',
    'social',
    '补一句感谢',
    'Send one thank-you note',
    '把想过但没说的话补上。',
    'Say the thing you thought but did not send.',
  ),
  _activity(
    'do_social_plan',
    'social',
    '约一个低压力见面',
    'Suggest a low-pressure meetup',
    '比如散步、咖啡或一起吃饭。',
    'For example walk, coffee, or a meal.',
  ),
];
DailyChoiceOption _activity(
  String id,
  String category,
  String titleZh,
  String titleEn,
  String subtitleZh,
  String subtitleEn,
) {
  return _choice(
    id: id,
    moduleId: 'activity',
    categoryId: category,
    titleZh: titleZh,
    titleEn: titleEn,
    subtitleZh: subtitleZh,
    subtitleEn: subtitleEn,
    detailsZh: '把行动切成一个明确、可结束的小块。完成后再决定是否继续，不把随机结果变成压力。',
    detailsEn:
        'Keep the action bounded and finishable. After one round, decide whether to continue.',
    materialsZh: <String>['一个计时器', '一个可见终点'],
    materialsEn: <String>['A timer', 'A visible endpoint'],
    stepsZh: <String>['把时间设短。', '只做当前这一个动作。', '结束后记录是否想继续。'],
    stepsEn: <String>[
      'Set a short timer.',
      'Do only this action.',
      'After finishing, note whether to continue.',
    ],
    tagsZh: <String>['行动', category],
    tagsEn: <String>['Action', category],
  );
}
