part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _legacyTimelineFacts02 = <_TimelineFact>[
  _TimelineFact(
    id: 'reformation_luther',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 509,
    displayKey: 'inline.plan295.life.1517_ce.3a3391c09bb4',
    titleKey: 'inline.plan295.life.protestant_reformation_begins.fd203bcca4fa',
    detailKey: 'inline.plan295.life.debates_associated_with_martin_luthe.7d228dba3ce7',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Reformation',
  ),
  _TimelineFact(
    id: 'copernicus',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 483,
    displayKey: 'inline.plan295.life.1543_ce.c05c3e413520',
    titleKey: 'inline.plan295.life.copernicus_publishes_heliocentric_mo.40f2da05c926',
    detailKey: 'inline.plan295.life.on_the_revolutions_proposed_a_helioc.67f428a648f5',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Nicolaus-Copernicus',
  ),
  _TimelineFact(
    id: 'galileo_telescope',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 416,
    displayKey: 'inline.plan295.life.1610_ce.0b3f308f7183',
    titleKey: 'inline.plan295.life.galileo_s_telescopic_observations.27ad07fec839',
    detailKey: 'inline.plan295.life.galileo_published_observations_of_th.deb92fa3b6b6',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Galileo-Galilei',
  ),
  _TimelineFact(
    id: 'westphalia',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 378,
    displayKey: 'inline.plan295.life.1648_ce.424b1ba5ca83',
    titleKey: 'inline.plan295.life.peace_of_westphalia.5511a5358ca3',
    detailKey: 'inline.plan295.life.the_thirty_years_war_ended_and_europ.460808c33b2e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Peace-of-Westphalia',
  ),
  _TimelineFact(
    id: 'qing_dynasty',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 382,
    displayKey: 'inline.plan295.life.1644_ce.f1822f087d4e',
    titleKey: 'inline.plan295.life.qing_dynasty_takes_beijing.bbf404837d19',
    detailKey: 'inline.plan295.life.the_qing_established_rule_from_beiji.60d3e1fd456c',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Qing-dynasty',
  ),
  _TimelineFact(
    id: 'slave_trade_abolition_britain',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 219,
    displayKey: 'inline.plan295.life.1807_ce.b56bba3ab80d',
    titleKey: 'inline.plan295.life.britain_abolishes_the_slave_trade.df49557c0bb2',
    detailKey: 'inline.plan295.life.britain_banned_the_slave_trade_a_maj.4cf40d86c6f8',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Slave-Trade-Act',
  ),
  _TimelineFact(
    id: 'haitian_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 222,
    displayKey: 'inline.plan295.life.1804_ce.54228a0e2fa6',
    titleKey: 'inline.plan295.life.haitian_independence.03ba05d23a7c',
    detailKey: 'inline.plan295.life.after_the_haitian_revolution_haiti_b.8a22605db418',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Haitian-Revolution',
  ),
  _TimelineFact(
    id: 'latin_american_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 216,
    displayKey: 'inline.plan295.life.from_c_1810_ce.cec8657ef097',
    titleKey: 'inline.plan295.life.latin_american_independence_movement.8cdd2407a6d7',
    detailKey: 'inline.plan295.life.spanish_and_portuguese_colonial_syst.d829f2613c30',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Latin-American-independence-movements',
  ),
  _TimelineFact(
    id: 'opium_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 187,
    displayKey: 'inline.plan295.life.1839_1842_ce.0054d86fbdce',
    titleKey: 'inline.plan295.life.first_opium_war.5106b71fac4a',
    detailKey: 'inline.plan295.life.after_war_with_britain_the_treaty_of.ae53ce2dd877',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Opium-Wars',
  ),
  _TimelineFact(
    id: 'meiji_restoration',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 158,
    displayKey: 'inline.plan295.life.1868_ce.7e875082fbab',
    titleKey: 'inline.plan295.life.meiji_restoration.7f0f3bf63fab',
    detailKey: 'inline.plan295.life.japan_reorganized_politics_military.6be8c0421008',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Meiji-Restoration',
  ),
  _TimelineFact(
    id: 'scramble_for_africa',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 142,
    displayKey: 'inline.plan295.life.c_1884_ce.13f9817a07b2',
    titleKey: 'inline.plan295.life.scramble_for_africa_and_berlin_confe.8a3cb26d34ff',
    detailKey: 'inline.plan295.life.european_powers_accelerated_colonial.b75586703a34',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Berlin-West-Africa-Conference',
  ),
  _TimelineFact(
    id: 'xinhai_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 115,
    displayKey: 'inline.plan295.life.1911_ce.1b9ed3df75e5',
    titleKey: 'inline.plan295.life.xinhai_revolution.86ada5ebd3fe',
    detailKey: 'inline.plan295.life.the_qing_imperial_order_ended_and_th.073335c48af7',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Chinese-Revolution-1911-1912',
  ),
  _TimelineFact(
    id: 'russian_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 109,
    displayKey: 'inline.plan295.life.1917_ce.52ed81ecc78e',
    titleKey: 'inline.plan295.life.russian_revolution.44c88d2ff2f7',
    detailKey: 'inline.plan295.life.the_russian_empire_collapsed_the_bol.17254cc9a6f7',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Russian-Revolution',
  ),
  _TimelineFact(
    id: 'league_of_nations',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 106,
    displayKey: 'inline.plan295.life.1920_ce.778fd3ce5951',
    titleKey: 'inline.plan295.life.league_of_nations_founded.782488e304fb',
    detailKey: 'inline.plan295.life.after_world_war_i_the_league_of_nati.5998e519c215',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/League-of-Nations',
  ),
  _TimelineFact(
    id: 'india_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 79,
    displayKey: 'inline.plan295.life.1947_ce.55833e8f064f',
    titleKey: 'inline.plan295.life.indian_independence_and_partition.dd4ce01da138',
    detailKey: 'inline.plan295.life.british_india_ended_colonial_rule_an.3709deb9e8dc',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Partition-of-India',
  ),
  _TimelineFact(
    id: 'prc_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 77,
    displayKey: 'inline.plan295.life.1949_ce.e2e1d51bd106',
    titleKey: 'inline.plan295.life.people_s_republic_of_china_founded.473f4d4d2e89',
    detailKey: 'inline.plan295.life.after_the_chinese_civil_war_the_peop.1607b34af165',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/China/Establishment-of-the-Peoples-Republic',
  ),
  _TimelineFact(
    id: 'european_integration',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 69,
    displayKey: 'inline.plan295.life.1957_ce.88f3349331f3',
    titleKey: 'inline.plan295.life.treaty_of_rome_and_european_integrat.3a07b52e83c9',
    detailKey: 'inline.plan295.life.the_european_economic_community_was.7b65e0b36b84',
    sourceNameKey: 'toolbox.life.timeline.source.eu',
    sourceUrl: 'https://european-union.europa.eu/principles-countries-history/history-eu_en',
  ),
  _TimelineFact(
    id: 'ghana_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 69,
    displayKey: 'inline.plan295.life.1957_ce.88f3349331f3',
    titleKey: 'inline.plan295.life.ghana_independence.99f3dce5979f',
    detailKey: 'inline.plan295.life.ghana_became_a_major_independent_sta.10ec2fcf1dde',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Ghana/Independence',
  ),
  _TimelineFact(
    id: 'civil_rights_act',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 62,
    displayKey: 'inline.plan295.life.1964_ce.f07c557ada57',
    titleKey: 'inline.plan295.life.u_s_civil_rights_act.ded179a3bbde',
    detailKey: 'inline.plan295.life.the_u_s_civil_rights_act_banned_disc.ab35fd24ef8a',
    sourceNameKey: 'toolbox.life.timeline.source.archives',
    sourceUrl: 'https://www.archives.gov/milestone-documents/civil-rights-act',
  ),
  _TimelineFact(
    id: 'green_revolution',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 61,
    displayKey: 'inline.plan295.life.c_1960s.9ffd81d8d691',
    titleKey: 'inline.plan295.life.green_revolution.35cf64bbc2c6',
    detailKey: 'inline.plan295.life.high_yield_varieties_fertilizers_irr.81f9beb857eb',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/green-revolution',
  ),
  _TimelineFact(
    id: 'microprocessor',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 55,
    displayKey: 'inline.plan295.life.1971_ce.6ef40c26e13f',
    titleKey: 'inline.plan295.life.commercial_microprocessor_appears.5bfd4718df0b',
    detailKey: 'inline.plan295.life.the_microprocessor_integrated_centra.9967d28e7094',
    sourceNameKey: 'toolbox.life.timeline.source.intel',
    sourceUrl: 'https://www.intel.com/content/www/us/en/history/museum-story-of-intel-4004.html',
  ),
  _TimelineFact(
    id: 'berlin_wall_fall',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 37,
    displayKey: 'inline.plan295.life.1989_ce.e6089f4a90ae',
    titleKey: 'inline.plan295.life.fall_of_the_berlin_wall.80397a965f9d',
    detailKey: 'inline.plan295.life.the_opening_of_the_berlin_wall_symbo.535f197e9820',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Berlin-Wall',
  ),
  _TimelineFact(
    id: 'soviet_union_dissolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 35,
    displayKey: 'inline.plan295.life.1991_ce.a2f898e25798',
    titleKey: 'inline.plan295.life.dissolution_of_the_soviet_union.bf1e693e0f80',
    detailKey: 'inline.plan295.life.the_soviet_union_dissolved_ending_th.219b5b9450b1',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Soviet-Union',
  ),
  _TimelineFact(
    id: 'wto_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 31,
    displayKey: 'inline.plan295.life.1995_ce.cf6d7deafdf5',
    titleKey: 'inline.plan295.life.world_trade_organization_founded.402cde2c22ed',
    detailKey: 'inline.plan295.life.the_wto_established_a_multilateral_t.95a5d5f172d3',
    sourceNameKey: 'toolbox.life.timeline.source.wto',
    sourceUrl: 'https://www.wto.org/english/thewto_e/whatis_e/tif_e/fact4_e.htm',
  ),
  _TimelineFact(
    id: 'smartphone_era',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 19,
    displayKey: 'inline.plan295.life.from_c_2007_ce.4ca5dfc59dba',
    titleKey: 'inline.plan295.life.smartphone_era_expands.8a018eed29e0',
    detailKey: 'inline.plan295.life.multi_touch_smartphones_and_mobile_i.9647ef10672c',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/technology/smartphone',
  ),
  _TimelineFact(
    id: 'crispr_gene_editing',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 14,
    displayKey: 'inline.plan295.life.2012_ce.70e3b2b7be75',
    titleKey: 'inline.plan295.life.crispr_gene_editing_methods_develop.1f34fab69028',
    detailKey: 'inline.plan295.life.crispr_cas9_became_a_major_gene_edit.d0b7d2db064e',
    sourceNameKey: 'toolbox.life.timeline.source.nobel',
    sourceUrl: 'https://www.nobelprize.org/prizes/chemistry/2020/summary/',
  ),
  _TimelineFact(
    id: 'paris_agreement',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 11,
    displayKey: 'inline.plan295.life.2015_ce.e659a08fed94',
    titleKey: 'inline.plan295.life.paris_agreement.66c3ce92015c',
    detailKey: 'inline.plan295.life.countries_adopted_an_international_c.a2e041c540be',
    sourceNameKey: 'toolbox.life.timeline.source.un',
    sourceUrl: 'https://unfccc.int/process-and-meetings/the-paris-agreement',
  ),
  _TimelineFact(
    id: 'covid19_pandemic',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 6,
    displayKey: 'inline.plan295.life.2020_ce.161118241ccf',
    titleKey: 'inline.plan295.life.covid_19_pandemic.4641786024ef',
    detailKey: 'inline.plan295.life.covid_19_became_a_major_public_healt.977460ff3357',
    sourceNameKey: 'toolbox.life.timeline.source.who',
    sourceUrl: 'https://www.who.int/emergencies/diseases/novel-coronavirus-2019',
  ),
  _TimelineFact(
    id: 'generative_ai_public_boom',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 4,
    displayKey: 'inline.plan295.life.from_c_2022_ce.ea142bfe814c',
    titleKey: 'inline.plan295.life.generative_ai_becomes_mainstream.2cac8f3fa526',
    detailKey: 'inline.plan295.life.large_language_models_and_multimodal.ee3db1fbf359',
    sourceNameKey: 'toolbox.life.timeline.source.stanford',
    sourceUrl: 'https://aiindex.stanford.edu/report/',
  ),
  _TimelineFact(
    id: 'acheulean_tools',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 1760000,
    displayKey: 'inline.plan295.life.c_1_76_million_years_ago.1dc71486db1f',
    titleKey: 'inline.plan295.life.acheulean_tool_tradition_appears.c14ff6a5c2e9',
    detailKey: 'inline.plan295.life.hand_axes_and_other_acheulean_tools.5b11d5b14241',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/behavior/stone-tools',
  ),
  _TimelineFact(
    id: 'homo_heidelbergensis',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 700000,
    displayKey: 'inline.plan295.life.c_700_000_years_ago.e9cbff726862',
    titleKey: 'inline.plan295.life.homo_heidelbergensis_evolves.adffddb7a682',
    detailKey: 'inline.plan295.life.homo_heidelbergensis_is_often_treate.eb40d3814940',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-heidelbergensis',
  ),
  _TimelineFact(
    id: 'blombos_symbolic_objects',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 75000,
    displayKey: 'inline.plan295.life.c_75_000_years_ago.6d1bade7fc9d',
    titleKey: 'inline.plan295.life.blombos_cave_symbolic_objects.f47db632623f',
    detailKey: 'inline.plan295.life.engraved_ochre_and_shell_beads_show.9007baa4f0f1',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Blombos-Cave',
  ),
  _TimelineFact(
    id: 'first_australia_settlement',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 65000,
    displayKey: 'inline.plan295.life.c_65_000_years_ago.76bc7326e514',
    titleKey: 'inline.plan295.life.humans_reach_australia.a3636d9e2ada',
    detailKey: 'inline.plan295.life.archaeological_evidence_shows_modern.55029c88cdde',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Australian-Aboriginal',
  ),
  _TimelineFact(
    id: 'lascaux_cave_art',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 17000,
    displayKey: 'inline.plan295.life.c_17_000_years_ago.2b1c51ad1f51',
    titleKey: 'inline.plan295.life.lascaux_cave_paintings.4153c67d93a6',
    detailKey: 'inline.plan295.life.lascaux_is_a_major_upper_paleolithic.af6bf1276e73',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Lascaux-Grotto',
  ),
  _TimelineFact(
    id: 'domestication_dog',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 15000,
    displayKey: 'inline.plan295.life.c_15_000_years_ago.532ba49caa33',
    titleKey: 'inline.plan295.life.dog_domestication_spreads.0a6857b65448',
    detailKey: 'inline.plan295.life.dogs_became_among_the_earliest_domes.b9c19ee4a1c2',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/animal/dog',
  ),
  _TimelineFact(
    id: 'natufian_culture',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 14526,
    displayKey: 'inline.plan295.life.c_12_500_bce.2977702c0d67',
    titleKey: 'inline.plan295.life.natufian_culture_and_semi_sedentism.ae44d76e108f',
    detailKey: 'inline.plan295.life.natufian_culture_in_the_levant_shows.819211ba801f',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Natufian-culture',
  ),
  _TimelineFact(
    id: 'fertile_crescent_farming',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 11526,
    displayKey: 'inline.plan295.life.c_9500_bce.c34979bfdaba',
    titleKey: 'inline.plan295.life.farming_expands_in_the_fertile_cresc.d1cb92e158e2',
    detailKey: 'inline.plan295.life.domesticated_wheat_barley_goats_and.b5bb0ec85b83',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/agriculture',
  ),
  _TimelineFact(
    id: 'rice_domestication',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 10026,
    displayKey: 'inline.plan295.life.c_8000_bce.cf46dab0fbb6',
    titleKey: 'inline.plan295.life.rice_domestication_and_east_asian_fa.9dde5cd5e2e7',
    detailKey: 'inline.plan295.life.rice_farming_developed_in_regions_su.8119fb975b67',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/plant/rice',
  ),
  _TimelineFact(
    id: 'wheel_invention',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5526,
    displayKey: 'inline.plan295.life.c_3500_bce.ef81f130a2be',
    titleKey: 'inline.plan295.life.wheel_and_wheeled_vehicles_appear.bc67c9eda3f8',
    detailKey: 'inline.plan295.life.wheeled_vehicles_and_potter_wheels_c.223c29771d68',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/technology/wheel',
  ),
  _TimelineFact(
    id: 'horse_domestication',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5526,
    displayKey: 'inline.plan295.life.c_3500_bce.ef81f130a2be',
    titleKey: 'inline.plan295.life.horse_domestication_and_steppe_mobil.e5c37132d936',
    detailKey: 'inline.plan295.life.horse_domestication_strengthened_mob.d629f2cd94ec',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/animal/horse',
  ),
  _TimelineFact(
    id: 'pyramids_giza',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4596,
    displayKey: 'inline.plan295.life.c_2570_bce.cb803ecf8cd3',
    titleKey: 'inline.plan295.life.giza_pyramid_complex_built.2cb3c1f535a4',
    detailKey: 'inline.plan295.life.the_giza_pyramids_show_ancient_egypt.a67b243ce1e9',
    sourceNameKey: 'toolbox.life.timeline.source.unesco',
    sourceUrl: 'https://whc.unesco.org/en/list/86/',
  ),
  _TimelineFact(
    id: 'akkadian_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4360,
    displayKey: 'inline.plan295.life.c_2334_bce.15b7b091cfd1',
    titleKey: 'inline.plan295.life.akkadian_empire_rises.52d0e9bd62fb',
    detailKey: 'inline.plan295.life.the_akkadian_empire_is_often_treated.c4cd5a3793a8',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Akkad',
  ),
  _TimelineFact(
    id: 'minoan_civilization',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4026,
    displayKey: 'inline.plan295.life.c_2000_bce.414b215155a6',
    titleKey: 'inline.plan295.life.minoan_palace_civilization.9bb4530c3b17',
    detailKey: 'inline.plan295.life.cretan_palace_centers_and_maritime_n.e03e72c94429',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Minoan-civilization',
  ),
  _TimelineFact(
    id: 'mycenaean_greece',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3626,
    displayKey: 'inline.plan295.life.c_1600_bce.8f39d72f1fea',
    titleKey: 'inline.plan295.life.mycenaean_greece_rises.401e3f9eba08',
    detailKey: 'inline.plan295.life.mycenaean_palaces_linear_b_writing_a.26eece56044d',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Mycenaean-civilization',
  ),
  _TimelineFact(
    id: 'late_bronze_age_collapse',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3226,
    displayKey: 'inline.plan295.life.c_1200_bce.c86e53a5baee',
    titleKey: 'inline.plan295.life.late_bronze_age_collapse.bcb69de8091c',
    detailKey: 'inline.plan295.life.palace_states_across_the_eastern_med.1ed5394aa223',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Bronze-Age',
  ),
  _TimelineFact(
    id: 'phoenician_alphabet',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3076,
    displayKey: 'inline.plan295.life.c_1050_bce.915e303eff79',
    titleKey: 'inline.plan295.life.phoenician_alphabet_spreads.4a1d9fd37ba1',
    detailKey: 'inline.plan295.life.the_phoenician_alphabet_spread_throu.47aa7ca65cb9',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Phoenician-alphabet',
  ),
  _TimelineFact(
    id: 'spring_and_autumn_period',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2796,
    displayKey: 'inline.plan295.life.c_770_bce.209f74263022',
    titleKey: 'inline.plan295.life.spring_and_autumn_period_begins.166fc8d78444',
    detailKey: 'inline.plan295.life.zhou_royal_authority_weakened_as_int.0f4d7e7120af',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Spring-and-Autumn-period',
  ),
  _TimelineFact(
    id: 'first_olympics',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2802,
    displayKey: 'inline.plan295.life.776_bce.50a03597871c',
    titleKey: 'inline.plan295.life.ancient_olympic_games_tradition.1626334bfa74',
    detailKey: 'inline.plan295.life.the_games_at_olympia_became_a_shared.aa6865235939',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/sports/Olympic-Games',
  ),
  _TimelineFact(
    id: 'rome_founding_tradition',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2779,
    displayKey: 'inline.plan295.life.traditional_date_753_bce.a76b4c11cdf1',
    titleKey: 'inline.plan295.life.traditional_founding_of_rome.8c0f4b49e13d',
    detailKey: 'inline.plan295.life.the_founding_tradition_includes_lege.488dedb218e5',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Rome',
  ),
  _TimelineFact(
    id: 'upanishads',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2726,
    displayKey: 'inline.plan295.life.c_700_bce.e47880b05cc0',
    titleKey: 'inline.plan295.life.upanishadic_traditions_form.cff346e58fb7',
    detailKey: 'inline.plan295.life.upanishadic_texts_explored_brahman_a.daa15631fb16',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Upanishad',
  ),
  _TimelineFact(
    id: 'babylonian_exile',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2612,
    displayKey: 'inline.plan295.life.586_bce.0c2277473cdc',
    titleKey: 'inline.plan295.life.babylonian_exile.d05db61a4011',
    detailKey: 'inline.plan295.life.the_fall_of_jerusalem_and_exile_deep.660f2aa02650',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Babylonian-Captivity',
  ),
  _TimelineFact(
    id: 'cyrus_cylinder',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2565,
    displayKey: 'inline.plan295.life.539_bce.13938ee4a464',
    titleKey: 'inline.plan295.life.cyrus_captures_babylon.5710c7770b60',
    detailKey: 'inline.plan295.life.after_cyrus_entered_babylon_the_acha.fa7298e690a2',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Cyrus-the-Great',
  ),
  _TimelineFact(
    id: 'greco_persian_wars',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2525,
    displayKey: 'inline.plan295.life.499_449_bce.18d22da66df7',
    titleKey: 'inline.plan295.life.greco_persian_wars.b5beee6194fe',
    detailKey: 'inline.plan295.life.wars_between_greek_city_states_and_p.6cb850c2afce',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Greco-Persian-Wars',
  ),
  _TimelineFact(
    id: 'peloponnesian_war',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2457,
    displayKey: 'inline.plan295.life.431_404_bce.cb47ed834afd',
    titleKey: 'inline.plan295.life.peloponnesian_war.384840a74e42',
    detailKey: 'inline.plan295.life.the_long_war_between_athenian_and_sp.f5810f342453',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Peloponnesian-War',
  ),
  _TimelineFact(
    id: 'socrates_trial',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2425,
    displayKey: 'inline.plan295.life.399_bce.bb38a2d4ca47',
    titleKey: 'inline.plan295.life.trial_and_death_of_socrates.9dabf8614252',
    detailKey: 'inline.plan295.life.the_death_of_socrates_became_a_key_s.9d9916b732c0',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Socrates',
  ),
  _TimelineFact(
    id: 'alexander_conquests',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2360,
    displayKey: 'inline.plan295.life.from_334_bce.5dff2e522d35',
    titleKey: 'inline.plan295.life.alexander_conquests_begin.a54efa2cd071',
    detailKey: 'inline.plan295.life.macedonian_expansion_linked_the_east.c0a766778b7f',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Alexander-the-Great',
  ),
  _TimelineFact(
    id: 'punic_wars',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2290,
    displayKey: 'inline.plan295.life.264_146_bce.700ac3eaa4a5',
    titleKey: 'inline.plan295.life.punic_wars.37476b02fb5f',
    detailKey: 'inline.plan295.life.the_wars_between_rome_and_carthage_e.e79073766392',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Punic-Wars',
  ),
  _TimelineFact(
    id: 'silk_road_han',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2156,
    displayKey: 'inline.plan295.life.c_130_bce.075aba7e590b',
    titleKey: 'inline.plan295.life.silk_road_overland_exchange_expands.2ef893325f8b',
    detailKey: 'inline.plan295.life.han_westward_routes_joined_central_a.d6c7a4e7a540',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Silk-Road-trade-route',
  ),
  _TimelineFact(
    id: 'caesar_assassination',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2070,
    displayKey: 'inline.plan295.life.44_bce.f74bebb5cacd',
    titleKey: 'inline.plan295.life.assassination_of_julius_caesar.49bf6b0385b7',
    detailKey: 'inline.plan295.life.caesar_assassination_intensified_the.6dfcd7d751f9',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Julius-Caesar-Roman-ruler',
  ),
  _TimelineFact(
    id: 'second_temple_destroyed',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1956,
    displayKey: 'inline.plan295.life.70_ce.ca50fd7ec6d4',
    titleKey: 'inline.plan295.life.second_temple_destroyed.7ddf56d36d91',
    detailKey: 'inline.plan295.life.roman_forces_captured_jerusalem_and.4ad3671ddf2b',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Siege-of-Jerusalem-70',
  ),
  _TimelineFact(
    id: 'kushan_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1926,
    displayKey: 'inline.plan295.life.c_1st_century_ce.a0304d3ce50e',
    titleKey: 'inline.plan295.life.kushan_empire_links_eurasian_exchang.93b0231d2b23',
    detailKey: 'inline.plan295.life.the_kushan_empire_controlled_key_cen.7499e24a2b5e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Kushan-dynasty',
  ),
  _TimelineFact(
    id: 'three_kingdoms_china',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1806,
    displayKey: 'inline.plan295.life.220_ce.1f0dcb5169ef',
    titleKey: 'inline.plan295.life.three_kingdoms_period_begins_in_chin.d1ae8b583f7c',
    detailKey: 'inline.plan295.life.after_the_han_wei_shu_and_wu_shaped.5111fd81cbe4',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Three-Kingdoms',
  ),
  _TimelineFact(
    id: 'edict_of_milan',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1713,
    displayKey: 'inline.plan295.life.313_ce.63a6a54cb43b',
    titleKey: 'inline.plan295.life.edict_of_milan.985c802d86c7',
    detailKey: 'inline.plan295.life.constantine_and_licinius_recognized.aa7fa43e8fd4',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Edict-of-Milan',
  ),
  _TimelineFact(
    id: 'council_of_nicaea',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1701,
    displayKey: 'inline.plan295.life.325_ce.073ebe4fc829',
    titleKey: 'inline.plan295.life.first_council_of_nicaea.d85c55c959b1',
    detailKey: 'inline.plan295.life.nicaea_addressed_christological_disp.8f377a230806',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/First-Council-of-Nicaea-325',
  ),
  _TimelineFact(
    id: 'gupta_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1706,
    displayKey: 'inline.plan295.life.c_320_ce.060cf194f91c',
    titleKey: 'inline.plan295.life.gupta_empire_rises.988d038d9102',
    detailKey: 'inline.plan295.life.the_gupta_era_saw_major_developments.eff96b58bcb6',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Gupta-dynasty',
  ),
  _TimelineFact(
    id: 'western_rome_falls',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1550,
    displayKey: 'inline.plan295.life.476_ce.e7979b07ed20',
    titleKey: 'inline.plan295.life.western_roman_empire_ends.6ee4625a1091',
    detailKey: 'inline.plan295.life.the_deposition_of_the_western_empero.930268937b10',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Roman-Empire',
  ),
  _TimelineFact(
    id: 'justinian_code',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1497,
    displayKey: 'inline.plan295.life.529_ce.ec7c76b36a14',
    titleKey: 'inline.plan295.life.code_of_justinian_compiled.2744f387542e',
    detailKey: 'inline.plan295.life.the_byzantine_codification_organized.5197f5d1ce98',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Code-of-Justinian',
  ),
  _TimelineFact(
    id: 'sui_reunification',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1437,
    displayKey: 'inline.plan295.life.589_ce.47734f2fcd01',
    titleKey: 'inline.plan295.life.sui_reunification_of_china.e26de9dc2eaa',
    detailKey: 'inline.plan295.life.the_sui_ended_long_north_south_divis.36403adbc65a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Sui-dynasty',
  ),
  _TimelineFact(
    id: 'umayyad_caliphate',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1365,
    displayKey: 'inline.plan295.life.661_ce.2d28ceafaa22',
    titleKey: 'inline.plan295.life.umayyad_caliphate_begins.da48cd08cf61',
    detailKey: 'inline.plan295.life.the_umayyads_expanded_and_administer.c49fa0f38f54',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Umayyad-dynasty-Islamic-history',
  ),
  _TimelineFact(
    id: 'abbasid_baghdad',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1276,
    displayKey: 'inline.plan295.life.750_762_ce.483407fcbffb',
    titleKey: 'inline.plan295.life.abbasid_revolution_and_baghdad.8ee816dbd32c',
    detailKey: 'inline.plan295.life.the_abbasids_founded_baghdad_and_reo.5c7ba1dd8f17',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Abbasid-dynasty',
  ),
];
