part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _denseModernTimelineFacts = <_TimelineFact>[
  _TimelineFact(
    id: 'mughal_empire',
    category: 'modern',
    yearsBeforePresent: 500,
    displayZh: '1526 年',
    displayEn: '1526 CE',
    titleZh: '莫卧儿帝国建立',
    titleEn: 'Mughal Empire begins',
    detailZh: '巴布尔在北印度建立莫卧儿帝国，后续形成南亚重要的帝国行政、艺术和建筑传统。',
    detailEn:
        'Babur founded the Mughal Empire in North India, later shaping South Asian administration, art, and architecture.',
    sourceName: 'Britannica: Mughal dynasty',
    sourceUrl: 'https://www.britannica.com/place/Mughal-dynasty',
  ),
  _TimelineFact(
    id: 'east_india_company',
    category: 'modern',
    yearsBeforePresent: 426,
    displayZh: '1600 年',
    displayEn: '1600 CE',
    titleZh: '英国东印度公司成立',
    titleEn: 'English East India Company founded',
    detailZh: '特许贸易公司成为早期现代商业帝国、殖民治理和全球商品网络的重要载体。',
    detailEn:
        'A chartered trading company became a vehicle of commercial empire, colonial governance, and global commodity networks.',
    sourceName: 'Britannica: East India Company',
    sourceUrl: 'https://www.britannica.com/topic/East-India-Company',
  ),
  _TimelineFact(
    id: 'tokugawa_shogunate',
    category: 'modern',
    yearsBeforePresent: 423,
    displayZh: '1603 年',
    displayEn: '1603 CE',
    titleZh: '德川幕府建立',
    titleEn: 'Tokugawa shogunate begins',
    detailZh: '江户时代开始，日本进入长期和平、城镇经济扩张和严格身份秩序并存的时期。',
    detailEn:
        'The Edo period began, combining long peace, urban economic growth, and structured social status orders.',
    sourceName: 'Britannica: Tokugawa period',
    sourceUrl: 'https://www.britannica.com/event/Tokugawa-period',
  ),
  _TimelineFact(
    id: 'english_civil_war',
    category: 'modern',
    yearsBeforePresent: 384,
    displayZh: '1642-1651 年',
    displayEn: '1642-1651 CE',
    titleZh: '英国内战',
    titleEn: 'English Civil Wars',
    detailZh: '王权、议会、宗教和军队之间的冲突改变英格兰政治制度和宪政传统。',
    detailEn:
        'Conflict among crown, Parliament, religion, and army transformed English politics and constitutional tradition.',
    sourceName: 'Britannica: English Civil Wars',
    sourceUrl: 'https://www.britannica.com/event/English-Civil-Wars',
  ),
  _TimelineFact(
    id: 'glorious_revolution',
    category: 'modern',
    yearsBeforePresent: 338,
    displayZh: '1688 年',
    displayEn: '1688 CE',
    titleZh: '光荣革命',
    titleEn: 'Glorious Revolution',
    detailZh: '英国王权与议会关系重组，权利法案和君主立宪传统获得关键制度基础。',
    detailEn:
        'Relations between crown and Parliament were reorganized, strengthening constitutional monarchy traditions.',
    sourceName: 'Britannica: Glorious Revolution',
    sourceUrl: 'https://www.britannica.com/event/Glorious-Revolution',
  ),
  _TimelineFact(
    id: 'seven_years_war',
    category: 'modern',
    yearsBeforePresent: 270,
    displayZh: '1756-1763 年',
    displayEn: '1756-1763 CE',
    titleZh: '七年战争',
    titleEn: 'Seven Years War',
    detailZh: '欧洲、北美、印度和海上战场相互连接，重塑英法殖民竞争和财政压力。',
    detailEn:
        'Connected theaters in Europe, North America, India, and at sea reshaped imperial competition and state finance.',
    sourceName: 'Britannica: Seven Years War',
    sourceUrl: 'https://www.britannica.com/event/Seven-Years-War',
  ),
  _TimelineFact(
    id: 'american_declaration',
    category: 'modern',
    yearsBeforePresent: 250,
    displayZh: '1776 年',
    displayEn: '1776 CE',
    titleZh: '美国《独立宣言》',
    titleEn: 'U.S. Declaration of Independence',
    detailZh: '北美十三州宣布脱离英国，启发现代共和国、主权和革命政治的新实验。',
    detailEn:
        'The thirteen colonies declared separation from Britain, launching a modern republican and revolutionary experiment.',
    sourceName: 'U.S. National Archives: Declaration',
    sourceUrl: 'https://www.archives.gov/founding-docs/declaration',
  ),
  _TimelineFact(
    id: 'french_revolution',
    category: 'modern',
    yearsBeforePresent: 237,
    displayZh: '1789 年',
    displayEn: '1789 CE',
    titleZh: '法国大革命爆发',
    titleEn: 'French Revolution begins',
    detailZh: '革命挑战旧制度等级和君主权威，推动公民权、民族国家和群众政治扩散。',
    detailEn:
        'The revolution challenged old-regime hierarchy and monarchy, spreading citizenship, nationalism, and mass politics.',
    sourceName: 'Britannica: French Revolution',
    sourceUrl: 'https://www.britannica.com/event/French-Revolution',
  ),
  _TimelineFact(
    id: 'napoleonic_wars',
    category: 'modern',
    yearsBeforePresent: 223,
    displayZh: '1803-1815 年',
    displayEn: '1803-1815 CE',
    titleZh: '拿破仑战争',
    titleEn: 'Napoleonic Wars',
    detailZh: '法国革命战争扩展为欧洲大陆体系重组，影响法律、行政、民族主义和国际秩序。',
    detailEn:
        'The wars reorganized European power and affected law, administration, nationalism, and international order.',
    sourceName: 'Britannica: Napoleonic Wars',
    sourceUrl: 'https://www.britannica.com/event/Napoleonic-Wars',
  ),
  _TimelineFact(
    id: 'congress_vienna',
    category: 'modern',
    yearsBeforePresent: 211,
    displayZh: '1815 年',
    displayEn: '1815 CE',
    titleZh: '维也纳会议',
    titleEn: 'Congress of Vienna',
    detailZh: '欧洲列强重建均势体系，形成 19 世纪国际会议外交的重要基础。',
    detailEn:
        'European powers rebuilt a balance-of-power system and a major basis for nineteenth-century conference diplomacy.',
    sourceName: 'Britannica: Congress of Vienna',
    sourceUrl: 'https://www.britannica.com/event/Congress-of-Vienna',
  ),
  _TimelineFact(
    id: 'revolutions_1848',
    category: 'modern',
    yearsBeforePresent: 178,
    displayZh: '1848 年',
    displayEn: '1848 CE',
    titleZh: '1848 年欧洲革命',
    titleEn: 'Revolutions of 1848',
    detailZh: '民族主义、自由主义和社会诉求在欧洲多地爆发，显示工业时代政治动员扩展。',
    detailEn:
        'Nationalist, liberal, and social demands erupted across Europe, showing expanded industrial-age mobilization.',
    sourceName: 'Britannica: Revolutions of 1848',
    sourceUrl: 'https://www.britannica.com/event/Revolutions-of-1848',
  ),
  _TimelineFact(
    id: 'communist_manifesto',
    category: 'modern',
    yearsBeforePresent: 178,
    displayZh: '1848 年',
    displayEn: '1848 CE',
    titleZh: '《共产党宣言》出版',
    titleEn: 'The Communist Manifesto published',
    detailZh: '马克思和恩格斯的小册子成为社会主义运动、阶级政治和现代思想史的重要文本。',
    detailEn:
        'The pamphlet by Marx and Engels became a major text in socialism, class politics, and modern intellectual history.',
    sourceName: 'Britannica: The Communist Manifesto',
    sourceUrl: 'https://www.britannica.com/topic/The-Communist-Manifesto',
  ),
  _TimelineFact(
    id: 'indian_rebellion',
    category: 'modern',
    yearsBeforePresent: 169,
    displayZh: '1857 年',
    displayEn: '1857 CE',
    titleZh: '印度民族大起义',
    titleEn: 'Indian Rebellion of 1857',
    detailZh: '反英起义后，英国东印度公司统治终结，英属印度转入王冠直接治理。',
    detailEn:
        'After the anti-British rebellion, Company rule ended and British India moved under direct Crown rule.',
    sourceName: 'Britannica: Indian Mutiny',
    sourceUrl: 'https://www.britannica.com/event/Indian-Mutiny',
  ),
  _TimelineFact(
    id: 'american_civil_war',
    category: 'modern',
    yearsBeforePresent: 165,
    displayZh: '1861-1865 年',
    displayEn: '1861-1865 CE',
    titleZh: '美国内战',
    titleEn: 'American Civil War',
    detailZh: '战争围绕联邦、奴隶制和国家未来展开，最终推动奴隶制废除和美国国家重构。',
    detailEn:
        'The war over Union, slavery, and national future led to abolition and a reconstruction of the United States.',
    sourceName: 'Britannica: American Civil War',
    sourceUrl: 'https://www.britannica.com/event/American-Civil-War',
  ),
  _TimelineFact(
    id: 'suez_canal',
    category: 'modern',
    yearsBeforePresent: 157,
    displayZh: '1869 年',
    displayEn: '1869 CE',
    titleZh: '苏伊士运河通航',
    titleEn: 'Suez Canal opens',
    detailZh: '运河连接地中海和红海，大幅改变欧亚海运、帝国战略和全球贸易路径。',
    detailEn:
        'The canal linked the Mediterranean and Red Sea, changing Eurasian shipping, imperial strategy, and trade routes.',
    sourceName: 'Britannica: Suez Canal',
    sourceUrl: 'https://www.britannica.com/topic/Suez-Canal',
  ),
  _TimelineFact(
    id: 'german_unification',
    category: 'modern',
    yearsBeforePresent: 155,
    displayZh: '1871 年',
    displayEn: '1871 CE',
    titleZh: '德意志帝国成立',
    titleEn: 'German unification',
    detailZh: '普鲁士主导德意志统一，欧洲大国体系和工业军事竞争格局随之改变。',
    detailEn:
        'Prussia-led unification changed European great-power politics and industrial-military competition.',
    sourceName: 'Britannica: German Empire',
    sourceUrl: 'https://www.britannica.com/place/German-Empire',
  ),
  _TimelineFact(
    id: 'wright_brothers',
    category: 'science',
    yearsBeforePresent: 123,
    displayZh: '1903 年',
    displayEn: '1903 CE',
    titleZh: '莱特兄弟动力飞行',
    titleEn: 'Wright brothers powered flight',
    detailZh: '受控动力飞行成功开启航空技术时代，改变战争、交通、贸易和全球感知。',
    detailEn:
        'Controlled powered flight opened the aviation age, changing war, transport, commerce, and global perception.',
    sourceName: 'Britannica: Wright brothers',
    sourceUrl: 'https://www.britannica.com/biography/Wright-brothers',
  ),
  _TimelineFact(
    id: 'world_war_i',
    category: 'modern',
    yearsBeforePresent: 112,
    displayZh: '1914-1918 年',
    displayEn: '1914-1918 CE',
    titleZh: '第一次世界大战',
    titleEn: 'World War I',
    detailZh: '工业化总体战摧毁多个帝国，重塑边界、社会动员和国际政治语言。',
    detailEn:
        'Industrial total war destroyed empires and reshaped borders, mass mobilization, and international politics.',
    sourceName: 'Britannica: World War I',
    sourceUrl: 'https://www.britannica.com/event/World-War-I',
  ),
  _TimelineFact(
    id: 'influenza_1918',
    category: 'modern',
    yearsBeforePresent: 108,
    displayZh: '1918-1919 年',
    displayEn: '1918-1919 CE',
    titleZh: '1918 年流感大流行',
    titleEn: '1918 influenza pandemic',
    detailZh: '全球流感大流行造成巨大死亡，成为现代公共卫生和流行病史的重要参照。',
    detailEn:
        'The global influenza pandemic caused massive mortality and became a major reference in modern public health.',
    sourceName: 'CDC: 1918 pandemic',
    sourceUrl:
        'https://www.cdc.gov/flu/pandemic-resources/1918-pandemic-h1n1.html',
  ),
  _TimelineFact(
    id: 'treaty_versailles',
    category: 'modern',
    yearsBeforePresent: 107,
    displayZh: '1919 年',
    displayEn: '1919 CE',
    titleZh: '凡尔赛条约',
    titleEn: 'Treaty of Versailles',
    detailZh: '一战后和约重划欧洲和殖民秩序，同时留下赔款、安全和民族问题争议。',
    detailEn:
        'The postwar treaty redrew Europe and colonial order while leaving disputes over reparations, security, and nationalism.',
    sourceName: 'Britannica: Treaty of Versailles',
    sourceUrl: 'https://www.britannica.com/event/Treaty-of-Versailles-1919',
  ),
  _TimelineFact(
    id: 'great_depression',
    category: 'modern',
    yearsBeforePresent: 97,
    displayZh: '1929 年起',
    displayEn: 'from 1929 CE',
    titleZh: '大萧条',
    titleEn: 'Great Depression',
    detailZh: '全球经济危机冲击工业社会、贸易、金融和政治制度，推动国家干预政策扩展。',
    detailEn:
        'The global economic crisis disrupted industry, trade, finance, and politics, expanding state intervention.',
    sourceName: 'Britannica: Great Depression',
    sourceUrl: 'https://www.britannica.com/event/Great-Depression',
  ),
  _TimelineFact(
    id: 'nazi_power',
    category: 'modern',
    yearsBeforePresent: 93,
    displayZh: '1933 年',
    displayEn: '1933 CE',
    titleZh: '纳粹党掌权',
    titleEn: 'Nazi Party takes power',
    detailZh: '希特勒出任德国总理后，民主制度迅速瓦解，极权统治和侵略政策展开。',
    detailEn:
        'After Hitler became German chancellor, democracy collapsed rapidly and totalitarian rule and aggression expanded.',
    sourceName: 'Britannica: Nazi Party',
    sourceUrl: 'https://www.britannica.com/topic/Nazi-Party',
  ),
  _TimelineFact(
    id: 'world_war_ii',
    category: 'modern',
    yearsBeforePresent: 87,
    displayZh: '1939-1945 年',
    displayEn: '1939-1945 CE',
    titleZh: '第二次世界大战',
    titleEn: 'World War II',
    detailZh: '全球战争造成巨大伤亡，重塑国际秩序、殖民体系、科技发展和集体安全制度。',
    detailEn:
        'The global war caused immense casualties and reshaped international order, colonial systems, technology, and security institutions.',
    sourceName: 'Britannica: World War II',
    sourceUrl: 'https://www.britannica.com/event/World-War-II',
  ),
  _TimelineFact(
    id: 'holocaust',
    category: 'modern',
    yearsBeforePresent: 85,
    displayZh: '1941-1945 年',
    displayEn: '1941-1945 CE',
    titleZh: '纳粹大屠杀',
    titleEn: 'The Holocaust',
    detailZh: '纳粹德国及其合作者系统性屠杀欧洲犹太人和其他受迫害群体，是现代史重大罪行。',
    detailEn:
        'Nazi Germany and collaborators systematically murdered European Jews and other persecuted groups.',
    sourceName: 'Britannica: Holocaust',
    sourceUrl: 'https://www.britannica.com/event/Holocaust',
  ),
  _TimelineFact(
    id: 'bretton_woods',
    category: 'modern',
    yearsBeforePresent: 82,
    displayZh: '1944 年',
    displayEn: '1944 CE',
    titleZh: '布雷顿森林会议',
    titleEn: 'Bretton Woods Conference',
    detailZh: '会议奠定战后国际货币金融机构框架，推动 IMF 和世界银行体系形成。',
    detailEn:
        'The conference laid foundations for postwar monetary institutions, including the IMF and World Bank system.',
    sourceName: 'Britannica: Bretton Woods Conference',
    sourceUrl: 'https://www.britannica.com/event/Bretton-Woods-Conference',
  ),
  _TimelineFact(
    id: 'atomic_bombings',
    category: 'science',
    yearsBeforePresent: 81,
    displayZh: '1945 年',
    displayEn: '1945 CE',
    titleZh: '广岛与长崎原子弹爆炸',
    titleEn: 'Atomic bombings of Hiroshima and Nagasaki',
    detailZh: '核武器首次用于战争，开启核时代并深刻改变国际安全、伦理和科技治理。',
    detailEn:
        'Nuclear weapons were used in war for the first time, opening the nuclear age and transforming security ethics.',
    sourceName: 'Britannica: atomic bombings',
    sourceUrl:
        'https://www.britannica.com/event/atomic-bombings-of-Hiroshima-and-Nagasaki',
  ),
  _TimelineFact(
    id: 'universal_declaration_human_rights',
    category: 'modern',
    yearsBeforePresent: 78,
    displayZh: '1948 年',
    displayEn: '1948 CE',
    titleZh: '《世界人权宣言》通过',
    titleEn: 'Universal Declaration of Human Rights',
    detailZh: '联合国大会通过宣言，形成战后国际人权语言和制度建设的重要基础。',
    detailEn:
        'The UN General Assembly adopted the declaration, grounding postwar international human-rights language.',
    sourceName: 'UN: Universal Declaration of Human Rights',
    sourceUrl:
        'https://www.un.org/en/about-us/universal-declaration-of-human-rights',
  ),
  _TimelineFact(
    id: 'nato_founded',
    category: 'modern',
    yearsBeforePresent: 77,
    displayZh: '1949 年',
    displayEn: '1949 CE',
    titleZh: '北大西洋公约组织成立',
    titleEn: 'NATO founded',
    detailZh: '北约成为冷战西方集体防务体系核心机构，并持续影响跨大西洋安全安排。',
    detailEn:
        'NATO became the core western collective-defense organization of the Cold War and later transatlantic security.',
    sourceName: 'NATO: founding treaty',
    sourceUrl: 'https://www.nato.int/cps/en/natohq/topics_52044.htm',
  ),
  _TimelineFact(
    id: 'korean_war',
    category: 'modern',
    yearsBeforePresent: 76,
    displayZh: '1950-1953 年',
    displayEn: '1950-1953 CE',
    titleZh: '朝鲜战争',
    titleEn: 'Korean War',
    detailZh: '战争成为冷战亚洲格局的重要节点，朝鲜半岛分裂和军事安全结构延续至今。',
    detailEn:
        'The war became a major Cold War node in Asia, entrenching Korean division and regional security structures.',
    sourceName: 'Britannica: Korean War',
    sourceUrl: 'https://www.britannica.com/event/Korean-War',
  ),
  _TimelineFact(
    id: 'bandung_conference',
    category: 'modern',
    yearsBeforePresent: 71,
    displayZh: '1955 年',
    displayEn: '1955 CE',
    titleZh: '万隆会议',
    titleEn: 'Bandung Conference',
    detailZh: '亚非国家会议推动反殖民、和平共处和不结盟政治语言的形成。',
    detailEn:
        'The Asian-African conference advanced anticolonial, peaceful-coexistence, and nonaligned political language.',
    sourceName: 'Britannica: Bandung Conference',
    sourceUrl: 'https://www.britannica.com/event/Bandung-Conference',
  ),
  _TimelineFact(
    id: 'sputnik',
    category: 'science',
    yearsBeforePresent: 69,
    displayZh: '1957 年',
    displayEn: '1957 CE',
    titleZh: '斯普特尼克一号发射',
    titleEn: 'Sputnik 1 launched',
    detailZh: '第一颗人造地球卫星开启太空时代，并加速冷战科技、教育和航天竞争。',
    detailEn:
        'The first artificial satellite opened the space age and accelerated Cold War science and education competition.',
    sourceName: 'NASA: Sputnik',
    sourceUrl: 'https://www.nasa.gov/history/sputnik/',
  ),
  _TimelineFact(
    id: 'year_of_africa',
    category: 'modern',
    yearsBeforePresent: 66,
    displayZh: '1960 年',
    displayEn: '1960 CE',
    titleZh: '非洲独立年',
    titleEn: 'Year of Africa',
    detailZh: '多国在 1960 年独立，非洲去殖民化进入高潮并重塑联合国成员结构。',
    detailEn:
        'Many African states became independent in 1960, accelerating decolonization and reshaping UN membership.',
    sourceName: 'UN: decolonization',
    sourceUrl: 'https://www.un.org/dppa/decolonization/en/history',
  ),
  _TimelineFact(
    id: 'cuban_missile_crisis',
    category: 'modern',
    yearsBeforePresent: 64,
    displayZh: '1962 年',
    displayEn: '1962 CE',
    titleZh: '古巴导弹危机',
    titleEn: 'Cuban Missile Crisis',
    detailZh: '美苏核对峙达到危险高峰，危机后军控沟通和核风险管理机制加强。',
    detailEn:
        'U.S.-Soviet nuclear confrontation peaked dangerously, later strengthening arms-control communication and risk management.',
    sourceName: 'Office of the Historian: Cuban Missile Crisis',
    sourceUrl:
        'https://history.state.gov/milestones/1961-1968/cuban-missile-crisis',
  ),
  _TimelineFact(
    id: 'arpanet',
    category: 'science',
    yearsBeforePresent: 57,
    displayZh: '1969 年',
    displayEn: '1969 CE',
    titleZh: 'ARPANET 首次连接',
    titleEn: 'ARPANET first connection',
    detailZh: '早期分组交换网络连接研究机构，成为互联网技术谱系中的关键实验。',
    detailEn:
        'The early packet-switching network connected research institutions and became a key experiment in Internet history.',
    sourceName: 'DARPA: ARPANET',
    sourceUrl: 'https://www.darpa.mil/about-us/timeline/arpanet',
  ),
  _TimelineFact(
    id: 'un_resolution_2758',
    category: 'modern',
    yearsBeforePresent: 55,
    displayZh: '1971 年',
    displayEn: '1971 CE',
    titleZh: '联合国大会第 2758 号决议',
    titleEn: 'UN General Assembly Resolution 2758',
    detailZh: '该决议改变中国在联合国的代表权安排，成为 20 世纪国际组织史的重要节点。',
    detailEn:
        'The resolution changed China representation arrangements at the UN, a major institutional moment in twentieth-century diplomacy.',
    sourceName: 'UN Digital Library: Resolution 2758',
    sourceUrl: 'https://digitallibrary.un.org/record/192054',
  ),
  _TimelineFact(
    id: 'oil_crisis_1973',
    category: 'modern',
    yearsBeforePresent: 53,
    displayZh: '1973 年',
    displayEn: '1973 CE',
    titleZh: '第一次石油危机',
    titleEn: '1973 oil crisis',
    detailZh: '油价冲击改变能源安全、通胀、工业政策和全球南北经济关系。',
    detailEn:
        'The oil shock changed energy security, inflation, industrial policy, and global economic relationships.',
    sourceName: 'Britannica: oil crisis',
    sourceUrl: 'https://www.britannica.com/event/oil-crisis',
  ),
  _TimelineFact(
    id: 'china_reform_opening',
    category: 'modern',
    yearsBeforePresent: 48,
    displayZh: '1978 年起',
    displayEn: 'from 1978 CE',
    titleZh: '中国改革开放启动',
    titleEn: 'China reform and opening begins',
    detailZh: '经济政策转向市场化、开放和工业化，加速中国社会经济结构与全球贸易联系变化。',
    detailEn:
        'Policy shifted toward markets, opening, and industrialization, accelerating China economic and global trade transformation.',
    sourceName: 'Britannica: China economic policy',
    sourceUrl: 'https://www.britannica.com/place/China/Economic-policy-changes',
  ),
  _TimelineFact(
    id: 'iranian_revolution',
    category: 'modern',
    yearsBeforePresent: 47,
    displayZh: '1979 年',
    displayEn: '1979 CE',
    titleZh: '伊朗革命',
    titleEn: 'Iranian Revolution',
    detailZh: '巴列维王朝结束，伊朗伊斯兰共和国建立，西亚政治和国际关系格局改变。',
    detailEn:
        'The Pahlavi monarchy ended and the Islamic Republic was founded, changing West Asian and global politics.',
    sourceName: 'Britannica: Iranian Revolution',
    sourceUrl: 'https://www.britannica.com/event/Iranian-Revolution',
  ),
  _TimelineFact(
    id: 'chernobyl',
    category: 'science',
    yearsBeforePresent: 40,
    displayZh: '1986 年',
    displayEn: '1986 CE',
    titleZh: '切尔诺贝利核事故',
    titleEn: 'Chernobyl nuclear accident',
    detailZh: '核电站事故造成长期环境和健康影响，也改变核安全、透明度和风险治理实践。',
    detailEn:
        'The accident caused long-term environmental and health impacts and changed nuclear safety and risk governance.',
    sourceName: 'IAEA: Chornobyl',
    sourceUrl: 'https://www.iaea.org/topics/chornobyl',
  ),
  _TimelineFact(
    id: 'apartheid_ends',
    category: 'modern',
    yearsBeforePresent: 32,
    displayZh: '1994 年',
    displayEn: '1994 CE',
    titleZh: '南非种族隔离制度终结',
    titleEn: 'Apartheid ends in South Africa',
    detailZh: '南非举行首次多族群普选，种族隔离制度正式结束，民主转型开启。',
    detailEn:
        'South Africa held its first multiracial election, formally ending apartheid and beginning democratic transition.',
    sourceName: 'Britannica: apartheid',
    sourceUrl: 'https://www.britannica.com/event/apartheid',
  ),
  _TimelineFact(
    id: 'september_11_attacks',
    category: 'modern',
    yearsBeforePresent: 25,
    displayZh: '2001 年',
    displayEn: '2001 CE',
    titleZh: '9·11 袭击',
    titleEn: 'September 11 attacks',
    detailZh: '袭击改变美国和全球安全政策，推动反恐战争、航空安检和国际情报合作扩展。',
    detailEn:
        'The attacks changed U.S. and global security policy, expanding counterterrorism, aviation security, and intelligence cooperation.',
    sourceName: 'Britannica: September 11 attacks',
    sourceUrl: 'https://www.britannica.com/event/September-11-attacks',
  ),
  _TimelineFact(
    id: 'china_wto_accession',
    category: 'modern',
    yearsBeforePresent: 25,
    displayZh: '2001 年',
    displayEn: '2001 CE',
    titleZh: '中国加入世界贸易组织',
    titleEn: 'China joins the WTO',
    detailZh: '中国加入 WTO 后深度接入多边贸易体系，影响全球制造、供应链和消费市场。',
    detailEn:
        'China WTO accession deepened integration into multilateral trade, affecting global manufacturing, supply chains, and markets.',
    sourceName: 'WTO: China member profile',
    sourceUrl: 'https://www.wto.org/english/thewto_e/countries_e/china_e.htm',
  ),
  _TimelineFact(
    id: 'global_financial_crisis_2008',
    category: 'modern',
    yearsBeforePresent: 18,
    displayZh: '2008 年',
    displayEn: '2008 CE',
    titleZh: '全球金融危机',
    titleEn: 'Global financial crisis',
    detailZh: '美国次贷危机扩散为全球金融冲击，改变监管、货币政策和公众对金融风险的认识。',
    detailEn:
        'The U.S. subprime crisis spread globally, changing regulation, monetary policy, and public views of financial risk.',
    sourceName: 'Britannica: financial crisis of 2007-2008',
    sourceUrl: 'https://www.britannica.com/event/financial-crisis-of-2007-2008',
  ),
  _TimelineFact(
    id: 'arab_spring',
    category: 'modern',
    yearsBeforePresent: 16,
    displayZh: '2010-2011 年',
    displayEn: '2010-2011 CE',
    titleZh: '阿拉伯之春',
    titleEn: 'Arab Spring',
    detailZh: '西亚北非多国抗议和政权危机显示数字传播、青年失业和政治改革压力交织。',
    detailEn:
        'Protests and regime crises across MENA showed intertwined digital communication, youth unemployment, and reform pressure.',
    sourceName: 'Britannica: Arab Spring',
    sourceUrl: 'https://www.britannica.com/event/Arab-Spring',
  ),
  _TimelineFact(
    id: 'higgs_boson',
    category: 'science',
    yearsBeforePresent: 14,
    displayZh: '2012 年',
    displayEn: '2012 CE',
    titleZh: '希格斯玻色子发现',
    titleEn: 'Higgs boson discovered',
    detailZh: '欧洲核子研究中心实验确认希格斯玻色子，完善粒子物理标准模型的关键环节。',
    detailEn:
        'CERN experiments confirmed the Higgs boson, a key piece of the Standard Model of particle physics.',
    sourceName: 'CERN: Higgs boson',
    sourceUrl: 'https://home.cern/science/physics/higgs-boson',
  ),
  _TimelineFact(
    id: 'jwst_first_images',
    category: 'science',
    yearsBeforePresent: 4,
    displayZh: '2022 年',
    displayEn: '2022 CE',
    titleZh: '詹姆斯·韦布空间望远镜首批图像',
    titleEn: 'JWST first images',
    detailZh: '韦布望远镜首批科学图像展示深空、星云和系外行星观测能力，开启红外天文学新阶段。',
    detailEn:
        'JWST first science images showed deep-field, nebula, and exoplanet capabilities, opening a new infrared astronomy phase.',
    sourceName: 'NASA: Webb first images',
    sourceUrl:
        'https://www.nasa.gov/image-article/nasas-webb-delivers-deepest-infrared-image-of-universe-yet/',
  ),
];
