part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _legacyTimelineFacts01 = <_TimelineFact>[
  _TimelineFact(
    id: 'big_bang',
    collection: 'general',
    category: 'cosmic',
    yearsBeforePresent: 13800000000,
    displayKey: 'inline.plan297.life.c_13_8_billion_years_ago.7be0c38b2237',
    titleKey: 'inline.plan297.life.hot_big_bang_era_of_the_observable_universe.c44c3e48fccd',
    detailKey: 'inline.plan297.life.modern_cosmology_places_the_hot_dense_early_stat.27acefcef07b',
    sourceNameKey: 'toolbox.life.timeline.source.nasa',
    sourceUrl: 'https://science.nasa.gov/universe/',
  ),
  _TimelineFact(
    id: 'earth_forms',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 4540000000,
    displayKey: 'inline.plan297.life.c_4_54_billion_years_ago.3e92a42c6c11',
    titleKey: 'inline.plan297.life.earth_forms.3a01ebc4fbb3',
    detailKey: 'inline.plan297.life.radiometric_dating_and_meteorite_evidence_suppor.93da1e1fd6c3',
    sourceNameKey: 'toolbox.life.timeline.source.usgs',
    sourceUrl: 'https://www.usgs.gov/faqs/how-old-earth',
  ),
  _TimelineFact(
    id: 'first_life',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 3500000000,
    displayKey: 'inline.plan297.life.c_3_5_billion_years_ago.99b0f19ad58c',
    titleKey: 'inline.plan297.life.early_evidence_of_life.16b7d9543020',
    detailKey: 'inline.plan297.life.common_summaries_place_early_microbial_life_evid.cacd8f02b050',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/',
  ),
  _TimelineFact(
    id: 'great_oxidation',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 2400000000,
    displayKey: 'inline.plan297.life.c_2_4_billion_years_ago.8c4881d27f07',
    titleKey: 'inline.plan297.life.great_oxidation_event.226b180bfb05',
    detailKey: 'inline.plan297.life.atmospheric_and_ocean_oxygen_rose_substantially_.226ae67d384d',
    sourceNameKey: 'toolbox.life.timeline.source.nasa',
    sourceUrl: 'https://astrobiology.nasa.gov/',
  ),
  _TimelineFact(
    id: 'eukaryotes',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 1800000000,
    displayKey: 'inline.plan297.life.c_1_8_billion_years_ago.48c555bca08a',
    titleKey: 'inline.plan297.life.eukaryotes_appear.70f3a67d47ce',
    detailKey: 'inline.plan297.life.nucleated_eukaryotic_cells_appeared_in_the_paleo.9d348e50d788',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/science/eukaryote',
  ),
  _TimelineFact(
    id: 'cambrian',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 538800000,
    displayKey: 'inline.plan297.life.c_538_8_million_years_ago.ee736a11101d',
    titleKey: 'inline.plan297.life.cambrian_period_begins.cd7c9d487e70',
    detailKey: 'inline.plan297.life.the_ics_2024_12_chart_places_the_start_of_the_ca.a537b96554d9',
    sourceNameKey: 'toolbox.life.timeline.source.ics',
    sourceUrl: 'https://stratigraphy.org/chart',
  ),
  _TimelineFact(
    id: 'land_plants',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 470000000,
    displayKey: 'inline.plan297.life.c_470_million_years_ago.789ef2fe6dcb',
    titleKey: 'inline.plan297.life.land_plants_spread.fbda3524b4fe',
    detailKey: 'inline.plan297.life.plant_expansion_onto_land_laid_the_foundation_fo.f7c4870dc8df',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/science/plant/Evolution-and-paleobotany',
  ),
  _TimelineFact(
    id: 'dinosaurs',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 230000000,
    displayKey: 'inline.plan297.life.c_230_million_years_ago.6cc6127f81da',
    titleKey: 'inline.plan297.life.dinosaurs_appear.3b05c1158769',
    detailKey: 'inline.plan297.life.dinosaurs_appeared_in_the_late_triassic_and_late.44b2ee700575',
    sourceNameKey: 'toolbox.life.timeline.source.reference',
    sourceUrl: 'https://www.nhm.ac.uk/discover/when-did-dinosaurs-live.html',
  ),
  _TimelineFact(
    id: 'kpg_extinction',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 66000000,
    displayKey: 'inline.plan297.life.c_66_million_years_ago.8c21bacf1731',
    titleKey: 'inline.plan297.life.cretaceous_paleogene_extinction.465c9ac92be9',
    detailKey: 'inline.plan297.life.a_mass_extinction_ended_non_avian_dinosaurs_and_.41c5389d3c3d',
    sourceNameKey: 'toolbox.life.timeline.source.usgs',
    sourceUrl: 'https://www.usgs.gov/programs/national-geologic-map-database/geologic-time',
  ),
  _TimelineFact(
    id: 'homo_genus',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 2800000,
    displayKey: 'inline.plan297.life.c_2_8_million_years_ago.2cc73ff3a938',
    titleKey: 'inline.plan297.life.early_homo_fossil_record.9b85ece8428d',
    detailKey: 'inline.plan297.life.early_homo_fossil_evidence_is_commonly_placed_ar.71989fcb7cc2',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-habilis',
  ),
  _TimelineFact(
    id: 'stone_tools',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 2600000,
    displayKey: 'inline.plan297.life.c_2_6_million_years_ago.63eb23887f49',
    titleKey: 'inline.plan297.life.oldowan_stone_tools.1bd3ae4fc95e',
    detailKey: 'inline.plan297.life.oldowan_tools_are_a_classic_evidence_line_for_ea.5b34c867e6a8',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/behavior/stone-tools',
  ),
  _TimelineFact(
    id: 'homo_sapiens',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 300000,
    displayKey: 'inline.plan297.life.c_300_000_years_ago.de7abada8a32',
    titleKey: 'inline.plan297.life.homo_sapiens_appear.f5c862da7196',
    detailKey: 'inline.plan297.life.current_fossil_and_genetic_evidence_commonly_pla.aa3c8989f502',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens',
  ),
  _TimelineFact(
    id: 'last_glacial_maximum',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 26500,
    displayKey: 'inline.plan297.life.c_26_500_years_ago.fe13320c5b27',
    titleKey: 'inline.plan297.life.last_glacial_maximum.2e32264076e5',
    detailKey: 'inline.plan297.life.ice_sheets_reached_near_maximum_extent_during_th.9a3e9b4a19da',
    sourceNameKey: 'toolbox.life.timeline.source.noaa',
    sourceUrl: 'https://www.ncei.noaa.gov/products/paleoclimatology',
  ),
  _TimelineFact(
    id: 'agriculture',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 12000,
    displayKey: 'inline.plan297.life.c_10_000_bce.1d96609e49ed',
    titleKey: 'inline.plan297.life.agriculture_and_neolithic_transition.fbd60f7f2490',
    detailKey: 'inline.plan297.life.plant_and_animal_domestication_developed_in_mult.c1f342554684',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Neolithic-Revolution',
  ),
  _TimelineFact(
    id: 'bronze_age',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5300,
    displayKey: 'inline.plan297.life.c_3300_bce.69daaba38d63',
    titleKey: 'inline.plan297.life.early_bronze_age.e86493ece9bf',
    detailKey: 'inline.plan297.life.bronze_metallurgy_and_complex_urban_societies_de.a861cffe8c17',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Bronze-Age',
  ),
  _TimelineFact(
    id: 'writing',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5200,
    displayKey: 'inline.plan297.life.c_3200_bce.af82a17e41bb',
    titleKey: 'inline.plan297.life.early_writing_systems.40796a41a1e7',
    detailKey: 'inline.plan297.life.early_writing_systems_such_as_mesopotamian_cunei.10b8e3125af5',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/writing',
  ),
  _TimelineFact(
    id: 'iron_age',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3200,
    displayKey: 'inline.plan297.life.c_1200_bce.c46f7582314a',
    titleKey: 'inline.plan297.life.iron_age_expansion.4644a1346fc2',
    detailKey: 'inline.plan297.life.widespread_iron_tools_and_weapons_changed_agricu.a8893e4b247c',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Iron-Age',
  ),
  _TimelineFact(
    id: 'qin_unification',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2247,
    displayKey: 'inline.plan297.life.221_bce.0c1cb92a4a80',
    titleKey: 'inline.plan297.life.qin_unifies_china.96f98eadf559',
    detailKey: 'inline.plan297.life.the_qin_dynasty_completed_a_major_political_unif.e579146f199d',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Qin-dynasty',
  ),
  _TimelineFact(
    id: 'paper',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1921,
    displayKey: 'inline.plan297.life.c_105_ce.d579b9eca006',
    titleKey: 'inline.plan297.life.papermaking_refined.1ba392c0ad4b',
    detailKey: 'inline.plan297.life.traditional_accounts_place_cai_lun_s_papermaking.a710a304813e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/technology/papermaking',
  ),
  _TimelineFact(
    id: 'black_death',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 679,
    displayKey: 'inline.plan297.life.1347_1351_ce.1f5d640e460e',
    titleKey: 'inline.plan297.life.black_death_across_eurasia_and_north_africa.a70556cb8a72',
    detailKey: 'inline.plan297.life.the_mid_14th_century_plague_pandemic_caused_enor.1e12db430d36',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Black-Death',
  ),
  _TimelineFact(
    id: 'gutenberg',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 576,
    displayKey: 'inline.plan297.life.c_1450_ce.6b23789e9ca4',
    titleKey: 'inline.plan297.life.movable_type_printing_spreads_in_europe.51aa534eb9c2',
    detailKey: 'inline.plan297.life.gutenberg_era_printing_lowered_book_reproduction.e444d4345c3b',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/technology/printing-press',
  ),
  _TimelineFact(
    id: 'newton',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 339,
    displayKey: 'inline.plan297.life.1687_ce.dc8be3138fef',
    titleKey: 'inline.plan297.life.newton_s_principia_published.13319f61403b',
    detailKey: 'inline.plan297.life.newton_systematized_laws_of_motion_and_universal.430748982a46',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Philosophiae-Naturalis-Principia-Mathematica',
  ),
  _TimelineFact(
    id: 'industrial_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 266,
    displayKey: 'inline.plan297.life.from_c_1760_ce.060213656827',
    titleKey: 'inline.plan297.life.industrial_revolution_begins.968024e1ca7d',
    detailKey: 'inline.plan297.life.mechanized_production_fossil_energy_and_factory_.dbff79d41a9a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Industrial-Revolution',
  ),
  _TimelineFact(
    id: 'darwin',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 167,
    displayKey: 'inline.plan297.life.1859_ce.1f611a91fd8b',
    titleKey: 'inline.plan297.life.on_the_origin_of_species_published.01f6749ee8fc',
    detailKey: 'inline.plan297.life.darwin_s_theory_of_natural_selection_became_one_.2415b0a8a0ed',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/On-the-Origin-of-Species-by-Means-of-Natural-Selection',
  ),
  _TimelineFact(
    id: 'periodic_table',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 157,
    displayKey: 'inline.plan297.life.1869_ce.37a5348fc0d5',
    titleKey: 'inline.plan297.life.mendeleev_periodic_table.21cba26a5695',
    detailKey: 'inline.plan297.life.mendeleev_arranged_elements_by_atomic_weight_and.1634dfb74a4a',
    sourceNameKey: 'toolbox.life.timeline.source.iupac',
    sourceUrl: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
  ),
  _TimelineFact(
    id: 'un_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 81,
    displayKey: 'inline.plan297.life.1945_ce.c29d4b3651a1',
    titleKey: 'inline.plan297.life.united_nations_founded.fb41992a5d60',
    detailKey: 'inline.plan297.life.after_world_war_ii_the_united_nations_was_formal.5c5b7a6ba72c',
    sourceNameKey: 'toolbox.life.timeline.source.un',
    sourceUrl: 'https://www.un.org/en/about-us/history-of-the-un',
  ),
  _TimelineFact(
    id: 'dna_double_helix',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 73,
    displayKey: 'inline.plan297.life.1953_ce.8daabed68cf1',
    titleKey: 'inline.plan297.life.dna_double_helix_proposed.a206edea1a73',
    detailKey: 'inline.plan297.life.watson_and_crick_proposed_the_dna_double_helix_m.dcf58f76cefe',
    sourceNameKey: 'toolbox.life.timeline.source.nobel',
    sourceUrl: 'https://www.nobelprize.org/prizes/medicine/1962/summary/',
  ),
  _TimelineFact(
    id: 'moon_landing',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 57,
    displayKey: 'inline.plan297.life.1969_ce.58209d5f0570',
    titleKey: 'inline.plan297.life.apollo_11_moon_landing.e4c951f9a1a1',
    detailKey: 'inline.plan297.life.humans_walked_on_the_moon_for_the_first_time.4ffc3353fc40',
    sourceNameKey: 'toolbox.life.timeline.source.nasa',
    sourceUrl: 'https://www.nasa.gov/history/apollo-11/',
  ),
  _TimelineFact(
    id: 'web',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 35,
    displayKey: 'inline.plan297.life.1991_ce.8057f820b589',
    titleKey: 'inline.plan297.life.world_wide_web_becomes_publicly_available.a34308c282d7',
    detailKey: 'inline.plan297.life.the_web_combined_hypertext_urls_and_the_internet.1ba6c98ba3c5',
    sourceNameKey: 'toolbox.life.timeline.source.cern',
    sourceUrl: 'https://home.cern/science/computing/birth-web',
  ),
  _TimelineFact(
    id: 'human_genome',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 23,
    displayKey: 'inline.plan297.life.2003_ce.ce0b724ff07b',
    titleKey: 'inline.plan297.life.human_genome_project_completed.6d8232a172d1',
    detailKey: 'inline.plan297.life.the_human_genome_project_completed_a_major_phase.94e05340cb6e',
    sourceNameKey: 'toolbox.life.timeline.source.nih',
    sourceUrl: 'https://www.genome.gov/human-genome-project',
  ),
  _TimelineFact(
    id: 'gravitational_waves',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 11,
    displayKey: 'inline.plan297.life.2015_ce.4c5143e3995a',
    titleKey: 'inline.plan297.life.first_direct_detection_of_gravitational_waves.9ac99d71a47d',
    detailKey: 'inline.plan297.life.ligo_directly_detected_gravitational_waves_from_.b4ab5a4c856d',
    sourceNameKey: 'toolbox.life.timeline.source.ligo',
    sourceUrl: 'https://www.ligo.caltech.edu/page/detection-companion-papers',
  ),
  _TimelineFact(
    id: 'first_controlled_fire',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 1000000,
    displayKey: 'inline.plan295.life.c_1_million_years_ago.d35b98cbdbdd',
    titleKey: 'inline.plan295.life.early_evidence_for_controlled_fire.31e12b4448f9',
    detailKey: 'inline.plan295.life.fire_changed_warmth_protection_food.9b9b1ecc3a05',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/science/control-of-fire',
  ),
  _TimelineFact(
    id: 'homo_erectus_spreads',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 1900000,
    displayKey: 'inline.plan295.life.c_1_9_million_years_ago.515b7ecaeb55',
    titleKey: 'inline.plan295.life.homo_erectus_expands.68632f0c5bac',
    detailKey: 'inline.plan295.life.homo_erectus_fossils_and_tools_mark.5f3820922e21',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-erectus',
  ),
  _TimelineFact(
    id: 'neanderthals',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 400000,
    displayKey: 'inline.plan295.life.c_400_000_years_ago.d9b4cc0b5653',
    titleKey: 'inline.plan295.life.neanderthals_evolve.21aa17bb5960',
    detailKey: 'inline.plan295.life.neanderthals_left_fossils_tools_and.6082eefdfb4d',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/evidence/human-fossils/species/homo-neanderthalensis',
  ),
  _TimelineFact(
    id: 'out_of_africa_major_dispersal',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 70000,
    displayKey: 'inline.plan295.life.c_70_000_years_ago.6c696798fdf3',
    titleKey: 'inline.plan295.life.major_homo_sapiens_dispersals_beyond.699ff46525cf',
    detailKey: 'inline.plan295.life.genetic_and_archaeological_evidence.eeb63a9179a4',
    sourceNameKey: 'toolbox.life.timeline.source.smithsonian',
    sourceUrl: 'https://humanorigins.si.edu/',
  ),
  _TimelineFact(
    id: 'upper_paleolithic_art',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 40000,
    displayKey: 'inline.plan295.life.c_40_000_years_ago.f0fd17323f71',
    titleKey: 'inline.plan295.life.upper_paleolithic_art_expands.4a3b446c8d8c',
    detailKey: 'inline.plan295.life.cave_paintings_carvings_and_symbolic.ccc43b049f89',
    sourceNameKey: 'toolbox.life.timeline.source.met',
    sourceUrl: 'https://www.metmuseum.org/toah/hd/pale/hd_pale.htm',
  ),
  _TimelineFact(
    id: 'settlement_gobekli_tepe',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 11600,
    displayKey: 'inline.plan295.life.c_9600_bce.5018e1d1d53a',
    titleKey: 'inline.plan295.life.early_monumental_ritual_sites_such_a.e5c90b6a9183',
    detailKey: 'inline.plan295.life.monumental_stone_sites_show_that_set.2b0e91d208c0',
    sourceNameKey: 'toolbox.life.timeline.source.unesco',
    sourceUrl: 'https://whc.unesco.org/en/list/1572/',
  ),
  _TimelineFact(
    id: 'catalhoyuk',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 9400,
    displayKey: 'inline.plan295.life.c_7400_bce.cad560f88b74',
    titleKey: 'inline.plan295.life.catalhoyuk_settlement.e5dc83717dfe',
    detailKey: 'inline.plan295.life.catalhoyuk_is_a_major_neolithic_sett.d637ee1638d5',
    sourceNameKey: 'toolbox.life.timeline.source.unesco',
    sourceUrl: 'https://whc.unesco.org/en/list/1405/',
  ),
  _TimelineFact(
    id: 'pottery_spread',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 10000,
    displayKey: 'inline.plan295.life.c_8000_bce.cf46dab0fbb6',
    titleKey: 'inline.plan295.life.pottery_becomes_widespread.a995b3fca9e1',
    detailKey: 'inline.plan295.life.pottery_improved_storage_cooking_and.2919c9259613',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/art/pottery',
  ),
  _TimelineFact(
    id: 'sumerian_city_states',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5200,
    displayKey: 'inline.plan295.life.c_3200_bce.cb9b39a6a0fd',
    titleKey: 'inline.plan295.life.sumerian_city_states_and_urban_civil.64e2d687b883',
    detailKey: 'inline.plan295.life.southern_mesopotamia_developed_city.721c7173f1ef',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Sumer',
  ),
  _TimelineFact(
    id: 'egypt_unification',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5126,
    displayKey: 'inline.plan295.life.c_3100_bce.0423397dd886',
    titleKey: 'inline.plan295.life.unification_of_ancient_egypt.8a4b0f4e3e53',
    detailKey: 'inline.plan295.life.upper_and_lower_egypt_unified_along.2790f387b547',
    sourceNameKey: 'toolbox.life.timeline.source.met',
    sourceUrl: 'https://www.metmuseum.org/toah/hd/egyp/hd_egyp.htm',
  ),
  _TimelineFact(
    id: 'indus_civilization',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4626,
    displayKey: 'inline.plan295.life.c_2600_bce.f7cfa53fa549',
    titleKey: 'inline.plan295.life.mature_indus_civilization.696af5631900',
    detailKey: 'inline.plan295.life.cities_such_as_harappa_and_mohenjo_d.8c7719991d85',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Indus-civilization',
  ),
  _TimelineFact(
    id: 'old_babylon_hammurabi',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3776,
    displayKey: 'inline.plan295.life.c_1750_bce.1d20bc69ee35',
    titleKey: 'inline.plan295.life.code_of_hammurabi.d8ee457ead13',
    detailKey: 'inline.plan295.life.the_babylonian_law_code_tradition_sh.4bc693740601',
    sourceNameKey: 'toolbox.life.timeline.source.louvre',
    sourceUrl: 'https://www.louvre.fr/en/oeuvre-notices/law-code-hammurabi-king-babylon',
  ),
  _TimelineFact(
    id: 'shang_dynasty_oracle_bones',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3526,
    displayKey: 'inline.plan295.life.c_1500_bce.1f9ceaff84bc',
    titleKey: 'inline.plan295.life.shang_dynasty_and_oracle_bone_writin.07585c405e91',
    detailKey: 'inline.plan295.life.shang_oracle_bone_inscriptions_are_k.b834f49b4c54',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Shang-dynasty',
  ),
  _TimelineFact(
    id: 'olmec_civilization',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3226,
    displayKey: 'inline.plan295.life.c_1200_bce.c86e53a5baee',
    titleKey: 'inline.plan295.life.olmec_civilization_rises.0f5fc8c296d1',
    detailKey: 'inline.plan295.life.the_olmec_were_an_early_complex_soci.f9dc98be527f',
    sourceNameKey: 'toolbox.life.timeline.source.met',
    sourceUrl: 'https://www.metmuseum.org/toah/hd/olmc/hd_olmc.htm',
  ),
  _TimelineFact(
    id: 'zhou_mandate_of_heaven',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3072,
    displayKey: 'inline.plan295.life.1046_bce.c9ee5c188aa4',
    titleKey: 'inline.plan295.life.zhou_replaces_shang_and_mandate_of_h.2aa88d7a7c42',
    detailKey: 'inline.plan295.life.after_the_zhou_replaced_shang_the_ma.ee4fdd608081',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Zhou-dynasty',
  ),
  _TimelineFact(
    id: 'greek_alphabet',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2826,
    displayKey: 'inline.plan295.life.c_800_bce.4e6f3663df60',
    titleKey: 'inline.plan295.life.greek_alphabet_develops.5d8475c82c60',
    detailKey: 'inline.plan295.life.the_greek_alphabet_developed_from_ph.b20b20a8c8fd',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Greek-alphabet',
  ),
  _TimelineFact(
    id: 'buddha_life_tradition',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2526,
    displayKey: 'inline.plan295.life.c_5th_century_bce.8c5ec54f9150',
    titleKey: 'inline.plan295.life.buddhist_tradition_forms.3e03dd96c809',
    detailKey: 'inline.plan295.life.teachings_associated_with_the_buddha.597f503f0bbb',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Buddhism',
  ),
  _TimelineFact(
    id: 'confucius',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2505,
    displayKey: 'inline.plan295.life.551_bce.d6db0a5f22c4',
    titleKey: 'inline.plan295.life.birth_of_confucius.109ec4c7c710',
    detailKey: 'inline.plan295.life.confucius_ideas_later_compiled_and_i.29f2c9cd8d3a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Confucius',
  ),
  _TimelineFact(
    id: 'persian_empire_achaemenid',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2576,
    displayKey: 'inline.plan295.life.c_550_bce.95575bc7b349',
    titleKey: 'inline.plan295.life.achaemenid_persian_empire_rises.aece3cccaad9',
    detailKey: 'inline.plan295.life.the_persian_empire_built_cross_regio.6f1db9a86858',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Achaemenian-dynasty',
  ),
  _TimelineFact(
    id: 'athenian_democracy',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2534,
    displayKey: 'inline.plan295.life.c_508_bce.94cbc4af0dab',
    titleKey: 'inline.plan295.life.athenian_democratic_reforms.13ce6b580206',
    detailKey: 'inline.plan295.life.athenian_reforms_developed_assemblie.4d58d0aa20b3',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Athenian-democracy',
  ),
  _TimelineFact(
    id: 'roman_republic',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2535,
    displayKey: 'inline.plan295.life.c_509_bce.6c389759109e',
    titleKey: 'inline.plan295.life.roman_republic_begins.4667354205ee',
    detailKey: 'inline.plan295.life.the_roman_republic_developed_consuls.95b7e6c01151',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Roman-Republic',
  ),
  _TimelineFact(
    id: 'mauryan_empire_ashoka',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2294,
    displayKey: 'inline.plan295.life.c_268_bce.e0e31c5b9213',
    titleKey: 'inline.plan295.life.ashoka_and_the_mauryan_empire.cb9bc7679233',
    detailKey: 'inline.plan295.life.under_ashoka_the_mauryan_empire_cove.64d7a88967b5',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Ashoka',
  ),
  _TimelineFact(
    id: 'han_dynasty',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2232,
    displayKey: 'inline.plan295.life.206_bce.539c13685b7e',
    titleKey: 'inline.plan295.life.han_dynasty_begins.67b4f7f844ac',
    detailKey: 'inline.plan295.life.the_han_integrated_imperial_administ.97ab88859a0c',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Han-dynasty',
  ),
  _TimelineFact(
    id: 'roman_empire_augustus',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2053,
    displayKey: 'inline.plan295.life.27_bce.018fa48af9ec',
    titleKey: 'inline.plan295.life.augustus_and_the_roman_empire.4f1b8a13d603',
    detailKey: 'inline.plan295.life.augustus_established_the_principate.65e80d7cd9c3',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Augustus-Roman-emperor',
  ),
  _TimelineFact(
    id: 'christianity_early_spread',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1996,
    displayKey: 'inline.plan295.life.c_30_ce.962b686be116',
    titleKey: 'inline.plan295.life.early_christianity_forms.3baccde94367',
    detailKey: 'inline.plan295.life.the_jesus_movement_and_early_churche.d6bb58dcd30e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Christianity',
  ),
  _TimelineFact(
    id: 'constantinople_founded',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1696,
    displayKey: 'inline.plan295.life.330_ce.69a6e45e0806',
    titleKey: 'inline.plan295.life.constantinople_becomes_imperial_capi.d42cdcb6ac41',
    detailKey: 'inline.plan295.life.constantinople_positioned_between_eu.d9f68d5aac18',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Constantinople',
  ),
  _TimelineFact(
    id: 'islam_hijra',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1404,
    displayKey: 'inline.plan295.life.622_ce.fc5090449012',
    titleKey: 'inline.plan295.life.hijra_and_the_islamic_community.d77f4472e0c2',
    detailKey: 'inline.plan295.life.muhammad_s_migration_to_medina_marks.278420191f71',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Hijrah-Islam',
  ),
  _TimelineFact(
    id: 'tang_dynasty',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1408,
    displayKey: 'inline.plan295.life.618_ce.cf0ceee03fe8',
    titleKey: 'inline.plan295.life.tang_dynasty_begins.6c6a81a29e0a',
    detailKey: 'inline.plan295.life.the_tang_linked_east_asia_central_as.f507fd28165a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Tang-dynasty',
  ),
  _TimelineFact(
    id: 'carolingian_coronation',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1226,
    displayKey: 'inline.plan295.life.800_ce.a78476628d64',
    titleKey: 'inline.plan295.life.charlemagne_crowned_emperor.e929caa43cef',
    detailKey: 'inline.plan295.life.charlemagne_s_coronation_symbolized.ee22b6070d94',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Charlemagne',
  ),
  _TimelineFact(
    id: 'song_printing_commerce',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1066,
    displayKey: 'inline.plan295.life.960_ce.fb419755375a',
    titleKey: 'inline.plan295.life.song_commerce_and_printing_expand.8be54296811a',
    detailKey: 'inline.plan295.life.song_urban_commerce_paper_money_prin.16ca9af94de4',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Song-dynasty',
  ),
  _TimelineFact(
    id: 'crusades_begin',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 931,
    displayKey: 'inline.plan295.life.1095_ce.9849e9d4774f',
    titleKey: 'inline.plan295.life.crusades_begin.0f8a7ad60685',
    detailKey: 'inline.plan295.life.the_crusades_reshaped_mediterranean.0f838f68d7d4',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Crusades',
  ),
  _TimelineFact(
    id: 'mongol_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 820,
    displayKey: 'inline.plan295.life.1206_ce.b1c3b49f2ee8',
    titleKey: 'inline.plan295.life.mongol_empire_forms.7a5272e30ef0',
    detailKey: 'inline.plan295.life.chinggis_khan_united_mongol_groups_l.ebd2f28551e1',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Mongol-empire',
  ),
  _TimelineFact(
    id: 'mali_mansa_musa',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 702,
    displayKey: 'inline.plan295.life.1324_1325_ce.62e78094771c',
    titleKey: 'inline.plan295.life.mansa_musa_s_pilgrimage.929038626fdd',
    detailKey: 'inline.plan295.life.mansa_musa_s_pilgrimage_highlighted.e0739812168e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Musa-I-of-Mali',
  ),
  _TimelineFact(
    id: 'ming_voyages_zheng_he',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 621,
    displayKey: 'inline.plan295.life.1405_1433_ce.21f670f9c3e2',
    titleKey: 'inline.plan295.life.zheng_he_voyages.70f85ff97657',
    detailKey: 'inline.plan295.life.ming_maritime_expeditions_connected.9d5b682d258a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Zheng-He',
  ),
  _TimelineFact(
    id: 'constantinople_1453',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 573,
    displayKey: 'inline.plan295.life.1453_ce.d40f21a3b1ae',
    titleKey: 'inline.plan295.life.fall_of_constantinople.bfa8b54ced54',
    detailKey: 'inline.plan295.life.the_ottomans_captured_constantinople.785535181a12',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Fall-of-Constantinople-1453',
  ),
  _TimelineFact(
    id: 'columbus_voyage',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 534,
    displayKey: 'inline.plan295.life.1492_ce.6c42a1ba8b2e',
    titleKey: 'inline.plan295.life.columbus_reaches_the_americas.3297236453f8',
    detailKey: 'inline.plan295.life.atlantic_voyages_initiated_sustained.d02ebe731505',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Christopher-Columbus',
  ),
  _TimelineFact(
    id: 'vasco_da_gama',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 528,
    displayKey: 'inline.plan295.life.1498_ce.1c187e96edaa',
    titleKey: 'inline.plan295.life.vasco_da_gama_reaches_india_by_sea.13b722261519',
    detailKey: 'inline.plan295.life.the_portuguese_sea_route_connected_e.964b12e90b59',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Vasco-da-Gama',
  ),
  _TimelineFact(
    id: 'aztec_conquest',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 505,
    displayKey: 'inline.plan295.life.1521_ce.244ddf65a93e',
    titleKey: 'inline.plan295.life.spanish_conquest_of_the_aztec_empire.5fcdf2bea2c9',
    detailKey: 'inline.plan295.life.after_tenochtitlan_fell_spanish_colo.60f2a78684e9',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Aztec',
  ),
  _TimelineFact(
    id: 'inca_conquest',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 493,
    displayKey: 'inline.plan295.life.1533_ce.f72694baaa9b',
    titleKey: 'inline.plan295.life.spanish_conquest_of_the_inca_empire.52e7f65a0502',
    detailKey: 'inline.plan295.life.the_inca_imperial_core_was_conquered.ff0c857092ec',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Inca',
  ),
];
