part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _chinaTimelineFacts01 = <_TimelineFact>[
  _TimelineFact(
    id: 'yuanmou_hominin',
    collection: 'china_overview',
    category: 'human',
    yearsBeforePresent: 1702026,
    displayKey: 'toolbox.life.timeline.china_overview.yuanmou_hominin.date',
    titleKey: 'toolbox.life.timeline.china_overview.yuanmou_hominin.title',
    detailKey: 'toolbox.life.timeline.china_overview.yuanmou_hominin.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Yuanmou%20Man',
    imageAsset: 'assets/toolbox/history_timeline/prehistoric.webp',
  ),
  _TimelineFact(
    id: 'lantian_hominin',
    collection: 'china_overview',
    category: 'human',
    yearsBeforePresent: 632026,
    displayKey: 'toolbox.life.timeline.china_overview.lantian_hominin.date',
    titleKey: 'toolbox.life.timeline.china_overview.lantian_hominin.title',
    detailKey: 'toolbox.life.timeline.china_overview.lantian_hominin.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Lantian%20Man',
    imageAsset: 'assets/toolbox/history_timeline/prehistoric.webp',
  ),
  _TimelineFact(
    id: 'peking_man',
    collection: 'china_overview',
    category: 'human',
    yearsBeforePresent: 502026,
    displayKey: 'toolbox.life.timeline.china_overview.peking_man.date',
    titleKey: 'toolbox.life.timeline.china_overview.peking_man.title',
    detailKey: 'toolbox.life.timeline.china_overview.peking_man.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Peking%20Man',
    imageAsset: 'assets/toolbox/history_timeline/prehistoric.webp',
  ),
  _TimelineFact(
    id: 'upper_cave_zhoukoudian',
    collection: 'china_overview',
    category: 'human',
    yearsBeforePresent: 32026,
    displayKey: 'toolbox.life.timeline.china_overview.upper_cave_zhoukoudian.date',
    titleKey: 'toolbox.life.timeline.china_overview.upper_cave_zhoukoudian.title',
    detailKey: 'toolbox.life.timeline.china_overview.upper_cave_zhoukoudian.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Upper%20Cave%20Zhoukoudian',
    imageAsset: 'assets/toolbox/history_timeline/prehistoric.webp',
  ),
  _TimelineFact(
    id: 'hemudu_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 6176,
    displayKey: 'toolbox.life.timeline.china_overview.hemudu_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.hemudu_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.hemudu_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hemudu%20culture',
    imageAsset: 'assets/toolbox/history_timeline/neolithic.webp',
  ),
  _TimelineFact(
    id: 'yangshao_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 6026,
    displayKey: 'toolbox.life.timeline.china_overview.yangshao_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.yangshao_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.yangshao_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Yangshao%20culture',
    imageAsset: 'assets/toolbox/history_timeline/neolithic.webp',
  ),
  _TimelineFact(
    id: 'hongshan_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 5476,
    displayKey: 'toolbox.life.timeline.china_overview.hongshan_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.hongshan_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.hongshan_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hongshan%20culture',
    imageAsset: 'assets/toolbox/history_timeline/neolithic.webp',
  ),
  _TimelineFact(
    id: 'liangzhu_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 4826,
    displayKey: 'toolbox.life.timeline.china_overview.liangzhu_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.liangzhu_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.liangzhu_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Liangzhu%20culture',
    imageAsset: 'assets/toolbox/history_timeline/neolithic.webp',
  ),
  _TimelineFact(
    id: 'longshan_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 4476,
    displayKey: 'toolbox.life.timeline.china_overview.longshan_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.longshan_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.longshan_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Longshan%20culture',
    imageAsset: 'assets/toolbox/history_timeline/neolithic.webp',
  ),
  _TimelineFact(
    id: 'taosi_site',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 4126,
    displayKey: 'toolbox.life.timeline.china_overview.taosi_site.date',
    titleKey: 'toolbox.life.timeline.china_overview.taosi_site.title',
    detailKey: 'toolbox.life.timeline.china_overview.taosi_site.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Taosi%20site',
    imageAsset: 'assets/toolbox/history_timeline/neolithic.webp',
  ),
  _TimelineFact(
    id: 'erlitou_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 3726,
    displayKey: 'toolbox.life.timeline.china_overview.erlitou_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.erlitou_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.erlitou_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Erlitou%20culture',
    imageAsset: 'assets/toolbox/history_timeline/bronze_age.webp',
  ),
  _TimelineFact(
    id: 'sanxingdui_culture',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 3451,
    displayKey: 'toolbox.life.timeline.china_overview.sanxingdui_culture.date',
    titleKey: 'toolbox.life.timeline.china_overview.sanxingdui_culture.title',
    detailKey: 'toolbox.life.timeline.china_overview.sanxingdui_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Sanxingdui',
    imageAsset: 'assets/toolbox/history_timeline/bronze_age.webp',
  ),
  _TimelineFact(
    id: 'silk_production_origins',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 4276,
    displayKey: 'toolbox.life.timeline.china_overview.silk_production_origins.date',
    titleKey: 'toolbox.life.timeline.china_overview.silk_production_origins.title',
    detailKey: 'toolbox.life.timeline.china_overview.silk_production_origins.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Silk%20production%20China',
    imageAsset: 'assets/toolbox/history_timeline/bronze_age.webp',
  ),
  _TimelineFact(
    id: 'oracle_bone_writing',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 3174,
    displayKey: 'toolbox.life.timeline.china_overview.oracle_bone_writing.date',
    titleKey: 'toolbox.life.timeline.china_overview.oracle_bone_writing.title',
    detailKey: 'toolbox.life.timeline.china_overview.oracle_bone_writing.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Oracle%20bone%20script',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'xia_dynasty_tradition',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 3861,
    displayKey: 'toolbox.life.timeline.china_overview.xia_dynasty_tradition.date',
    titleKey: 'toolbox.life.timeline.china_overview.xia_dynasty_tradition.title',
    detailKey: 'toolbox.life.timeline.china_overview.xia_dynasty_tradition.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Xia%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'shang_dynasty',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 3349,
    displayKey: 'toolbox.life.timeline.china_overview.shang_dynasty.date',
    titleKey: 'toolbox.life.timeline.china_overview.shang_dynasty.title',
    detailKey: 'toolbox.life.timeline.china_overview.shang_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Shang%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'zhou_conquest_shang',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 3072,
    displayKey: 'toolbox.life.timeline.china_overview.zhou_conquest_shang.date',
    titleKey: 'toolbox.life.timeline.china_overview.zhou_conquest_shang.title',
    detailKey: 'toolbox.life.timeline.china_overview.zhou_conquest_shang.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zhou%20conquest%20of%20Shang',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'western_zhou',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2934.5,
    displayKey: 'toolbox.life.timeline.china_overview.western_zhou.date',
    titleKey: 'toolbox.life.timeline.china_overview.western_zhou.title',
    detailKey: 'toolbox.life.timeline.china_overview.western_zhou.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Western%20Zhou',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'eastern_zhou',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2539,
    displayKey: 'toolbox.life.timeline.china_overview.eastern_zhou.date',
    titleKey: 'toolbox.life.timeline.china_overview.eastern_zhou.title',
    detailKey: 'toolbox.life.timeline.china_overview.eastern_zhou.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Eastern%20Zhou',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'spring_autumn_period',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2649,
    displayKey: 'toolbox.life.timeline.china_overview.spring_autumn_period.date',
    titleKey: 'toolbox.life.timeline.china_overview.spring_autumn_period.title',
    detailKey: 'toolbox.life.timeline.china_overview.spring_autumn_period.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Spring%20and%20Autumn%20period',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'confucius',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2541,
    displayKey: 'toolbox.life.timeline.china_overview.confucius.date',
    titleKey: 'toolbox.life.timeline.china_overview.confucius.title',
    detailKey: 'toolbox.life.timeline.china_overview.confucius.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Confucius',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'mozi_school',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 2456,
    displayKey: 'toolbox.life.timeline.china_overview.mozi_school.date',
    titleKey: 'toolbox.life.timeline.china_overview.mozi_school.title',
    detailKey: 'toolbox.life.timeline.china_overview.mozi_school.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Mohism',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'warring_states',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2374,
    displayKey: 'toolbox.life.timeline.china_overview.warring_states.date',
    titleKey: 'toolbox.life.timeline.china_overview.warring_states.title',
    detailKey: 'toolbox.life.timeline.china_overview.warring_states.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Warring%20States%20period',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'baijia_thought',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2376,
    displayKey: 'toolbox.life.timeline.china_overview.baijia_thought.date',
    titleKey: 'toolbox.life.timeline.china_overview.baijia_thought.title',
    detailKey: 'toolbox.life.timeline.china_overview.baijia_thought.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hundred%20Schools%20of%20Thought',
    imageAsset: 'assets/toolbox/history_timeline/shang_zhou.webp',
  ),
  _TimelineFact(
    id: 'nine_chapters_mathematics',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 2026,
    displayKey: 'toolbox.life.timeline.china_overview.nine_chapters_mathematics.date',
    titleKey: 'toolbox.life.timeline.china_overview.nine_chapters_mathematics.title',
    detailKey: 'toolbox.life.timeline.china_overview.nine_chapters_mathematics.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Nine%20Chapters%20on%20the%20Mathematical%20Art',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'qin_unification',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2247,
    displayKey: 'toolbox.life.timeline.china_overview.qin_unification.date',
    titleKey: 'toolbox.life.timeline.china_overview.qin_unification.title',
    detailKey: 'toolbox.life.timeline.china_overview.qin_unification.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Qin%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'qin_standardization',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2241.5,
    displayKey: 'toolbox.life.timeline.china_overview.qin_standardization.date',
    titleKey: 'toolbox.life.timeline.china_overview.qin_standardization.title',
    detailKey: 'toolbox.life.timeline.china_overview.qin_standardization.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Qin%20dynasty%20standardization',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'qin_great_wall',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2240,
    displayKey: 'toolbox.life.timeline.china_overview.qin_great_wall.date',
    titleKey: 'toolbox.life.timeline.china_overview.qin_great_wall.title',
    detailKey: 'toolbox.life.timeline.china_overview.qin_great_wall.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Great%20Wall%20of%20China%20Qin',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'han_dynasty_founded',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2228,
    displayKey: 'toolbox.life.timeline.china_overview.han_dynasty_founded.date',
    titleKey: 'toolbox.life.timeline.china_overview.han_dynasty_founded.title',
    detailKey: 'toolbox.life.timeline.china_overview.han_dynasty_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Han%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'zhang_qian_silk_road',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 2158,
    displayKey: 'toolbox.life.timeline.china_overview.zhang_qian_silk_road.date',
    titleKey: 'toolbox.life.timeline.china_overview.zhang_qian_silk_road.title',
    detailKey: 'toolbox.life.timeline.china_overview.zhang_qian_silk_road.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zhang%20Qian',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'paper_early_use',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 2026,
    displayKey: 'toolbox.life.timeline.china_overview.paper_early_use.date',
    titleKey: 'toolbox.life.timeline.china_overview.paper_early_use.title',
    detailKey: 'toolbox.life.timeline.china_overview.paper_early_use.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Paper%20history%20China',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'shiji_completed',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 2117,
    displayKey: 'toolbox.life.timeline.china_overview.shiji_completed.date',
    titleKey: 'toolbox.life.timeline.china_overview.shiji_completed.title',
    detailKey: 'toolbox.life.timeline.china_overview.shiji_completed.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Records%20of%20the%20Grand%20Historian',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'eastern_han_buddhism',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1893.5,
    displayKey: 'toolbox.life.timeline.china_overview.eastern_han_buddhism.date',
    titleKey: 'toolbox.life.timeline.china_overview.eastern_han_buddhism.title',
    detailKey: 'toolbox.life.timeline.china_overview.eastern_han_buddhism.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Buddhism%20in%20China',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'zhang_heng_seismoscope',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 1894,
    displayKey: 'toolbox.life.timeline.china_overview.zhang_heng_seismoscope.date',
    titleKey: 'toolbox.life.timeline.china_overview.zhang_heng_seismoscope.title',
    detailKey: 'toolbox.life.timeline.china_overview.zhang_heng_seismoscope.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zhang%20Heng%20seismoscope',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'yellow_turban_rebellion',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 1842,
    displayKey: 'toolbox.life.timeline.china_overview.yellow_turban_rebellion.date',
    titleKey: 'toolbox.life.timeline.china_overview.yellow_turban_rebellion.title',
    detailKey: 'toolbox.life.timeline.china_overview.yellow_turban_rebellion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Yellow%20Turban%20rebellion',
    imageAsset: 'assets/toolbox/history_timeline/qin_han.webp',
  ),
  _TimelineFact(
    id: 'three_kingdoms',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1776,
    displayKey: 'toolbox.life.timeline.china_overview.three_kingdoms.date',
    titleKey: 'toolbox.life.timeline.china_overview.three_kingdoms.title',
    detailKey: 'toolbox.life.timeline.china_overview.three_kingdoms.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Three%20Kingdoms%20China',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'liu_hui_mathematics',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 1763,
    displayKey: 'toolbox.life.timeline.china_overview.liu_hui_mathematics.date',
    titleKey: 'toolbox.life.timeline.china_overview.liu_hui_mathematics.title',
    detailKey: 'toolbox.life.timeline.china_overview.liu_hui_mathematics.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Liu%20Hui%20mathematics',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'jin_unification',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1746,
    displayKey: 'toolbox.life.timeline.china_overview.jin_unification.date',
    titleKey: 'toolbox.life.timeline.china_overview.jin_unification.title',
    detailKey: 'toolbox.life.timeline.china_overview.jin_unification.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Jin%20dynasty%20China',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'sixteen_kingdoms',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1654.5,
    displayKey: 'toolbox.life.timeline.china_overview.sixteen_kingdoms.date',
    titleKey: 'toolbox.life.timeline.china_overview.sixteen_kingdoms.title',
    detailKey: 'toolbox.life.timeline.china_overview.sixteen_kingdoms.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Sixteen%20Kingdoms',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'northern_wei',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1566,
    displayKey: 'toolbox.life.timeline.china_overview.northern_wei.date',
    titleKey: 'toolbox.life.timeline.china_overview.northern_wei.title',
    detailKey: 'toolbox.life.timeline.china_overview.northern_wei.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Northern%20Wei',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'dunhuang_caves',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1343,
    displayKey: 'toolbox.life.timeline.china_overview.dunhuang_caves.date',
    titleKey: 'toolbox.life.timeline.china_overview.dunhuang_caves.title',
    detailKey: 'toolbox.life.timeline.china_overview.dunhuang_caves.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Mogao%20Caves',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'southern_northern_dynasties',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1521.5,
    displayKey: 'toolbox.life.timeline.china_overview.southern_northern_dynasties.date',
    titleKey: 'toolbox.life.timeline.china_overview.southern_northern_dynasties.title',
    detailKey: 'toolbox.life.timeline.china_overview.southern_northern_dynasties.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Northern%20and%20Southern%20dynasties',
    imageAsset: 'assets/toolbox/history_timeline/six_dynasties.webp',
  ),
  _TimelineFact(
    id: 'sui_reunification',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1437,
    displayKey: 'toolbox.life.timeline.china_overview.sui_reunification.date',
    titleKey: 'toolbox.life.timeline.china_overview.sui_reunification.title',
    detailKey: 'toolbox.life.timeline.china_overview.sui_reunification.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Sui%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'grand_canal_sui',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1418.5,
    displayKey: 'toolbox.life.timeline.china_overview.grand_canal_sui.date',
    titleKey: 'toolbox.life.timeline.china_overview.grand_canal_sui.title',
    detailKey: 'toolbox.life.timeline.china_overview.grand_canal_sui.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Grand%20Canal%20China',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'tang_dynasty',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1263.5,
    displayKey: 'toolbox.life.timeline.china_overview.tang_dynasty.date',
    titleKey: 'toolbox.life.timeline.china_overview.tang_dynasty.title',
    detailKey: 'toolbox.life.timeline.china_overview.tang_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Tang%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'xuanzang_journey',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1389,
    displayKey: 'toolbox.life.timeline.china_overview.xuanzang_journey.date',
    titleKey: 'toolbox.life.timeline.china_overview.xuanzang_journey.title',
    detailKey: 'toolbox.life.timeline.china_overview.xuanzang_journey.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Xuanzang',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'tea_culture_tang',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1226,
    displayKey: 'toolbox.life.timeline.china_overview.tea_culture_tang.date',
    titleKey: 'toolbox.life.timeline.china_overview.tea_culture_tang.title',
    detailKey: 'toolbox.life.timeline.china_overview.tea_culture_tang.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Tea%20in%20China',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'an_lushan_rebellion',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 1267,
    displayKey: 'toolbox.life.timeline.china_overview.an_lushan_rebellion.date',
    titleKey: 'toolbox.life.timeline.china_overview.an_lushan_rebellion.title',
    detailKey: 'toolbox.life.timeline.china_overview.an_lushan_rebellion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=An%20Lushan%20rebellion',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'woodblock_printing_diamond_sutra',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 1158,
    displayKey: 'toolbox.life.timeline.china_overview.woodblock_printing_diamond_sutra.date',
    titleKey: 'toolbox.life.timeline.china_overview.woodblock_printing_diamond_sutra.title',
    detailKey: 'toolbox.life.timeline.china_overview.woodblock_printing_diamond_sutra.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Diamond%20Sutra%20868',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'huang_chao_rebellion',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 1147,
    displayKey: 'toolbox.life.timeline.china_overview.huang_chao_rebellion.date',
    titleKey: 'toolbox.life.timeline.china_overview.huang_chao_rebellion.title',
    detailKey: 'toolbox.life.timeline.china_overview.huang_chao_rebellion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Huang%20Chao%20rebellion',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'five_dynasties_ten_kingdoms',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 1092.5,
    displayKey: 'toolbox.life.timeline.china_overview.five_dynasties_ten_kingdoms.date',
    titleKey: 'toolbox.life.timeline.china_overview.five_dynasties_ten_kingdoms.title',
    detailKey: 'toolbox.life.timeline.china_overview.five_dynasties_ten_kingdoms.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Five%20Dynasties%20and%20Ten%20Kingdoms',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'song_dynasty',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 906.5,
    displayKey: 'toolbox.life.timeline.china_overview.song_dynasty.date',
    titleKey: 'toolbox.life.timeline.china_overview.song_dynasty.title',
    detailKey: 'toolbox.life.timeline.china_overview.song_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Song%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'bi_sheng_movable_type',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 986,
    displayKey: 'toolbox.life.timeline.china_overview.bi_sheng_movable_type.date',
    titleKey: 'toolbox.life.timeline.china_overview.bi_sheng_movable_type.title',
    detailKey: 'toolbox.life.timeline.china_overview.bi_sheng_movable_type.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Bi%20Sheng',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'wujing_zongyao',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 982,
    displayKey: 'toolbox.life.timeline.china_overview.wujing_zongyao.date',
    titleKey: 'toolbox.life.timeline.china_overview.wujing_zongyao.title',
    detailKey: 'toolbox.life.timeline.china_overview.wujing_zongyao.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Wujing%20Zongyao',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'shen_kuo_dream_pool',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 938,
    displayKey: 'toolbox.life.timeline.china_overview.shen_kuo_dream_pool.date',
    titleKey: 'toolbox.life.timeline.china_overview.shen_kuo_dream_pool.title',
    detailKey: 'toolbox.life.timeline.china_overview.shen_kuo_dream_pool.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Dream%20Pool%20Essays',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'compass_navigation_song',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 876,
    displayKey: 'toolbox.life.timeline.china_overview.compass_navigation_song.date',
    titleKey: 'toolbox.life.timeline.china_overview.compass_navigation_song.title',
    detailKey: 'toolbox.life.timeline.china_overview.compass_navigation_song.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Compass%20history%20China',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'southern_song',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 823,
    displayKey: 'toolbox.life.timeline.china_overview.southern_song.date',
    titleKey: 'toolbox.life.timeline.china_overview.southern_song.title',
    detailKey: 'toolbox.life.timeline.china_overview.southern_song.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Southern%20Song',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
  _TimelineFact(
    id: 'zhuxi_neo_confucianism',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 861,
    displayKey: 'toolbox.life.timeline.china_overview.zhuxi_neo_confucianism.date',
    titleKey: 'toolbox.life.timeline.china_overview.zhuxi_neo_confucianism.title',
    detailKey: 'toolbox.life.timeline.china_overview.zhuxi_neo_confucianism.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zhu%20Xi',
    imageAsset: 'assets/toolbox/history_timeline/tang_song.webp',
  ),
];
