part of '../toolbox_life_tools.dart';

const List<_ElementFact> _elementFacts01 = <_ElementFact>[
  _ElementFact(
    atomicNumber: 1,
    symbol: 'H',
    nameKey: 'toolbox.life.element.h.name',
    nameEn: 'Hydrogen',
    atomicMass: '1.0080',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1766',
    electronConfiguration: '1s1',
    electronegativity: '2.2',
    atomicRadius: '120',
    ionizationEnergy: '13.598',
    electronAffinity: '0.754',
    oxidationStates: '+1, -1',
    meltingPoint: '13.81',
    boilingPoint: '20.28',
    density: '0.00008988',
    period: 1,
    group: 1,
    displayRow: 1,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 2,
    symbol: 'He',
    nameKey: 'toolbox.life.element.he.name',
    nameEn: 'Helium',
    atomicMass: '4.00260',
    groupBlock: 'Noble gas',
    groupBlockKey: 'toolbox.life.element.block.noble_gas',
    standardState: 'Gas',
    yearDiscovered: '1868',
    electronConfiguration: '1s2',
    electronegativity: '',
    atomicRadius: '140',
    ionizationEnergy: '24.587',
    electronAffinity: '',
    oxidationStates: '0',
    meltingPoint: '0.95',
    boilingPoint: '4.22',
    density: '0.0001785',
    period: 1,
    group: 18,
    displayRow: 1,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 3,
    symbol: 'Li',
    nameKey: 'toolbox.life.element.li.name',
    nameEn: 'Lithium',
    atomicMass: '7.0',
    groupBlock: 'Alkali metal',
    groupBlockKey: 'toolbox.life.element.block.alkali_metal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[He]2s1',
    electronegativity: '0.98',
    atomicRadius: '182',
    ionizationEnergy: '5.392',
    electronAffinity: '0.618',
    oxidationStates: '+1',
    meltingPoint: '453.65',
    boilingPoint: '1615',
    density: '0.534',
    period: 2,
    group: 1,
    displayRow: 2,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 4,
    symbol: 'Be',
    nameKey: 'toolbox.life.element.be.name',
    nameEn: 'Beryllium',
    atomicMass: '9.012183',
    groupBlock: 'Alkaline earth metal',
    groupBlockKey: 'toolbox.life.element.block.alkaline_earth_metal',
    standardState: 'Solid',
    yearDiscovered: '1798',
    electronConfiguration: '[He]2s2',
    electronegativity: '1.57',
    atomicRadius: '153',
    ionizationEnergy: '9.323',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '1560',
    boilingPoint: '2744',
    density: '1.85',
    period: 2,
    group: 2,
    displayRow: 2,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 5,
    symbol: 'B',
    nameKey: 'toolbox.life.element.b.name',
    nameEn: 'Boron',
    atomicMass: '10.81',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[He]2s2 2p1',
    electronegativity: '2.04',
    atomicRadius: '192',
    ionizationEnergy: '8.298',
    electronAffinity: '0.277',
    oxidationStates: '+3',
    meltingPoint: '2348',
    boilingPoint: '4273',
    density: '2.37',
    period: 2,
    group: 13,
    displayRow: 2,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 6,
    symbol: 'C',
    nameKey: 'toolbox.life.element.c.name',
    nameEn: 'Carbon',
    atomicMass: '12.011',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[He]2s2 2p2',
    electronegativity: '2.55',
    atomicRadius: '170',
    ionizationEnergy: '11.260',
    electronAffinity: '1.263',
    oxidationStates: '+4, +2, -4',
    meltingPoint: '3823',
    boilingPoint: '4098',
    density: '2.2670',
    period: 2,
    group: 14,
    displayRow: 2,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 7,
    symbol: 'N',
    nameKey: 'toolbox.life.element.n.name',
    nameEn: 'Nitrogen',
    atomicMass: '14.007',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1772',
    electronConfiguration: '[He] 2s2 2p3',
    electronegativity: '3.04',
    atomicRadius: '155',
    ionizationEnergy: '14.534',
    electronAffinity: '',
    oxidationStates: '+5, +4, +3, +2, +1, -1, -2, -3',
    meltingPoint: '63.15',
    boilingPoint: '77.36',
    density: '0.0012506',
    period: 2,
    group: 15,
    displayRow: 2,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 8,
    symbol: 'O',
    nameKey: 'toolbox.life.element.o.name',
    nameEn: 'Oxygen',
    atomicMass: '15.999',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1774',
    electronConfiguration: '[He]2s2 2p4',
    electronegativity: '3.44',
    atomicRadius: '152',
    ionizationEnergy: '13.618',
    electronAffinity: '1.461',
    oxidationStates: '-2',
    meltingPoint: '54.36',
    boilingPoint: '90.2',
    density: '0.001429',
    period: 2,
    group: 16,
    displayRow: 2,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 9,
    symbol: 'F',
    nameKey: 'toolbox.life.element.f.name',
    nameEn: 'Fluorine',
    atomicMass: '18.99840316',
    groupBlock: 'Halogen',
    groupBlockKey: 'toolbox.life.element.block.halogen',
    standardState: 'Gas',
    yearDiscovered: '1670',
    electronConfiguration: '[He]2s2 2p5',
    electronegativity: '3.98',
    atomicRadius: '135',
    ionizationEnergy: '17.423',
    electronAffinity: '3.339',
    oxidationStates: '-1',
    meltingPoint: '53.53',
    boilingPoint: '85.03',
    density: '0.001696',
    period: 2,
    group: 17,
    displayRow: 2,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 10,
    symbol: 'Ne',
    nameKey: 'toolbox.life.element.ne.name',
    nameEn: 'Neon',
    atomicMass: '20.180',
    groupBlock: 'Noble gas',
    groupBlockKey: 'toolbox.life.element.block.noble_gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[He]2s2 2p6',
    electronegativity: '',
    atomicRadius: '154',
    ionizationEnergy: '21.565',
    electronAffinity: '',
    oxidationStates: '0',
    meltingPoint: '24.56',
    boilingPoint: '27.07',
    density: '0.0008999',
    period: 2,
    group: 18,
    displayRow: 2,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 11,
    symbol: 'Na',
    nameKey: 'toolbox.life.element.na.name',
    nameEn: 'Sodium',
    atomicMass: '22.9897693',
    groupBlock: 'Alkali metal',
    groupBlockKey: 'toolbox.life.element.block.alkali_metal',
    standardState: 'Solid',
    yearDiscovered: '1807',
    electronConfiguration: '[Ne]3s1',
    electronegativity: '0.93',
    atomicRadius: '227',
    ionizationEnergy: '5.139',
    electronAffinity: '0.548',
    oxidationStates: '+1',
    meltingPoint: '370.95',
    boilingPoint: '1156',
    density: '0.97',
    period: 3,
    group: 1,
    displayRow: 3,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 12,
    symbol: 'Mg',
    nameKey: 'toolbox.life.element.mg.name',
    nameEn: 'Magnesium',
    atomicMass: '24.305',
    groupBlock: 'Alkaline earth metal',
    groupBlockKey: 'toolbox.life.element.block.alkaline_earth_metal',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[Ne]3s2',
    electronegativity: '1.31',
    atomicRadius: '173',
    ionizationEnergy: '7.646',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '923',
    boilingPoint: '1363',
    density: '1.74',
    period: 3,
    group: 2,
    displayRow: 3,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 13,
    symbol: 'Al',
    nameKey: 'toolbox.life.element.al.name',
    nameEn: 'Aluminum',
    atomicMass: '26.981538',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ne]3s2 3p1',
    electronegativity: '1.61',
    atomicRadius: '184',
    ionizationEnergy: '5.986',
    electronAffinity: '0.441',
    oxidationStates: '+3',
    meltingPoint: '933.437',
    boilingPoint: '2792',
    density: '2.70',
    period: 3,
    group: 13,
    displayRow: 3,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 14,
    symbol: 'Si',
    nameKey: 'toolbox.life.element.si.name',
    nameEn: 'Silicon',
    atomicMass: '28.085',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: '1854',
    electronConfiguration: '[Ne]3s2 3p2',
    electronegativity: '1.9',
    atomicRadius: '210',
    ionizationEnergy: '8.152',
    electronAffinity: '1.385',
    oxidationStates: '+4, +2, -4',
    meltingPoint: '1687',
    boilingPoint: '3538',
    density: '2.3296',
    period: 3,
    group: 14,
    displayRow: 3,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 15,
    symbol: 'P',
    nameKey: 'toolbox.life.element.p.name',
    nameEn: 'Phosphorus',
    atomicMass: '30.97376200',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Solid',
    yearDiscovered: '1669',
    electronConfiguration: '[Ne]3s2 3p3',
    electronegativity: '2.19',
    atomicRadius: '180',
    ionizationEnergy: '10.487',
    electronAffinity: '0.746',
    oxidationStates: '+5, +3, -3',
    meltingPoint: '317.3',
    boilingPoint: '553.65',
    density: '1.82',
    period: 3,
    group: 15,
    displayRow: 3,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 16,
    symbol: 'S',
    nameKey: 'toolbox.life.element.s.name',
    nameEn: 'Sulfur',
    atomicMass: '32.07',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ne]3s2 3p4',
    electronegativity: '2.58',
    atomicRadius: '180',
    ionizationEnergy: '10.360',
    electronAffinity: '2.077',
    oxidationStates: '+6, +4, -2',
    meltingPoint: '388.36',
    boilingPoint: '717.75',
    density: '2.067',
    period: 3,
    group: 16,
    displayRow: 3,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 17,
    symbol: 'Cl',
    nameKey: 'toolbox.life.element.cl.name',
    nameEn: 'Chlorine',
    atomicMass: '35.45',
    groupBlock: 'Halogen',
    groupBlockKey: 'toolbox.life.element.block.halogen',
    standardState: 'Gas',
    yearDiscovered: '1774',
    electronConfiguration: '[Ne]3s2 3p5',
    electronegativity: '3.16',
    atomicRadius: '175',
    ionizationEnergy: '12.968',
    electronAffinity: '3.617',
    oxidationStates: '+7, +5, +1, -1',
    meltingPoint: '171.65',
    boilingPoint: '239.11',
    density: '0.003214',
    period: 3,
    group: 17,
    displayRow: 3,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 18,
    symbol: 'Ar',
    nameKey: 'toolbox.life.element.ar.name',
    nameEn: 'Argon',
    atomicMass: '39.9',
    groupBlock: 'Noble gas',
    groupBlockKey: 'toolbox.life.element.block.noble_gas',
    standardState: 'Gas',
    yearDiscovered: '1894',
    electronConfiguration: '[Ne]3s2 3p6',
    electronegativity: '',
    atomicRadius: '188',
    ionizationEnergy: '15.760',
    electronAffinity: '',
    oxidationStates: '0',
    meltingPoint: '83.8',
    boilingPoint: '87.3',
    density: '0.0017837',
    period: 3,
    group: 18,
    displayRow: 3,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 19,
    symbol: 'K',
    nameKey: 'toolbox.life.element.k.name',
    nameEn: 'Potassium',
    atomicMass: '39.0983',
    groupBlock: 'Alkali metal',
    groupBlockKey: 'toolbox.life.element.block.alkali_metal',
    standardState: 'Solid',
    yearDiscovered: '1807',
    electronConfiguration: '[Ar]4s1',
    electronegativity: '0.82',
    atomicRadius: '275',
    ionizationEnergy: '4.341',
    electronAffinity: '0.501',
    oxidationStates: '+1',
    meltingPoint: '336.53',
    boilingPoint: '1032',
    density: '0.89',
    period: 4,
    group: 1,
    displayRow: 4,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 20,
    symbol: 'Ca',
    nameKey: 'toolbox.life.element.ca.name',
    nameEn: 'Calcium',
    atomicMass: '40.08',
    groupBlock: 'Alkaline earth metal',
    groupBlockKey: 'toolbox.life.element.block.alkaline_earth_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2',
    electronegativity: '1',
    atomicRadius: '231',
    ionizationEnergy: '6.113',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '1115',
    boilingPoint: '1757',
    density: '1.54',
    period: 4,
    group: 2,
    displayRow: 4,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 21,
    symbol: 'Sc',
    nameKey: 'toolbox.life.element.sc.name',
    nameEn: 'Scandium',
    atomicMass: '44.95591',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Ar]4s2 3d1',
    electronegativity: '1.36',
    atomicRadius: '211',
    ionizationEnergy: '6.561',
    electronAffinity: '0.188',
    oxidationStates: '+3',
    meltingPoint: '1814',
    boilingPoint: '3109',
    density: '2.99',
    period: 4,
    group: 3,
    displayRow: 4,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 22,
    symbol: 'Ti',
    nameKey: 'toolbox.life.element.ti.name',
    nameEn: 'Titanium',
    atomicMass: '47.867',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1791',
    electronConfiguration: '[Ar]4s2 3d2',
    electronegativity: '1.54',
    atomicRadius: '187',
    ionizationEnergy: '6.828',
    electronAffinity: '0.079',
    oxidationStates: '+4, +3, +2',
    meltingPoint: '1941',
    boilingPoint: '3560',
    density: '4.5',
    period: 4,
    group: 4,
    displayRow: 4,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 23,
    symbol: 'V',
    nameKey: 'toolbox.life.element.v.name',
    nameEn: 'Vanadium',
    atomicMass: '50.9415',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1801',
    electronConfiguration: '[Ar]4s2 3d3',
    electronegativity: '1.63',
    atomicRadius: '179',
    ionizationEnergy: '6.746',
    electronAffinity: '0.525',
    oxidationStates: '+5, +4, +3, +2',
    meltingPoint: '2183',
    boilingPoint: '3680',
    density: '6.0',
    period: 4,
    group: 5,
    displayRow: 4,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 24,
    symbol: 'Cr',
    nameKey: 'toolbox.life.element.cr.name',
    nameEn: 'Chromium',
    atomicMass: '51.996',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1797',
    electronConfiguration: '[Ar]3d5 4s1',
    electronegativity: '1.66',
    atomicRadius: '189',
    ionizationEnergy: '6.767',
    electronAffinity: '0.666',
    oxidationStates: '+6, +3, +2',
    meltingPoint: '2180',
    boilingPoint: '2944',
    density: '7.15',
    period: 4,
    group: 6,
    displayRow: 4,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 25,
    symbol: 'Mn',
    nameKey: 'toolbox.life.element.mn.name',
    nameEn: 'Manganese',
    atomicMass: '54.93804',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1774',
    electronConfiguration: '[Ar]4s2 3d5',
    electronegativity: '1.55',
    atomicRadius: '197',
    ionizationEnergy: '7.434',
    electronAffinity: '',
    oxidationStates: '+7, +4, +3, +2',
    meltingPoint: '1519',
    boilingPoint: '2334',
    density: '7.3',
    period: 4,
    group: 7,
    displayRow: 4,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 26,
    symbol: 'Fe',
    nameKey: 'toolbox.life.element.fe.name',
    nameEn: 'Iron',
    atomicMass: '55.84',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2 3d6',
    electronegativity: '1.83',
    atomicRadius: '194',
    ionizationEnergy: '7.902',
    electronAffinity: '0.163',
    oxidationStates: '+3, +2',
    meltingPoint: '1811',
    boilingPoint: '3134',
    density: '7.874',
    period: 4,
    group: 8,
    displayRow: 4,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 27,
    symbol: 'Co',
    nameKey: 'toolbox.life.element.co.name',
    nameEn: 'Cobalt',
    atomicMass: '58.93319',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1735',
    electronConfiguration: '[Ar]4s2 3d7',
    electronegativity: '1.88',
    atomicRadius: '192',
    ionizationEnergy: '7.881',
    electronAffinity: '0.661',
    oxidationStates: '+3, +2',
    meltingPoint: '1768',
    boilingPoint: '3200',
    density: '8.86',
    period: 4,
    group: 9,
    displayRow: 4,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 28,
    symbol: 'Ni',
    nameKey: 'toolbox.life.element.ni.name',
    nameEn: 'Nickel',
    atomicMass: '58.693',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1751',
    electronConfiguration: '[Ar]4s2 3d8',
    electronegativity: '1.91',
    atomicRadius: '163',
    ionizationEnergy: '7.640',
    electronAffinity: '1.156',
    oxidationStates: '+3, +2',
    meltingPoint: '1728',
    boilingPoint: '3186',
    density: '8.912',
    period: 4,
    group: 10,
    displayRow: 4,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 29,
    symbol: 'Cu',
    nameKey: 'toolbox.life.element.cu.name',
    nameEn: 'Copper',
    atomicMass: '63.55',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s1 3d10',
    electronegativity: '1.9',
    atomicRadius: '140',
    ionizationEnergy: '7.726',
    electronAffinity: '1.228',
    oxidationStates: '+2, +1',
    meltingPoint: '1357.77',
    boilingPoint: '2835',
    density: '8.933',
    period: 4,
    group: 11,
    displayRow: 4,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 30,
    symbol: 'Zn',
    nameKey: 'toolbox.life.element.zn.name',
    nameEn: 'Zinc',
    atomicMass: '65.4',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1746',
    electronConfiguration: '[Ar]4s2 3d10',
    electronegativity: '1.65',
    atomicRadius: '139',
    ionizationEnergy: '9.394',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '692.68',
    boilingPoint: '1180',
    density: '7.134',
    period: 4,
    group: 12,
    displayRow: 4,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 31,
    symbol: 'Ga',
    nameKey: 'toolbox.life.element.ga.name',
    nameEn: 'Gallium',
    atomicMass: '69.723',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1875',
    electronConfiguration: '[Ar]4s2 3d10 4p1',
    electronegativity: '1.81',
    atomicRadius: '187',
    ionizationEnergy: '5.999',
    electronAffinity: '0.3',
    oxidationStates: '+3',
    meltingPoint: '302.91',
    boilingPoint: '2477',
    density: '5.91',
    period: 4,
    group: 13,
    displayRow: 4,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 32,
    symbol: 'Ge',
    nameKey: 'toolbox.life.element.ge.name',
    nameEn: 'Germanium',
    atomicMass: '72.63',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: '1886',
    electronConfiguration: '[Ar]4s2 3d10 4p2',
    electronegativity: '2.01',
    atomicRadius: '211',
    ionizationEnergy: '7.900',
    electronAffinity: '1.35',
    oxidationStates: '+4, +2',
    meltingPoint: '1211.4',
    boilingPoint: '3106',
    density: '5.323',
    period: 4,
    group: 14,
    displayRow: 4,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 33,
    symbol: 'As',
    nameKey: 'toolbox.life.element.as.name',
    nameEn: 'Arsenic',
    atomicMass: '74.92159',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2 3d10 4p3',
    electronegativity: '2.18',
    atomicRadius: '185',
    ionizationEnergy: '9.815',
    electronAffinity: '0.81',
    oxidationStates: '+5, +3, -3',
    meltingPoint: '1090',
    boilingPoint: '887',
    density: '5.776',
    period: 4,
    group: 15,
    displayRow: 4,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 34,
    symbol: 'Se',
    nameKey: 'toolbox.life.element.se.name',
    nameEn: 'Selenium',
    atomicMass: '78.97',
    groupBlock: 'Nonmetal',
    groupBlockKey: 'toolbox.life.element.block.nonmetal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[Ar]4s2 3d10 4p4',
    electronegativity: '2.55',
    atomicRadius: '190',
    ionizationEnergy: '9.752',
    electronAffinity: '2.021',
    oxidationStates: '+6, +4, -2',
    meltingPoint: '493.65',
    boilingPoint: '958',
    density: '4.809',
    period: 4,
    group: 16,
    displayRow: 4,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 35,
    symbol: 'Br',
    nameKey: 'toolbox.life.element.br.name',
    nameEn: 'Bromine',
    atomicMass: '79.90',
    groupBlock: 'Halogen',
    groupBlockKey: 'toolbox.life.element.block.halogen',
    standardState: 'Liquid',
    yearDiscovered: '1826',
    electronConfiguration: '[Ar]4s2 3d10 4p5',
    electronegativity: '2.96',
    atomicRadius: '183',
    ionizationEnergy: '11.814',
    electronAffinity: '3.365',
    oxidationStates: '+5, +1, -1',
    meltingPoint: '265.95',
    boilingPoint: '331.95',
    density: '3.11',
    period: 4,
    group: 17,
    displayRow: 4,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 36,
    symbol: 'Kr',
    nameKey: 'toolbox.life.element.kr.name',
    nameEn: 'Krypton',
    atomicMass: '83.80',
    groupBlock: 'Noble gas',
    groupBlockKey: 'toolbox.life.element.block.noble_gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[Ar]4s2 3d10 4p6',
    electronegativity: '3',
    atomicRadius: '202',
    ionizationEnergy: '14.000',
    electronAffinity: '',
    oxidationStates: '0',
    meltingPoint: '115.79',
    boilingPoint: '119.93',
    density: '0.003733',
    period: 4,
    group: 18,
    displayRow: 4,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 37,
    symbol: 'Rb',
    nameKey: 'toolbox.life.element.rb.name',
    nameEn: 'Rubidium',
    atomicMass: '85.468',
    groupBlock: 'Alkali metal',
    groupBlockKey: 'toolbox.life.element.block.alkali_metal',
    standardState: 'Solid',
    yearDiscovered: '1861',
    electronConfiguration: '[Kr]5s1',
    electronegativity: '0.82',
    atomicRadius: '303',
    ionizationEnergy: '4.177',
    electronAffinity: '0.468',
    oxidationStates: '+1',
    meltingPoint: '312.46',
    boilingPoint: '961',
    density: '1.53',
    period: 5,
    group: 1,
    displayRow: 5,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 38,
    symbol: 'Sr',
    nameKey: 'toolbox.life.element.sr.name',
    nameEn: 'Strontium',
    atomicMass: '87.62',
    groupBlock: 'Alkaline earth metal',
    groupBlockKey: 'toolbox.life.element.block.alkaline_earth_metal',
    standardState: 'Solid',
    yearDiscovered: '1790',
    electronConfiguration: '[Kr]5s2',
    electronegativity: '0.95',
    atomicRadius: '249',
    ionizationEnergy: '5.695',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '1050',
    boilingPoint: '1655',
    density: '2.64',
    period: 5,
    group: 2,
    displayRow: 5,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 39,
    symbol: 'Y',
    nameKey: 'toolbox.life.element.y.name',
    nameEn: 'Yttrium',
    atomicMass: '88.90584',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1794',
    electronConfiguration: '[Kr]5s2 4d1',
    electronegativity: '1.22',
    atomicRadius: '219',
    ionizationEnergy: '6.217',
    electronAffinity: '0.307',
    oxidationStates: '+3',
    meltingPoint: '1795',
    boilingPoint: '3618',
    density: '4.47',
    period: 5,
    group: 3,
    displayRow: 5,
    displayColumn: 3,
  ),
];
