part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _densePremodernTimelineFacts = <_TimelineFact>[
  _TimelineFact(
    id: 'acheulean_tools',
    category: 'human',
    yearsBeforePresent: 1760000,
    displayZh: '约 176 万年前',
    displayEn: 'c. 1.76 million years ago',
    titleZh: '阿舍利石器传统出现',
    titleEn: 'Acheulean tool tradition appears',
    detailZh: '手斧等阿舍利工具体现早期人属长期稳定的技术传统和空间规划能力。',
    detailEn:
        'Hand axes and other Acheulean tools show durable early human technical traditions and spatial planning.',
    sourceName: 'Smithsonian Human Origins: tools',
    sourceUrl: 'https://humanorigins.si.edu/evidence/behavior/stone-tools',
  ),
  _TimelineFact(
    id: 'homo_heidelbergensis',
    category: 'human',
    yearsBeforePresent: 700000,
    displayZh: '约 70 万年前',
    displayEn: 'c. 700,000 years ago',
    titleZh: '海德堡人演化',
    titleEn: 'Homo heidelbergensis evolves',
    detailZh: '海德堡人常被视为尼安德特人、丹尼索瓦人和现代人类演化谱系中的重要近亲。',
    detailEn:
        'Homo heidelbergensis is often treated as an important relative in the ancestry of Neanderthals, Denisovans, and modern humans.',
    sourceName: 'Smithsonian: Homo heidelbergensis',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-heidelbergensis',
  ),
  _TimelineFact(
    id: 'blombos_symbolic_objects',
    category: 'human',
    yearsBeforePresent: 75000,
    displayZh: '约 7.5 万年前',
    displayEn: 'c. 75,000 years ago',
    titleZh: '布隆伯斯洞穴象征物证据',
    titleEn: 'Blombos Cave symbolic objects',
    detailZh: '刻划赭石和贝壳饰物显示早期现代人象征行为、装饰和社会身份表达。',
    detailEn:
        'Engraved ochre and shell beads show early modern human symbolic behavior, ornament, and social signaling.',
    sourceName: 'Britannica: Blombos Cave',
    sourceUrl: 'https://www.britannica.com/place/Blombos-Cave',
  ),
  _TimelineFact(
    id: 'first_australia_settlement',
    category: 'human',
    yearsBeforePresent: 65000,
    displayZh: '约 6.5 万年前',
    displayEn: 'c. 65,000 years ago',
    titleZh: '人类抵达澳大利亚大陆',
    titleEn: 'Humans reach Australia',
    detailZh: '考古证据显示现代人类很早便跨越海峡进入萨胡尔地区，扩展了全球迁徙范围。',
    detailEn:
        'Archaeological evidence shows modern humans crossed sea gaps into Sahul early in global dispersal.',
    sourceName: 'Britannica: Aboriginal peoples',
    sourceUrl: 'https://www.britannica.com/topic/Australian-Aboriginal',
  ),
  _TimelineFact(
    id: 'lascaux_cave_art',
    category: 'human',
    yearsBeforePresent: 17000,
    displayZh: '约 1.7 万年前',
    displayEn: 'c. 17,000 years ago',
    titleZh: '拉斯科洞穴绘画',
    titleEn: 'Lascaux cave paintings',
    detailZh: '拉斯科壁画是旧石器时代晚期视觉艺术的重要代表，呈现复杂动物图像和洞穴空间组织。',
    detailEn:
        'Lascaux is a major Upper Paleolithic visual-art site, with complex animal imagery and cave-space organization.',
    sourceName: 'Britannica: Lascaux',
    sourceUrl: 'https://www.britannica.com/place/Lascaux-Grotto',
  ),
  _TimelineFact(
    id: 'domestication_dog',
    category: 'human',
    yearsBeforePresent: 15000,
    displayZh: '约 1.5 万年前',
    displayEn: 'c. 15,000 years ago',
    titleZh: '犬的驯化扩展',
    titleEn: 'Dog domestication spreads',
    detailZh: '犬成为人类最早驯化动物之一，参与狩猎、警戒、迁徙和社会生活。',
    detailEn:
        'Dogs became among the earliest domesticated animals, joining hunting, guarding, mobility, and social life.',
    sourceName: 'Britannica: dog',
    sourceUrl: 'https://www.britannica.com/animal/dog',
  ),
  _TimelineFact(
    id: 'natufian_culture',
    category: 'civilization',
    yearsBeforePresent: 14526,
    displayZh: '约公元前 12500 年',
    displayEn: 'c. 12,500 BCE',
    titleZh: '纳图夫文化与半定居生活',
    titleEn: 'Natufian culture and semi-sedentism',
    detailZh: '黎凡特地区纳图夫文化显示采集狩猎人群的半定居、墓葬和谷物利用趋势。',
    detailEn:
        'Natufian culture in the Levant shows semi-sedentary foragers, burials, and intensive grain use.',
    sourceName: 'Britannica: Natufian culture',
    sourceUrl: 'https://www.britannica.com/topic/Natufian-culture',
  ),
  _TimelineFact(
    id: 'fertile_crescent_farming',
    category: 'civilization',
    yearsBeforePresent: 11526,
    displayZh: '约公元前 9500 年',
    displayEn: 'c. 9500 BCE',
    titleZh: '新月沃地农业扩展',
    titleEn: 'Farming expands in the Fertile Crescent',
    detailZh: '小麦、大麦、山羊和绵羊等驯化推动定居村落、储存经济和人口增长。',
    detailEn:
        'Domesticated wheat, barley, goats, and sheep supported villages, storage economies, and population growth.',
    sourceName: 'Britannica: agriculture origins',
    sourceUrl: 'https://www.britannica.com/topic/agriculture',
  ),
  _TimelineFact(
    id: 'rice_domestication',
    category: 'civilization',
    yearsBeforePresent: 10026,
    displayZh: '约公元前 8000 年',
    displayEn: 'c. 8000 BCE',
    titleZh: '水稻驯化与东亚农业',
    titleEn: 'Rice domestication and East Asian farming',
    detailZh: '稻作农业在长江流域等地区发展，成为东亚社会长期人口承载力的重要基础。',
    detailEn:
        'Rice farming developed in regions such as the Yangtze basin and became a long-term foundation of East Asian populations.',
    sourceName: 'Britannica: rice',
    sourceUrl: 'https://www.britannica.com/plant/rice',
  ),
  _TimelineFact(
    id: 'wheel_invention',
    category: 'civilization',
    yearsBeforePresent: 5526,
    displayZh: '约公元前 3500 年',
    displayEn: 'c. 3500 BCE',
    titleZh: '轮与轮车技术出现',
    titleEn: 'Wheel and wheeled vehicles appear',
    detailZh: '轮车与陶轮等技术改变运输、生产和区域交换，是欧亚技术史中的关键节点。',
    detailEn:
        'Wheeled vehicles and potter wheels changed transport, production, and regional exchange across Eurasia.',
    sourceName: 'Britannica: wheel',
    sourceUrl: 'https://www.britannica.com/technology/wheel',
  ),
  _TimelineFact(
    id: 'horse_domestication',
    category: 'civilization',
    yearsBeforePresent: 5526,
    displayZh: '约公元前 3500 年',
    displayEn: 'c. 3500 BCE',
    titleZh: '马的驯化与草原交通',
    titleEn: 'Horse domestication and steppe mobility',
    detailZh: '马的驯化增强长距离移动、运输和军事能力，深刻影响欧亚草原与农耕世界互动。',
    detailEn:
        'Horse domestication strengthened mobility, transport, and warfare, reshaping steppe and farming-world interactions.',
    sourceName: 'Britannica: horse',
    sourceUrl: 'https://www.britannica.com/animal/horse',
  ),
  _TimelineFact(
    id: 'pyramids_giza',
    category: 'civilization',
    yearsBeforePresent: 4596,
    displayZh: '约公元前 2570 年',
    displayEn: 'c. 2570 BCE',
    titleZh: '吉萨金字塔群建成',
    titleEn: 'Giza pyramid complex built',
    detailZh: '吉萨金字塔群体现古埃及国家动员、工程组织、宗教观念和王权象征。',
    detailEn:
        'The Giza pyramids show ancient Egyptian state mobilization, engineering, religion, and royal symbolism.',
    sourceName: 'UNESCO: Memphis and its Necropolis',
    sourceUrl: 'https://whc.unesco.org/en/list/86/',
  ),
  _TimelineFact(
    id: 'akkadian_empire',
    category: 'civilization',
    yearsBeforePresent: 4360,
    displayZh: '约公元前 2334 年',
    displayEn: 'c. 2334 BCE',
    titleZh: '阿卡德帝国兴起',
    titleEn: 'Akkadian Empire rises',
    detailZh: '阿卡德帝国常被视为最早的跨城邦帝国之一，整合美索不达米亚多地政治网络。',
    detailEn:
        'The Akkadian Empire is often treated as an early inter-city empire integrating Mesopotamian political networks.',
    sourceName: 'Britannica: Akkadian empire',
    sourceUrl: 'https://www.britannica.com/place/Akkad',
  ),
  _TimelineFact(
    id: 'minoan_civilization',
    category: 'civilization',
    yearsBeforePresent: 4026,
    displayZh: '约公元前 2000 年',
    displayEn: 'c. 2000 BCE',
    titleZh: '米诺斯文明宫殿体系',
    titleEn: 'Minoan palace civilization',
    detailZh: '克里特岛宫殿中心和海上网络展示青铜时代爱琴海复杂社会和艺术传统。',
    detailEn:
        'Cretan palace centers and maritime networks show complex Bronze Age Aegean society and art.',
    sourceName: 'Britannica: Minoan civilization',
    sourceUrl: 'https://www.britannica.com/topic/Minoan-civilization',
  ),
  _TimelineFact(
    id: 'mycenaean_greece',
    category: 'civilization',
    yearsBeforePresent: 3626,
    displayZh: '约公元前 1600 年',
    displayEn: 'c. 1600 BCE',
    titleZh: '迈锡尼希腊兴起',
    titleEn: 'Mycenaean Greece rises',
    detailZh: '迈锡尼宫殿、线形文字 B 和武士贵族文化构成希腊青铜时代晚期的重要形态。',
    detailEn:
        'Mycenaean palaces, Linear B writing, and warrior elites shaped Late Bronze Age Greece.',
    sourceName: 'Britannica: Mycenaean civilization',
    sourceUrl: 'https://www.britannica.com/topic/Mycenaean-civilization',
  ),
  _TimelineFact(
    id: 'late_bronze_age_collapse',
    category: 'civilization',
    yearsBeforePresent: 3226,
    displayZh: '约公元前 1200 年',
    displayEn: 'c. 1200 BCE',
    titleZh: '青铜时代晚期崩溃',
    titleEn: 'Late Bronze Age collapse',
    detailZh: '东地中海多处宫殿国家瓦解，贸易、战争、气候和迁徙等因素共同重塑区域秩序。',
    detailEn:
        'Palace states across the eastern Mediterranean collapsed amid trade, war, climate, and migration pressures.',
    sourceName: 'Britannica: Bronze Age',
    sourceUrl: 'https://www.britannica.com/event/Bronze-Age',
  ),
  _TimelineFact(
    id: 'phoenician_alphabet',
    category: 'civilization',
    yearsBeforePresent: 3076,
    displayZh: '约公元前 1050 年',
    displayEn: 'c. 1050 BCE',
    titleZh: '腓尼基字母传播',
    titleEn: 'Phoenician alphabet spreads',
    detailZh: '腓尼基字母通过贸易网络扩散，深刻影响希腊、拉丁和多种后世字母系统。',
    detailEn:
        'The Phoenician alphabet spread through trade networks and influenced Greek, Latin, and later alphabets.',
    sourceName: 'Britannica: Phoenician alphabet',
    sourceUrl: 'https://www.britannica.com/topic/Phoenician-alphabet',
  ),
  _TimelineFact(
    id: 'spring_and_autumn_period',
    category: 'civilization',
    yearsBeforePresent: 2796,
    displayZh: '约公元前 770 年',
    displayEn: 'c. 770 BCE',
    titleZh: '春秋时期开始',
    titleEn: 'Spring and Autumn period begins',
    detailZh: '周王室权威下降，诸侯竞争和思想流派发展，奠定东亚古典政治文化背景。',
    detailEn:
        'Zhou royal authority weakened as interstate competition and philosophical traditions developed in ancient China.',
    sourceName: 'Britannica: Spring and Autumn period',
    sourceUrl: 'https://www.britannica.com/event/Spring-and-Autumn-period',
  ),
  _TimelineFact(
    id: 'first_olympics',
    category: 'civilization',
    yearsBeforePresent: 2802,
    displayZh: '公元前 776 年',
    displayEn: '776 BCE',
    titleZh: '古代奥林匹克运动会传统',
    titleEn: 'Ancient Olympic Games tradition',
    detailZh: '奥林匹亚竞技会成为希腊城邦共同宗教、竞技和纪年传统的重要象征。',
    detailEn:
        'The games at Olympia became a shared Greek symbol of religion, athletics, and chronological tradition.',
    sourceName: 'Britannica: Olympic Games',
    sourceUrl: 'https://www.britannica.com/sports/Olympic-Games',
  ),
  _TimelineFact(
    id: 'rome_founding_tradition',
    category: 'civilization',
    yearsBeforePresent: 2779,
    displayZh: '传统纪年公元前 753 年',
    displayEn: 'traditional date 753 BCE',
    titleZh: '罗马建城传统',
    titleEn: 'Traditional founding of Rome',
    detailZh: '罗马建城传统虽含传说成分，但成为罗马身份、纪年和政治记忆的核心起点。',
    detailEn:
        'The founding tradition includes legend but became central to Roman identity, chronology, and political memory.',
    sourceName: 'Britannica: Rome',
    sourceUrl: 'https://www.britannica.com/place/Rome',
  ),
  _TimelineFact(
    id: 'upanishads',
    category: 'civilization',
    yearsBeforePresent: 2726,
    displayZh: '约公元前 700 年',
    displayEn: 'c. 700 BCE',
    titleZh: '《奥义书》思想传统形成',
    titleEn: 'Upanishadic traditions form',
    detailZh: '奥义书文本传统讨论梵、我、轮回和解脱，对南亚宗教哲学产生长期影响。',
    detailEn:
        'Upanishadic texts explored brahman, atman, rebirth, and liberation, deeply shaping South Asian thought.',
    sourceName: 'Britannica: Upanishad',
    sourceUrl: 'https://www.britannica.com/topic/Upanishad',
  ),
  _TimelineFact(
    id: 'babylonian_exile',
    category: 'civilization',
    yearsBeforePresent: 2612,
    displayZh: '公元前 586 年',
    displayEn: '586 BCE',
    titleZh: '巴比伦之囚',
    titleEn: 'Babylonian Exile',
    detailZh: '耶路撒冷陷落和流亡经历深刻影响犹太宗教传统、文本整理和共同体身份。',
    detailEn:
        'The fall of Jerusalem and exile deeply affected Jewish religious tradition, textual formation, and communal identity.',
    sourceName: 'Britannica: Babylonian Captivity',
    sourceUrl: 'https://www.britannica.com/event/Babylonian-Captivity',
  ),
  _TimelineFact(
    id: 'cyrus_cylinder',
    category: 'civilization',
    yearsBeforePresent: 2565,
    displayZh: '公元前 539 年',
    displayEn: '539 BCE',
    titleZh: '居鲁士占领巴比伦',
    titleEn: 'Cyrus captures Babylon',
    detailZh: '居鲁士进入巴比伦后，阿契美尼德帝国接管两河核心区，并形成帝国统治叙事。',
    detailEn:
        'After Cyrus entered Babylon, the Achaemenid Empire took over Mesopotamian cores and shaped imperial rule narratives.',
    sourceName: 'Britannica: Cyrus the Great',
    sourceUrl: 'https://www.britannica.com/biography/Cyrus-the-Great',
  ),
  _TimelineFact(
    id: 'greco_persian_wars',
    category: 'civilization',
    yearsBeforePresent: 2525,
    displayZh: '公元前 499-449 年',
    displayEn: '499-449 BCE',
    titleZh: '希波战争',
    titleEn: 'Greco-Persian Wars',
    detailZh: '希腊城邦与波斯帝国的战争重塑爱琴海政治格局，并影响古典希腊自我叙事。',
    detailEn:
        'Wars between Greek city-states and Persia reshaped Aegean politics and classical Greek self-understanding.',
    sourceName: 'Britannica: Greco-Persian Wars',
    sourceUrl: 'https://www.britannica.com/event/Greco-Persian-Wars',
  ),
  _TimelineFact(
    id: 'peloponnesian_war',
    category: 'civilization',
    yearsBeforePresent: 2457,
    displayZh: '公元前 431-404 年',
    displayEn: '431-404 BCE',
    titleZh: '伯罗奔尼撒战争',
    titleEn: 'Peloponnesian War',
    detailZh: '雅典与斯巴达联盟体系的长期战争削弱希腊城邦，并成为政治史书写经典案例。',
    detailEn:
        'The long war between Athenian and Spartan alliance systems weakened Greek poleis and became a classic political history case.',
    sourceName: 'Britannica: Peloponnesian War',
    sourceUrl: 'https://www.britannica.com/event/Peloponnesian-War',
  ),
  _TimelineFact(
    id: 'socrates_trial',
    category: 'civilization',
    yearsBeforePresent: 2425,
    displayZh: '公元前 399 年',
    displayEn: '399 BCE',
    titleZh: '苏格拉底受审与死亡',
    titleEn: 'Trial and death of Socrates',
    detailZh: '苏格拉底之死成为哲学、城邦法律、公共言论和教育传统讨论中的关键象征。',
    detailEn:
        'The death of Socrates became a key symbol in debates on philosophy, civic law, speech, and education.',
    sourceName: 'Britannica: Socrates',
    sourceUrl: 'https://www.britannica.com/biography/Socrates',
  ),
  _TimelineFact(
    id: 'alexander_conquests',
    category: 'civilization',
    yearsBeforePresent: 2360,
    displayZh: '公元前 334 年起',
    displayEn: 'from 334 BCE',
    titleZh: '亚历山大东征',
    titleEn: 'Alexander conquests begin',
    detailZh: '马其顿扩张连接东地中海、埃及、波斯和中亚，开启广泛的希腊化交流。',
    detailEn:
        'Macedonian expansion linked the eastern Mediterranean, Egypt, Persia, and Central Asia, launching Hellenistic exchange.',
    sourceName: 'Britannica: Alexander the Great',
    sourceUrl: 'https://www.britannica.com/biography/Alexander-the-Great',
  ),
  _TimelineFact(
    id: 'punic_wars',
    category: 'civilization',
    yearsBeforePresent: 2290,
    displayZh: '公元前 264-146 年',
    displayEn: '264-146 BCE',
    titleZh: '布匿战争',
    titleEn: 'Punic Wars',
    detailZh: '罗马与迦太基的系列战争确立罗马在西地中海的霸权，并推动共和国扩张。',
    detailEn:
        'The wars between Rome and Carthage established Roman dominance in the western Mediterranean.',
    sourceName: 'Britannica: Punic Wars',
    sourceUrl: 'https://www.britannica.com/event/Punic-Wars',
  ),
  _TimelineFact(
    id: 'silk_road_han',
    category: 'civilization',
    yearsBeforePresent: 2156,
    displayZh: '约公元前 130 年',
    displayEn: 'c. 130 BCE',
    titleZh: '丝绸之路陆路交流扩展',
    titleEn: 'Silk Road overland exchange expands',
    detailZh: '汉代向西交通与中亚网络结合，推动商品、技术、宗教和外交信息跨欧亚流动。',
    detailEn:
        'Han westward routes joined Central Asian networks, moving goods, technologies, religions, and diplomacy across Eurasia.',
    sourceName: 'Britannica: Silk Road',
    sourceUrl: 'https://www.britannica.com/topic/Silk-Road-trade-route',
  ),
  _TimelineFact(
    id: 'caesar_assassination',
    category: 'civilization',
    yearsBeforePresent: 2070,
    displayZh: '公元前 44 年',
    displayEn: '44 BCE',
    titleZh: '凯撒遇刺',
    titleEn: 'Assassination of Julius Caesar',
    detailZh: '凯撒遇刺加剧罗马共和国危机，最终推动罗马政治向帝国结构转变。',
    detailEn:
        'Caesar assassination intensified the Roman Republic crisis and helped push Roman politics toward empire.',
    sourceName: 'Britannica: Julius Caesar',
    sourceUrl: 'https://www.britannica.com/biography/Julius-Caesar-Roman-ruler',
  ),
  _TimelineFact(
    id: 'second_temple_destroyed',
    category: 'civilization',
    yearsBeforePresent: 1956,
    displayZh: '70 年',
    displayEn: '70 CE',
    titleZh: '第二圣殿被毁',
    titleEn: 'Second Temple destroyed',
    detailZh: '罗马军队攻陷耶路撒冷，第二圣殿被毁，犹太宗教与离散历史进入新阶段。',
    detailEn:
        'Roman forces captured Jerusalem and destroyed the Second Temple, reshaping Jewish religion and diaspora history.',
    sourceName: 'Britannica: Siege of Jerusalem',
    sourceUrl: 'https://www.britannica.com/event/Siege-of-Jerusalem-70',
  ),
  _TimelineFact(
    id: 'kushan_empire',
    category: 'civilization',
    yearsBeforePresent: 1926,
    displayZh: '约 1 世纪',
    displayEn: 'c. 1st century CE',
    titleZh: '贵霜帝国连接欧亚贸易',
    titleEn: 'Kushan Empire links Eurasian exchange',
    detailZh: '贵霜帝国控制中亚与北印度关键通道，促进佛教艺术、钱币和商贸传播。',
    detailEn:
        'The Kushan Empire controlled key Central Asian and North Indian routes, spreading Buddhist art, coinage, and trade.',
    sourceName: 'Britannica: Kushan dynasty',
    sourceUrl: 'https://www.britannica.com/place/Kushan-dynasty',
  ),
  _TimelineFact(
    id: 'three_kingdoms_china',
    category: 'civilization',
    yearsBeforePresent: 1806,
    displayZh: '220 年',
    displayEn: '220 CE',
    titleZh: '中国三国时期开始',
    titleEn: 'Three Kingdoms period begins in China',
    detailZh: '东汉结束后，魏蜀吴鼎立，长期影响中国政治记忆、军事叙事和文学传统。',
    detailEn:
        'After the Han, Wei, Shu, and Wu shaped Chinese political memory, military narratives, and literature.',
    sourceName: 'Britannica: Three Kingdoms',
    sourceUrl: 'https://www.britannica.com/event/Three-Kingdoms',
  ),
  _TimelineFact(
    id: 'edict_of_milan',
    category: 'civilization',
    yearsBeforePresent: 1713,
    displayZh: '313 年',
    displayEn: '313 CE',
    titleZh: '米兰敕令',
    titleEn: 'Edict of Milan',
    detailZh: '君士坦丁与李锡尼承认基督徒合法地位，改变罗马帝国宗教政策格局。',
    detailEn:
        'Constantine and Licinius recognized Christian legal standing, changing Roman imperial religious policy.',
    sourceName: 'Britannica: Edict of Milan',
    sourceUrl: 'https://www.britannica.com/event/Edict-of-Milan',
  ),
  _TimelineFact(
    id: 'council_of_nicaea',
    category: 'civilization',
    yearsBeforePresent: 1701,
    displayZh: '325 年',
    displayEn: '325 CE',
    titleZh: '第一次尼西亚公会议',
    titleEn: 'First Council of Nicaea',
    detailZh: '尼西亚会议处理基督论争议并形成信经传统，是早期基督教制度化的重要节点。',
    detailEn:
        'Nicaea addressed Christological disputes and shaped creedal tradition in early Christian institutional history.',
    sourceName: 'Britannica: Council of Nicaea',
    sourceUrl: 'https://www.britannica.com/event/First-Council-of-Nicaea-325',
  ),
  _TimelineFact(
    id: 'gupta_empire',
    category: 'civilization',
    yearsBeforePresent: 1706,
    displayZh: '约 320 年',
    displayEn: 'c. 320 CE',
    titleZh: '笈多帝国兴起',
    titleEn: 'Gupta Empire rises',
    detailZh: '笈多时期南亚数学、文学、宗教和艺术繁荣，成为古典印度文明的重要阶段。',
    detailEn:
        'The Gupta era saw major developments in South Asian mathematics, literature, religion, and art.',
    sourceName: 'Britannica: Gupta dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Gupta-dynasty',
  ),
  _TimelineFact(
    id: 'western_rome_falls',
    category: 'civilization',
    yearsBeforePresent: 1550,
    displayZh: '476 年',
    displayEn: '476 CE',
    titleZh: '西罗马帝国终结',
    titleEn: 'Western Roman Empire ends',
    detailZh: '西罗马皇帝被废常被作为古代晚期向欧洲中世纪政治结构转变的象征节点。',
    detailEn:
        'The deposition of the western emperor is often used as a marker of late antique political transformation.',
    sourceName: 'Britannica: Roman Empire',
    sourceUrl: 'https://www.britannica.com/place/Roman-Empire',
  ),
  _TimelineFact(
    id: 'justinian_code',
    category: 'civilization',
    yearsBeforePresent: 1497,
    displayZh: '529 年',
    displayEn: '529 CE',
    titleZh: '《查士丁尼法典》编纂',
    titleEn: 'Code of Justinian compiled',
    detailZh: '拜占庭法典整理罗马法传统，对后世欧洲法律教育和民法体系影响深远。',
    detailEn:
        'The Byzantine codification organized Roman law and deeply influenced later European legal traditions.',
    sourceName: 'Britannica: Code of Justinian',
    sourceUrl: 'https://www.britannica.com/topic/Code-of-Justinian',
  ),
  _TimelineFact(
    id: 'sui_reunification',
    category: 'civilization',
    yearsBeforePresent: 1437,
    displayZh: '589 年',
    displayEn: '589 CE',
    titleZh: '隋朝统一中国',
    titleEn: 'Sui reunification of China',
    detailZh: '隋朝结束南北长期分裂，重建大一统帝国行政，并开启大运河等工程。',
    detailEn:
        'The Sui ended long north-south division, rebuilt imperial administration, and launched major canal works.',
    sourceName: 'Britannica: Sui dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Sui-dynasty',
  ),
  _TimelineFact(
    id: 'umayyad_caliphate',
    category: 'civilization',
    yearsBeforePresent: 1365,
    displayZh: '661 年',
    displayEn: '661 CE',
    titleZh: '倭马亚哈里发王朝建立',
    titleEn: 'Umayyad Caliphate begins',
    detailZh: '倭马亚王朝推动阿拉伯帝国从伊比利亚至中亚的扩张和行政整合。',
    detailEn:
        'The Umayyads expanded and administered an Arab empire stretching from Iberia toward Central Asia.',
    sourceName: 'Britannica: Umayyad dynasty',
    sourceUrl:
        'https://www.britannica.com/topic/Umayyad-dynasty-Islamic-history',
  ),
  _TimelineFact(
    id: 'abbasid_baghdad',
    category: 'civilization',
    yearsBeforePresent: 1276,
    displayZh: '750-762 年',
    displayEn: '750-762 CE',
    titleZh: '阿拔斯革命与巴格达建都',
    titleEn: 'Abbasid revolution and Baghdad',
    detailZh: '阿拔斯王朝建立后建都巴格达，推动伊斯兰世界政治、商业和学术网络重组。',
    detailEn:
        'The Abbasids founded Baghdad and reorganized political, commercial, and scholarly networks in the Islamic world.',
    sourceName: 'Britannica: Abbasid dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Abbasid-dynasty',
  ),
  _TimelineFact(
    id: 'heian_period',
    category: 'civilization',
    yearsBeforePresent: 1232,
    displayZh: '794 年',
    displayEn: '794 CE',
    titleZh: '日本平安时代开始',
    titleEn: 'Heian period begins',
    detailZh: '迁都平安京后，日本宫廷文化、文学和贵族政治发展出稳定传统。',
    detailEn:
        'After the capital moved to Heian-kyo, court culture, literature, and aristocratic politics developed durable forms.',
    sourceName: 'Britannica: Heian period',
    sourceUrl: 'https://www.britannica.com/event/Heian-period',
  ),
  _TimelineFact(
    id: 'classic_maya',
    category: 'civilization',
    yearsBeforePresent: 1776,
    displayZh: '约 250 年起',
    displayEn: 'from c. 250 CE',
    titleZh: '玛雅古典期城市发展',
    titleEn: 'Classic Maya cities develop',
    detailZh: '玛雅低地城市国家发展出碑铭、天文历法、王权建筑和复杂区域竞争。',
    detailEn:
        'Maya lowland city-states developed inscriptions, astronomy, royal architecture, and regional competition.',
    sourceName: 'Britannica: Maya',
    sourceUrl: 'https://www.britannica.com/topic/Maya-people',
  ),
  _TimelineFact(
    id: 'viking_expansion',
    category: 'civilization',
    yearsBeforePresent: 1233,
    displayZh: '约 793 年起',
    displayEn: 'from c. 793 CE',
    titleZh: '维京扩张时代',
    titleEn: 'Viking expansion begins',
    detailZh: '斯堪的纳维亚航海者在欧洲、北大西洋和河流网络中贸易、定居和劫掠。',
    detailEn:
        'Scandinavian seafarers traded, settled, and raided across Europe, the North Atlantic, and river networks.',
    sourceName: 'Britannica: Viking',
    sourceUrl: 'https://www.britannica.com/topic/Viking-people',
  ),
  _TimelineFact(
    id: 'angkor_rise',
    category: 'civilization',
    yearsBeforePresent: 1224,
    displayZh: '802 年',
    displayEn: '802 CE',
    titleZh: '吴哥王权传统兴起',
    titleEn: 'Angkorian kingship rises',
    detailZh: '高棉吴哥政治中心依托水利、寺庙建筑和区域权力网络发展。',
    detailEn:
        'Angkorian centers developed through hydraulic works, temple architecture, and regional power networks.',
    sourceName: 'UNESCO: Angkor',
    sourceUrl: 'https://whc.unesco.org/en/list/668/',
  ),
  _TimelineFact(
    id: 'treaty_of_verdun',
    category: 'civilization',
    yearsBeforePresent: 1183,
    displayZh: '843 年',
    displayEn: '843 CE',
    titleZh: '凡尔登条约',
    titleEn: 'Treaty of Verdun',
    detailZh: '查理曼帝国被分割，成为西欧中世纪王国格局演变的重要起点之一。',
    detailEn:
        'The Carolingian Empire was divided, shaping later medieval kingdom patterns in western Europe.',
    sourceName: 'Britannica: Treaty of Verdun',
    sourceUrl: 'https://www.britannica.com/event/Treaty-of-Verdun',
  ),
  _TimelineFact(
    id: 'east_west_schism',
    category: 'civilization',
    yearsBeforePresent: 972,
    displayZh: '1054 年',
    displayEn: '1054 CE',
    titleZh: '东西教会大分裂',
    titleEn: 'East-West Schism',
    detailZh: '罗马公教和东正教传统的分裂加深，影响欧洲和地中海宗教政治格局。',
    detailEn:
        'The split between Roman Catholic and Eastern Orthodox traditions deepened across European and Mediterranean politics.',
    sourceName: 'Britannica: East-West Schism',
    sourceUrl: 'https://www.britannica.com/event/East-West-Schism-1054',
  ),
  _TimelineFact(
    id: 'norman_conquest',
    category: 'civilization',
    yearsBeforePresent: 960,
    displayZh: '1066 年',
    displayEn: '1066 CE',
    titleZh: '诺曼征服英格兰',
    titleEn: 'Norman Conquest of England',
    detailZh: '诺曼征服重塑英格兰贵族、土地制度、语言文化和王权结构。',
    detailEn:
        'The Norman Conquest reshaped English elites, landholding, language, and royal administration.',
    sourceName: 'Britannica: Norman Conquest',
    sourceUrl: 'https://www.britannica.com/event/Norman-Conquest',
  ),
  _TimelineFact(
    id: 'great_zimbabwe',
    category: 'civilization',
    yearsBeforePresent: 926,
    displayZh: '约 1100 年起',
    displayEn: 'from c. 1100 CE',
    titleZh: '大津巴布韦兴起',
    titleEn: 'Great Zimbabwe rises',
    detailZh: '石构城址和贸易网络展示南部非洲复杂社会、黄金贸易和区域权力。',
    detailEn:
        'Stone enclosures and trade networks show complex society, gold trade, and regional power in southern Africa.',
    sourceName: 'UNESCO: Great Zimbabwe',
    sourceUrl: 'https://whc.unesco.org/en/list/364/',
  ),
  _TimelineFact(
    id: 'kamakura_shogunate',
    category: 'civilization',
    yearsBeforePresent: 841,
    displayZh: '1185 年',
    displayEn: '1185 CE',
    titleZh: '镰仓幕府建立',
    titleEn: 'Kamakura shogunate begins',
    detailZh: '武家政权制度化，日本政治从宫廷贵族主导转向幕府和武士集团长期并存。',
    detailEn:
        'Warrior government became institutionalized as Japanese politics shifted toward shogunate and samurai power.',
    sourceName: 'Britannica: Kamakura period',
    sourceUrl: 'https://www.britannica.com/event/Kamakura-period',
  ),
  _TimelineFact(
    id: 'magna_carta',
    category: 'civilization',
    yearsBeforePresent: 811,
    displayZh: '1215 年',
    displayEn: '1215 CE',
    titleZh: '《大宪章》签署',
    titleEn: 'Magna Carta sealed',
    detailZh: '《大宪章》限制王权并确认部分贵族权利，后世成为法治和宪政传统的重要象征。',
    detailEn:
        'Magna Carta constrained royal power and became an enduring symbol in later rule-of-law traditions.',
    sourceName: 'UK National Archives: Magna Carta',
    sourceUrl:
        'https://www.nationalarchives.gov.uk/education/resources/magna-carta/',
  ),
  _TimelineFact(
    id: 'baghdad_1258',
    category: 'civilization',
    yearsBeforePresent: 768,
    displayZh: '1258 年',
    displayEn: '1258 CE',
    titleZh: '巴格达陷落',
    titleEn: 'Fall of Baghdad',
    detailZh: '蒙古军攻陷巴格达，阿拔斯哈里发在当地的政治中心终结，西亚格局重组。',
    detailEn:
        'Mongol forces captured Baghdad, ending the local Abbasid political center and reshaping West Asian politics.',
    sourceName: 'Britannica: Siege of Baghdad',
    sourceUrl: 'https://www.britannica.com/event/Siege-of-Baghdad-1258',
  ),
  _TimelineFact(
    id: 'yuan_dynasty',
    category: 'civilization',
    yearsBeforePresent: 755,
    displayZh: '1271 年',
    displayEn: '1271 CE',
    titleZh: '元朝建立',
    titleEn: 'Yuan dynasty founded',
    detailZh: '忽必烈建立元朝，蒙古帝国东亚部分转化为中国王朝体制，并连接欧亚网络。',
    detailEn:
        'Kublai Khan founded the Yuan, transforming the East Asian Mongol realm into a Chinese dynastic state.',
    sourceName: 'Britannica: Yuan dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Yuan-dynasty',
  ),
  _TimelineFact(
    id: 'ottoman_rise',
    category: 'civilization',
    yearsBeforePresent: 727,
    displayZh: '约 1299 年',
    displayEn: 'c. 1299 CE',
    titleZh: '奥斯曼国家兴起',
    titleEn: 'Ottoman state rises',
    detailZh: '安纳托利亚边疆政权逐步扩展为跨欧亚非三洲的奥斯曼帝国。',
    detailEn:
        'A frontier polity in Anatolia gradually expanded into the Ottoman Empire across Europe, Asia, and Africa.',
    sourceName: 'Britannica: Ottoman Empire',
    sourceUrl: 'https://www.britannica.com/place/Ottoman-Empire',
  ),
  _TimelineFact(
    id: 'hundred_years_war',
    category: 'civilization',
    yearsBeforePresent: 689,
    displayZh: '1337-1453 年',
    displayEn: '1337-1453 CE',
    titleZh: '英法百年战争',
    titleEn: 'Hundred Years War',
    detailZh: '英法长期战争推动王权财政、军事组织和民族政治认同变化。',
    detailEn:
        'The long Anglo-French war transformed royal finance, military organization, and political identity.',
    sourceName: 'Britannica: Hundred Years War',
    sourceUrl: 'https://www.britannica.com/event/Hundred-Years-War',
  ),
  _TimelineFact(
    id: 'renaissance',
    category: 'civilization',
    yearsBeforePresent: 626,
    displayZh: '约 1400 年起',
    displayEn: 'from c. 1400 CE',
    titleZh: '欧洲文艺复兴扩展',
    titleEn: 'European Renaissance expands',
    detailZh: '人文主义、古典文本复兴、艺术赞助和城市经济共同推动欧洲知识与视觉文化转型。',
    detailEn:
        'Humanism, classical texts, patronage, and urban economies transformed European knowledge and visual culture.',
    sourceName: 'Britannica: Renaissance',
    sourceUrl: 'https://www.britannica.com/event/Renaissance',
  ),
  _TimelineFact(
    id: 'treaty_tordesillas',
    category: 'modern',
    yearsBeforePresent: 532,
    displayZh: '1494 年',
    displayEn: '1494 CE',
    titleZh: '托尔德西里亚斯条约',
    titleEn: 'Treaty of Tordesillas',
    detailZh: '西班牙与葡萄牙划分海外势力范围，显示早期大西洋殖民扩张的制度化竞争。',
    detailEn:
        'Spain and Portugal divided overseas spheres, showing institutionalized competition in early Atlantic expansion.',
    sourceName: 'Britannica: Treaty of Tordesillas',
    sourceUrl: 'https://www.britannica.com/event/Treaty-of-Tordesillas',
  ),
];
