part of '../toolbox_life_tools.dart';

const List<_ElementFact> _elementFacts02 = <_ElementFact>[
  _ElementFact(
    atomicNumber: 40,
    symbol: 'Zr',
    nameKey: 'toolbox.life.element.zr.name',
    nameEn: 'Zirconium',
    atomicMass: '91.22',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1789',
    electronConfiguration: '[Kr]5s2 4d2',
    electronegativity: '1.33',
    atomicRadius: '186',
    ionizationEnergy: '6.634',
    electronAffinity: '0.426',
    oxidationStates: '+4',
    meltingPoint: '2128',
    boilingPoint: '4682',
    density: '6.52',
    period: 5,
    group: 4,
    displayRow: 5,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 41,
    symbol: 'Nb',
    nameKey: 'toolbox.life.element.nb.name',
    nameEn: 'Niobium',
    atomicMass: '92.90637',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1801',
    electronConfiguration: '[Kr]5s1 4d4',
    electronegativity: '1.6',
    atomicRadius: '207',
    ionizationEnergy: '6.759',
    electronAffinity: '0.893',
    oxidationStates: '+5, +3',
    meltingPoint: '2750',
    boilingPoint: '5017',
    density: '8.57',
    period: 5,
    group: 5,
    displayRow: 5,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 42,
    symbol: 'Mo',
    nameKey: 'toolbox.life.element.mo.name',
    nameEn: 'Molybdenum',
    atomicMass: '95.95',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1778',
    electronConfiguration: '[Kr]5s1 4d5',
    electronegativity: '2.16',
    atomicRadius: '209',
    ionizationEnergy: '7.092',
    electronAffinity: '0.746',
    oxidationStates: '+6',
    meltingPoint: '2896',
    boilingPoint: '4912',
    density: '10.2',
    period: 5,
    group: 6,
    displayRow: 5,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 43,
    symbol: 'Tc',
    nameKey: 'toolbox.life.element.tc.name',
    nameEn: 'Technetium',
    atomicMass: '96.90636',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1937',
    electronConfiguration: '[Kr]5s2 4d5',
    electronegativity: '1.9',
    atomicRadius: '209',
    ionizationEnergy: '7.28',
    electronAffinity: '0.55',
    oxidationStates: '+7, +6, +4',
    meltingPoint: '2430',
    boilingPoint: '4538',
    density: '11',
    period: 5,
    group: 7,
    displayRow: 5,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 44,
    symbol: 'Ru',
    nameKey: 'toolbox.life.element.ru.name',
    nameEn: 'Ruthenium',
    atomicMass: '101.1',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1827',
    electronConfiguration: '[Kr]5s1 4d7',
    electronegativity: '2.2',
    atomicRadius: '207',
    ionizationEnergy: '7.361',
    electronAffinity: '1.05',
    oxidationStates: '+3',
    meltingPoint: '2607',
    boilingPoint: '4423',
    density: '12.1',
    period: 5,
    group: 8,
    displayRow: 5,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 45,
    symbol: 'Rh',
    nameKey: 'toolbox.life.element.rh.name',
    nameEn: 'Rhodium',
    atomicMass: '102.9055',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Kr]5s1 4d8',
    electronegativity: '2.28',
    atomicRadius: '195',
    ionizationEnergy: '7.459',
    electronAffinity: '1.137',
    oxidationStates: '+3',
    meltingPoint: '2237',
    boilingPoint: '3968',
    density: '12.4',
    period: 5,
    group: 9,
    displayRow: 5,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 46,
    symbol: 'Pd',
    nameKey: 'toolbox.life.element.pd.name',
    nameEn: 'Palladium',
    atomicMass: '106.42',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Kr]4d10',
    electronegativity: '2.2',
    atomicRadius: '202',
    ionizationEnergy: '8.337',
    electronAffinity: '0.557',
    oxidationStates: '+3, +2',
    meltingPoint: '1828.05',
    boilingPoint: '3236',
    density: '12.0',
    period: 5,
    group: 10,
    displayRow: 5,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 47,
    symbol: 'Ag',
    nameKey: 'toolbox.life.element.ag.name',
    nameEn: 'Silver',
    atomicMass: '107.868',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s1 4d10',
    electronegativity: '1.93',
    atomicRadius: '172',
    ionizationEnergy: '7.576',
    electronAffinity: '1.302',
    oxidationStates: '+1',
    meltingPoint: '1234.93',
    boilingPoint: '2435',
    density: '10.501',
    period: 5,
    group: 11,
    displayRow: 5,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 48,
    symbol: 'Cd',
    nameKey: 'toolbox.life.element.cd.name',
    nameEn: 'Cadmium',
    atomicMass: '112.41',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[Kr]5s2 4d10',
    electronegativity: '1.69',
    atomicRadius: '158',
    ionizationEnergy: '8.994',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '594.22',
    boilingPoint: '1040',
    density: '8.69',
    period: 5,
    group: 12,
    displayRow: 5,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 49,
    symbol: 'In',
    nameKey: 'toolbox.life.element.in.name',
    nameEn: 'Indium',
    atomicMass: '114.818',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1863',
    electronConfiguration: '[Kr]5s2 4d10 5p1',
    electronegativity: '1.78',
    atomicRadius: '193',
    ionizationEnergy: '5.786',
    electronAffinity: '0.3',
    oxidationStates: '+3',
    meltingPoint: '429.75',
    boilingPoint: '2345',
    density: '7.31',
    period: 5,
    group: 13,
    displayRow: 5,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 50,
    symbol: 'Sn',
    nameKey: 'toolbox.life.element.sn.name',
    nameEn: 'Tin',
    atomicMass: '118.71',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s2 4d10 5p2',
    electronegativity: '1.96',
    atomicRadius: '217',
    ionizationEnergy: '7.344',
    electronAffinity: '1.2',
    oxidationStates: '+4, +2',
    meltingPoint: '505.08',
    boilingPoint: '2875',
    density: '7.287',
    period: 5,
    group: 14,
    displayRow: 5,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 51,
    symbol: 'Sb',
    nameKey: 'toolbox.life.element.sb.name',
    nameEn: 'Antimony',
    atomicMass: '121.760',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s2 4d10 5p3',
    electronegativity: '2.05',
    atomicRadius: '206',
    ionizationEnergy: '8.64',
    electronAffinity: '1.07',
    oxidationStates: '+5, +3, -3',
    meltingPoint: '903.78',
    boilingPoint: '1860',
    density: '6.685',
    period: 5,
    group: 15,
    displayRow: 5,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 52,
    symbol: 'Te',
    nameKey: 'toolbox.life.element.te.name',
    nameEn: 'Tellurium',
    atomicMass: '127.6',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: '1782',
    electronConfiguration: '[Kr]5s2 4d10 5p4',
    electronegativity: '2.1',
    atomicRadius: '206',
    ionizationEnergy: '9.010',
    electronAffinity: '1.971',
    oxidationStates: '+6, +4, -2',
    meltingPoint: '722.66',
    boilingPoint: '1261',
    density: '6.232',
    period: 5,
    group: 16,
    displayRow: 5,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 53,
    symbol: 'I',
    nameKey: 'toolbox.life.element.i.name',
    nameEn: 'Iodine',
    atomicMass: '126.9045',
    groupBlock: 'Halogen',
    groupBlockKey: 'toolbox.life.element.block.halogen',
    standardState: 'Solid',
    yearDiscovered: '1811',
    electronConfiguration: '[Kr]5s2 4d10 5p5',
    electronegativity: '2.66',
    atomicRadius: '198',
    ionizationEnergy: '10.451',
    electronAffinity: '3.059',
    oxidationStates: '+7, +5, +1, -1',
    meltingPoint: '386.85',
    boilingPoint: '457.55',
    density: '4.93',
    period: 5,
    group: 17,
    displayRow: 5,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 54,
    symbol: 'Xe',
    nameKey: 'toolbox.life.element.xe.name',
    nameEn: 'Xenon',
    atomicMass: '131.29',
    groupBlock: 'Noble gas',
    groupBlockKey: 'toolbox.life.element.block.noble_gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[Kr]5s2 4d10 5p6',
    electronegativity: '2.6',
    atomicRadius: '216',
    ionizationEnergy: '12.130',
    electronAffinity: '',
    oxidationStates: '0',
    meltingPoint: '161.36',
    boilingPoint: '165.03',
    density: '0.005887',
    period: 5,
    group: 18,
    displayRow: 5,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 55,
    symbol: 'Cs',
    nameKey: 'toolbox.life.element.cs.name',
    nameEn: 'Cesium',
    atomicMass: '132.9054520',
    groupBlock: 'Alkali metal',
    groupBlockKey: 'toolbox.life.element.block.alkali_metal',
    standardState: 'Solid',
    yearDiscovered: '1860',
    electronConfiguration: '[Xe]6s1',
    electronegativity: '0.79',
    atomicRadius: '343',
    ionizationEnergy: '3.894',
    electronAffinity: '0.472',
    oxidationStates: '+1',
    meltingPoint: '301.59',
    boilingPoint: '944',
    density: '1.93',
    period: 6,
    group: 1,
    displayRow: 6,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 56,
    symbol: 'Ba',
    nameKey: 'toolbox.life.element.ba.name',
    nameEn: 'Barium',
    atomicMass: '137.33',
    groupBlock: 'Alkaline earth metal',
    groupBlockKey: 'toolbox.life.element.block.alkaline_earth_metal',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[Xe]6s2',
    electronegativity: '0.89',
    atomicRadius: '268',
    ionizationEnergy: '5.212',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '1000',
    boilingPoint: '2170',
    density: '3.62',
    period: 6,
    group: 2,
    displayRow: 6,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 57,
    symbol: 'La',
    nameKey: 'toolbox.life.element.la.name',
    nameEn: 'Lanthanum',
    atomicMass: '138.9055',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1839',
    electronConfiguration: '[Xe]6s2 5d1',
    electronegativity: '1.1',
    atomicRadius: '240',
    ionizationEnergy: '5.577',
    electronAffinity: '0.5',
    oxidationStates: '+3',
    meltingPoint: '1191',
    boilingPoint: '3737',
    density: '6.15',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 58,
    symbol: 'Ce',
    nameKey: 'toolbox.life.element.ce.name',
    nameEn: 'Cerium',
    atomicMass: '140.116',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f1 5d1',
    electronegativity: '1.12',
    atomicRadius: '235',
    ionizationEnergy: '5.539',
    electronAffinity: '0.5',
    oxidationStates: '+4, +3',
    meltingPoint: '1071',
    boilingPoint: '3697',
    density: '6.770',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 59,
    symbol: 'Pr',
    nameKey: 'toolbox.life.element.pr.name',
    nameEn: 'Praseodymium',
    atomicMass: '140.90766',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1885',
    electronConfiguration: '[Xe]6s2 4f3',
    electronegativity: '1.13',
    atomicRadius: '239',
    ionizationEnergy: '5.464',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1204',
    boilingPoint: '3793',
    density: '6.77',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 60,
    symbol: 'Nd',
    nameKey: 'toolbox.life.element.nd.name',
    nameEn: 'Neodymium',
    atomicMass: '144.24',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1885',
    electronConfiguration: '[Xe]6s2 4f4',
    electronegativity: '1.14',
    atomicRadius: '229',
    ionizationEnergy: '5.525',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1294',
    boilingPoint: '3347',
    density: '7.01',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 61,
    symbol: 'Pm',
    nameKey: 'toolbox.life.element.pm.name',
    nameEn: 'Promethium',
    atomicMass: '144.91276',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1945',
    electronConfiguration: '[Xe]6s2 4f5',
    electronegativity: '',
    atomicRadius: '236',
    ionizationEnergy: '5.55',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1315',
    boilingPoint: '3273',
    density: '7.26',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 62,
    symbol: 'Sm',
    nameKey: 'toolbox.life.element.sm.name',
    nameEn: 'Samarium',
    atomicMass: '150.4',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Xe]6s2 4f6',
    electronegativity: '1.17',
    atomicRadius: '229',
    ionizationEnergy: '5.644',
    electronAffinity: '',
    oxidationStates: '+3, +2',
    meltingPoint: '1347',
    boilingPoint: '2067',
    density: '7.52',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 63,
    symbol: 'Eu',
    nameKey: 'toolbox.life.element.eu.name',
    nameEn: 'Europium',
    atomicMass: '151.964',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1901',
    electronConfiguration: '[Xe]6s2 4f7',
    electronegativity: '',
    atomicRadius: '233',
    ionizationEnergy: '5.670',
    electronAffinity: '',
    oxidationStates: '+3, +2',
    meltingPoint: '1095',
    boilingPoint: '1802',
    density: '5.24',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 64,
    symbol: 'Gd',
    nameKey: 'toolbox.life.element.gd.name',
    nameEn: 'Gadolinium',
    atomicMass: '157.25',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1880',
    electronConfiguration: '[Xe]6s2 4f7 5d1',
    electronegativity: '1.2',
    atomicRadius: '237',
    ionizationEnergy: '6.150',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1586',
    boilingPoint: '3546',
    density: '7.90',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 65,
    symbol: 'Tb',
    nameKey: 'toolbox.life.element.tb.name',
    nameEn: 'Terbium',
    atomicMass: '158.92535',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1843',
    electronConfiguration: '[Xe]6s2 4f9',
    electronegativity: '',
    atomicRadius: '221',
    ionizationEnergy: '5.864',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1629',
    boilingPoint: '3503',
    density: '8.23',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 66,
    symbol: 'Dy',
    nameKey: 'toolbox.life.element.dy.name',
    nameEn: 'Dysprosium',
    atomicMass: '162.500',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1886',
    electronConfiguration: '[Xe]6s2 4f10',
    electronegativity: '1.22',
    atomicRadius: '229',
    ionizationEnergy: '5.939',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1685',
    boilingPoint: '2840',
    density: '8.55',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 67,
    symbol: 'Ho',
    nameKey: 'toolbox.life.element.ho.name',
    nameEn: 'Holmium',
    atomicMass: '164.93033',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1878',
    electronConfiguration: '[Xe]6s2 4f11',
    electronegativity: '1.23',
    atomicRadius: '216',
    ionizationEnergy: '6.022',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1747',
    boilingPoint: '2973',
    density: '8.80',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 68,
    symbol: 'Er',
    nameKey: 'toolbox.life.element.er.name',
    nameEn: 'Erbium',
    atomicMass: '167.26',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1843',
    electronConfiguration: '[Xe]6s2 4f12',
    electronegativity: '1.24',
    atomicRadius: '235',
    ionizationEnergy: '6.108',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1802',
    boilingPoint: '3141',
    density: '9.07',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 69,
    symbol: 'Tm',
    nameKey: 'toolbox.life.element.tm.name',
    nameEn: 'Thulium',
    atomicMass: '168.93422',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Xe]6s2 4f13',
    electronegativity: '1.25',
    atomicRadius: '227',
    ionizationEnergy: '6.184',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1818',
    boilingPoint: '2223',
    density: '9.32',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 70,
    symbol: 'Yb',
    nameKey: 'toolbox.life.element.yb.name',
    nameEn: 'Ytterbium',
    atomicMass: '173.05',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1878',
    electronConfiguration: '[Xe]6s2 4f14',
    electronegativity: '',
    atomicRadius: '242',
    ionizationEnergy: '6.254',
    electronAffinity: '',
    oxidationStates: '+3, +2',
    meltingPoint: '1092',
    boilingPoint: '1469',
    density: '6.90',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 71,
    symbol: 'Lu',
    nameKey: 'toolbox.life.element.lu.name',
    nameEn: 'Lutetium',
    atomicMass: '174.9667',
    groupBlock: 'Lanthanide',
    groupBlockKey: 'toolbox.life.element.block.lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1907',
    electronConfiguration: '[Xe]6s2 4f14 5d1',
    electronegativity: '1.27',
    atomicRadius: '221',
    ionizationEnergy: '5.426',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1936',
    boilingPoint: '3675',
    density: '9.84',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 72,
    symbol: 'Hf',
    nameKey: 'toolbox.life.element.hf.name',
    nameEn: 'Hafnium',
    atomicMass: '178.49',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1923',
    electronConfiguration: '[Xe]6s2 4f14 5d2',
    electronegativity: '1.3',
    atomicRadius: '212',
    ionizationEnergy: '6.825',
    electronAffinity: '',
    oxidationStates: '+4',
    meltingPoint: '2506',
    boilingPoint: '4876',
    density: '13.3',
    period: 6,
    group: 4,
    displayRow: 6,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 73,
    symbol: 'Ta',
    nameKey: 'toolbox.life.element.ta.name',
    nameEn: 'Tantalum',
    atomicMass: '180.9479',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1802',
    electronConfiguration: '[Xe]6s2 4f14 5d3',
    electronegativity: '1.5',
    atomicRadius: '217',
    ionizationEnergy: '7.89',
    electronAffinity: '0.322',
    oxidationStates: '+5',
    meltingPoint: '3290',
    boilingPoint: '5731',
    density: '16.4',
    period: 6,
    group: 5,
    displayRow: 6,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 74,
    symbol: 'W',
    nameKey: 'toolbox.life.element.w.name',
    nameEn: 'Tungsten',
    atomicMass: '183.84',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1783',
    electronConfiguration: '[Xe]6s2 4f14 5d4',
    electronegativity: '2.36',
    atomicRadius: '210',
    ionizationEnergy: '7.98',
    electronAffinity: '0.815',
    oxidationStates: '+6',
    meltingPoint: '3695',
    boilingPoint: '5828',
    density: '19.3',
    period: 6,
    group: 6,
    displayRow: 6,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 75,
    symbol: 'Re',
    nameKey: 'toolbox.life.element.re.name',
    nameEn: 'Rhenium',
    atomicMass: '186.207',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1925',
    electronConfiguration: '[Xe]6s2 4f14 5d5',
    electronegativity: '1.9',
    atomicRadius: '217',
    ionizationEnergy: '7.88',
    electronAffinity: '0.15',
    oxidationStates: '+7, +6, +4',
    meltingPoint: '3459',
    boilingPoint: '5869',
    density: '20.8',
    period: 6,
    group: 7,
    displayRow: 6,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 76,
    symbol: 'Os',
    nameKey: 'toolbox.life.element.os.name',
    nameEn: 'Osmium',
    atomicMass: '190.2',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f14 5d6',
    electronegativity: '2.2',
    atomicRadius: '216',
    ionizationEnergy: '8.7',
    electronAffinity: '1.1',
    oxidationStates: '+4, +3',
    meltingPoint: '3306',
    boilingPoint: '5285',
    density: '22.57',
    period: 6,
    group: 8,
    displayRow: 6,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 77,
    symbol: 'Ir',
    nameKey: 'toolbox.life.element.ir.name',
    nameEn: 'Iridium',
    atomicMass: '192.22',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f14 5d7',
    electronegativity: '2.2',
    atomicRadius: '202',
    ionizationEnergy: '9.1',
    electronAffinity: '1.565',
    oxidationStates: '+4, +3',
    meltingPoint: '2719',
    boilingPoint: '4701',
    density: '22.42',
    period: 6,
    group: 9,
    displayRow: 6,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 78,
    symbol: 'Pt',
    nameKey: 'toolbox.life.element.pt.name',
    nameEn: 'Platinum',
    atomicMass: '195.08',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1735',
    electronConfiguration: '[Xe]6s1 4f14 5d9',
    electronegativity: '2.28',
    atomicRadius: '209',
    ionizationEnergy: '9',
    electronAffinity: '2.128',
    oxidationStates: '+4, +2',
    meltingPoint: '2041.55',
    boilingPoint: '4098',
    density: '21.46',
    period: 6,
    group: 10,
    displayRow: 6,
    displayColumn: 10,
  ),
];
