part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _generalTimelineFacts03 = <_TimelineFact>[
  _TimelineFact(
    id: 'germ_theory',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 153.5,
    displayKey: 'toolbox.life.timeline.general.germ_theory.date',
    titleKey: 'toolbox.life.timeline.general.germ_theory.title',
    detailKey: 'toolbox.life.timeline.general.germ_theory.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=germ%20theory%20of%20disease',
  ),
  _TimelineFact(
    id: 'maxwell_equations',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 161,
    displayKey: 'toolbox.life.timeline.general.maxwell_equations.date',
    titleKey: 'toolbox.life.timeline.general.maxwell_equations.title',
    detailKey: 'toolbox.life.timeline.general.maxwell_equations.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Maxwell\'s%20equations',
  ),
  _TimelineFact(
    id: 'telephone_patent',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 150,
    displayKey: 'toolbox.life.timeline.general.telephone_patent.date',
    titleKey: 'toolbox.life.timeline.general.telephone_patent.title',
    detailKey: 'toolbox.life.timeline.general.telephone_patent.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=invention%20of%20the%20telephone',
  ),
  _TimelineFact(
    id: 'incandescent_light',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 147,
    displayKey: 'toolbox.life.timeline.general.incandescent_light.date',
    titleKey: 'toolbox.life.timeline.general.incandescent_light.title',
    detailKey: 'toolbox.life.timeline.general.incandescent_light.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=incandescent%20light%20bulb',
  ),
  _TimelineFact(
    id: 'hertz_radio_waves',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 139,
    displayKey: 'toolbox.life.timeline.general.hertz_radio_waves.date',
    titleKey: 'toolbox.life.timeline.general.hertz_radio_waves.title',
    detailKey: 'toolbox.life.timeline.general.hertz_radio_waves.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Heinrich%20Hertz%20radio%20waves',
  ),
  _TimelineFact(
    id: 'x_rays_discovered',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 131,
    displayKey: 'toolbox.life.timeline.general.x_rays_discovered.date',
    titleKey: 'toolbox.life.timeline.general.x_rays_discovered.title',
    detailKey: 'toolbox.life.timeline.general.x_rays_discovered.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=discovery%20of%20X-rays',
  ),
  _TimelineFact(
    id: 'radioactivity_discovered',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 130,
    displayKey: 'toolbox.life.timeline.general.radioactivity_discovered.date',
    titleKey: 'toolbox.life.timeline.general.radioactivity_discovered.title',
    detailKey: 'toolbox.life.timeline.general.radioactivity_discovered.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=discovery%20of%20radioactivity',
  ),
  _TimelineFact(
    id: 'electron_discovered',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 129,
    displayKey: 'toolbox.life.timeline.general.electron_discovered.date',
    titleKey: 'toolbox.life.timeline.general.electron_discovered.title',
    detailKey: 'toolbox.life.timeline.general.electron_discovered.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=discovery%20of%20the%20electron',
  ),
  _TimelineFact(
    id: 'planck_quantum_hypothesis',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 126,
    displayKey: 'toolbox.life.timeline.general.planck_quantum_hypothesis.date',
    titleKey: 'toolbox.life.timeline.general.planck_quantum_hypothesis.title',
    detailKey: 'toolbox.life.timeline.general.planck_quantum_hypothesis.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Planck%20quantum%20hypothesis',
  ),
  _TimelineFact(
    id: 'special_relativity',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 121,
    displayKey: 'toolbox.life.timeline.general.special_relativity.date',
    titleKey: 'toolbox.life.timeline.general.special_relativity.title',
    detailKey: 'toolbox.life.timeline.general.special_relativity.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=special%20relativity',
  ),
  _TimelineFact(
    id: 'haber_bosch_process',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 115,
    displayKey: 'toolbox.life.timeline.general.haber_bosch_process.date',
    titleKey: 'toolbox.life.timeline.general.haber_bosch_process.title',
    detailKey: 'toolbox.life.timeline.general.haber_bosch_process.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Haber%20process',
  ),
  _TimelineFact(
    id: 'continental_drift',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 114,
    displayKey: 'toolbox.life.timeline.general.continental_drift.date',
    titleKey: 'toolbox.life.timeline.general.continental_drift.title',
    detailKey: 'toolbox.life.timeline.general.continental_drift.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=continental%20drift',
  ),
  _TimelineFact(
    id: 'penicillin_discovered',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 98,
    displayKey: 'toolbox.life.timeline.general.penicillin_discovered.date',
    titleKey: 'toolbox.life.timeline.general.penicillin_discovered.title',
    detailKey: 'toolbox.life.timeline.general.penicillin_discovered.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=discovery%20of%20penicillin',
  ),
  _TimelineFact(
    id: 'nuclear_fission',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 88,
    displayKey: 'toolbox.life.timeline.general.nuclear_fission.date',
    titleKey: 'toolbox.life.timeline.general.nuclear_fission.title',
    detailKey: 'toolbox.life.timeline.general.nuclear_fission.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=discovery%20of%20nuclear%20fission',
  ),
  _TimelineFact(
    id: 'transistor_invented',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 79,
    displayKey: 'toolbox.life.timeline.general.transistor_invented.date',
    titleKey: 'toolbox.life.timeline.general.transistor_invented.title',
    detailKey: 'toolbox.life.timeline.general.transistor_invented.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=invention%20of%20the%20transistor',
  ),
  _TimelineFact(
    id: 'eniac_completed',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 80.5,
    displayKey: 'toolbox.life.timeline.general.eniac_completed.date',
    titleKey: 'toolbox.life.timeline.general.eniac_completed.title',
    detailKey: 'toolbox.life.timeline.general.eniac_completed.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=ENIAC',
  ),
  _TimelineFact(
    id: 'polio_vaccine',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 71,
    displayKey: 'toolbox.life.timeline.general.polio_vaccine.date',
    titleKey: 'toolbox.life.timeline.general.polio_vaccine.title',
    detailKey: 'toolbox.life.timeline.general.polio_vaccine.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=polio%20vaccine',
  ),
  _TimelineFact(
    id: 'gagarin_spaceflight',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 65,
    displayKey: 'toolbox.life.timeline.general.gagarin_spaceflight.date',
    titleKey: 'toolbox.life.timeline.general.gagarin_spaceflight.title',
    detailKey: 'toolbox.life.timeline.general.gagarin_spaceflight.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Vostok%201',
  ),
  _TimelineFact(
    id: 'first_laser',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 66,
    displayKey: 'toolbox.life.timeline.general.first_laser.date',
    titleKey: 'toolbox.life.timeline.general.first_laser.title',
    detailKey: 'toolbox.life.timeline.general.first_laser.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=first%20working%20laser',
  ),
  _TimelineFact(
    id: 'plate_tectonics_consensus',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 59.5,
    displayKey: 'toolbox.life.timeline.general.plate_tectonics_consensus.date',
    titleKey: 'toolbox.life.timeline.general.plate_tectonics_consensus.title',
    detailKey: 'toolbox.life.timeline.general.plate_tectonics_consensus.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=plate%20tectonics',
  ),
  _TimelineFact(
    id: 'first_ivf_birth',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 48,
    displayKey: 'toolbox.life.timeline.general.first_ivf_birth.date',
    titleKey: 'toolbox.life.timeline.general.first_ivf_birth.title',
    detailKey: 'toolbox.life.timeline.general.first_ivf_birth.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Louise%20Brown',
  ),
  _TimelineFact(
    id: 'pcr_invented',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 43,
    displayKey: 'toolbox.life.timeline.general.pcr_invented.date',
    titleKey: 'toolbox.life.timeline.general.pcr_invented.title',
    detailKey: 'toolbox.life.timeline.general.pcr_invented.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=polymerase%20chain%20reaction',
  ),
  _TimelineFact(
    id: 'hubble_space_telescope',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 36,
    displayKey: 'toolbox.life.timeline.general.hubble_space_telescope.date',
    titleKey: 'toolbox.life.timeline.general.hubble_space_telescope.title',
    detailKey: 'toolbox.life.timeline.general.hubble_space_telescope.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hubble%20Space%20Telescope',
  ),
  _TimelineFact(
    id: 'first_exoplanet_sunlike_star',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 31,
    displayKey: 'toolbox.life.timeline.general.first_exoplanet_sunlike_star.date',
    titleKey: 'toolbox.life.timeline.general.first_exoplanet_sunlike_star.title',
    detailKey: 'toolbox.life.timeline.general.first_exoplanet_sunlike_star.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=51%20Pegasi%20b',
  ),
  _TimelineFact(
    id: 'dolly_cloned',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 30,
    displayKey: 'toolbox.life.timeline.general.dolly_cloned.date',
    titleKey: 'toolbox.life.timeline.general.dolly_cloned.title',
    detailKey: 'toolbox.life.timeline.general.dolly_cloned.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Dolly%20sheep',
  ),
  _TimelineFact(
    id: 'large_hadron_collider',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 18,
    displayKey: 'toolbox.life.timeline.general.large_hadron_collider.date',
    titleKey: 'toolbox.life.timeline.general.large_hadron_collider.title',
    detailKey: 'toolbox.life.timeline.general.large_hadron_collider.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Large%20Hadron%20Collider',
  ),
  _TimelineFact(
    id: 'mrna_vaccines_deployed',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 6,
    displayKey: 'toolbox.life.timeline.general.mrna_vaccines_deployed.date',
    titleKey: 'toolbox.life.timeline.general.mrna_vaccines_deployed.title',
    detailKey: 'toolbox.life.timeline.general.mrna_vaccines_deployed.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=mRNA%20vaccine',
  ),
  _TimelineFact(
    id: 'portuguese_goa',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 516,
    displayKey: 'toolbox.life.timeline.general.portuguese_goa.date',
    titleKey: 'toolbox.life.timeline.general.portuguese_goa.title',
    detailKey: 'toolbox.life.timeline.general.portuguese_goa.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Portuguese%20conquest%20of%20Goa',
  ),
  _TimelineFact(
    id: 'dutch_east_india_company',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 325.5,
    displayKey: 'toolbox.life.timeline.general.dutch_east_india_company.date',
    titleKey: 'toolbox.life.timeline.general.dutch_east_india_company.title',
    detailKey: 'toolbox.life.timeline.general.dutch_east_india_company.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Dutch%20East%20India%20Company',
  ),
  _TimelineFact(
    id: 'treaty_of_utrecht',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 312,
    displayKey: 'toolbox.life.timeline.general.treaty_of_utrecht.date',
    titleKey: 'toolbox.life.timeline.general.treaty_of_utrecht.title',
    detailKey: 'toolbox.life.timeline.general.treaty_of_utrecht.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Treaty%20of%20Utrecht',
  ),
  _TimelineFact(
    id: 'encyclopedie_publication',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 264.5,
    displayKey: 'toolbox.life.timeline.general.encyclopedie_publication.date',
    titleKey: 'toolbox.life.timeline.general.encyclopedie_publication.title',
    detailKey: 'toolbox.life.timeline.general.encyclopedie_publication.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Encyclopedie',
  ),
  _TimelineFact(
    id: 'greek_war_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 201,
    displayKey: 'toolbox.life.timeline.general.greek_war_independence.date',
    titleKey: 'toolbox.life.timeline.general.greek_war_independence.title',
    detailKey: 'toolbox.life.timeline.general.greek_war_independence.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Greek%20War%20of%20Independence',
  ),
  _TimelineFact(
    id: 'taiping_rebellion',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 169,
    displayKey: 'toolbox.life.timeline.general.taiping_rebellion.date',
    titleKey: 'toolbox.life.timeline.general.taiping_rebellion.title',
    detailKey: 'toolbox.life.timeline.general.taiping_rebellion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Taiping%20Rebellion',
  ),
  _TimelineFact(
    id: 'crimean_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 171.5,
    displayKey: 'toolbox.life.timeline.general.crimean_war.date',
    titleKey: 'toolbox.life.timeline.general.crimean_war.title',
    detailKey: 'toolbox.life.timeline.general.crimean_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Crimean%20War',
  ),
  _TimelineFact(
    id: 'perry_expedition_japan',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 172.5,
    displayKey: 'toolbox.life.timeline.general.perry_expedition_japan.date',
    titleKey: 'toolbox.life.timeline.general.perry_expedition_japan.title',
    detailKey: 'toolbox.life.timeline.general.perry_expedition_japan.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Perry%20Expedition',
  ),
  _TimelineFact(
    id: 'italian_unification',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 166.5,
    displayKey: 'toolbox.life.timeline.general.italian_unification.date',
    titleKey: 'toolbox.life.timeline.general.italian_unification.title',
    detailKey: 'toolbox.life.timeline.general.italian_unification.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Unification%20of%20Italy',
  ),
  _TimelineFact(
    id: 'emancipation_proclamation',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 163,
    displayKey: 'toolbox.life.timeline.general.emancipation_proclamation.date',
    titleKey: 'toolbox.life.timeline.general.emancipation_proclamation.title',
    detailKey: 'toolbox.life.timeline.general.emancipation_proclamation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Emancipation%20Proclamation',
  ),
  _TimelineFact(
    id: 'first_geneva_convention',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 162,
    displayKey: 'toolbox.life.timeline.general.first_geneva_convention.date',
    titleKey: 'toolbox.life.timeline.general.first_geneva_convention.title',
    detailKey: 'toolbox.life.timeline.general.first_geneva_convention.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=First%20Geneva%20Convention',
  ),
  _TimelineFact(
    id: 'first_international',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 156,
    displayKey: 'toolbox.life.timeline.general.first_international.date',
    titleKey: 'toolbox.life.timeline.general.first_international.title',
    detailKey: 'toolbox.life.timeline.general.first_international.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=International%20Workingmen\'s%20Association',
  ),
  _TimelineFact(
    id: 'berlin_conference',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 141.5,
    displayKey: 'toolbox.life.timeline.general.berlin_conference.date',
    titleKey: 'toolbox.life.timeline.general.berlin_conference.title',
    detailKey: 'toolbox.life.timeline.general.berlin_conference.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Berlin%20Conference',
  ),
  _TimelineFact(
    id: 'first_sino_japanese_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 131.5,
    displayKey: 'toolbox.life.timeline.general.first_sino_japanese_war.date',
    titleKey: 'toolbox.life.timeline.general.first_sino_japanese_war.title',
    detailKey: 'toolbox.life.timeline.general.first_sino_japanese_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=First%20Sino-Japanese%20War',
  ),
  _TimelineFact(
    id: 'spanish_american_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 128,
    displayKey: 'toolbox.life.timeline.general.spanish_american_war.date',
    titleKey: 'toolbox.life.timeline.general.spanish_american_war.title',
    detailKey: 'toolbox.life.timeline.general.spanish_american_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Spanish-American%20War',
  ),
  _TimelineFact(
    id: 'boxer_uprising',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 126,
    displayKey: 'toolbox.life.timeline.general.boxer_uprising.date',
    titleKey: 'toolbox.life.timeline.general.boxer_uprising.title',
    detailKey: 'toolbox.life.timeline.general.boxer_uprising.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Boxer%20Rebellion',
  ),
  _TimelineFact(
    id: 'russo_japanese_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 121.5,
    displayKey: 'toolbox.life.timeline.general.russo_japanese_war.date',
    titleKey: 'toolbox.life.timeline.general.russo_japanese_war.title',
    detailKey: 'toolbox.life.timeline.general.russo_japanese_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Russo-Japanese%20War',
  ),
  _TimelineFact(
    id: 'new_zealand_womens_suffrage',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 133,
    displayKey: 'toolbox.life.timeline.general.new_zealand_womens_suffrage.date',
    titleKey: 'toolbox.life.timeline.general.new_zealand_womens_suffrage.title',
    detailKey: 'toolbox.life.timeline.general.new_zealand_womens_suffrage.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=women\'s%20suffrage%20in%20New%20Zealand',
  ),
  _TimelineFact(
    id: 'mexican_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 111,
    displayKey: 'toolbox.life.timeline.general.mexican_revolution.date',
    titleKey: 'toolbox.life.timeline.general.mexican_revolution.title',
    detailKey: 'toolbox.life.timeline.general.mexican_revolution.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Mexican%20Revolution',
  ),
  _TimelineFact(
    id: 'march_on_rome',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 104,
    displayKey: 'toolbox.life.timeline.general.march_on_rome.date',
    titleKey: 'toolbox.life.timeline.general.march_on_rome.title',
    detailKey: 'toolbox.life.timeline.general.march_on_rome.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=March%20on%20Rome',
  ),
  _TimelineFact(
    id: 'turkish_republic_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 103,
    displayKey: 'toolbox.life.timeline.general.turkish_republic_founded.date',
    titleKey: 'toolbox.life.timeline.general.turkish_republic_founded.title',
    detailKey: 'toolbox.life.timeline.general.turkish_republic_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=proclamation%20of%20the%20Republic%20of%20Turkey',
  ),
  _TimelineFact(
    id: 'irish_free_state',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 104,
    displayKey: 'toolbox.life.timeline.general.irish_free_state.date',
    titleKey: 'toolbox.life.timeline.general.irish_free_state.title',
    detailKey: 'toolbox.life.timeline.general.irish_free_state.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Irish%20Free%20State',
  ),
  _TimelineFact(
    id: 'gandhi_salt_march',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 96,
    displayKey: 'toolbox.life.timeline.general.gandhi_salt_march.date',
    titleKey: 'toolbox.life.timeline.general.gandhi_salt_march.title',
    detailKey: 'toolbox.life.timeline.general.gandhi_salt_march.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Salt%20March',
  ),
  _TimelineFact(
    id: 'spanish_civil_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 88.5,
    displayKey: 'toolbox.life.timeline.general.spanish_civil_war.date',
    titleKey: 'toolbox.life.timeline.general.spanish_civil_war.title',
    detailKey: 'toolbox.life.timeline.general.spanish_civil_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Spanish%20Civil%20War',
  ),
  _TimelineFact(
    id: 'second_sino_japanese_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 85,
    displayKey: 'toolbox.life.timeline.general.second_sino_japanese_war.date',
    titleKey: 'toolbox.life.timeline.general.second_sino_japanese_war.title',
    detailKey: 'toolbox.life.timeline.general.second_sino_japanese_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Second%20Sino-Japanese%20War',
  ),
  _TimelineFact(
    id: 'indonesian_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 79,
    displayKey: 'toolbox.life.timeline.general.indonesian_independence.date',
    titleKey: 'toolbox.life.timeline.general.indonesian_independence.title',
    detailKey: 'toolbox.life.timeline.general.indonesian_independence.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Indonesian%20National%20Revolution',
  ),
  _TimelineFact(
    id: 'vietnam_independence_declared',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 81,
    displayKey: 'toolbox.life.timeline.general.vietnam_independence_declared.date',
    titleKey: 'toolbox.life.timeline.general.vietnam_independence_declared.title',
    detailKey: 'toolbox.life.timeline.general.vietnam_independence_declared.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Proclamation%20of%20Independence%20of%20the%20Democratic%20Republic%20of%20Vietnam',
  ),
  _TimelineFact(
    id: 'israel_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 78,
    displayKey: 'toolbox.life.timeline.general.israel_independence.date',
    titleKey: 'toolbox.life.timeline.general.israel_independence.title',
    detailKey: 'toolbox.life.timeline.general.israel_independence.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Israeli%20Declaration%20of%20Independence',
  ),
  _TimelineFact(
    id: 'geneva_conventions_1949',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 77,
    displayKey: 'toolbox.life.timeline.general.geneva_conventions_1949.date',
    titleKey: 'toolbox.life.timeline.general.geneva_conventions_1949.title',
    detailKey: 'toolbox.life.timeline.general.geneva_conventions_1949.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Geneva%20Conventions',
  ),
  _TimelineFact(
    id: 'european_human_rights_convention',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 76,
    displayKey: 'toolbox.life.timeline.general.european_human_rights_convention.date',
    titleKey: 'toolbox.life.timeline.general.european_human_rights_convention.title',
    detailKey: 'toolbox.life.timeline.general.european_human_rights_convention.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=European%20Convention%20on%20Human%20Rights',
  ),
  _TimelineFact(
    id: 'algerian_independence',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 64,
    displayKey: 'toolbox.life.timeline.general.algerian_independence.date',
    titleKey: 'toolbox.life.timeline.general.algerian_independence.title',
    detailKey: 'toolbox.life.timeline.general.algerian_independence.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Algerian%20independence',
  ),
  _TimelineFact(
    id: 'organization_african_unity',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 63,
    displayKey: 'toolbox.life.timeline.general.organization_african_unity.date',
    titleKey: 'toolbox.life.timeline.general.organization_african_unity.title',
    detailKey: 'toolbox.life.timeline.general.organization_african_unity.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Organisation%20of%20African%20Unity',
  ),
  _TimelineFact(
    id: 'asean_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 59,
    displayKey: 'toolbox.life.timeline.general.asean_founded.date',
    titleKey: 'toolbox.life.timeline.general.asean_founded.title',
    detailKey: 'toolbox.life.timeline.general.asean_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=ASEAN',
  ),
  _TimelineFact(
    id: 'vietnam_war_ends',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 51,
    displayKey: 'toolbox.life.timeline.general.vietnam_war_ends.date',
    titleKey: 'toolbox.life.timeline.general.vietnam_war_ends.title',
    detailKey: 'toolbox.life.timeline.general.vietnam_war_ends.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Fall%20of%20Saigon',
  ),
  _TimelineFact(
    id: 'helsinki_accords',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 51,
    displayKey: 'toolbox.life.timeline.general.helsinki_accords.date',
    titleKey: 'toolbox.life.timeline.general.helsinki_accords.title',
    detailKey: 'toolbox.life.timeline.general.helsinki_accords.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Helsinki%20Accords',
  ),
  _TimelineFact(
    id: 'solidarity_poland',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 41.5,
    displayKey: 'toolbox.life.timeline.general.solidarity_poland.date',
    titleKey: 'toolbox.life.timeline.general.solidarity_poland.title',
    detailKey: 'toolbox.life.timeline.general.solidarity_poland.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Solidarity%20Polish%20trade%20union',
  ),
  _TimelineFact(
    id: 'iran_iraq_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 42,
    displayKey: 'toolbox.life.timeline.general.iran_iraq_war.date',
    titleKey: 'toolbox.life.timeline.general.iran_iraq_war.title',
    detailKey: 'toolbox.life.timeline.general.iran_iraq_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Iran-Iraq%20War',
  ),
  _TimelineFact(
    id: 'maastricht_treaty',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 33.5,
    displayKey: 'toolbox.life.timeline.general.maastricht_treaty.date',
    titleKey: 'toolbox.life.timeline.general.maastricht_treaty.title',
    detailKey: 'toolbox.life.timeline.general.maastricht_treaty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Maastricht%20Treaty',
  ),
  _TimelineFact(
    id: 'rwandan_genocide',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 32,
    displayKey: 'toolbox.life.timeline.general.rwandan_genocide.date',
    titleKey: 'toolbox.life.timeline.general.rwandan_genocide.title',
    detailKey: 'toolbox.life.timeline.general.rwandan_genocide.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Rwandan%20genocide',
  ),
  _TimelineFact(
    id: 'good_friday_agreement',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 28,
    displayKey: 'toolbox.life.timeline.general.good_friday_agreement.date',
    titleKey: 'toolbox.life.timeline.general.good_friday_agreement.title',
    detailKey: 'toolbox.life.timeline.general.good_friday_agreement.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Good%20Friday%20Agreement',
  ),
  _TimelineFact(
    id: 'euro_introduced',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 25.5,
    displayKey: 'toolbox.life.timeline.general.euro_introduced.date',
    titleKey: 'toolbox.life.timeline.general.euro_introduced.title',
    detailKey: 'toolbox.life.timeline.general.euro_introduced.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=introduction%20of%20the%20euro',
  ),
  _TimelineFact(
    id: 'kyoto_protocol',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 25,
    displayKey: 'toolbox.life.timeline.general.kyoto_protocol.date',
    titleKey: 'toolbox.life.timeline.general.kyoto_protocol.title',
    detailKey: 'toolbox.life.timeline.general.kyoto_protocol.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Kyoto%20Protocol',
  ),
  _TimelineFact(
    id: 'war_in_afghanistan',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 15,
    displayKey: 'toolbox.life.timeline.general.war_in_afghanistan.date',
    titleKey: 'toolbox.life.timeline.general.war_in_afghanistan.title',
    detailKey: 'toolbox.life.timeline.general.war_in_afghanistan.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=War%20in%20Afghanistan%202001-2021',
  ),
  _TimelineFact(
    id: 'iraq_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 19,
    displayKey: 'toolbox.life.timeline.general.iraq_war.date',
    titleKey: 'toolbox.life.timeline.general.iraq_war.title',
    detailKey: 'toolbox.life.timeline.general.iraq_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Iraq%20War',
  ),
  _TimelineFact(
    id: 'african_union_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 24,
    displayKey: 'toolbox.life.timeline.general.african_union_founded.date',
    titleKey: 'toolbox.life.timeline.general.african_union_founded.title',
    detailKey: 'toolbox.life.timeline.general.african_union_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=African%20Union',
  ),
  _TimelineFact(
    id: 'brexit',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 8,
    displayKey: 'toolbox.life.timeline.general.brexit.date',
    titleKey: 'toolbox.life.timeline.general.brexit.title',
    detailKey: 'toolbox.life.timeline.general.brexit.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Brexit',
  ),
  _TimelineFact(
    id: 'russian_invasion_ukraine',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 4,
    displayKey: 'toolbox.life.timeline.general.russian_invasion_ukraine.date',
    titleKey: 'toolbox.life.timeline.general.russian_invasion_ukraine.title',
    detailKey: 'toolbox.life.timeline.general.russian_invasion_ukraine.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Russian%20invasion%20of%20Ukraine',
  ),
];
