part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _expandedHumanTimelineFacts = <_TimelineFact>[
  _TimelineFact(
    id: 'first_controlled_fire',
    category: 'human',
    yearsBeforePresent: 1000000,
    displayZh: '约 100 万年前',
    displayEn: 'c. 1 million years ago',
    titleZh: '早期人类控制用火证据',
    titleEn: 'Early evidence for controlled fire',
    detailZh: '用火改变了取暖、防御、食物处理和迁徙能力，是人类行为演化的重要进程。',
    detailEn:
        'Fire changed warmth, protection, food processing, and mobility, becoming a major process in human behavioral evolution.',
    sourceName: 'Britannica: control of fire',
    sourceUrl: 'https://www.britannica.com/science/control-of-fire',
  ),
  _TimelineFact(
    id: 'homo_erectus_spreads',
    category: 'human',
    yearsBeforePresent: 1900000,
    displayZh: '约 190 万年前',
    displayEn: 'c. 1.9 million years ago',
    titleZh: '直立人扩散',
    titleEn: 'Homo erectus expands',
    detailZh: '直立人相关化石和工具记录显示早期人属向非洲以外扩散，是人类迁徙史的重要阶段。',
    detailEn:
        'Homo erectus fossils and tools mark a major stage in early human dispersal beyond Africa.',
    sourceName: 'Smithsonian: Homo erectus',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-erectus',
  ),
  _TimelineFact(
    id: 'neanderthals',
    category: 'human',
    yearsBeforePresent: 400000,
    displayZh: '约 40 万年前',
    displayEn: 'c. 400,000 years ago',
    titleZh: '尼安德特人演化',
    titleEn: 'Neanderthals evolve',
    detailZh: '尼安德特人在欧亚多地留下化石、工具和文化行为证据，并与现代人类存在复杂互动。',
    detailEn:
        'Neanderthals left fossils, tools, and cultural evidence across Eurasia and interacted with modern humans.',
    sourceName: 'Smithsonian: Homo neanderthalensis',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-neanderthalensis',
  ),
  _TimelineFact(
    id: 'out_of_africa_major_dispersal',
    category: 'human',
    yearsBeforePresent: 70000,
    displayZh: '约 7 万年前',
    displayEn: 'c. 70,000 years ago',
    titleZh: '现代人类向非洲以外扩散',
    titleEn: 'Major Homo sapiens dispersals beyond Africa',
    detailZh: '遗传和考古证据支持现代人类在晚更新世向欧亚和更远地区扩散。',
    detailEn:
        'Genetic and archaeological evidence supports Late Pleistocene dispersals of modern humans across Eurasia and beyond.',
    sourceName: 'Smithsonian Human Origins Program',
    sourceUrl: 'https://humanorigins.si.edu/',
  ),
  _TimelineFact(
    id: 'upper_paleolithic_art',
    category: 'human',
    yearsBeforePresent: 40000,
    displayZh: '约 4 万年前',
    displayEn: 'c. 40,000 years ago',
    titleZh: '旧石器时代晚期艺术扩展',
    titleEn: 'Upper Paleolithic art expands',
    detailZh: '洞穴绘画、雕刻和象征性物件显示人类象征表达和社会传播能力的发展。',
    detailEn:
        'Cave paintings, carvings, and symbolic objects show expanding symbolic expression and social communication.',
    sourceName: 'Met Heilbrunn Timeline: Paleolithic Art',
    sourceUrl: 'https://www.metmuseum.org/toah/hd/pale/hd_pale.htm',
  ),
  _TimelineFact(
    id: 'settlement_gobekli_tepe',
    category: 'civilization',
    yearsBeforePresent: 11600,
    displayZh: '约公元前 9600 年',
    displayEn: 'c. 9600 BCE',
    titleZh: '哥贝克力石阵等早期仪式遗址',
    titleEn: 'Early monumental ritual sites such as Gobekli Tepe',
    detailZh: '大型石构遗址显示定居、仪式和组织能力在农业社会成熟前已开始发展。',
    detailEn:
        'Monumental stone sites show that settlement, ritual, and organization developed before mature farming societies.',
    sourceName: 'UNESCO: Gobekli Tepe',
    sourceUrl: 'https://whc.unesco.org/en/list/1572/',
  ),
  _TimelineFact(
    id: 'catalhoyuk',
    category: 'civilization',
    yearsBeforePresent: 9400,
    displayZh: '约公元前 7400 年',
    displayEn: 'c. 7400 BCE',
    titleZh: '加泰土丘聚落',
    titleEn: 'Catalhoyuk settlement',
    detailZh: '加泰土丘是新石器时代大型聚落代表，体现早期定居生活、建筑和象征文化。',
    detailEn:
        'Catalhoyuk is a major Neolithic settlement showing early settled life, architecture, and symbolic culture.',
    sourceName: 'UNESCO: Catalhoyuk',
    sourceUrl: 'https://whc.unesco.org/en/list/1405/',
  ),
  _TimelineFact(
    id: 'pottery_spread',
    category: 'civilization',
    yearsBeforePresent: 10000,
    displayZh: '约公元前 8000 年',
    displayEn: 'c. 8000 BCE',
    titleZh: '陶器技术广泛使用',
    titleEn: 'Pottery becomes widespread',
    detailZh: '陶器改善了储存、烹饪和定居生活的物质条件，在多地独立或扩散发展。',
    detailEn:
        'Pottery improved storage, cooking, and settled life and developed independently or through diffusion in multiple regions.',
    sourceName: 'Britannica: pottery',
    sourceUrl: 'https://www.britannica.com/art/pottery',
  ),
  _TimelineFact(
    id: 'sumerian_city_states',
    category: 'civilization',
    yearsBeforePresent: 5200,
    displayZh: '约公元前 3200 年',
    displayEn: 'c. 3200 BCE',
    titleZh: '苏美尔城邦与城市文明',
    titleEn: 'Sumerian city-states and urban civilization',
    detailZh: '美索不达米亚南部形成城邦、神庙经济、文字管理和复杂城市社会。',
    detailEn:
        'Southern Mesopotamia developed city-states, temple economies, written administration, and complex urban society.',
    sourceName: 'Britannica: Sumer',
    sourceUrl: 'https://www.britannica.com/place/Sumer',
  ),
  _TimelineFact(
    id: 'egypt_unification',
    category: 'civilization',
    yearsBeforePresent: 5126,
    displayZh: '约公元前 3100 年',
    displayEn: 'c. 3100 BCE',
    titleZh: '古埃及统一',
    titleEn: 'Unification of ancient Egypt',
    detailZh: '尼罗河流域上下埃及统一，形成持续数千年的王朝国家传统。',
    detailEn:
        'Upper and Lower Egypt unified along the Nile, beginning a dynastic state tradition lasting millennia.',
    sourceName: 'Met Heilbrunn Timeline: Egypt',
    sourceUrl: 'https://www.metmuseum.org/toah/hd/egyp/hd_egyp.htm',
  ),
  _TimelineFact(
    id: 'indus_civilization',
    category: 'civilization',
    yearsBeforePresent: 4626,
    displayZh: '约公元前 2600 年',
    displayEn: 'c. 2600 BCE',
    titleZh: '印度河文明成熟期',
    titleEn: 'Mature Indus Civilization',
    detailZh: '哈拉帕、摩亨佐-达罗等城市体现规划、排水、贸易和标准化度量体系。',
    detailEn:
        'Cities such as Harappa and Mohenjo-daro show planning, drainage, trade, and standardized measures.',
    sourceName: 'Britannica: Indus civilization',
    sourceUrl: 'https://www.britannica.com/topic/Indus-civilization',
  ),
  _TimelineFact(
    id: 'old_babylon_hammurabi',
    category: 'civilization',
    yearsBeforePresent: 3776,
    displayZh: '约公元前 1750 年',
    displayEn: 'c. 1750 BCE',
    titleZh: '汉谟拉比法典',
    titleEn: 'Code of Hammurabi',
    detailZh: '巴比伦法典传统展示早期国家治理、法律文本和社会等级秩序。',
    detailEn:
        'The Babylonian law-code tradition shows early state governance, legal writing, and social hierarchy.',
    sourceName: 'Louvre: Code of Hammurabi',
    sourceUrl:
        'https://www.louvre.fr/en/oeuvre-notices/law-code-hammurabi-king-babylon',
  ),
  _TimelineFact(
    id: 'shang_dynasty_oracle_bones',
    category: 'civilization',
    yearsBeforePresent: 3526,
    displayZh: '约公元前 1500 年',
    displayEn: 'c. 1500 BCE',
    titleZh: '商代与甲骨文',
    titleEn: 'Shang dynasty and oracle-bone writing',
    detailZh: '商代甲骨文是中国早期文字和国家祭祀、王权管理的重要证据。',
    detailEn:
        'Shang oracle-bone inscriptions are key evidence for early Chinese writing, ritual, and royal administration.',
    sourceName: 'Britannica: Shang dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Shang-dynasty',
  ),
  _TimelineFact(
    id: 'olmec_civilization',
    category: 'civilization',
    yearsBeforePresent: 3226,
    displayZh: '约公元前 1200 年',
    displayEn: 'c. 1200 BCE',
    titleZh: '奥尔梅克文明兴起',
    titleEn: 'Olmec civilization rises',
    detailZh: '奥尔梅克是中美洲早期复杂社会代表，其巨石头像和宗教艺术影响深远。',
    detailEn:
        'The Olmec were an early complex society in Mesoamerica, noted for colossal heads and influential religious art.',
    sourceName: 'Met Heilbrunn Timeline: Olmec',
    sourceUrl: 'https://www.metmuseum.org/toah/hd/olmc/hd_olmc.htm',
  ),
  _TimelineFact(
    id: 'zhou_mandate_of_heaven',
    category: 'civilization',
    yearsBeforePresent: 3072,
    displayZh: '公元前 1046 年',
    displayEn: '1046 BCE',
    titleZh: '周取代商与天命观念',
    titleEn: 'Zhou replaces Shang and Mandate of Heaven idea',
    detailZh: '周王朝建立后，天命观念成为东亚政治合法性叙事的重要传统。',
    detailEn:
        'After the Zhou replaced Shang, the Mandate of Heaven became a major East Asian narrative of political legitimacy.',
    sourceName: 'Britannica: Zhou dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Zhou-dynasty',
  ),
  _TimelineFact(
    id: 'greek_alphabet',
    category: 'civilization',
    yearsBeforePresent: 2826,
    displayZh: '约公元前 800 年',
    displayEn: 'c. 800 BCE',
    titleZh: '希腊字母形成',
    titleEn: 'Greek alphabet develops',
    detailZh: '希腊字母由腓尼基字母发展而来，对地中海文字传统和知识传播产生深远影响。',
    detailEn:
        'The Greek alphabet developed from Phoenician writing and deeply influenced Mediterranean literacy and knowledge transmission.',
    sourceName: 'Britannica: Greek alphabet',
    sourceUrl: 'https://www.britannica.com/topic/Greek-alphabet',
  ),
  _TimelineFact(
    id: 'buddha_life_tradition',
    category: 'civilization',
    yearsBeforePresent: 2526,
    displayZh: '约公元前 5 世纪',
    displayEn: 'c. 5th century BCE',
    titleZh: '佛教传统形成',
    titleEn: 'Buddhist tradition forms',
    detailZh: '释迦牟尼相关教法在南亚形成，并在后续数世纪传播至亚洲多地。',
    detailEn:
        'Teachings associated with the Buddha formed in South Asia and later spread widely across Asia.',
    sourceName: 'Britannica: Buddhism',
    sourceUrl: 'https://www.britannica.com/topic/Buddhism',
  ),
  _TimelineFact(
    id: 'confucius',
    category: 'civilization',
    yearsBeforePresent: 2505,
    displayZh: '公元前 551 年',
    displayEn: '551 BCE',
    titleZh: '孔子出生',
    titleEn: 'Birth of Confucius',
    detailZh: '孔子思想经后世整理、传承和制度化，深刻影响东亚伦理、教育和政治文化。',
    detailEn:
        'Confucius\' ideas, later compiled and institutionalized, profoundly shaped East Asian ethics, education, and political culture.',
    sourceName: 'Britannica: Confucius',
    sourceUrl: 'https://www.britannica.com/biography/Confucius',
  ),
  _TimelineFact(
    id: 'persian_empire_achaemenid',
    category: 'civilization',
    yearsBeforePresent: 2576,
    displayZh: '约公元前 550 年',
    displayEn: 'c. 550 BCE',
    titleZh: '阿契美尼德波斯帝国兴起',
    titleEn: 'Achaemenid Persian Empire rises',
    detailZh: '波斯帝国建立跨区域行政、道路和贡赋体系，连接西亚、埃及和中亚。',
    detailEn:
        'The Persian Empire built cross-regional administration, roads, and tribute systems across West Asia, Egypt, and Central Asia.',
    sourceName: 'Britannica: Achaemenian dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Achaemenian-dynasty',
  ),
  _TimelineFact(
    id: 'athenian_democracy',
    category: 'civilization',
    yearsBeforePresent: 2534,
    displayZh: '约公元前 508 年',
    displayEn: 'c. 508 BCE',
    titleZh: '雅典民主改革',
    titleEn: 'Athenian democratic reforms',
    detailZh: '雅典政治改革形成公民大会、抽签和陪审等制度传统，是古典民主史的重要节点。',
    detailEn:
        'Athenian reforms developed assemblies, selection by lot, and juries, a key node in the history of classical democracy.',
    sourceName: 'Britannica: Athenian democracy',
    sourceUrl: 'https://www.britannica.com/topic/Athenian-democracy',
  ),
  _TimelineFact(
    id: 'roman_republic',
    category: 'civilization',
    yearsBeforePresent: 2535,
    displayZh: '约公元前 509 年',
    displayEn: 'c. 509 BCE',
    titleZh: '罗马共和国传统开始',
    titleEn: 'Roman Republic begins',
    detailZh: '罗马共和国形成执政官、元老院和公民政治传统，并为后来的地中海扩张奠定制度基础。',
    detailEn:
        'The Roman Republic developed consuls, senate traditions, and citizen politics, shaping later Mediterranean expansion.',
    sourceName: 'Britannica: Roman Republic',
    sourceUrl: 'https://www.britannica.com/place/Roman-Republic',
  ),
  _TimelineFact(
    id: 'mauryan_empire_ashoka',
    category: 'civilization',
    yearsBeforePresent: 2294,
    displayZh: '约公元前 268 年',
    displayEn: 'c. 268 BCE',
    titleZh: '阿育王统治与孔雀帝国',
    titleEn: 'Ashoka and the Mauryan Empire',
    detailZh: '阿育王统治时期，孔雀帝国覆盖南亚大片地区，佛教传播和碑铭政治尤为重要。',
    detailEn:
        'Under Ashoka, the Mauryan Empire covered much of South Asia, with Buddhist patronage and edict inscriptions central to its legacy.',
    sourceName: 'Britannica: Ashoka',
    sourceUrl: 'https://www.britannica.com/biography/Ashoka',
  ),
  _TimelineFact(
    id: 'han_dynasty',
    category: 'civilization',
    yearsBeforePresent: 2232,
    displayZh: '公元前 206 年',
    displayEn: '206 BCE',
    titleZh: '汉朝建立',
    titleEn: 'Han dynasty begins',
    detailZh: '汉朝整合帝国行政、儒学传统和丝绸之路交流，成为东亚历史核心王朝之一。',
    detailEn:
        'The Han integrated imperial administration, Confucian traditions, and Silk Road exchange, becoming a core East Asian dynasty.',
    sourceName: 'Britannica: Han dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Han-dynasty',
  ),
  _TimelineFact(
    id: 'roman_empire_augustus',
    category: 'civilization',
    yearsBeforePresent: 2053,
    displayZh: '公元前 27 年',
    displayEn: '27 BCE',
    titleZh: '奥古斯都与罗马帝国',
    titleEn: 'Augustus and the Roman Empire',
    detailZh: '奥古斯都建立元首制，罗马从共和国转向帝国政治结构。',
    detailEn:
        'Augustus established the principate, shifting Rome from republican institutions toward imperial rule.',
    sourceName: 'Britannica: Augustus',
    sourceUrl: 'https://www.britannica.com/biography/Augustus-Roman-emperor',
  ),
  _TimelineFact(
    id: 'christianity_early_spread',
    category: 'civilization',
    yearsBeforePresent: 1996,
    displayZh: '约公元 30 年',
    displayEn: 'c. 30 CE',
    titleZh: '早期基督教形成',
    titleEn: 'Early Christianity forms',
    detailZh: '耶稣运动和早期教会在罗马帝国境内传播，逐步成为世界主要宗教传统之一。',
    detailEn:
        'The Jesus movement and early churches spread within the Roman Empire and became one of the world\'s major religious traditions.',
    sourceName: 'Britannica: Christianity',
    sourceUrl: 'https://www.britannica.com/topic/Christianity',
  ),
  _TimelineFact(
    id: 'constantinople_founded',
    category: 'civilization',
    yearsBeforePresent: 1696,
    displayZh: '330 年',
    displayEn: '330 CE',
    titleZh: '君士坦丁堡成为新都',
    titleEn: 'Constantinople becomes imperial capital',
    detailZh: '君士坦丁堡位于欧亚交汇处，成为东罗马/拜占庭政治、宗教和贸易中心。',
    detailEn:
        'Constantinople, positioned between Europe and Asia, became a political, religious, and trade center of the eastern Roman/Byzantine world.',
    sourceName: 'Britannica: Constantinople',
    sourceUrl: 'https://www.britannica.com/place/Constantinople',
  ),
  _TimelineFact(
    id: 'islam_hijra',
    category: 'civilization',
    yearsBeforePresent: 1404,
    displayZh: '622 年',
    displayEn: '622 CE',
    titleZh: '希吉拉与伊斯兰共同体',
    titleEn: 'Hijra and the Islamic community',
    detailZh: '穆罕默德迁徙至麦地那，成为伊斯兰历元和早期穆斯林共同体形成的重要节点。',
    detailEn:
        'Muhammad\'s migration to Medina marks the Islamic calendar epoch and a key step in forming the early Muslim community.',
    sourceName: 'Britannica: Hijrah',
    sourceUrl: 'https://www.britannica.com/event/Hijrah-Islam',
  ),
  _TimelineFact(
    id: 'tang_dynasty',
    category: 'civilization',
    yearsBeforePresent: 1408,
    displayZh: '618 年',
    displayEn: '618 CE',
    titleZh: '唐朝建立',
    titleEn: 'Tang dynasty begins',
    detailZh: '唐朝连接东亚、中亚和海上贸易网络，文学、制度和国际交流高度发展。',
    detailEn:
        'The Tang linked East Asia, Central Asia, and maritime networks, with highly developed literature, institutions, and exchange.',
    sourceName: 'Britannica: Tang dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Tang-dynasty',
  ),
  _TimelineFact(
    id: 'carolingian_coronation',
    category: 'civilization',
    yearsBeforePresent: 1226,
    displayZh: '800 年',
    displayEn: '800 CE',
    titleZh: '查理曼加冕',
    titleEn: 'Charlemagne crowned emperor',
    detailZh: '查理曼加冕象征西欧拉丁基督教政治秩序重组，对中世纪欧洲影响深远。',
    detailEn:
        'Charlemagne\'s coronation symbolized a reorganization of Latin Christian political order in western Europe.',
    sourceName: 'Britannica: Charlemagne',
    sourceUrl: 'https://www.britannica.com/biography/Charlemagne',
  ),
  _TimelineFact(
    id: 'song_printing_commerce',
    category: 'civilization',
    yearsBeforePresent: 1066,
    displayZh: '960 年',
    displayEn: '960 CE',
    titleZh: '宋代商业与印刷扩展',
    titleEn: 'Song commerce and printing expand',
    detailZh: '宋代城市商业、纸币、印刷和技术传播发展，改变东亚经济与知识流通。',
    detailEn:
        'Song urban commerce, paper money, printing, and technologies reshaped East Asian economy and knowledge circulation.',
    sourceName: 'Britannica: Song dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Song-dynasty',
  ),
  _TimelineFact(
    id: 'crusades_begin',
    category: 'civilization',
    yearsBeforePresent: 931,
    displayZh: '1095 年',
    displayEn: '1095 CE',
    titleZh: '十字军运动开始',
    titleEn: 'Crusades begin',
    detailZh: '十字军运动改变地中海政治、宗教和贸易互动，也加深欧亚文化接触。',
    detailEn:
        'The Crusades reshaped Mediterranean politics, religion, and trade and intensified Eurasian cultural contacts.',
    sourceName: 'Britannica: Crusades',
    sourceUrl: 'https://www.britannica.com/event/Crusades',
  ),
  _TimelineFact(
    id: 'mongol_empire',
    category: 'civilization',
    yearsBeforePresent: 820,
    displayZh: '1206 年',
    displayEn: '1206 CE',
    titleZh: '蒙古帝国形成',
    titleEn: 'Mongol Empire forms',
    detailZh: '成吉思汗统一蒙古诸部，随后建立横跨欧亚的帝国网络。',
    detailEn:
        'Chinggis Khan united Mongol groups, launching an empire-spanning Eurasian network.',
    sourceName: 'Britannica: Mongol empire',
    sourceUrl: 'https://www.britannica.com/place/Mongol-empire',
  ),
  _TimelineFact(
    id: 'mali_mansa_musa',
    category: 'civilization',
    yearsBeforePresent: 702,
    displayZh: '1324-1325 年',
    displayEn: '1324-1325 CE',
    titleZh: '曼萨·穆萨朝觐',
    titleEn: 'Mansa Musa\'s pilgrimage',
    detailZh: '马里帝国统治者曼萨·穆萨朝觐麦加，凸显西非黄金贸易、伊斯兰网络和廷巴克图声望。',
    detailEn:
        'Mansa Musa\'s pilgrimage highlighted West African gold trade, Islamic networks, and Timbuktu\'s prestige.',
    sourceName: 'Britannica: Mansa Musa',
    sourceUrl: 'https://www.britannica.com/biography/Musa-I-of-Mali',
  ),
  _TimelineFact(
    id: 'ming_voyages_zheng_he',
    category: 'civilization',
    yearsBeforePresent: 621,
    displayZh: '1405-1433 年',
    displayEn: '1405-1433 CE',
    titleZh: '郑和下西洋',
    titleEn: 'Zheng He voyages',
    detailZh: '明代大型远航连接东南亚、印度洋、阿拉伯海和东非，展示国家级海上动员能力。',
    detailEn:
        'Ming maritime expeditions connected Southeast Asia, the Indian Ocean, the Arabian Sea, and East Africa.',
    sourceName: 'Britannica: Zheng He',
    sourceUrl: 'https://www.britannica.com/biography/Zheng-He',
  ),
  _TimelineFact(
    id: 'constantinople_1453',
    category: 'civilization',
    yearsBeforePresent: 573,
    displayZh: '1453 年',
    displayEn: '1453 CE',
    titleZh: '君士坦丁堡陷落',
    titleEn: 'Fall of Constantinople',
    detailZh: '奥斯曼帝国攻占君士坦丁堡，拜占庭帝国终结，地中海政治格局改变。',
    detailEn:
        'The Ottomans captured Constantinople, ending the Byzantine Empire and changing Mediterranean politics.',
    sourceName: 'Britannica: Fall of Constantinople',
    sourceUrl: 'https://www.britannica.com/event/Fall-of-Constantinople-1453',
  ),
  _TimelineFact(
    id: 'columbus_voyage',
    category: 'modern',
    yearsBeforePresent: 534,
    displayZh: '1492 年',
    displayEn: '1492 CE',
    titleZh: '哥伦布航行至美洲',
    titleEn: 'Columbus reaches the Americas',
    detailZh: '大西洋航行开启持续的欧亚非美洲交流、殖民扩张和哥伦布大交换。',
    detailEn:
        'Atlantic voyages initiated sustained exchange, colonial expansion, and the Columbian Exchange among Afro-Eurasia and the Americas.',
    sourceName: 'Britannica: Christopher Columbus',
    sourceUrl: 'https://www.britannica.com/biography/Christopher-Columbus',
  ),
  _TimelineFact(
    id: 'vasco_da_gama',
    category: 'modern',
    yearsBeforePresent: 528,
    displayZh: '1498 年',
    displayEn: '1498 CE',
    titleZh: '达伽马抵达印度洋贸易网络',
    titleEn: 'Vasco da Gama reaches India by sea',
    detailZh: '葡萄牙航路将欧洲直接接入印度洋贸易体系，重塑全球海上商业竞争。',
    detailEn:
        'The Portuguese sea route connected Europe directly to Indian Ocean trade and reshaped global maritime commerce.',
    sourceName: 'Britannica: Vasco da Gama',
    sourceUrl: 'https://www.britannica.com/biography/Vasco-da-Gama',
  ),
  _TimelineFact(
    id: 'aztec_conquest',
    category: 'modern',
    yearsBeforePresent: 505,
    displayZh: '1521 年',
    displayEn: '1521 CE',
    titleZh: '阿兹特克帝国被西班牙征服',
    titleEn: 'Spanish conquest of the Aztec Empire',
    detailZh: '特诺奇蒂特兰陷落后，西班牙殖民统治在墨西哥中部展开。',
    detailEn:
        'After Tenochtitlan fell, Spanish colonial rule expanded in central Mexico.',
    sourceName: 'Britannica: Aztec',
    sourceUrl: 'https://www.britannica.com/topic/Aztec',
  ),
  _TimelineFact(
    id: 'inca_conquest',
    category: 'modern',
    yearsBeforePresent: 493,
    displayZh: '1533 年',
    displayEn: '1533 CE',
    titleZh: '印加帝国被西班牙征服',
    titleEn: 'Spanish conquest of the Inca Empire',
    detailZh: '印加帝国核心被西班牙征服，安第斯地区殖民秩序逐步形成。',
    detailEn:
        'The Inca imperial core was conquered by Spain, and colonial order developed across the Andes.',
    sourceName: 'Britannica: Inca',
    sourceUrl: 'https://www.britannica.com/topic/Inca',
  ),
  _TimelineFact(
    id: 'reformation_luther',
    category: 'modern',
    yearsBeforePresent: 509,
    displayZh: '1517 年',
    displayEn: '1517 CE',
    titleZh: '宗教改革开始',
    titleEn: 'Protestant Reformation begins',
    detailZh: '马丁·路德相关争论引发西欧宗教、政治和印刷传播格局变化。',
    detailEn:
        'Debates associated with Martin Luther reshaped western European religion, politics, and print communication.',
    sourceName: 'Britannica: Reformation',
    sourceUrl: 'https://www.britannica.com/event/Reformation',
  ),
  _TimelineFact(
    id: 'copernicus',
    category: 'science',
    yearsBeforePresent: 483,
    displayZh: '1543 年',
    displayEn: '1543 CE',
    titleZh: '哥白尼日心说著作出版',
    titleEn: 'Copernicus publishes heliocentric model',
    detailZh: '《天体运行论》提出日心宇宙模型，成为近代科学革命的重要开端之一。',
    detailEn:
        'On the Revolutions proposed a heliocentric model and became a major starting point of the Scientific Revolution.',
    sourceName: 'Britannica: Copernicus',
    sourceUrl: 'https://www.britannica.com/biography/Nicolaus-Copernicus',
  ),
  _TimelineFact(
    id: 'galileo_telescope',
    category: 'science',
    yearsBeforePresent: 416,
    displayZh: '1610 年',
    displayEn: '1610 CE',
    titleZh: '伽利略望远镜观测',
    titleEn: 'Galileo\'s telescopic observations',
    detailZh: '伽利略发表月面、木星卫星等观测，推动天文学和实验科学方法发展。',
    detailEn:
        'Galileo published observations of the Moon, Jupiter\'s moons, and more, advancing astronomy and experimental science.',
    sourceName: 'Britannica: Galileo',
    sourceUrl: 'https://www.britannica.com/biography/Galileo-Galilei',
  ),
  _TimelineFact(
    id: 'westphalia',
    category: 'modern',
    yearsBeforePresent: 378,
    displayZh: '1648 年',
    displayEn: '1648 CE',
    titleZh: '威斯特伐利亚和约',
    titleEn: 'Peace of Westphalia',
    detailZh: '三十年战争结束，欧洲国家主权和国际关系秩序出现重要重组。',
    detailEn:
        'The Thirty Years\' War ended, and European sovereignty and international relations were significantly reorganized.',
    sourceName: 'Britannica: Peace of Westphalia',
    sourceUrl: 'https://www.britannica.com/event/Peace-of-Westphalia',
  ),
  _TimelineFact(
    id: 'qing_dynasty',
    category: 'modern',
    yearsBeforePresent: 382,
    displayZh: '1644 年',
    displayEn: '1644 CE',
    titleZh: '清朝入主中原',
    titleEn: 'Qing dynasty takes Beijing',
    detailZh: '清朝在北京建立全国统治，成为中国最后一个帝制王朝。',
    detailEn:
        'The Qing established rule from Beijing and became China\'s last imperial dynasty.',
    sourceName: 'Britannica: Qing dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Qing-dynasty',
  ),
  _TimelineFact(
    id: 'slave_trade_abolition_britain',
    category: 'modern',
    yearsBeforePresent: 219,
    displayZh: '1807 年',
    displayEn: '1807 CE',
    titleZh: '英国废除奴隶贸易',
    titleEn: 'Britain abolishes the slave trade',
    detailZh: '英国通过法案禁止奴隶贸易，是跨大西洋奴隶制废除进程中的重要节点。',
    detailEn:
        'Britain banned the slave trade, a major step in the wider abolition of transatlantic slavery.',
    sourceName: 'Britannica: Slave Trade Act',
    sourceUrl: 'https://www.britannica.com/event/Slave-Trade-Act',
  ),
  _TimelineFact(
    id: 'haitian_independence',
    category: 'modern',
    yearsBeforePresent: 222,
    displayZh: '1804 年',
    displayEn: '1804 CE',
    titleZh: '海地独立',
    titleEn: 'Haitian independence',
    detailZh: '海地革命后建立独立国家，是大西洋世界奴隶制与殖民秩序中的重大转折。',
    detailEn:
        'After the Haitian Revolution, Haiti became independent, a major turning point in Atlantic slavery and colonial order.',
    sourceName: 'Britannica: Haitian Revolution',
    sourceUrl: 'https://www.britannica.com/topic/Haitian-Revolution',
  ),
  _TimelineFact(
    id: 'latin_american_independence',
    category: 'modern',
    yearsBeforePresent: 216,
    displayZh: '约 1810 年起',
    displayEn: 'from c. 1810 CE',
    titleZh: '拉丁美洲独立运动',
    titleEn: 'Latin American independence movements',
    detailZh: '西班牙和葡萄牙殖民体系在美洲多地瓦解，新的共和国和帝国政治体制出现。',
    detailEn:
        'Spanish and Portuguese colonial systems broke down across the Americas, producing new republics and imperial arrangements.',
    sourceName: 'Britannica: Latin American independence',
    sourceUrl:
        'https://www.britannica.com/event/Latin-American-independence-movements',
  ),
  _TimelineFact(
    id: 'opium_war',
    category: 'modern',
    yearsBeforePresent: 187,
    displayZh: '1839-1842 年',
    displayEn: '1839-1842 CE',
    titleZh: '第一次鸦片战争',
    titleEn: 'First Opium War',
    detailZh: '清朝与英国战争后签订《南京条约》，中国近代条约港和帝国主义压力格局形成。',
    detailEn:
        'After war with Britain, the Treaty of Nanjing opened treaty-port arrangements and intensified imperial pressure on Qing China.',
    sourceName: 'Britannica: Opium Wars',
    sourceUrl: 'https://www.britannica.com/topic/Opium-Wars',
  ),
  _TimelineFact(
    id: 'meiji_restoration',
    category: 'modern',
    yearsBeforePresent: 158,
    displayZh: '1868 年',
    displayEn: '1868 CE',
    titleZh: '明治维新',
    titleEn: 'Meiji Restoration',
    detailZh: '日本重组政治制度、军队、教育和工业，快速进入现代国家建构进程。',
    detailEn:
        'Japan reorganized politics, military, education, and industry, rapidly entering modern state-building.',
    sourceName: 'Britannica: Meiji Restoration',
    sourceUrl: 'https://www.britannica.com/event/Meiji-Restoration',
  ),
  _TimelineFact(
    id: 'scramble_for_africa',
    category: 'modern',
    yearsBeforePresent: 142,
    displayZh: '约 1884 年',
    displayEn: 'c. 1884 CE',
    titleZh: '瓜分非洲与柏林会议',
    titleEn: 'Scramble for Africa and Berlin Conference',
    detailZh: '欧洲列强加速殖民瓜分非洲，深刻影响非洲边界、经济和政治结构。',
    detailEn:
        'European powers accelerated colonial partition of Africa, profoundly shaping borders, economies, and politics.',
    sourceName: 'Britannica: Berlin West Africa Conference',
    sourceUrl: 'https://www.britannica.com/event/Berlin-West-Africa-Conference',
  ),
  _TimelineFact(
    id: 'xinhai_revolution',
    category: 'modern',
    yearsBeforePresent: 115,
    displayZh: '1911 年',
    displayEn: '1911 CE',
    titleZh: '辛亥革命',
    titleEn: 'Xinhai Revolution',
    detailZh: '清朝帝制终结，中华民国建立，中国政治秩序进入共和与军阀并存的新阶段。',
    detailEn:
        'The Qing imperial order ended and the Republic of China was founded, ushering in republican and warlord-era politics.',
    sourceName: 'Britannica: Chinese Revolution',
    sourceUrl: 'https://www.britannica.com/event/Chinese-Revolution-1911-1912',
  ),
  _TimelineFact(
    id: 'russian_revolution',
    category: 'modern',
    yearsBeforePresent: 109,
    displayZh: '1917 年',
    displayEn: '1917 CE',
    titleZh: '俄国革命',
    titleEn: 'Russian Revolution',
    detailZh: '帝俄政权崩溃，布尔什维克夺取政权，世界社会主义运动和 20 世纪国际政治格局改变。',
    detailEn:
        'The Russian Empire collapsed, the Bolsheviks seized power, and world socialism and twentieth-century politics were transformed.',
    sourceName: 'Britannica: Russian Revolution',
    sourceUrl: 'https://www.britannica.com/event/Russian-Revolution',
  ),
  _TimelineFact(
    id: 'league_of_nations',
    category: 'modern',
    yearsBeforePresent: 106,
    displayZh: '1920 年',
    displayEn: '1920 CE',
    titleZh: '国际联盟成立',
    titleEn: 'League of Nations founded',
    detailZh: '一战后国际联盟成立，代表早期全球集体安全和国际组织实验。',
    detailEn:
        'After World War I, the League of Nations represented an early experiment in global collective security and international organization.',
    sourceName: 'Britannica: League of Nations',
    sourceUrl: 'https://www.britannica.com/topic/League-of-Nations',
  ),
  _TimelineFact(
    id: 'india_independence',
    category: 'modern',
    yearsBeforePresent: 79,
    displayZh: '1947 年',
    displayEn: '1947 CE',
    titleZh: '印度独立与印巴分治',
    titleEn: 'Indian independence and Partition',
    detailZh: '英属印度结束殖民统治，印度和巴基斯坦分治，引发大规模迁徙和暴力。',
    detailEn:
        'British India ended colonial rule and was partitioned into India and Pakistan, causing mass migration and violence.',
    sourceName: 'Britannica: Partition of India',
    sourceUrl: 'https://www.britannica.com/event/Partition-of-India',
  ),
  _TimelineFact(
    id: 'prc_founded',
    category: 'modern',
    yearsBeforePresent: 77,
    displayZh: '1949 年',
    displayEn: '1949 CE',
    titleZh: '中华人民共和国成立',
    titleEn: 'People\'s Republic of China founded',
    detailZh: '中国内战后，中华人民共和国在北京成立，东亚冷战格局随之重组。',
    detailEn:
        'After the Chinese Civil War, the People\'s Republic of China was founded in Beijing, reshaping Cold War East Asia.',
    sourceName: 'Britannica: People\'s Republic of China',
    sourceUrl:
        'https://www.britannica.com/place/China/Establishment-of-the-Peoples-Republic',
  ),
  _TimelineFact(
    id: 'european_integration',
    category: 'modern',
    yearsBeforePresent: 69,
    displayZh: '1957 年',
    displayEn: '1957 CE',
    titleZh: '罗马条约与欧洲一体化',
    titleEn: 'Treaty of Rome and European integration',
    detailZh: '欧洲经济共同体建立，为后来的欧盟制度和欧洲一体化奠定基础。',
    detailEn:
        'The European Economic Community was founded, laying foundations for later European Union institutions and integration.',
    sourceName: 'European Union: history',
    sourceUrl:
        'https://european-union.europa.eu/principles-countries-history/history-eu_en',
  ),
  _TimelineFact(
    id: 'ghana_independence',
    category: 'modern',
    yearsBeforePresent: 69,
    displayZh: '1957 年',
    displayEn: '1957 CE',
    titleZh: '加纳独立',
    titleEn: 'Ghana independence',
    detailZh: '加纳成为撒哈拉以南非洲重要的独立国家之一，推动非洲去殖民化浪潮。',
    detailEn:
        'Ghana became a major independent state in sub-Saharan Africa and helped accelerate African decolonization.',
    sourceName: 'Britannica: Ghana',
    sourceUrl: 'https://www.britannica.com/place/Ghana/Independence',
  ),
  _TimelineFact(
    id: 'civil_rights_act',
    category: 'modern',
    yearsBeforePresent: 62,
    displayZh: '1964 年',
    displayEn: '1964 CE',
    titleZh: '美国民权法案',
    titleEn: 'U.S. Civil Rights Act',
    detailZh: '美国通过民权法案，禁止公共场所和就业中的种族歧视，是民权运动的重要制度成果。',
    detailEn:
        'The U.S. Civil Rights Act banned discrimination in public accommodations and employment, a key institutional outcome of the civil rights movement.',
    sourceName: 'National Archives: Civil Rights Act',
    sourceUrl: 'https://www.archives.gov/milestone-documents/civil-rights-act',
  ),
  _TimelineFact(
    id: 'green_revolution',
    category: 'science',
    yearsBeforePresent: 61,
    displayZh: '约 1960 年代',
    displayEn: 'c. 1960s',
    titleZh: '绿色革命',
    titleEn: 'Green Revolution',
    detailZh: '高产品种、化肥、灌溉和农业技术推广提高粮食产量，同时带来环境和社会争议。',
    detailEn:
        'High-yield varieties, fertilizers, irrigation, and farming techniques raised food production while raising environmental and social debates.',
    sourceName: 'Britannica: Green Revolution',
    sourceUrl: 'https://www.britannica.com/event/green-revolution',
  ),
  _TimelineFact(
    id: 'microprocessor',
    category: 'science',
    yearsBeforePresent: 55,
    displayZh: '1971 年',
    displayEn: '1971 CE',
    titleZh: '商用微处理器出现',
    titleEn: 'Commercial microprocessor appears',
    detailZh: '微处理器将计算机中央处理能力集成到芯片上，推动个人计算和嵌入式计算发展。',
    detailEn:
        'The microprocessor integrated central processing onto a chip, driving personal and embedded computing.',
    sourceName: 'Intel: 4004 microprocessor',
    sourceUrl:
        'https://www.intel.com/content/www/us/en/history/museum-story-of-intel-4004.html',
  ),
  _TimelineFact(
    id: 'berlin_wall_fall',
    category: 'modern',
    yearsBeforePresent: 37,
    displayZh: '1989 年',
    displayEn: '1989 CE',
    titleZh: '柏林墙倒塌',
    titleEn: 'Fall of the Berlin Wall',
    detailZh: '柏林墙开放象征东欧剧变和冷战秩序瓦解。',
    detailEn:
        'The opening of the Berlin Wall symbolized the collapse of Eastern Bloc regimes and the Cold War order.',
    sourceName: 'Britannica: Berlin Wall',
    sourceUrl: 'https://www.britannica.com/topic/Berlin-Wall',
  ),
  _TimelineFact(
    id: 'soviet_union_dissolution',
    category: 'modern',
    yearsBeforePresent: 35,
    displayZh: '1991 年',
    displayEn: '1991 CE',
    titleZh: '苏联解体',
    titleEn: 'Dissolution of the Soviet Union',
    detailZh: '苏联解体标志冷战结构终结，欧亚政治和全球秩序重组。',
    detailEn:
        'The Soviet Union dissolved, ending the Cold War structure and reorganizing Eurasian and global politics.',
    sourceName: 'Britannica: Soviet Union',
    sourceUrl: 'https://www.britannica.com/place/Soviet-Union',
  ),
  _TimelineFact(
    id: 'wto_founded',
    category: 'modern',
    yearsBeforePresent: 31,
    displayZh: '1995 年',
    displayEn: '1995 CE',
    titleZh: '世界贸易组织成立',
    titleEn: 'World Trade Organization founded',
    detailZh: 'WTO 建立多边贸易规则框架，成为全球化经济治理的重要机构。',
    detailEn:
        'The WTO established a multilateral trade-rule framework and became a major institution of global economic governance.',
    sourceName: 'WTO: history',
    sourceUrl:
        'https://www.wto.org/english/thewto_e/whatis_e/tif_e/fact4_e.htm',
  ),
  _TimelineFact(
    id: 'smartphone_era',
    category: 'modern',
    yearsBeforePresent: 19,
    displayZh: '约 2007 年起',
    displayEn: 'from c. 2007 CE',
    titleZh: '智能手机时代扩展',
    titleEn: 'Smartphone era expands',
    detailZh: '多点触控智能手机和移动互联网平台改变通信、媒体、消费和软件生态。',
    detailEn:
        'Multi-touch smartphones and mobile internet platforms changed communication, media, consumption, and software ecosystems.',
    sourceName: 'Britannica: smartphone',
    sourceUrl: 'https://www.britannica.com/technology/smartphone',
  ),
  _TimelineFact(
    id: 'crispr_gene_editing',
    category: 'science',
    yearsBeforePresent: 14,
    displayZh: '2012 年',
    displayEn: '2012 CE',
    titleZh: 'CRISPR 基因编辑方法发展',
    titleEn: 'CRISPR gene-editing methods develop',
    detailZh: 'CRISPR-Cas9 技术成为生物医学和农业研究中的重要基因编辑工具。',
    detailEn:
        'CRISPR-Cas9 became a major gene-editing tool for biomedical and agricultural research.',
    sourceName: 'Nobel Prize: CRISPR',
    sourceUrl: 'https://www.nobelprize.org/prizes/chemistry/2020/summary/',
  ),
  _TimelineFact(
    id: 'paris_agreement',
    category: 'modern',
    yearsBeforePresent: 11,
    displayZh: '2015 年',
    displayEn: '2015 CE',
    titleZh: '巴黎协定',
    titleEn: 'Paris Agreement',
    detailZh: '各国达成应对气候变化的国际协定，围绕温升目标、减排承诺和气候治理展开合作。',
    detailEn:
        'Countries adopted an international climate agreement around temperature targets, emissions pledges, and climate governance.',
    sourceName: 'UNFCCC: Paris Agreement',
    sourceUrl: 'https://unfccc.int/process-and-meetings/the-paris-agreement',
  ),
  _TimelineFact(
    id: 'covid19_pandemic',
    category: 'modern',
    yearsBeforePresent: 6,
    displayZh: '2020 年',
    displayEn: '2020 CE',
    titleZh: 'COVID-19 全球大流行',
    titleEn: 'COVID-19 pandemic',
    detailZh: '新冠疫情成为 21 世纪重大公共卫生危机，改变全球医疗、供应链、工作方式和治理实践。',
    detailEn:
        'COVID-19 became a major public-health crisis, changing medicine, supply chains, work patterns, and governance practices.',
    sourceName: 'WHO: COVID-19',
    sourceUrl:
        'https://www.who.int/emergencies/diseases/novel-coronavirus-2019',
  ),
  _TimelineFact(
    id: 'generative_ai_public_boom',
    category: 'science',
    yearsBeforePresent: 4,
    displayZh: '约 2022 年起',
    displayEn: 'from c. 2022 CE',
    titleZh: '生成式 AI 大众化',
    titleEn: 'Generative AI becomes mainstream',
    detailZh: '大型语言模型和多模态生成系统进入公众使用，推动教育、软件、媒体和知识工作流程重组。',
    detailEn:
        'Large language models and multimodal generation systems entered public use, reshaping education, software, media, and knowledge work.',
    sourceName: 'Stanford AI Index',
    sourceUrl: 'https://aiindex.stanford.edu/report/',
  ),
];

final List<_TimelineFact> _timelineFacts = _sortedTimelineFacts(<_TimelineFact>[
  ..._coreTimelineFacts,
  ..._expandedHumanTimelineFacts,
  ..._densePremodernTimelineFacts,
  ..._denseModernTimelineFacts,
]);

List<_TimelineFact> _sortedTimelineFacts(List<_TimelineFact> facts) {
  return List<_TimelineFact>.unmodifiable(
    facts..sort((a, b) => b.yearsBeforePresent.compareTo(a.yearsBeforePresent)),
  );
}
