part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _chinaTimelineFacts02 = <_TimelineFact>[
  _TimelineFact(
    id: 'yuan_dynasty',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 706.5,
    displayKey: 'toolbox.life.timeline.china_overview.yuan_dynasty.date',
    titleKey: 'toolbox.life.timeline.china_overview.yuan_dynasty.title',
    detailKey: 'toolbox.life.timeline.china_overview.yuan_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Yuan%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'yuan_paper_currency',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 721,
    displayKey: 'toolbox.life.timeline.china_overview.yuan_paper_currency.date',
    titleKey: 'toolbox.life.timeline.china_overview.yuan_paper_currency.title',
    detailKey: 'toolbox.life.timeline.china_overview.yuan_paper_currency.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Yuan%20dynasty%20paper%20money',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'marco_polo_china',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 743,
    displayKey: 'toolbox.life.timeline.china_overview.marco_polo_china.date',
    titleKey: 'toolbox.life.timeline.china_overview.marco_polo_china.title',
    detailKey: 'toolbox.life.timeline.china_overview.marco_polo_china.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Marco%20Polo%20China',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'ming_dynasty',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 520,
    displayKey: 'toolbox.life.timeline.china_overview.ming_dynasty.date',
    titleKey: 'toolbox.life.timeline.china_overview.ming_dynasty.title',
    detailKey: 'toolbox.life.timeline.china_overview.ming_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ming%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'forbidden_city',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 613,
    displayKey: 'toolbox.life.timeline.china_overview.forbidden_city.date',
    titleKey: 'toolbox.life.timeline.china_overview.forbidden_city.title',
    detailKey: 'toolbox.life.timeline.china_overview.forbidden_city.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Forbidden%20City',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'zheng_he_voyages',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 607,
    displayKey: 'toolbox.life.timeline.china_overview.zheng_he_voyages.date',
    titleKey: 'toolbox.life.timeline.china_overview.zheng_he_voyages.title',
    detailKey: 'toolbox.life.timeline.china_overview.zheng_he_voyages.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zheng%20He%20voyages',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'yongle_encyclopedia',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 618,
    displayKey: 'toolbox.life.timeline.china_overview.yongle_encyclopedia.date',
    titleKey: 'toolbox.life.timeline.china_overview.yongle_encyclopedia.title',
    detailKey: 'toolbox.life.timeline.china_overview.yongle_encyclopedia.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Yongle%20Encyclopedia',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'wang_yangming_learning',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 511,
    displayKey: 'toolbox.life.timeline.china_overview.wang_yangming_learning.date',
    titleKey: 'toolbox.life.timeline.china_overview.wang_yangming_learning.title',
    detailKey: 'toolbox.life.timeline.china_overview.wang_yangming_learning.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Wang%20Yangming',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'li_shizhen_compendium',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 448,
    displayKey: 'toolbox.life.timeline.china_overview.li_shizhen_compendium.date',
    titleKey: 'toolbox.life.timeline.china_overview.li_shizhen_compendium.title',
    detailKey: 'toolbox.life.timeline.china_overview.li_shizhen_compendium.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Compendium%20of%20Materia%20Medica',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'xu_guangqi_agriculture',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 387,
    displayKey: 'toolbox.life.timeline.china_overview.xu_guangqi_agriculture.date',
    titleKey: 'toolbox.life.timeline.china_overview.xu_guangqi_agriculture.title',
    detailKey: 'toolbox.life.timeline.china_overview.xu_guangqi_agriculture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Nongzheng%20Quanshu',
    imageAsset: 'assets/toolbox/history_timeline/yuan_ming.webp',
  ),
  _TimelineFact(
    id: 'late_ming_transition',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 394,
    displayKey: 'toolbox.life.timeline.china_overview.late_ming_transition.date',
    titleKey: 'toolbox.life.timeline.china_overview.late_ming_transition.title',
    detailKey: 'toolbox.life.timeline.china_overview.late_ming_transition.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ming%20Qing%20transition',
    imageAsset: 'assets/toolbox/history_timeline/qing.webp',
  ),
  _TimelineFact(
    id: 'qing_dynasty',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 248,
    displayKey: 'toolbox.life.timeline.china_overview.qing_dynasty.date',
    titleKey: 'toolbox.life.timeline.china_overview.qing_dynasty.title',
    detailKey: 'toolbox.life.timeline.china_overview.qing_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Qing%20dynasty',
    imageAsset: 'assets/toolbox/history_timeline/qing.webp',
  ),
  _TimelineFact(
    id: 'kangxi_reign',
    collection: 'china_overview',
    category: 'civilization',
    yearsBeforePresent: 334.5,
    displayKey: 'toolbox.life.timeline.china_overview.kangxi_reign.date',
    titleKey: 'toolbox.life.timeline.china_overview.kangxi_reign.title',
    detailKey: 'toolbox.life.timeline.china_overview.kangxi_reign.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Kangxi%20Emperor',
    imageAsset: 'assets/toolbox/history_timeline/qing.webp',
  ),
  _TimelineFact(
    id: 'qing_taiwan_1683',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 343,
    displayKey: 'toolbox.life.timeline.china_overview.qing_taiwan_1683.date',
    titleKey: 'toolbox.life.timeline.china_overview.qing_taiwan_1683.title',
    detailKey: 'toolbox.life.timeline.china_overview.qing_taiwan_1683.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Qing%20conquest%20of%20Taiwan',
    imageAsset: 'assets/toolbox/history_timeline/qing.webp',
  ),
  _TimelineFact(
    id: 'four_encyclopedia',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 248.5,
    displayKey: 'toolbox.life.timeline.china_overview.four_encyclopedia.date',
    titleKey: 'toolbox.life.timeline.china_overview.four_encyclopedia.title',
    detailKey: 'toolbox.life.timeline.china_overview.four_encyclopedia.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Siku%20Quanshu',
    imageAsset: 'assets/toolbox/history_timeline/qing.webp',
  ),
  _TimelineFact(
    id: 'jesuit_science_exchange',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 351,
    displayKey: 'toolbox.life.timeline.china_overview.jesuit_science_exchange.date',
    titleKey: 'toolbox.life.timeline.china_overview.jesuit_science_exchange.title',
    detailKey: 'toolbox.life.timeline.china_overview.jesuit_science_exchange.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Jesuit%20China%20missions',
    imageAsset: 'assets/toolbox/history_timeline/qing.webp',
  ),
  _TimelineFact(
    id: 'opium_war',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 185.5,
    displayKey: 'toolbox.life.timeline.china_overview.opium_war.date',
    titleKey: 'toolbox.life.timeline.china_overview.opium_war.title',
    detailKey: 'toolbox.life.timeline.china_overview.opium_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=First%20Opium%20War',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'treaty_nanjing',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 184,
    displayKey: 'toolbox.life.timeline.china_overview.treaty_nanjing.date',
    titleKey: 'toolbox.life.timeline.china_overview.treaty_nanjing.title',
    detailKey: 'toolbox.life.timeline.china_overview.treaty_nanjing.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Treaty%20of%20Nanking',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'taiping_rebellion',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 169,
    displayKey: 'toolbox.life.timeline.china_overview.taiping_rebellion.date',
    titleKey: 'toolbox.life.timeline.china_overview.taiping_rebellion.title',
    detailKey: 'toolbox.life.timeline.china_overview.taiping_rebellion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Taiping%20Rebellion',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'self_strengthening',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 148,
    displayKey: 'toolbox.life.timeline.china_overview.self_strengthening.date',
    titleKey: 'toolbox.life.timeline.china_overview.self_strengthening.title',
    detailKey: 'toolbox.life.timeline.china_overview.self_strengthening.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Self-Strengthening%20Movement',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'first_sino_japanese_war',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 131.5,
    displayKey: 'toolbox.life.timeline.china_overview.first_sino_japanese_war.date',
    titleKey: 'toolbox.life.timeline.china_overview.first_sino_japanese_war.title',
    detailKey: 'toolbox.life.timeline.china_overview.first_sino_japanese_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=First%20Sino-Japanese%20War',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'hundred_days_reform',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 128,
    displayKey: 'toolbox.life.timeline.china_overview.hundred_days_reform.date',
    titleKey: 'toolbox.life.timeline.china_overview.hundred_days_reform.title',
    detailKey: 'toolbox.life.timeline.china_overview.hundred_days_reform.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hundred%20Days\'%20Reform',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'boxer_uprising',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 126,
    displayKey: 'toolbox.life.timeline.china_overview.boxer_uprising.date',
    titleKey: 'toolbox.life.timeline.china_overview.boxer_uprising.title',
    detailKey: 'toolbox.life.timeline.china_overview.boxer_uprising.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Boxer%20Rebellion',
    imageAsset: 'assets/toolbox/history_timeline/late_qing.webp',
  ),
  _TimelineFact(
    id: 'xinhai_revolution',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 114.5,
    displayKey: 'toolbox.life.timeline.china_overview.xinhai_revolution.date',
    titleKey: 'toolbox.life.timeline.china_overview.xinhai_revolution.title',
    detailKey: 'toolbox.life.timeline.china_overview.xinhai_revolution.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Xinhai%20Revolution',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'republic_founded',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 114,
    displayKey: 'toolbox.life.timeline.china_overview.republic_founded.date',
    titleKey: 'toolbox.life.timeline.china_overview.republic_founded.title',
    detailKey: 'toolbox.life.timeline.china_overview.republic_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Republic%20of%20China',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'may_fourth',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 107,
    displayKey: 'toolbox.life.timeline.china_overview.may_fourth.date',
    titleKey: 'toolbox.life.timeline.china_overview.may_fourth.title',
    detailKey: 'toolbox.life.timeline.china_overview.may_fourth.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=May%20Fourth%20Movement',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'cpc_founded',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 105,
    displayKey: 'toolbox.life.timeline.china_overview.cpc_founded.date',
    titleKey: 'toolbox.life.timeline.china_overview.cpc_founded.title',
    detailKey: 'toolbox.life.timeline.china_overview.cpc_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chinese%20Communist%20Party',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'northern_expedition',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 99,
    displayKey: 'toolbox.life.timeline.china_overview.northern_expedition.date',
    titleKey: 'toolbox.life.timeline.china_overview.northern_expedition.title',
    detailKey: 'toolbox.life.timeline.china_overview.northern_expedition.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Northern%20Expedition%20China',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'nanjing_decade',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 94,
    displayKey: 'toolbox.life.timeline.china_overview.nanjing_decade.date',
    titleKey: 'toolbox.life.timeline.china_overview.nanjing_decade.title',
    detailKey: 'toolbox.life.timeline.china_overview.nanjing_decade.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Nanjing%20decade%20China',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'manchurian_incident',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 95,
    displayKey: 'toolbox.life.timeline.china_overview.manchurian_incident.date',
    titleKey: 'toolbox.life.timeline.china_overview.manchurian_incident.title',
    detailKey: 'toolbox.life.timeline.china_overview.manchurian_incident.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Mukden%20Incident',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'long_march',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 91.5,
    displayKey: 'toolbox.life.timeline.china_overview.long_march.date',
    titleKey: 'toolbox.life.timeline.china_overview.long_march.title',
    detailKey: 'toolbox.life.timeline.china_overview.long_march.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Long%20March%20China',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'second_sino_japanese_war',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 85,
    displayKey: 'toolbox.life.timeline.china_overview.second_sino_japanese_war.date',
    titleKey: 'toolbox.life.timeline.china_overview.second_sino_japanese_war.title',
    detailKey: 'toolbox.life.timeline.china_overview.second_sino_japanese_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Second%20Sino-Japanese%20War',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'united_front',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 85,
    displayKey: 'toolbox.life.timeline.china_overview.united_front.date',
    titleKey: 'toolbox.life.timeline.china_overview.united_front.title',
    detailKey: 'toolbox.life.timeline.china_overview.united_front.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Second%20United%20Front%20China',
    imageAsset: 'assets/toolbox/history_timeline/republic.webp',
  ),
  _TimelineFact(
    id: 'prc_founded',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 77,
    displayKey: 'toolbox.life.timeline.china_overview.prc_founded.date',
    titleKey: 'toolbox.life.timeline.china_overview.prc_founded.title',
    detailKey: 'toolbox.life.timeline.china_overview.prc_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=People\'s%20Republic%20of%20China',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'land_reform_early_prc',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 74.5,
    displayKey: 'toolbox.life.timeline.china_overview.land_reform_early_prc.date',
    titleKey: 'toolbox.life.timeline.china_overview.land_reform_early_prc.title',
    detailKey: 'toolbox.life.timeline.china_overview.land_reform_early_prc.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Land%20reform%20China%201950',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'korean_war_china',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 74.5,
    displayKey: 'toolbox.life.timeline.china_overview.korean_war_china.date',
    titleKey: 'toolbox.life.timeline.china_overview.korean_war_china.title',
    detailKey: 'toolbox.life.timeline.china_overview.korean_war_china.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Korean%20War%20China',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'first_five_year_plan',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 71,
    displayKey: 'toolbox.life.timeline.china_overview.first_five_year_plan.date',
    titleKey: 'toolbox.life.timeline.china_overview.first_five_year_plan.title',
    detailKey: 'toolbox.life.timeline.china_overview.first_five_year_plan.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=First%20Five-Year%20Plan%20China',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'great_leap_forward',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 66,
    displayKey: 'toolbox.life.timeline.china_overview.great_leap_forward.date',
    titleKey: 'toolbox.life.timeline.china_overview.great_leap_forward.title',
    detailKey: 'toolbox.life.timeline.china_overview.great_leap_forward.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Great%20Leap%20Forward',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'cultural_revolution',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 55,
    displayKey: 'toolbox.life.timeline.china_overview.cultural_revolution.date',
    titleKey: 'toolbox.life.timeline.china_overview.cultural_revolution.title',
    detailKey: 'toolbox.life.timeline.china_overview.cultural_revolution.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Cultural%20Revolution',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'un_seat_restored',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 55,
    displayKey: 'toolbox.life.timeline.china_overview.un_seat_restored.date',
    titleKey: 'toolbox.life.timeline.china_overview.un_seat_restored.title',
    detailKey: 'toolbox.life.timeline.china_overview.un_seat_restored.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=China%20United%20Nations%20representation%201971',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'reform_opening_1978',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 48,
    displayKey: 'toolbox.life.timeline.china_overview.reform_opening_1978.date',
    titleKey: 'toolbox.life.timeline.china_overview.reform_opening_1978.title',
    detailKey: 'toolbox.life.timeline.china_overview.reform_opening_1978.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chinese%20economic%20reform',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'shenzhen_sez',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 46,
    displayKey: 'toolbox.life.timeline.china_overview.shenzhen_sez.date',
    titleKey: 'toolbox.life.timeline.china_overview.shenzhen_sez.title',
    detailKey: 'toolbox.life.timeline.china_overview.shenzhen_sez.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Shenzhen%20special%20economic%20zone',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'chinese_space_program',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 30,
    displayKey: 'toolbox.life.timeline.china_overview.chinese_space_program.date',
    titleKey: 'toolbox.life.timeline.china_overview.chinese_space_program.title',
    detailKey: 'toolbox.life.timeline.china_overview.chinese_space_program.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chinese%20space%20program',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'hk_handover',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 29,
    displayKey: 'toolbox.life.timeline.china_overview.hk_handover.date',
    titleKey: 'toolbox.life.timeline.china_overview.hk_handover.title',
    detailKey: 'toolbox.life.timeline.china_overview.hk_handover.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hong%20Kong%20handover',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'macao_handover',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 27,
    displayKey: 'toolbox.life.timeline.china_overview.macao_handover.date',
    titleKey: 'toolbox.life.timeline.china_overview.macao_handover.title',
    detailKey: 'toolbox.life.timeline.china_overview.macao_handover.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Macau%20handover',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'wto_accession',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 25,
    displayKey: 'toolbox.life.timeline.china_overview.wto_accession.date',
    titleKey: 'toolbox.life.timeline.china_overview.wto_accession.title',
    detailKey: 'toolbox.life.timeline.china_overview.wto_accession.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=China%20WTO%20accession',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'beidou_system',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 16,
    displayKey: 'toolbox.life.timeline.china_overview.beidou_system.date',
    titleKey: 'toolbox.life.timeline.china_overview.beidou_system.title',
    detailKey: 'toolbox.life.timeline.china_overview.beidou_system.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=BeiDou%20Navigation%20Satellite%20System',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'shenzhou5',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 23,
    displayKey: 'toolbox.life.timeline.china_overview.shenzhou5.date',
    titleKey: 'toolbox.life.timeline.china_overview.shenzhou5.title',
    detailKey: 'toolbox.life.timeline.china_overview.shenzhou5.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Shenzhou%205',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'three_gorges_completed',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 20,
    displayKey: 'toolbox.life.timeline.china_overview.three_gorges_completed.date',
    titleKey: 'toolbox.life.timeline.china_overview.three_gorges_completed.title',
    detailKey: 'toolbox.life.timeline.china_overview.three_gorges_completed.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Three%20Gorges%20Dam',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'beijing_olympics',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 18,
    displayKey: 'toolbox.life.timeline.china_overview.beijing_olympics.date',
    titleKey: 'toolbox.life.timeline.china_overview.beijing_olympics.title',
    detailKey: 'toolbox.life.timeline.china_overview.beijing_olympics.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=2008%20Beijing%20Olympics',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'high_speed_rail',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 9.5,
    displayKey: 'toolbox.life.timeline.china_overview.high_speed_rail.date',
    titleKey: 'toolbox.life.timeline.china_overview.high_speed_rail.title',
    detailKey: 'toolbox.life.timeline.china_overview.high_speed_rail.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=China%20high-speed%20rail',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'belt_road_initiative',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 13,
    displayKey: 'toolbox.life.timeline.china_overview.belt_road_initiative.date',
    titleKey: 'toolbox.life.timeline.china_overview.belt_road_initiative.title',
    detailKey: 'toolbox.life.timeline.china_overview.belt_road_initiative.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Belt%20and%20Road%20Initiative',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'change3',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 13,
    displayKey: 'toolbox.life.timeline.china_overview.change3.date',
    titleKey: 'toolbox.life.timeline.china_overview.change3.title',
    detailKey: 'toolbox.life.timeline.china_overview.change3.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chang\'e%203',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'change4',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 7,
    displayKey: 'toolbox.life.timeline.china_overview.change4.date',
    titleKey: 'toolbox.life.timeline.china_overview.change4.title',
    detailKey: 'toolbox.life.timeline.china_overview.change4.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chang\'e%204',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'covid19_china',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 5,
    displayKey: 'toolbox.life.timeline.china_overview.covid19_china.date',
    titleKey: 'toolbox.life.timeline.china_overview.covid19_china.title',
    detailKey: 'toolbox.life.timeline.china_overview.covid19_china.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=COVID-19%20pandemic%20China',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'poverty_alleviation_2020',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 6,
    displayKey: 'toolbox.life.timeline.china_overview.poverty_alleviation_2020.date',
    titleKey: 'toolbox.life.timeline.china_overview.poverty_alleviation_2020.title',
    detailKey: 'toolbox.life.timeline.china_overview.poverty_alleviation_2020.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=China%20poverty%20alleviation%202020',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'carbon_neutrality_goal',
    collection: 'china_overview',
    category: 'modern',
    yearsBeforePresent: 0,
    displayKey: 'toolbox.life.timeline.china_overview.carbon_neutrality_goal.date',
    titleKey: 'toolbox.life.timeline.china_overview.carbon_neutrality_goal.title',
    detailKey: 'toolbox.life.timeline.china_overview.carbon_neutrality_goal.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=China%20carbon%20neutrality%20goal',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
  _TimelineFact(
    id: 'tiangong_space_station',
    collection: 'china_overview',
    category: 'science',
    yearsBeforePresent: 4,
    displayKey: 'toolbox.life.timeline.china_overview.tiangong_space_station.date',
    titleKey: 'toolbox.life.timeline.china_overview.tiangong_space_station.title',
    detailKey: 'toolbox.life.timeline.china_overview.tiangong_space_station.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Tiangong%20space%20station',
    imageAsset: 'assets/toolbox/history_timeline/modern.webp',
  ),
];
