part of '../toolbox_life_tools.dart';

class _TimelineFact {
  const _TimelineFact({
    required this.id,
    required this.category,
    required this.yearsBeforePresent,
    required this.displayZh,
    required this.displayEn,
    required this.titleZh,
    required this.titleEn,
    required this.detailZh,
    required this.detailEn,
    required this.sourceName,
    required this.sourceUrl,
  });
  final String id;
  final String category;
  final double yearsBeforePresent;
  final String displayZh;
  final String displayEn;
  final String titleZh;
  final String titleEn;
  final String detailZh;
  final String detailEn;
  final String sourceName;
  final String sourceUrl;
}

class _ElementFact {
  const _ElementFact({
    required this.atomicNumber,
    required this.symbol,
    required this.nameEn,
    required this.atomicMass,
    required this.groupBlock,
    required this.standardState,
    required this.yearDiscovered,
    required this.electronConfiguration,
    required this.electronegativity,
    required this.period,
    required this.group,
    required this.displayRow,
    required this.displayColumn,
  });
  final int atomicNumber;
  final String symbol;
  final String nameEn;
  final String atomicMass;
  final String groupBlock;
  final String standardState;
  final String yearDiscovered;
  final String electronConfiguration;
  final String electronegativity;
  final int period;
  final int group;
  final int displayRow;
  final int displayColumn;
}

class _TimelineBackdropAsset {
  const _TimelineBackdropAsset({
    required this.id,
    required this.category,
    required this.imageUrl,
    required this.sourceName,
    required this.sourceUrl,
    required this.credit,
  });

  final String id;
  final String category;
  final String imageUrl;
  final String sourceName;
  final String sourceUrl;
  final String credit;
}

const List<_TimelineBackdropAsset>
_timelineBackdropAssets = <_TimelineBackdropAsset>[
  _TimelineBackdropAsset(
    id: 'cosmic_cliffs',
    category: 'cosmic',
    imageUrl:
        'https://images-assets.nasa.gov/image/carina_nebula/carina_nebula~large.jpg',
    sourceName: 'NASA Image Library: Cosmic Cliffs',
    sourceUrl: 'https://images.nasa.gov/details/carina_nebula',
    credit: 'NASA/ESA/CSA/STScI',
  ),
  _TimelineBackdropAsset(
    id: 'basalt_rock',
    category: 'earth',
    imageUrl:
        'https://commons.wikimedia.org/wiki/Special:FilePath/BasaltUSGOV.jpg?width=1400',
    sourceName: 'USGS basalt rock photograph',
    sourceUrl: 'https://www.usgs.gov/media/images/basalt-rock-photograph',
    credit: 'U.S. Geological Survey, public domain',
  ),
  _TimelineBackdropAsset(
    id: 'rosetta_stone',
    category: 'civilization',
    imageUrl:
        'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Rosetta%20Stone.jpg?width=1400',
    sourceName: 'Wikimedia Commons: Rosetta Stone',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Rosetta_Stone.jpg',
    credit: 'Wikimedia Commons public-domain media',
  ),
  _TimelineBackdropAsset(
    id: 'apollo_earth',
    category: 'science',
    imageUrl:
        'https://images-assets.nasa.gov/image/as17-148-22727/as17-148-22727~large.jpg',
    sourceName: 'NASA Image Library: Apollo 17 Earth',
    sourceUrl: 'https://images.nasa.gov/details/as17-148-22727',
    credit: 'NASA/JSC',
  ),
  _TimelineBackdropAsset(
    id: 'world_wide_web',
    category: 'modern',
    imageUrl:
        'https://images-assets.nasa.gov/image/as17-148-22727/as17-148-22727~large.jpg',
    sourceName: 'NASA Image Library: Apollo 17 Earth',
    sourceUrl: 'https://images.nasa.gov/details/as17-148-22727',
    credit: 'NASA/JSC',
  ),
  _TimelineBackdropAsset(
    id: 'human_artifact',
    category: 'human',
    imageUrl:
        'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Rosetta%20Stone.jpg?width=1400',
    sourceName: 'Wikimedia Commons: Rosetta Stone',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Rosetta_Stone.jpg',
    credit: 'Wikimedia Commons public-domain media',
  ),
];

const List<_TimelineFact> _coreTimelineFacts = <_TimelineFact>[
  _TimelineFact(
    id: 'big_bang',
    category: 'cosmic',
    yearsBeforePresent: 13800000000.0,
    displayZh: '\u7ea6 138 \u4ebf\u5e74\u524d',
    displayEn: 'c. 13.8 billion years ago',
    titleZh:
        '\u53ef\u89c2\u6d4b\u5b87\u5b99\u65e9\u671f\u70ed\u5927\u7206\u70b8\u9636\u6bb5',
    titleEn: 'Hot Big Bang era of the observable universe',
    detailZh:
        '\u73b0\u4ee3\u5b87\u5b99\u5b66\u7684\u4e3b\u6d41\u6a21\u578b\u8ba4\u4e3a\uff0c\u53ef\u89c2\u6d4b\u5b87\u5b99\u4ece\u7ea6 138 \u4ebf\u5e74\u524d\u7684\u9ad8\u6e29\u9ad8\u5bc6\u72b6\u6001\u6f14\u5316\u800c\u6765\u3002',
    detailEn:
        'Modern cosmology places the hot, dense early state of the observable universe about 13.8 billion years ago.',
    sourceName: 'NASA Universe overview',
    sourceUrl: 'https://science.nasa.gov/universe/',
  ),
  _TimelineFact(
    id: 'earth_forms',
    category: 'earth',
    yearsBeforePresent: 4540000000.0,
    displayZh: '\u7ea6 45.4 \u4ebf\u5e74\u524d',
    displayEn: 'c. 4.54 billion years ago',
    titleZh: '\u5730\u7403\u5f62\u6210',
    titleEn: 'Earth forms',
    detailZh:
        '\u653e\u5c04\u6027\u6d4b\u5e74\u548c\u9668\u77f3\u8bc1\u636e\u652f\u6301\u5730\u7403\u7ea6\u5728 45.4 \u4ebf\u5e74\u524d\u5f62\u6210\u3002',
    detailEn:
        'Radiometric dating and meteorite evidence support an Earth age of about 4.54 billion years.',
    sourceName: 'USGS: How old is Earth?',
    sourceUrl: 'https://www.usgs.gov/faqs/how-old-earth',
  ),
  _TimelineFact(
    id: 'first_life',
    category: 'earth',
    yearsBeforePresent: 3500000000.0,
    displayZh: '\u7ea6 35 \u4ebf\u5e74\u524d',
    displayEn: 'c. 3.5 billion years ago',
    titleZh: '\u65e9\u671f\u751f\u547d\u8bc1\u636e',
    titleEn: 'Early evidence of life',
    detailZh:
        '\u65e9\u671f\u5fae\u751f\u7269\u751f\u547d\u8bc1\u636e\u901a\u5e38\u88ab\u653e\u5728\u7ea6 35 \u4ebf\u5e74\u524d\u7684\u65f6\u95f4\u8303\u56f4\u5185\u3002',
    detailEn:
        'Common summaries place early microbial life evidence around 3.5 billion years ago.',
    sourceName: 'Smithsonian Human Origins Program',
    sourceUrl: 'https://humanorigins.si.edu/',
  ),
  _TimelineFact(
    id: 'great_oxidation',
    category: 'earth',
    yearsBeforePresent: 2400000000.0,
    displayZh: '\u7ea6 24 \u4ebf\u5e74\u524d',
    displayEn: 'c. 2.4 billion years ago',
    titleZh: '\u5927\u6c27\u5316\u4e8b\u4ef6',
    titleEn: 'Great Oxidation Event',
    detailZh:
        '\u5730\u7403\u5927\u6c14\u548c\u6d77\u6d0b\u4e2d\u7684\u6c27\u542b\u91cf\u663e\u8457\u4e0a\u5347\uff0c\u6539\u53d8\u4e86\u540e\u7eed\u751f\u547d\u6f14\u5316\u73af\u5883\u3002',
    detailEn:
        'Atmospheric and ocean oxygen rose substantially, reshaping later biological evolution.',
    sourceName: 'NASA Astrobiology',
    sourceUrl: 'https://astrobiology.nasa.gov/',
  ),
  _TimelineFact(
    id: 'eukaryotes',
    category: 'earth',
    yearsBeforePresent: 1800000000.0,
    displayZh: '\u7ea6 18 \u4ebf\u5e74\u524d',
    displayEn: 'c. 1.8 billion years ago',
    titleZh: '\u771f\u6838\u751f\u7269\u51fa\u73b0',
    titleEn: 'Eukaryotes appear',
    detailZh:
        '\u5177\u6709\u7ec6\u80de\u6838\u7684\u771f\u6838\u751f\u7269\u5728\u53e4\u5143\u53e4\u4ee3\u5230\u4e2d\u5143\u53e4\u4ee3\u65e9\u671f\u51fa\u73b0\uff0c\u662f\u590d\u6742\u751f\u547d\u7684\u91cd\u8981\u57fa\u7840\u3002',
    detailEn:
        'Nucleated eukaryotic cells appeared in the Paleoproterozoic to early Mesoproterozoic, enabling later complex life.',
    sourceName: 'Encyclopaedia Britannica: eukaryote',
    sourceUrl: 'https://www.britannica.com/science/eukaryote',
  ),
  _TimelineFact(
    id: 'cambrian',
    category: 'earth',
    yearsBeforePresent: 538800000.0,
    displayZh: '\u7ea6 5.388 \u4ebf\u5e74\u524d',
    displayEn: 'c. 538.8 million years ago',
    titleZh: '\u5bd2\u6b66\u7eaa\u5f00\u59cb',
    titleEn: 'Cambrian Period begins',
    detailZh:
        'ICS 2024/12 \u5e74\u4ee3\u8868\u5c06\u5bd2\u6b66\u7eaa\u8d77\u70b9\u7f6e\u4e8e\u7ea6 5.388 \u4ebf\u5e74\u524d\u3002',
    detailEn:
        'The ICS 2024/12 chart places the start of the Cambrian at about 538.8 Ma.',
    sourceName: 'International Commission on Stratigraphy',
    sourceUrl: 'https://stratigraphy.org/chart',
  ),
  _TimelineFact(
    id: 'land_plants',
    category: 'earth',
    yearsBeforePresent: 470000000.0,
    displayZh: '\u7ea6 4.7 \u4ebf\u5e74\u524d',
    displayEn: 'c. 470 million years ago',
    titleZh: '\u9646\u5730\u690d\u7269\u6269\u6563',
    titleEn: 'Land plants spread',
    detailZh:
        '\u690d\u7269\u5411\u9646\u5730\u6269\u5c55\uff0c\u4e3a\u540e\u7eed\u9646\u751f\u751f\u6001\u7cfb\u7edf\u5960\u5b9a\u57fa\u7840\u3002',
    detailEn:
        'Plant expansion onto land laid the foundation for later terrestrial ecosystems.',
    sourceName: 'Encyclopaedia Britannica: plant evolution',
    sourceUrl:
        'https://www.britannica.com/science/plant/Evolution-and-paleobotany',
  ),
  _TimelineFact(
    id: 'dinosaurs',
    category: 'earth',
    yearsBeforePresent: 230000000.0,
    displayZh: '\u7ea6 2.3 \u4ebf\u5e74\u524d',
    displayEn: 'c. 230 million years ago',
    titleZh: '\u6050\u9f99\u51fa\u73b0',
    titleEn: 'Dinosaurs appear',
    detailZh:
        '\u6050\u9f99\u5728\u4e09\u53e0\u7eaa\u665a\u671f\u51fa\u73b0\uff0c\u5e76\u5728\u4e2d\u751f\u4ee3\u957f\u671f\u5360\u636e\u91cd\u8981\u751f\u6001\u4f4d\u3002',
    detailEn:
        'Dinosaurs appeared in the Late Triassic and later dominated many Mesozoic ecosystems.',
    sourceName: 'Natural History Museum',
    sourceUrl: 'https://www.nhm.ac.uk/discover/when-did-dinosaurs-live.html',
  ),
  _TimelineFact(
    id: 'kpg_extinction',
    category: 'earth',
    yearsBeforePresent: 66000000.0,
    displayZh: '\u7ea6 6600 \u4e07\u5e74\u524d',
    displayEn: 'c. 66 million years ago',
    titleZh: '\u767d\u57a9\u7eaa-\u53e4\u8fd1\u7eaa\u706d\u7edd\u4e8b\u4ef6',
    titleEn: 'Cretaceous-Paleogene extinction',
    detailZh:
        '\u4e00\u6b21\u5927\u89c4\u6a21\u706d\u7edd\u4e8b\u4ef6\u7ec8\u7ed3\u4e86\u975e\u9e1f\u7c7b\u6050\u9f99\u65f6\u4ee3\uff0c\u5e76\u6539\u53d8\u4e86\u54fa\u4e73\u52a8\u7269\u6f14\u5316\u683c\u5c40\u3002',
    detailEn:
        'A mass extinction ended non-avian dinosaurs and reshaped mammalian evolution.',
    sourceName: 'USGS: Geologic time',
    sourceUrl:
        'https://www.usgs.gov/programs/national-geologic-map-database/geologic-time',
  ),
  _TimelineFact(
    id: 'homo_genus',
    category: 'human',
    yearsBeforePresent: 2800000.0,
    displayZh: '\u7ea6 280 \u4e07\u5e74\u524d',
    displayEn: 'c. 2.8 million years ago',
    titleZh: '\u4eba\u5c5e\u65e9\u671f\u5316\u77f3\u8bb0\u5f55',
    titleEn: 'Early Homo fossil record',
    detailZh:
        '\u4eba\u5c5e\u65e9\u671f\u5316\u77f3\u901a\u5e38\u653e\u5728\u7ea6 280 \u4e07\u5e74\u524d\u7684\u65f6\u95f4\u8303\u56f4\u5185\u3002',
    detailEn:
        'Early Homo fossil evidence is commonly placed around 2.8 million years ago.',
    sourceName: 'Smithsonian Human Origins Program',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-habilis',
  ),
  _TimelineFact(
    id: 'stone_tools',
    category: 'human',
    yearsBeforePresent: 2600000.0,
    displayZh: '\u7ea6 260 \u4e07\u5e74\u524d',
    displayEn: 'c. 2.6 million years ago',
    titleZh: '\u5965\u675c\u5a01\u77f3\u5668\u4f20\u7edf',
    titleEn: 'Oldowan stone tools',
    detailZh:
        '\u5965\u675c\u5a01\u77f3\u5668\u4f20\u7edf\u662f\u65e9\u671f\u4eba\u7c7b\u6280\u672f\u884c\u4e3a\u7684\u7ecf\u5178\u8bc1\u636e\u4e4b\u4e00\u3002',
    detailEn:
        'Oldowan tools are a classic evidence line for early human technological behavior.',
    sourceName: 'Smithsonian: Stone tools',
    sourceUrl: 'https://humanorigins.si.edu/evidence/behavior/stone-tools',
  ),
  _TimelineFact(
    id: 'homo_sapiens',
    category: 'human',
    yearsBeforePresent: 300000.0,
    displayZh: '\u7ea6 30 \u4e07\u5e74\u524d',
    displayEn: 'c. 300,000 years ago',
    titleZh: '\u667a\u4eba\u51fa\u73b0',
    titleEn: 'Homo sapiens appear',
    detailZh:
        '\u73b0\u6709\u5316\u77f3\u4e0e\u9057\u4f20\u8bc1\u636e\u901a\u5e38\u5c06\u667a\u4eba\u7684\u51fa\u73b0\u653e\u5728\u7ea6 30 \u4e07\u5e74\u524d\u3002',
    detailEn:
        'Current fossil and genetic evidence commonly places Homo sapiens around 300,000 years ago.',
    sourceName: 'Smithsonian: Homo sapiens',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens',
  ),
  _TimelineFact(
    id: 'last_glacial_maximum',
    category: 'human',
    yearsBeforePresent: 26500.0,
    displayZh: '\u7ea6 2.65 \u4e07\u5e74\u524d',
    displayEn: 'c. 26,500 years ago',
    titleZh: '\u672b\u6b21\u76db\u51b0\u671f',
    titleEn: 'Last Glacial Maximum',
    detailZh:
        '\u5168\u7403\u51b0\u76d6\u5728\u672b\u6b21\u51b0\u671f\u4e2d\u8fbe\u5230\u63a5\u8fd1\u6700\u5927\u8303\u56f4\uff0c\u5bf9\u4eba\u7fa4\u8fc1\u5f99\u548c\u751f\u6001\u73af\u5883\u4ea7\u751f\u5f71\u54cd\u3002',
    detailEn:
        'Ice sheets reached near-maximum extent during the last glacial cycle, affecting environments and human movement.',
    sourceName: 'NOAA Paleoclimatology',
    sourceUrl: 'https://www.ncei.noaa.gov/products/paleoclimatology',
  ),
  _TimelineFact(
    id: 'agriculture',
    category: 'civilization',
    yearsBeforePresent: 12000.0,
    displayZh: '\u7ea6\u516c\u5143\u524d 10000 \u5e74',
    displayEn: 'c. 10,000 BCE',
    titleZh: '\u519c\u4e1a\u548c\u65b0\u77f3\u5668\u8f6c\u578b',
    titleEn: 'Agriculture and Neolithic transition',
    detailZh:
        '\u591a\u5730\u4eba\u7fa4\u9010\u6b65\u9a6f\u5316\u690d\u7269\u548c\u52a8\u7269\uff0c\u5b9a\u5c45\u4e0e\u98df\u7269\u751f\u4ea7\u6210\u4e3a\u91cd\u8981\u8d8b\u52bf\u3002',
    detailEn:
        'Plant and animal domestication developed in multiple regions, making settlement and food production increasingly important.',
    sourceName: 'Britannica: Neolithic Revolution',
    sourceUrl: 'https://www.britannica.com/event/Neolithic-Revolution',
  ),
  _TimelineFact(
    id: 'bronze_age',
    category: 'civilization',
    yearsBeforePresent: 5300.0,
    displayZh: '\u7ea6\u516c\u5143\u524d 3300 \u5e74',
    displayEn: 'c. 3300 BCE',
    titleZh: '\u9752\u94dc\u65f6\u4ee3\u65e9\u671f',
    titleEn: 'Early Bronze Age',
    detailZh:
        '\u9752\u94dc\u51b6\u91d1\u548c\u590d\u6742\u57ce\u5e02\u793e\u4f1a\u5728\u591a\u4e2a\u533a\u57df\u9010\u6b65\u53d1\u5c55\u3002',
    detailEn:
        'Bronze metallurgy and complex urban societies developed across several regions.',
    sourceName: 'Britannica: Bronze Age',
    sourceUrl: 'https://www.britannica.com/event/Bronze-Age',
  ),
  _TimelineFact(
    id: 'writing',
    category: 'civilization',
    yearsBeforePresent: 5200.0,
    displayZh: '\u7ea6\u516c\u5143\u524d 3200 \u5e74',
    displayEn: 'c. 3200 BCE',
    titleZh: '\u65e9\u671f\u6587\u5b57\u7cfb\u7edf',
    titleEn: 'Early writing systems',
    detailZh:
        '\u7f8e\u7d22\u4e0d\u8fbe\u7c73\u4e9a\u6954\u5f62\u6587\u5b57\u548c\u57c3\u53ca\u8c61\u5f62\u6587\u5b57\u7b49\u65e9\u671f\u6587\u5b57\u7cfb\u7edf\u51fa\u73b0\u3002',
    detailEn:
        'Early writing systems such as Mesopotamian cuneiform and Egyptian hieroglyphs appeared.',
    sourceName: 'Britannica: writing',
    sourceUrl: 'https://www.britannica.com/topic/writing',
  ),
  _TimelineFact(
    id: 'iron_age',
    category: 'civilization',
    yearsBeforePresent: 3200.0,
    displayZh: '\u7ea6\u516c\u5143\u524d 1200 \u5e74',
    displayEn: 'c. 1200 BCE',
    titleZh: '\u94c1\u5668\u65f6\u4ee3\u6269\u5c55',
    titleEn: 'Iron Age expansion',
    detailZh:
        '\u94c1\u5de5\u5177\u548c\u6b66\u5668\u7684\u5e7f\u6cdb\u4f7f\u7528\u6539\u53d8\u4e86\u519c\u4e1a\u3001\u6218\u4e89\u548c\u793e\u4f1a\u7ec4\u7ec7\u3002',
    detailEn:
        'Widespread iron tools and weapons changed agriculture, warfare, and social organization.',
    sourceName: 'Britannica: Iron Age',
    sourceUrl: 'https://www.britannica.com/event/Iron-Age',
  ),
  _TimelineFact(
    id: 'qin_unification',
    category: 'civilization',
    yearsBeforePresent: 2247.0,
    displayZh: '\u516c\u5143\u524d 221 \u5e74',
    displayEn: '221 BCE',
    titleZh: '\u79e6\u7edf\u4e00\u4e2d\u56fd',
    titleEn: 'Qin unifies China',
    detailZh:
        '\u79e6\u671d\u5b8c\u6210\u4e2d\u56fd\u5386\u53f2\u4e0a\u91cd\u8981\u7684\u653f\u6cbb\u7edf\u4e00\uff0c\u5e76\u63a8\u884c\u6807\u51c6\u5316\u5236\u5ea6\u3002',
    detailEn:
        'The Qin dynasty completed a major political unification in Chinese history and promoted standardization.',
    sourceName: 'Britannica: Qin dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Qin-dynasty',
  ),
  _TimelineFact(
    id: 'paper',
    category: 'civilization',
    yearsBeforePresent: 1921.0,
    displayZh: '\u7ea6\u516c\u5143 105 \u5e74',
    displayEn: 'c. 105 CE',
    titleZh: '\u9020\u7eb8\u672f\u6539\u8fdb\u4e0e\u4f20\u64ad\u57fa\u7840',
    titleEn: 'Papermaking refined',
    detailZh:
        '\u4f20\u7edf\u8bb0\u8f7d\u5c06\u8521\u4f26\u6539\u8fdb\u9020\u7eb8\u672f\u7f6e\u4e8e\u4e1c\u6c49\u65f6\u671f\uff0c\u7eb8\u5f20\u968f\u540e\u6210\u4e3a\u91cd\u8981\u4fe1\u606f\u8f7d\u4f53\u3002',
    detailEn:
        'Traditional accounts place Cai Lun\'s papermaking improvements in the Eastern Han, after which paper became a major information medium.',
    sourceName: 'Britannica: papermaking',
    sourceUrl: 'https://www.britannica.com/technology/papermaking',
  ),
  _TimelineFact(
    id: 'black_death',
    category: 'civilization',
    yearsBeforePresent: 679.0,
    displayZh: '1347-1351 \u5e74',
    displayEn: '1347-1351 CE',
    titleZh:
        '\u9ed1\u6b7b\u75c5\u5e2d\u5377\u6b27\u4e9a\u5317\u975e\u591a\u5730',
    titleEn: 'Black Death across Eurasia and North Africa',
    detailZh:
        '14 \u4e16\u7eaa\u4e2d\u53f6\u7684\u9f20\u75ab\u5927\u6d41\u884c\u9020\u6210\u5de8\u5927\u4eba\u53e3\u548c\u793e\u4f1a\u5f71\u54cd\u3002',
    detailEn:
        'The mid-14th-century plague pandemic caused enormous demographic and social consequences.',
    sourceName: 'Britannica: Black Death',
    sourceUrl: 'https://www.britannica.com/event/Black-Death',
  ),
  _TimelineFact(
    id: 'gutenberg',
    category: 'civilization',
    yearsBeforePresent: 576.0,
    displayZh: '\u7ea6 1450 \u5e74',
    displayEn: 'c. 1450 CE',
    titleZh: '\u6b27\u6d32\u6d3b\u5b57\u5370\u5237\u6269\u6563',
    titleEn: 'Movable-type printing spreads in Europe',
    detailZh:
        '\u53e4\u817e\u5821\u5370\u5237\u6280\u672f\u63a8\u52a8\u4e66\u7c4d\u590d\u5236\u6210\u672c\u4e0b\u964d\u548c\u77e5\u8bc6\u4f20\u64ad\u52a0\u901f\u3002',
    detailEn:
        'Gutenberg-era printing lowered book reproduction costs and accelerated knowledge circulation.',
    sourceName: 'Britannica: printing press',
    sourceUrl: 'https://www.britannica.com/technology/printing-press',
  ),
  _TimelineFact(
    id: 'newton',
    category: 'science',
    yearsBeforePresent: 339.0,
    displayZh: '1687 \u5e74',
    displayEn: '1687 CE',
    titleZh:
        '\u300a\u81ea\u7136\u54f2\u5b66\u7684\u6570\u5b66\u539f\u7406\u300b\u51fa\u7248',
    titleEn: 'Newton\'s Principia published',
    detailZh:
        '\u725b\u987f\u7cfb\u7edf\u9610\u8ff0\u8fd0\u52a8\u5b9a\u5f8b\u548c\u4e07\u6709\u5f15\u529b\uff0c\u6210\u4e3a\u8fd1\u4ee3\u79d1\u5b66\u7684\u91cd\u8981\u91cc\u7a0b\u7891\u3002',
    detailEn:
        'Newton systematized laws of motion and universal gravitation, a major milestone in modern science.',
    sourceName: 'Britannica: Principia',
    sourceUrl:
        'https://www.britannica.com/topic/Philosophiae-Naturalis-Principia-Mathematica',
  ),
  _TimelineFact(
    id: 'industrial_revolution',
    category: 'modern',
    yearsBeforePresent: 266.0,
    displayZh: '\u7ea6 1760 \u5e74\u8d77',
    displayEn: 'from c. 1760 CE',
    titleZh: '\u5de5\u4e1a\u9769\u547d\u5f00\u59cb',
    titleEn: 'Industrial Revolution begins',
    detailZh:
        '\u673a\u68b0\u5316\u751f\u4ea7\u3001\u5316\u77f3\u80fd\u6e90\u548c\u5de5\u5382\u5236\u5ea6\u9010\u6b65\u6539\u53d8\u7ecf\u6d4e\u7ed3\u6784\u3002',
    detailEn:
        'Mechanized production, fossil energy, and factory systems gradually transformed economies.',
    sourceName: 'Britannica: Industrial Revolution',
    sourceUrl: 'https://www.britannica.com/event/Industrial-Revolution',
  ),
  _TimelineFact(
    id: 'darwin',
    category: 'science',
    yearsBeforePresent: 167.0,
    displayZh: '1859 \u5e74',
    displayEn: '1859 CE',
    titleZh: '\u300a\u7269\u79cd\u8d77\u6e90\u300b\u51fa\u7248',
    titleEn: 'On the Origin of Species published',
    detailZh:
        '\u8fbe\u5c14\u6587\u7684\u81ea\u7136\u9009\u62e9\u7406\u8bba\u6210\u4e3a\u73b0\u4ee3\u751f\u7269\u5b66\u7684\u6838\u5fc3\u57fa\u7840\u4e4b\u4e00\u3002',
    detailEn:
        'Darwin\'s theory of natural selection became one of the foundations of modern biology.',
    sourceName: 'Britannica: On the Origin of Species',
    sourceUrl:
        'https://www.britannica.com/topic/On-the-Origin-of-Species-by-Means-of-Natural-Selection',
  ),
  _TimelineFact(
    id: 'periodic_table',
    category: 'science',
    yearsBeforePresent: 157.0,
    displayZh: '1869 \u5e74',
    displayEn: '1869 CE',
    titleZh: '\u95e8\u6377\u5217\u592b\u5468\u671f\u8868',
    titleEn: 'Mendeleev periodic table',
    detailZh:
        '\u95e8\u6377\u5217\u592b\u6309\u539f\u5b50\u91cf\u548c\u6027\u8d28\u6392\u5217\u5143\u7d20\uff0c\u5e76\u9884\u6d4b\u672a\u77e5\u5143\u7d20\u6027\u8d28\u3002',
    detailEn:
        'Mendeleev arranged elements by atomic weight and properties and predicted properties of undiscovered elements.',
    sourceName: 'IUPAC Periodic Table',
    sourceUrl: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
  ),
  _TimelineFact(
    id: 'un_founded',
    category: 'modern',
    yearsBeforePresent: 81.0,
    displayZh: '1945 \u5e74',
    displayEn: '1945 CE',
    titleZh: '\u8054\u5408\u56fd\u6210\u7acb',
    titleEn: 'United Nations founded',
    detailZh:
        '\u7b2c\u4e8c\u6b21\u4e16\u754c\u5927\u6218\u540e\uff0c\u8054\u5408\u56fd\u4f5c\u4e3a\u56fd\u9645\u7ec4\u7ec7\u6b63\u5f0f\u6210\u7acb\u3002',
    detailEn:
        'After World War II, the United Nations was formally established as an international organization.',
    sourceName: 'United Nations: History',
    sourceUrl: 'https://www.un.org/en/about-us/history-of-the-un',
  ),
  _TimelineFact(
    id: 'dna_double_helix',
    category: 'science',
    yearsBeforePresent: 73.0,
    displayZh: '1953 \u5e74',
    displayEn: '1953 CE',
    titleZh: 'DNA \u53cc\u87ba\u65cb\u7ed3\u6784\u63d0\u51fa',
    titleEn: 'DNA double helix proposed',
    detailZh:
        '\u6c83\u68ee\u548c\u514b\u91cc\u514b\u63d0\u51fa DNA \u53cc\u87ba\u65cb\u6a21\u578b\uff0c\u8fde\u63a5\u9057\u4f20\u5b66\u4e0e\u5206\u5b50\u7ed3\u6784\u3002',
    detailEn:
        'Watson and Crick proposed the DNA double-helix model, linking genetics with molecular structure.',
    sourceName: 'Nobel Prize: DNA structure',
    sourceUrl: 'https://www.nobelprize.org/prizes/medicine/1962/summary/',
  ),
  _TimelineFact(
    id: 'moon_landing',
    category: 'science',
    yearsBeforePresent: 57.0,
    displayZh: '1969 \u5e74',
    displayEn: '1969 CE',
    titleZh: '\u963f\u6ce2\u7f57 11 \u53f7\u767b\u6708',
    titleEn: 'Apollo 11 Moon landing',
    detailZh:
        '\u4eba\u7c7b\u9996\u6b21\u5728\u6708\u7403\u8868\u9762\u884c\u8d70\u3002',
    detailEn: 'Humans walked on the Moon for the first time.',
    sourceName: 'NASA Apollo 11',
    sourceUrl: 'https://www.nasa.gov/history/apollo-11/',
  ),
  _TimelineFact(
    id: 'web',
    category: 'modern',
    yearsBeforePresent: 35.0,
    displayZh: '1991 \u5e74',
    displayEn: '1991 CE',
    titleZh: '\u4e07\u7ef4\u7f51\u516c\u5f00\u53ef\u7528',
    titleEn: 'World Wide Web becomes publicly available',
    detailZh:
        '\u4e07\u7ef4\u7f51\u5c06\u8d85\u6587\u672c\u3001URL \u548c\u4e92\u8054\u7f51\u8fde\u63a5\u4e3a\u5927\u4f17\u4fe1\u606f\u5e73\u53f0\u3002',
    detailEn:
        'The Web combined hypertext, URLs, and the Internet into a public information platform.',
    sourceName: 'CERN: Birth of the Web',
    sourceUrl: 'https://home.cern/science/computing/birth-web',
  ),
  _TimelineFact(
    id: 'human_genome',
    category: 'science',
    yearsBeforePresent: 23.0,
    displayZh: '2003 \u5e74',
    displayEn: '2003 CE',
    titleZh: '\u4eba\u7c7b\u57fa\u56e0\u7ec4\u8ba1\u5212\u5b8c\u6210',
    titleEn: 'Human Genome Project completed',
    detailZh:
        '\u4eba\u7c7b\u57fa\u56e0\u7ec4\u8ba1\u5212\u5b8c\u6210\u4e86\u4eba\u7c7b\u57fa\u56e0\u7ec4\u53c2\u8003\u5e8f\u5217\u7684\u91cd\u8981\u9636\u6bb5\u3002',
    detailEn:
        'The Human Genome Project completed a major phase of the human reference genome sequence.',
    sourceName: 'NIH: Human Genome Project',
    sourceUrl: 'https://www.genome.gov/human-genome-project',
  ),
  _TimelineFact(
    id: 'gravitational_waves',
    category: 'science',
    yearsBeforePresent: 11.0,
    displayZh: '2015 \u5e74',
    displayEn: '2015 CE',
    titleZh: '\u9996\u6b21\u76f4\u63a5\u63a2\u6d4b\u5f15\u529b\u6ce2',
    titleEn: 'First direct detection of gravitational waves',
    detailZh:
        'LIGO \u9996\u6b21\u76f4\u63a5\u63a2\u6d4b\u5230\u6765\u81ea\u53cc\u9ed1\u6d1e\u5e76\u5408\u7684\u5f15\u529b\u6ce2\u4fe1\u53f7\u3002',
    detailEn:
        'LIGO directly detected gravitational waves from a binary black-hole merger.',
    sourceName: 'LIGO discovery',
    sourceUrl: 'https://www.ligo.caltech.edu/page/detection-companion-papers',
  ),
];

const List<_ElementFact> _elementFacts = <_ElementFact>[
  _ElementFact(
    atomicNumber: 1,
    symbol: 'H',
    nameEn: 'Hydrogen',
    atomicMass: '1.0080',
    groupBlock: 'Nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1766',
    electronConfiguration: '1s1',
    electronegativity: '2.2',
    period: 1,
    group: 1,
    displayRow: 1,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 2,
    symbol: 'He',
    nameEn: 'Helium',
    atomicMass: '4.00260',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1868',
    electronConfiguration: '1s2',
    electronegativity: '',
    period: 1,
    group: 18,
    displayRow: 1,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 3,
    symbol: 'Li',
    nameEn: 'Lithium',
    atomicMass: '7.0',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[He]2s1',
    electronegativity: '0.98',
    period: 2,
    group: 1,
    displayRow: 2,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 4,
    symbol: 'Be',
    nameEn: 'Beryllium',
    atomicMass: '9.012183',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1798',
    electronConfiguration: '[He]2s2',
    electronegativity: '1.57',
    period: 2,
    group: 2,
    displayRow: 2,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 5,
    symbol: 'B',
    nameEn: 'Boron',
    atomicMass: '10.81',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[He]2s2 2p1',
    electronegativity: '2.04',
    period: 2,
    group: 13,
    displayRow: 2,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 6,
    symbol: 'C',
    nameEn: 'Carbon',
    atomicMass: '12.011',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[He]2s2 2p2',
    electronegativity: '2.55',
    period: 2,
    group: 14,
    displayRow: 2,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 7,
    symbol: 'N',
    nameEn: 'Nitrogen',
    atomicMass: '14.007',
    groupBlock: 'Nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1772',
    electronConfiguration: '[He] 2s2 2p3',
    electronegativity: '3.04',
    period: 2,
    group: 15,
    displayRow: 2,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 8,
    symbol: 'O',
    nameEn: 'Oxygen',
    atomicMass: '15.999',
    groupBlock: 'Nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1774',
    electronConfiguration: '[He]2s2 2p4',
    electronegativity: '3.44',
    period: 2,
    group: 16,
    displayRow: 2,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 9,
    symbol: 'F',
    nameEn: 'Fluorine',
    atomicMass: '18.99840316',
    groupBlock: 'Halogen',
    standardState: 'Gas',
    yearDiscovered: '1670',
    electronConfiguration: '[He]2s2 2p5',
    electronegativity: '3.98',
    period: 2,
    group: 17,
    displayRow: 2,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 10,
    symbol: 'Ne',
    nameEn: 'Neon',
    atomicMass: '20.180',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[He]2s2 2p6',
    electronegativity: '',
    period: 2,
    group: 18,
    displayRow: 2,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 11,
    symbol: 'Na',
    nameEn: 'Sodium',
    atomicMass: '22.9897693',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1807',
    electronConfiguration: '[Ne]3s1',
    electronegativity: '0.93',
    period: 3,
    group: 1,
    displayRow: 3,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 12,
    symbol: 'Mg',
    nameEn: 'Magnesium',
    atomicMass: '24.305',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[Ne]3s2',
    electronegativity: '1.31',
    period: 3,
    group: 2,
    displayRow: 3,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 13,
    symbol: 'Al',
    nameEn: 'Aluminum',
    atomicMass: '26.981538',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ne]3s2 3p1',
    electronegativity: '1.61',
    period: 3,
    group: 13,
    displayRow: 3,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 14,
    symbol: 'Si',
    nameEn: 'Silicon',
    atomicMass: '28.085',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1854',
    electronConfiguration: '[Ne]3s2 3p2',
    electronegativity: '1.9',
    period: 3,
    group: 14,
    displayRow: 3,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 15,
    symbol: 'P',
    nameEn: 'Phosphorus',
    atomicMass: '30.97376200',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: '1669',
    electronConfiguration: '[Ne]3s2 3p3',
    electronegativity: '2.19',
    period: 3,
    group: 15,
    displayRow: 3,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 16,
    symbol: 'S',
    nameEn: 'Sulfur',
    atomicMass: '32.07',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ne]3s2 3p4',
    electronegativity: '2.58',
    period: 3,
    group: 16,
    displayRow: 3,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 17,
    symbol: 'Cl',
    nameEn: 'Chlorine',
    atomicMass: '35.45',
    groupBlock: 'Halogen',
    standardState: 'Gas',
    yearDiscovered: '1774',
    electronConfiguration: '[Ne]3s2 3p5',
    electronegativity: '3.16',
    period: 3,
    group: 17,
    displayRow: 3,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 18,
    symbol: 'Ar',
    nameEn: 'Argon',
    atomicMass: '39.9',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1894',
    electronConfiguration: '[Ne]3s2 3p6',
    electronegativity: '',
    period: 3,
    group: 18,
    displayRow: 3,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 19,
    symbol: 'K',
    nameEn: 'Potassium',
    atomicMass: '39.0983',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1807',
    electronConfiguration: '[Ar]4s1',
    electronegativity: '0.82',
    period: 4,
    group: 1,
    displayRow: 4,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 20,
    symbol: 'Ca',
    nameEn: 'Calcium',
    atomicMass: '40.08',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2',
    electronegativity: '1',
    period: 4,
    group: 2,
    displayRow: 4,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 21,
    symbol: 'Sc',
    nameEn: 'Scandium',
    atomicMass: '44.95591',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Ar]4s2 3d1',
    electronegativity: '1.36',
    period: 4,
    group: 3,
    displayRow: 4,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 22,
    symbol: 'Ti',
    nameEn: 'Titanium',
    atomicMass: '47.867',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1791',
    electronConfiguration: '[Ar]4s2 3d2',
    electronegativity: '1.54',
    period: 4,
    group: 4,
    displayRow: 4,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 23,
    symbol: 'V',
    nameEn: 'Vanadium',
    atomicMass: '50.9415',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1801',
    electronConfiguration: '[Ar]4s2 3d3',
    electronegativity: '1.63',
    period: 4,
    group: 5,
    displayRow: 4,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 24,
    symbol: 'Cr',
    nameEn: 'Chromium',
    atomicMass: '51.996',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1797',
    electronConfiguration: '[Ar]3d5 4s1',
    electronegativity: '1.66',
    period: 4,
    group: 6,
    displayRow: 4,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 25,
    symbol: 'Mn',
    nameEn: 'Manganese',
    atomicMass: '54.93804',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1774',
    electronConfiguration: '[Ar]4s2 3d5',
    electronegativity: '1.55',
    period: 4,
    group: 7,
    displayRow: 4,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 26,
    symbol: 'Fe',
    nameEn: 'Iron',
    atomicMass: '55.84',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2 3d6',
    electronegativity: '1.83',
    period: 4,
    group: 8,
    displayRow: 4,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 27,
    symbol: 'Co',
    nameEn: 'Cobalt',
    atomicMass: '58.93319',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1735',
    electronConfiguration: '[Ar]4s2 3d7',
    electronegativity: '1.88',
    period: 4,
    group: 9,
    displayRow: 4,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 28,
    symbol: 'Ni',
    nameEn: 'Nickel',
    atomicMass: '58.693',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1751',
    electronConfiguration: '[Ar]4s2 3d8',
    electronegativity: '1.91',
    period: 4,
    group: 10,
    displayRow: 4,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 29,
    symbol: 'Cu',
    nameEn: 'Copper',
    atomicMass: '63.55',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s1 3d10',
    electronegativity: '1.9',
    period: 4,
    group: 11,
    displayRow: 4,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 30,
    symbol: 'Zn',
    nameEn: 'Zinc',
    atomicMass: '65.4',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1746',
    electronConfiguration: '[Ar]4s2 3d10',
    electronegativity: '1.65',
    period: 4,
    group: 12,
    displayRow: 4,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 31,
    symbol: 'Ga',
    nameEn: 'Gallium',
    atomicMass: '69.723',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1875',
    electronConfiguration: '[Ar]4s2 3d10 4p1',
    electronegativity: '1.81',
    period: 4,
    group: 13,
    displayRow: 4,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 32,
    symbol: 'Ge',
    nameEn: 'Germanium',
    atomicMass: '72.63',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1886',
    electronConfiguration: '[Ar]4s2 3d10 4p2',
    electronegativity: '2.01',
    period: 4,
    group: 14,
    displayRow: 4,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 33,
    symbol: 'As',
    nameEn: 'Arsenic',
    atomicMass: '74.92159',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2 3d10 4p3',
    electronegativity: '2.18',
    period: 4,
    group: 15,
    displayRow: 4,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 34,
    symbol: 'Se',
    nameEn: 'Selenium',
    atomicMass: '78.97',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[Ar]4s2 3d10 4p4',
    electronegativity: '2.55',
    period: 4,
    group: 16,
    displayRow: 4,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 35,
    symbol: 'Br',
    nameEn: 'Bromine',
    atomicMass: '79.90',
    groupBlock: 'Halogen',
    standardState: 'Liquid',
    yearDiscovered: '1826',
    electronConfiguration: '[Ar]4s2 3d10 4p5',
    electronegativity: '2.96',
    period: 4,
    group: 17,
    displayRow: 4,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 36,
    symbol: 'Kr',
    nameEn: 'Krypton',
    atomicMass: '83.80',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[Ar]4s2 3d10 4p6',
    electronegativity: '3',
    period: 4,
    group: 18,
    displayRow: 4,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 37,
    symbol: 'Rb',
    nameEn: 'Rubidium',
    atomicMass: '85.468',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1861',
    electronConfiguration: '[Kr]5s1',
    electronegativity: '0.82',
    period: 5,
    group: 1,
    displayRow: 5,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 38,
    symbol: 'Sr',
    nameEn: 'Strontium',
    atomicMass: '87.62',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1790',
    electronConfiguration: '[Kr]5s2',
    electronegativity: '0.95',
    period: 5,
    group: 2,
    displayRow: 5,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 39,
    symbol: 'Y',
    nameEn: 'Yttrium',
    atomicMass: '88.90584',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1794',
    electronConfiguration: '[Kr]5s2 4d1',
    electronegativity: '1.22',
    period: 5,
    group: 3,
    displayRow: 5,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 40,
    symbol: 'Zr',
    nameEn: 'Zirconium',
    atomicMass: '91.22',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1789',
    electronConfiguration: '[Kr]5s2 4d2',
    electronegativity: '1.33',
    period: 5,
    group: 4,
    displayRow: 5,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 41,
    symbol: 'Nb',
    nameEn: 'Niobium',
    atomicMass: '92.90637',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1801',
    electronConfiguration: '[Kr]5s1 4d4',
    electronegativity: '1.6',
    period: 5,
    group: 5,
    displayRow: 5,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 42,
    symbol: 'Mo',
    nameEn: 'Molybdenum',
    atomicMass: '95.95',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1778',
    electronConfiguration: '[Kr]5s1 4d5',
    electronegativity: '2.16',
    period: 5,
    group: 6,
    displayRow: 5,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 43,
    symbol: 'Tc',
    nameEn: 'Technetium',
    atomicMass: '96.90636',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1937',
    electronConfiguration: '[Kr]5s2 4d5',
    electronegativity: '1.9',
    period: 5,
    group: 7,
    displayRow: 5,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 44,
    symbol: 'Ru',
    nameEn: 'Ruthenium',
    atomicMass: '101.1',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1827',
    electronConfiguration: '[Kr]5s1 4d7',
    electronegativity: '2.2',
    period: 5,
    group: 8,
    displayRow: 5,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 45,
    symbol: 'Rh',
    nameEn: 'Rhodium',
    atomicMass: '102.9055',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Kr]5s1 4d8',
    electronegativity: '2.28',
    period: 5,
    group: 9,
    displayRow: 5,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 46,
    symbol: 'Pd',
    nameEn: 'Palladium',
    atomicMass: '106.42',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Kr]4d10',
    electronegativity: '2.2',
    period: 5,
    group: 10,
    displayRow: 5,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 47,
    symbol: 'Ag',
    nameEn: 'Silver',
    atomicMass: '107.868',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s1 4d10',
    electronegativity: '1.93',
    period: 5,
    group: 11,
    displayRow: 5,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 48,
    symbol: 'Cd',
    nameEn: 'Cadmium',
    atomicMass: '112.41',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[Kr]5s2 4d10',
    electronegativity: '1.69',
    period: 5,
    group: 12,
    displayRow: 5,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 49,
    symbol: 'In',
    nameEn: 'Indium',
    atomicMass: '114.818',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1863',
    electronConfiguration: '[Kr]5s2 4d10 5p1',
    electronegativity: '1.78',
    period: 5,
    group: 13,
    displayRow: 5,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 50,
    symbol: 'Sn',
    nameEn: 'Tin',
    atomicMass: '118.71',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s2 4d10 5p2',
    electronegativity: '1.96',
    period: 5,
    group: 14,
    displayRow: 5,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 51,
    symbol: 'Sb',
    nameEn: 'Antimony',
    atomicMass: '121.760',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s2 4d10 5p3',
    electronegativity: '2.05',
    period: 5,
    group: 15,
    displayRow: 5,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 52,
    symbol: 'Te',
    nameEn: 'Tellurium',
    atomicMass: '127.6',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1782',
    electronConfiguration: '[Kr]5s2 4d10 5p4',
    electronegativity: '2.1',
    period: 5,
    group: 16,
    displayRow: 5,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 53,
    symbol: 'I',
    nameEn: 'Iodine',
    atomicMass: '126.9045',
    groupBlock: 'Halogen',
    standardState: 'Solid',
    yearDiscovered: '1811',
    electronConfiguration: '[Kr]5s2 4d10 5p5',
    electronegativity: '2.66',
    period: 5,
    group: 17,
    displayRow: 5,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 54,
    symbol: 'Xe',
    nameEn: 'Xenon',
    atomicMass: '131.29',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[Kr]5s2 4d10 5p6',
    electronegativity: '2.6',
    period: 5,
    group: 18,
    displayRow: 5,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 55,
    symbol: 'Cs',
    nameEn: 'Cesium',
    atomicMass: '132.9054520',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1860',
    electronConfiguration: '[Xe]6s1',
    electronegativity: '0.79',
    period: 6,
    group: 1,
    displayRow: 6,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 56,
    symbol: 'Ba',
    nameEn: 'Barium',
    atomicMass: '137.33',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[Xe]6s2',
    electronegativity: '0.89',
    period: 6,
    group: 2,
    displayRow: 6,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 57,
    symbol: 'La',
    nameEn: 'Lanthanum',
    atomicMass: '138.9055',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1839',
    electronConfiguration: '[Xe]6s2 5d1',
    electronegativity: '1.1',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 58,
    symbol: 'Ce',
    nameEn: 'Cerium',
    atomicMass: '140.116',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f1 5d1',
    electronegativity: '1.12',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 59,
    symbol: 'Pr',
    nameEn: 'Praseodymium',
    atomicMass: '140.90766',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1885',
    electronConfiguration: '[Xe]6s2 4f3',
    electronegativity: '1.13',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 60,
    symbol: 'Nd',
    nameEn: 'Neodymium',
    atomicMass: '144.24',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1885',
    electronConfiguration: '[Xe]6s2 4f4',
    electronegativity: '1.14',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 61,
    symbol: 'Pm',
    nameEn: 'Promethium',
    atomicMass: '144.91276',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1945',
    electronConfiguration: '[Xe]6s2 4f5',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 62,
    symbol: 'Sm',
    nameEn: 'Samarium',
    atomicMass: '150.4',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Xe]6s2 4f6',
    electronegativity: '1.17',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 63,
    symbol: 'Eu',
    nameEn: 'Europium',
    atomicMass: '151.964',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1901',
    electronConfiguration: '[Xe]6s2 4f7',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 64,
    symbol: 'Gd',
    nameEn: 'Gadolinium',
    atomicMass: '157.25',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1880',
    electronConfiguration: '[Xe]6s2 4f7 5d1',
    electronegativity: '1.2',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 65,
    symbol: 'Tb',
    nameEn: 'Terbium',
    atomicMass: '158.92535',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1843',
    electronConfiguration: '[Xe]6s2 4f9',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 66,
    symbol: 'Dy',
    nameEn: 'Dysprosium',
    atomicMass: '162.500',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1886',
    electronConfiguration: '[Xe]6s2 4f10',
    electronegativity: '1.22',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 67,
    symbol: 'Ho',
    nameEn: 'Holmium',
    atomicMass: '164.93033',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1878',
    electronConfiguration: '[Xe]6s2 4f11',
    electronegativity: '1.23',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 68,
    symbol: 'Er',
    nameEn: 'Erbium',
    atomicMass: '167.26',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1843',
    electronConfiguration: '[Xe]6s2 4f12',
    electronegativity: '1.24',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 69,
    symbol: 'Tm',
    nameEn: 'Thulium',
    atomicMass: '168.93422',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Xe]6s2 4f13',
    electronegativity: '1.25',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 70,
    symbol: 'Yb',
    nameEn: 'Ytterbium',
    atomicMass: '173.05',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1878',
    electronConfiguration: '[Xe]6s2 4f14',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 71,
    symbol: 'Lu',
    nameEn: 'Lutetium',
    atomicMass: '174.9667',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1907',
    electronConfiguration: '[Xe]6s2 4f14 5d1',
    electronegativity: '1.27',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 72,
    symbol: 'Hf',
    nameEn: 'Hafnium',
    atomicMass: '178.49',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1923',
    electronConfiguration: '[Xe]6s2 4f14 5d2',
    electronegativity: '1.3',
    period: 6,
    group: 4,
    displayRow: 6,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 73,
    symbol: 'Ta',
    nameEn: 'Tantalum',
    atomicMass: '180.9479',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1802',
    electronConfiguration: '[Xe]6s2 4f14 5d3',
    electronegativity: '1.5',
    period: 6,
    group: 5,
    displayRow: 6,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 74,
    symbol: 'W',
    nameEn: 'Tungsten',
    atomicMass: '183.84',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1783',
    electronConfiguration: '[Xe]6s2 4f14 5d4',
    electronegativity: '2.36',
    period: 6,
    group: 6,
    displayRow: 6,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 75,
    symbol: 'Re',
    nameEn: 'Rhenium',
    atomicMass: '186.207',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1925',
    electronConfiguration: '[Xe]6s2 4f14 5d5',
    electronegativity: '1.9',
    period: 6,
    group: 7,
    displayRow: 6,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 76,
    symbol: 'Os',
    nameEn: 'Osmium',
    atomicMass: '190.2',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f14 5d6',
    electronegativity: '2.2',
    period: 6,
    group: 8,
    displayRow: 6,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 77,
    symbol: 'Ir',
    nameEn: 'Iridium',
    atomicMass: '192.22',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f14 5d7',
    electronegativity: '2.2',
    period: 6,
    group: 9,
    displayRow: 6,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 78,
    symbol: 'Pt',
    nameEn: 'Platinum',
    atomicMass: '195.08',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1735',
    electronConfiguration: '[Xe]6s1 4f14 5d9',
    electronegativity: '2.28',
    period: 6,
    group: 10,
    displayRow: 6,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 79,
    symbol: 'Au',
    nameEn: 'Gold',
    atomicMass: '196.96657',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s1 4f14 5d10',
    electronegativity: '2.54',
    period: 6,
    group: 11,
    displayRow: 6,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 80,
    symbol: 'Hg',
    nameEn: 'Mercury',
    atomicMass: '200.59',
    groupBlock: 'Transition metal',
    standardState: 'Liquid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s2 4f14 5d10',
    electronegativity: '2',
    period: 6,
    group: 12,
    displayRow: 6,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 81,
    symbol: 'Tl',
    nameEn: 'Thallium',
    atomicMass: '204.383',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1861',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p1',
    electronegativity: '1.62',
    period: 6,
    group: 13,
    displayRow: 6,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 82,
    symbol: 'Pb',
    nameEn: 'Lead',
    atomicMass: '207',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p2',
    electronegativity: '2.33',
    period: 6,
    group: 14,
    displayRow: 6,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 83,
    symbol: 'Bi',
    nameEn: 'Bismuth',
    atomicMass: '208.98040',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1753',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p3',
    electronegativity: '2.02',
    period: 6,
    group: 15,
    displayRow: 6,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 84,
    symbol: 'Po',
    nameEn: 'Polonium',
    atomicMass: '208.98243',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1898',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p4',
    electronegativity: '2',
    period: 6,
    group: 16,
    displayRow: 6,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 85,
    symbol: 'At',
    nameEn: 'Astatine',
    atomicMass: '209.98715',
    groupBlock: 'Halogen',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p5',
    electronegativity: '2.2',
    period: 6,
    group: 17,
    displayRow: 6,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 86,
    symbol: 'Rn',
    nameEn: 'Radon',
    atomicMass: '222.01758',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1900',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p6',
    electronegativity: '',
    period: 6,
    group: 18,
    displayRow: 6,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 87,
    symbol: 'Fr',
    nameEn: 'Francium',
    atomicMass: '223.01973',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1939',
    electronConfiguration: '[Rn]7s1',
    electronegativity: '0.7',
    period: 7,
    group: 1,
    displayRow: 7,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 88,
    symbol: 'Ra',
    nameEn: 'Radium',
    atomicMass: '226.02541',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1898',
    electronConfiguration: '[Rn]7s2',
    electronegativity: '0.9',
    period: 7,
    group: 2,
    displayRow: 7,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 89,
    symbol: 'Ac',
    nameEn: 'Actinium',
    atomicMass: '227.02775',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1899',
    electronConfiguration: '[Rn]7s2 6d1',
    electronegativity: '1.1',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 90,
    symbol: 'Th',
    nameEn: 'Thorium',
    atomicMass: '232.038',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1828',
    electronConfiguration: '[Rn]7s2 6d2',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 91,
    symbol: 'Pa',
    nameEn: 'Protactinium',
    atomicMass: '231.03588',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1913',
    electronConfiguration: '[Rn]7s2 5f2 6d1',
    electronegativity: '1.5',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 92,
    symbol: 'U',
    nameEn: 'Uranium',
    atomicMass: '238.0289',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1789',
    electronConfiguration: '[Rn]7s2 5f3 6d1',
    electronegativity: '1.38',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 93,
    symbol: 'Np',
    nameEn: 'Neptunium',
    atomicMass: '237.048172',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Rn]7s2 5f4 6d1',
    electronegativity: '1.36',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 94,
    symbol: 'Pu',
    nameEn: 'Plutonium',
    atomicMass: '244.06420',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Rn]7s2 5f6',
    electronegativity: '1.28',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 95,
    symbol: 'Am',
    nameEn: 'Americium',
    atomicMass: '243.061380',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1944',
    electronConfiguration: '[Rn]7s2 5f7',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 96,
    symbol: 'Cm',
    nameEn: 'Curium',
    atomicMass: '247.07035',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1944',
    electronConfiguration: '[Rn]7s2 5f7 6d1',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 97,
    symbol: 'Bk',
    nameEn: 'Berkelium',
    atomicMass: '247.07031',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1949',
    electronConfiguration: '[Rn]7s2 5f9',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 98,
    symbol: 'Cf',
    nameEn: 'Californium',
    atomicMass: '251.07959',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1950',
    electronConfiguration: '[Rn]7s2 5f10',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 99,
    symbol: 'Es',
    nameEn: 'Einsteinium',
    atomicMass: '252.0830',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1952',
    electronConfiguration: '[Rn]7s2 5f11',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 100,
    symbol: 'Fm',
    nameEn: 'Fermium',
    atomicMass: '257.09511',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1952',
    electronConfiguration: '[Rn] 5f12 7s2',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 101,
    symbol: 'Md',
    nameEn: 'Mendelevium',
    atomicMass: '258.09843',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1955',
    electronConfiguration: '[Rn]7s2 5f13',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 102,
    symbol: 'No',
    nameEn: 'Nobelium',
    atomicMass: '259.10100',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1957',
    electronConfiguration: '[Rn]7s2 5f14',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 103,
    symbol: 'Lr',
    nameEn: 'Lawrencium',
    atomicMass: '266.120',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1961',
    electronConfiguration: '[Rn]7s2 5f14 6d1',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 104,
    symbol: 'Rf',
    nameEn: 'Rutherfordium',
    atomicMass: '267.122',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1964',
    electronConfiguration: '[Rn]7s2 5f14 6d2',
    electronegativity: '',
    period: 7,
    group: 4,
    displayRow: 7,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 105,
    symbol: 'Db',
    nameEn: 'Dubnium',
    atomicMass: '268.126',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1967',
    electronConfiguration: '[Rn]7s2 5f14 6d3',
    electronegativity: '',
    period: 7,
    group: 5,
    displayRow: 7,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 106,
    symbol: 'Sg',
    nameEn: 'Seaborgium',
    atomicMass: '269.128',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1974',
    electronConfiguration: '[Rn]7s2 5f14 6d4',
    electronegativity: '',
    period: 7,
    group: 6,
    displayRow: 7,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 107,
    symbol: 'Bh',
    nameEn: 'Bohrium',
    atomicMass: '270.133',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1976',
    electronConfiguration: '[Rn]7s2 5f14 6d5',
    electronegativity: '',
    period: 7,
    group: 7,
    displayRow: 7,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 108,
    symbol: 'Hs',
    nameEn: 'Hassium',
    atomicMass: '269.1336',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1984',
    electronConfiguration: '[Rn]7s2 5f14 6d6',
    electronegativity: '',
    period: 7,
    group: 8,
    displayRow: 7,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 109,
    symbol: 'Mt',
    nameEn: 'Meitnerium',
    atomicMass: '277.154',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1982',
    electronConfiguration: '[Rn]7s2 5f14 6d7 (calculated)',
    electronegativity: '',
    period: 7,
    group: 9,
    displayRow: 7,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 110,
    symbol: 'Ds',
    nameEn: 'Darmstadtium',
    atomicMass: '282.166',
    groupBlock: 'Transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1994',
    electronConfiguration: '[Rn]7s2 5f14 6d8 (predicted)',
    electronegativity: '',
    period: 7,
    group: 10,
    displayRow: 7,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 111,
    symbol: 'Rg',
    nameEn: 'Roentgenium',
    atomicMass: '282.169',
    groupBlock: 'Transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1994',
    electronConfiguration: '[Rn]7s2 5f14 6d9 (predicted)',
    electronegativity: '',
    period: 7,
    group: 11,
    displayRow: 7,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 112,
    symbol: 'Cn',
    nameEn: 'Copernicium',
    atomicMass: '286.179',
    groupBlock: 'Transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1996',
    electronConfiguration: '[Rn]7s2 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 12,
    displayRow: 7,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 113,
    symbol: 'Nh',
    nameEn: 'Nihonium',
    atomicMass: '286.182',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2004',
    electronConfiguration: '[Rn]5f14 6d10 7s2 7p1 (predicted)',
    electronegativity: '',
    period: 7,
    group: 13,
    displayRow: 7,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 114,
    symbol: 'Fl',
    nameEn: 'Flerovium',
    atomicMass: '290.192',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1998',
    electronConfiguration: '[Rn]7s2 7p2 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 14,
    displayRow: 7,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 115,
    symbol: 'Mc',
    nameEn: 'Moscovium',
    atomicMass: '290.196',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2003',
    electronConfiguration: '[Rn]7s2 7p3 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 15,
    displayRow: 7,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 116,
    symbol: 'Lv',
    nameEn: 'Livermorium',
    atomicMass: '293.205',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2000',
    electronConfiguration: '[Rn]7s2 7p4 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 16,
    displayRow: 7,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 117,
    symbol: 'Ts',
    nameEn: 'Tennessine',
    atomicMass: '294.211',
    groupBlock: 'Halogen',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2010',
    electronConfiguration: '[Rn]7s2 7p5 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 17,
    displayRow: 7,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 118,
    symbol: 'Og',
    nameEn: 'Oganesson',
    atomicMass: '295.216',
    groupBlock: 'Noble gas',
    standardState: 'Expected to be a Gas',
    yearDiscovered: '2006',
    electronConfiguration: '[Rn]7s2 7p6 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 18,
    displayRow: 7,
    displayColumn: 18,
  ),
];

const List<_LifeToolSource> _timelinePeriodicSources = <_LifeToolSource>[
  _LifeToolSource(
    name: 'PubChem PUG REST periodic table',
    url: 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON',
    copyrightNote:
        'Element facts: atomic number, symbol, atomic mass, group block, state, configuration, electronegativity, and discovery year.',
  ),
  _LifeToolSource(
    name: 'IUPAC Periodic Table of Elements',
    url: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
    copyrightNote: 'Authoritative periodic-table naming and element reference.',
  ),
  _LifeToolSource(
    name: 'CIAAW standard atomic weights',
    url: 'https://ciaaw.org/atomic-weights.htm',
    copyrightNote:
        'Reference body for standard atomic-weight intervals and revisions.',
  ),
  _LifeToolSource(
    name: 'International Chronostratigraphic Chart',
    url: 'https://stratigraphy.org/chart',
    copyrightNote: 'Geologic-period anchor dates.',
  ),
  _LifeToolSource(
    name: 'NASA Science',
    url: 'https://science.nasa.gov/',
    copyrightNote: 'Cosmic and space-science anchor dates.',
  ),
  _LifeToolSource(
    name: 'Smithsonian Human Origins Program',
    url: 'https://humanorigins.si.edu/',
    copyrightNote: 'Human-evolution anchor dates.',
  ),
  _LifeToolSource(
    name: 'Encyclopaedia Britannica',
    url: 'https://www.britannica.com/',
    copyrightNote: 'Civilization and science-history cross-checks.',
  ),
  _LifeToolSource(
    name: 'NASA Image Library media',
    url: 'https://images.nasa.gov/',
    copyrightNote:
        'Remote atmosphere images for cosmic and science timeline backdrops.',
  ),
  _LifeToolSource(
    name: 'USGS public-domain geology media',
    url: 'https://www.usgs.gov/media/images/basalt-rock-photograph',
    copyrightNote: 'Rock/geology backdrop reference.',
  ),
  _LifeToolSource(
    name: 'Wikimedia Commons public-domain artifacts',
    url: 'https://commons.wikimedia.org/wiki/File:The_Rosetta_Stone.jpg',
    copyrightNote: 'Artifact backdrop reference.',
  ),
];
