part of '../toolbox_life_tools.dart';

const List<_ElementFact> _elementFacts03 = <_ElementFact>[
  _ElementFact(
    atomicNumber: 79,
    symbol: 'Au',
    nameKey: 'toolbox.life.element.au.name',
    nameEn: 'Gold',
    atomicMass: '196.96657',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s1 4f14 5d10',
    electronegativity: '2.54',
    atomicRadius: '166',
    ionizationEnergy: '9.226',
    electronAffinity: '2.309',
    oxidationStates: '+3, +1',
    meltingPoint: '1337.33',
    boilingPoint: '3129',
    density: '19.282',
    period: 6,
    group: 11,
    displayRow: 6,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 80,
    symbol: 'Hg',
    nameKey: 'toolbox.life.element.hg.name',
    nameEn: 'Mercury',
    atomicMass: '200.59',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Liquid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s2 4f14 5d10',
    electronegativity: '2',
    atomicRadius: '209',
    ionizationEnergy: '10.438',
    electronAffinity: '',
    oxidationStates: '+2, +1',
    meltingPoint: '234.32',
    boilingPoint: '629.88',
    density: '13.5336',
    period: 6,
    group: 12,
    displayRow: 6,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 81,
    symbol: 'Tl',
    nameKey: 'toolbox.life.element.tl.name',
    nameEn: 'Thallium',
    atomicMass: '204.383',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1861',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p1',
    electronegativity: '1.62',
    atomicRadius: '196',
    ionizationEnergy: '6.108',
    electronAffinity: '0.2',
    oxidationStates: '+3, +1',
    meltingPoint: '577',
    boilingPoint: '1746',
    density: '11.8',
    period: 6,
    group: 13,
    displayRow: 6,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 82,
    symbol: 'Pb',
    nameKey: 'toolbox.life.element.pb.name',
    nameEn: 'Lead',
    atomicMass: '207',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p2',
    electronegativity: '2.33',
    atomicRadius: '202',
    ionizationEnergy: '7.417',
    electronAffinity: '0.36',
    oxidationStates: '+4, +2',
    meltingPoint: '600.61',
    boilingPoint: '2022',
    density: '11.342',
    period: 6,
    group: 14,
    displayRow: 6,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 83,
    symbol: 'Bi',
    nameKey: 'toolbox.life.element.bi.name',
    nameEn: 'Bismuth',
    atomicMass: '208.98040',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1753',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p3',
    electronegativity: '2.02',
    atomicRadius: '207',
    ionizationEnergy: '7.289',
    electronAffinity: '0.946',
    oxidationStates: '+5, +3',
    meltingPoint: '544.55',
    boilingPoint: '1837',
    density: '9.807',
    period: 6,
    group: 15,
    displayRow: 6,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 84,
    symbol: 'Po',
    nameKey: 'toolbox.life.element.po.name',
    nameEn: 'Polonium',
    atomicMass: '208.98243',
    groupBlock: 'Metalloid',
    groupBlockKey: 'toolbox.life.element.block.metalloid',
    standardState: 'Solid',
    yearDiscovered: '1898',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p4',
    electronegativity: '2',
    atomicRadius: '197',
    ionizationEnergy: '8.417',
    electronAffinity: '1.9',
    oxidationStates: '+4, +2',
    meltingPoint: '527',
    boilingPoint: '1235',
    density: '9.32',
    period: 6,
    group: 16,
    displayRow: 6,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 85,
    symbol: 'At',
    nameKey: 'toolbox.life.element.at.name',
    nameEn: 'Astatine',
    atomicMass: '209.98715',
    groupBlock: 'Halogen',
    groupBlockKey: 'toolbox.life.element.block.halogen',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p5',
    electronegativity: '2.2',
    atomicRadius: '202',
    ionizationEnergy: '9.5',
    electronAffinity: '2.8',
    oxidationStates: '7, 5, 3, 1, -1',
    meltingPoint: '575',
    boilingPoint: '',
    density: '7',
    period: 6,
    group: 17,
    displayRow: 6,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 86,
    symbol: 'Rn',
    nameKey: 'toolbox.life.element.rn.name',
    nameEn: 'Radon',
    atomicMass: '222.01758',
    groupBlock: 'Noble gas',
    groupBlockKey: 'toolbox.life.element.block.noble_gas',
    standardState: 'Gas',
    yearDiscovered: '1900',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p6',
    electronegativity: '',
    atomicRadius: '220',
    ionizationEnergy: '10.745',
    electronAffinity: '',
    oxidationStates: '0',
    meltingPoint: '202',
    boilingPoint: '211.45',
    density: '0.00973',
    period: 6,
    group: 18,
    displayRow: 6,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 87,
    symbol: 'Fr',
    nameKey: 'toolbox.life.element.fr.name',
    nameEn: 'Francium',
    atomicMass: '223.01973',
    groupBlock: 'Alkali metal',
    groupBlockKey: 'toolbox.life.element.block.alkali_metal',
    standardState: 'Solid',
    yearDiscovered: '1939',
    electronConfiguration: '[Rn]7s1',
    electronegativity: '0.7',
    atomicRadius: '348',
    ionizationEnergy: '3.9',
    electronAffinity: '0.47',
    oxidationStates: '+1',
    meltingPoint: '300',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 1,
    displayRow: 7,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 88,
    symbol: 'Ra',
    nameKey: 'toolbox.life.element.ra.name',
    nameEn: 'Radium',
    atomicMass: '226.02541',
    groupBlock: 'Alkaline earth metal',
    groupBlockKey: 'toolbox.life.element.block.alkaline_earth_metal',
    standardState: 'Solid',
    yearDiscovered: '1898',
    electronConfiguration: '[Rn]7s2',
    electronegativity: '0.9',
    atomicRadius: '283',
    ionizationEnergy: '5.279',
    electronAffinity: '',
    oxidationStates: '+2',
    meltingPoint: '973',
    boilingPoint: '1413',
    density: '5',
    period: 7,
    group: 2,
    displayRow: 7,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 89,
    symbol: 'Ac',
    nameKey: 'toolbox.life.element.ac.name',
    nameEn: 'Actinium',
    atomicMass: '227.02775',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1899',
    electronConfiguration: '[Rn]7s2 6d1',
    electronegativity: '1.1',
    atomicRadius: '260',
    ionizationEnergy: '5.17',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1324',
    boilingPoint: '3471',
    density: '10.07',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 90,
    symbol: 'Th',
    nameKey: 'toolbox.life.element.th.name',
    nameEn: 'Thorium',
    atomicMass: '232.038',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1828',
    electronConfiguration: '[Rn]7s2 6d2',
    electronegativity: '1.3',
    atomicRadius: '237',
    ionizationEnergy: '6.08',
    electronAffinity: '',
    oxidationStates: '+4',
    meltingPoint: '2023',
    boilingPoint: '5061',
    density: '11.72',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 91,
    symbol: 'Pa',
    nameKey: 'toolbox.life.element.pa.name',
    nameEn: 'Protactinium',
    atomicMass: '231.03588',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1913',
    electronConfiguration: '[Rn]7s2 5f2 6d1',
    electronegativity: '1.5',
    atomicRadius: '243',
    ionizationEnergy: '5.89',
    electronAffinity: '',
    oxidationStates: '+5, +4',
    meltingPoint: '1845',
    boilingPoint: '',
    density: '15.37',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 92,
    symbol: 'U',
    nameKey: 'toolbox.life.element.u.name',
    nameEn: 'Uranium',
    atomicMass: '238.0289',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1789',
    electronConfiguration: '[Rn]7s2 5f3 6d1',
    electronegativity: '1.38',
    atomicRadius: '240',
    ionizationEnergy: '6.194',
    electronAffinity: '',
    oxidationStates: '+6, +5, +4, +3',
    meltingPoint: '1408',
    boilingPoint: '4404',
    density: '18.95',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 93,
    symbol: 'Np',
    nameKey: 'toolbox.life.element.np.name',
    nameEn: 'Neptunium',
    atomicMass: '237.048172',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Rn]7s2 5f4 6d1',
    electronegativity: '1.36',
    atomicRadius: '221',
    ionizationEnergy: '6.266',
    electronAffinity: '',
    oxidationStates: '+6, +5, +4, +3',
    meltingPoint: '917',
    boilingPoint: '4175',
    density: '20.25',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 94,
    symbol: 'Pu',
    nameKey: 'toolbox.life.element.pu.name',
    nameEn: 'Plutonium',
    atomicMass: '244.06420',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Rn]7s2 5f6',
    electronegativity: '1.28',
    atomicRadius: '243',
    ionizationEnergy: '6.06',
    electronAffinity: '',
    oxidationStates: '+6, +5, +4, +3',
    meltingPoint: '913',
    boilingPoint: '3501',
    density: '19.84',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 95,
    symbol: 'Am',
    nameKey: 'toolbox.life.element.am.name',
    nameEn: 'Americium',
    atomicMass: '243.061380',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1944',
    electronConfiguration: '[Rn]7s2 5f7',
    electronegativity: '1.3',
    atomicRadius: '244',
    ionizationEnergy: '5.993',
    electronAffinity: '',
    oxidationStates: '+6, +5, +4, +3',
    meltingPoint: '1449',
    boilingPoint: '2284',
    density: '13.69',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 96,
    symbol: 'Cm',
    nameKey: 'toolbox.life.element.cm.name',
    nameEn: 'Curium',
    atomicMass: '247.07035',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1944',
    electronConfiguration: '[Rn]7s2 5f7 6d1',
    electronegativity: '1.3',
    atomicRadius: '245',
    ionizationEnergy: '6.02',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1618',
    boilingPoint: '3400',
    density: '13.51',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 97,
    symbol: 'Bk',
    nameKey: 'toolbox.life.element.bk.name',
    nameEn: 'Berkelium',
    atomicMass: '247.07031',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1949',
    electronConfiguration: '[Rn]7s2 5f9',
    electronegativity: '1.3',
    atomicRadius: '244',
    ionizationEnergy: '6.23',
    electronAffinity: '',
    oxidationStates: '+4, +3',
    meltingPoint: '1323',
    boilingPoint: '',
    density: '14',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 98,
    symbol: 'Cf',
    nameKey: 'toolbox.life.element.cf.name',
    nameEn: 'Californium',
    atomicMass: '251.07959',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1950',
    electronConfiguration: '[Rn]7s2 5f10',
    electronegativity: '1.3',
    atomicRadius: '245',
    ionizationEnergy: '6.30',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1173',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 99,
    symbol: 'Es',
    nameKey: 'toolbox.life.element.es.name',
    nameEn: 'Einsteinium',
    atomicMass: '252.0830',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1952',
    electronConfiguration: '[Rn]7s2 5f11',
    electronegativity: '1.3',
    atomicRadius: '245',
    ionizationEnergy: '6.42',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1133',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 100,
    symbol: 'Fm',
    nameKey: 'toolbox.life.element.fm.name',
    nameEn: 'Fermium',
    atomicMass: '257.09511',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1952',
    electronConfiguration: '[Rn] 5f12 7s2',
    electronegativity: '1.3',
    atomicRadius: '',
    ionizationEnergy: '6.50',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1800',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 101,
    symbol: 'Md',
    nameKey: 'toolbox.life.element.md.name',
    nameEn: 'Mendelevium',
    atomicMass: '258.09843',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1955',
    electronConfiguration: '[Rn]7s2 5f13',
    electronegativity: '1.3',
    atomicRadius: '',
    ionizationEnergy: '6.58',
    electronAffinity: '',
    oxidationStates: '+3, +2',
    meltingPoint: '1100',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 102,
    symbol: 'No',
    nameKey: 'toolbox.life.element.no.name',
    nameEn: 'Nobelium',
    atomicMass: '259.10100',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1957',
    electronConfiguration: '[Rn]7s2 5f14',
    electronegativity: '1.3',
    atomicRadius: '',
    ionizationEnergy: '6.65',
    electronAffinity: '',
    oxidationStates: '+3, +2',
    meltingPoint: '1100',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 103,
    symbol: 'Lr',
    nameKey: 'toolbox.life.element.lr.name',
    nameEn: 'Lawrencium',
    atomicMass: '266.120',
    groupBlock: 'Actinide',
    groupBlockKey: 'toolbox.life.element.block.actinide',
    standardState: 'Solid',
    yearDiscovered: '1961',
    electronConfiguration: '[Rn]7s2 5f14 6d1',
    electronegativity: '1.3',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '+3',
    meltingPoint: '1900',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 104,
    symbol: 'Rf',
    nameKey: 'toolbox.life.element.rf.name',
    nameEn: 'Rutherfordium',
    atomicMass: '267.122',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1964',
    electronConfiguration: '[Rn]7s2 5f14 6d2',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '+4',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 4,
    displayRow: 7,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 105,
    symbol: 'Db',
    nameKey: 'toolbox.life.element.db.name',
    nameEn: 'Dubnium',
    atomicMass: '268.126',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1967',
    electronConfiguration: '[Rn]7s2 5f14 6d3',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '5, 4, 3',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 5,
    displayRow: 7,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 106,
    symbol: 'Sg',
    nameKey: 'toolbox.life.element.sg.name',
    nameEn: 'Seaborgium',
    atomicMass: '269.128',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1974',
    electronConfiguration: '[Rn]7s2 5f14 6d4',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '6, 5, 4, 3, 0',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 6,
    displayRow: 7,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 107,
    symbol: 'Bh',
    nameKey: 'toolbox.life.element.bh.name',
    nameEn: 'Bohrium',
    atomicMass: '270.133',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1976',
    electronConfiguration: '[Rn]7s2 5f14 6d5',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '7, 5, 4, 3',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 7,
    displayRow: 7,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 108,
    symbol: 'Hs',
    nameKey: 'toolbox.life.element.hs.name',
    nameEn: 'Hassium',
    atomicMass: '269.1336',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1984',
    electronConfiguration: '[Rn]7s2 5f14 6d6',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '8, 6, 5, 4, 3, 2',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 8,
    displayRow: 7,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 109,
    symbol: 'Mt',
    nameKey: 'toolbox.life.element.mt.name',
    nameEn: 'Meitnerium',
    atomicMass: '277.154',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Solid',
    yearDiscovered: '1982',
    electronConfiguration: '[Rn]7s2 5f14 6d7 (calculated)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '9, 8, 6, 4, 3, 1',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 9,
    displayRow: 7,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 110,
    symbol: 'Ds',
    nameKey: 'toolbox.life.element.ds.name',
    nameEn: 'Darmstadtium',
    atomicMass: '282.166',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1994',
    electronConfiguration: '[Rn]7s2 5f14 6d8 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '8, 6, 4, 2, 0',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 10,
    displayRow: 7,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 111,
    symbol: 'Rg',
    nameKey: 'toolbox.life.element.rg.name',
    nameEn: 'Roentgenium',
    atomicMass: '282.169',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1994',
    electronConfiguration: '[Rn]7s2 5f14 6d9 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '5, 3, 1, -1',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 11,
    displayRow: 7,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 112,
    symbol: 'Cn',
    nameKey: 'toolbox.life.element.cn.name',
    nameEn: 'Copernicium',
    atomicMass: '286.179',
    groupBlock: 'Transition metal',
    groupBlockKey: 'toolbox.life.element.block.transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1996',
    electronConfiguration: '[Rn]7s2 5f14 6d10 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '2, 1, 0',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 12,
    displayRow: 7,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 113,
    symbol: 'Nh',
    nameKey: 'toolbox.life.element.nh.name',
    nameEn: 'Nihonium',
    atomicMass: '286.182',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2004',
    electronConfiguration: '[Rn]5f14 6d10 7s2 7p1 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 13,
    displayRow: 7,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 114,
    symbol: 'Fl',
    nameKey: 'toolbox.life.element.fl.name',
    nameEn: 'Flerovium',
    atomicMass: '290.192',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1998',
    electronConfiguration: '[Rn]7s2 7p2 5f14 6d10 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '6, 4,2, 1, 0',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 14,
    displayRow: 7,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 115,
    symbol: 'Mc',
    nameKey: 'toolbox.life.element.mc.name',
    nameEn: 'Moscovium',
    atomicMass: '290.196',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2003',
    electronConfiguration: '[Rn]7s2 7p3 5f14 6d10 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '3, 1',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 15,
    displayRow: 7,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 116,
    symbol: 'Lv',
    nameKey: 'toolbox.life.element.lv.name',
    nameEn: 'Livermorium',
    atomicMass: '293.205',
    groupBlock: 'Post-transition metal',
    groupBlockKey: 'toolbox.life.element.block.post_transition_metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2000',
    electronConfiguration: '[Rn]7s2 7p4 5f14 6d10 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '+4, +2, -2',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 16,
    displayRow: 7,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 117,
    symbol: 'Ts',
    nameKey: 'toolbox.life.element.ts.name',
    nameEn: 'Tennessine',
    atomicMass: '294.211',
    groupBlock: 'Halogen',
    groupBlockKey: 'toolbox.life.element.block.halogen',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2010',
    electronConfiguration: '[Rn]7s2 7p5 5f14 6d10 (predicted)',
    electronegativity: '',
    atomicRadius: '',
    ionizationEnergy: '',
    electronAffinity: '',
    oxidationStates: '+5, +3, +1, -1',
    meltingPoint: '',
    boilingPoint: '',
    density: '',
    period: 7,
    group: 17,
    displayRow: 7,
    displayColumn: 17,
  ),
];
