part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _generalTimelineFacts02 = <_TimelineFact>[
  _TimelineFact(
    id: 'ptolemaic_kingdom',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2193.5,
    displayKey: 'toolbox.life.timeline.general.ptolemaic_kingdom.date',
    titleKey: 'toolbox.life.timeline.general.ptolemaic_kingdom.title',
    detailKey: 'toolbox.life.timeline.general.ptolemaic_kingdom.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ptolemaic%20Kingdom',
  ),
  _TimelineFact(
    id: 'teotihuacan_rise',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1851,
    displayKey: 'toolbox.life.timeline.general.teotihuacan_rise.date',
    titleKey: 'toolbox.life.timeline.general.teotihuacan_rise.title',
    detailKey: 'toolbox.life.timeline.general.teotihuacan_rise.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Teotihuacan',
  ),
  _TimelineFact(
    id: 'kingdom_of_aksum',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1506,
    displayKey: 'toolbox.life.timeline.general.kingdom_of_aksum.date',
    titleKey: 'toolbox.life.timeline.general.kingdom_of_aksum.title',
    detailKey: 'toolbox.life.timeline.general.kingdom_of_aksum.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Kingdom%20of%20Aksum',
  ),
  _TimelineFact(
    id: 'nazca_culture',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1576,
    displayKey: 'toolbox.life.timeline.general.nazca_culture.date',
    titleKey: 'toolbox.life.timeline.general.nazca_culture.title',
    detailKey: 'toolbox.life.timeline.general.nazca_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Nazca%20culture',
  ),
  _TimelineFact(
    id: 'moche_civilization',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1626,
    displayKey: 'toolbox.life.timeline.general.moche_civilization.date',
    titleKey: 'toolbox.life.timeline.general.moche_civilization.title',
    detailKey: 'toolbox.life.timeline.general.moche_civilization.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Moche%20culture',
  ),
  _TimelineFact(
    id: 'sasanian_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1588.5,
    displayKey: 'toolbox.life.timeline.general.sasanian_empire.date',
    titleKey: 'toolbox.life.timeline.general.sasanian_empire.title',
    detailKey: 'toolbox.life.timeline.general.sasanian_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Sasanian%20Empire',
  ),
  _TimelineFact(
    id: 'buddhism_spreads_east_asia',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1676,
    displayKey: 'toolbox.life.timeline.general.buddhism_spreads_east_asia.date',
    titleKey: 'toolbox.life.timeline.general.buddhism_spreads_east_asia.title',
    detailKey: 'toolbox.life.timeline.general.buddhism_spreads_east_asia.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Silk%20Road%20transmission%20of%20Buddhism',
  ),
  _TimelineFact(
    id: 'hagia_sophia_completed',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1489,
    displayKey: 'toolbox.life.timeline.general.hagia_sophia_completed.date',
    titleKey: 'toolbox.life.timeline.general.hagia_sophia_completed.title',
    detailKey: 'toolbox.life.timeline.general.hagia_sophia_completed.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hagia%20Sophia',
  ),
  _TimelineFact(
    id: 'srivijaya_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1012.5,
    displayKey: 'toolbox.life.timeline.general.srivijaya_empire.date',
    titleKey: 'toolbox.life.timeline.general.srivijaya_empire.title',
    detailKey: 'toolbox.life.timeline.general.srivijaya_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Srivijaya',
  ),
  _TimelineFact(
    id: 'tibetan_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1296,
    displayKey: 'toolbox.life.timeline.general.tibetan_empire.date',
    titleKey: 'toolbox.life.timeline.general.tibetan_empire.title',
    detailKey: 'toolbox.life.timeline.general.tibetan_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Tibetan%20Empire',
  ),
  _TimelineFact(
    id: 'house_of_wisdom',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 997,
    displayKey: 'toolbox.life.timeline.general.house_of_wisdom.date',
    titleKey: 'toolbox.life.timeline.general.house_of_wisdom.title',
    detailKey: 'toolbox.life.timeline.general.house_of_wisdom.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=House%20of%20Wisdom',
  ),
  _TimelineFact(
    id: 'ghana_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1056,
    displayKey: 'toolbox.life.timeline.general.ghana_empire.date',
    titleKey: 'toolbox.life.timeline.general.ghana_empire.title',
    detailKey: 'toolbox.life.timeline.general.ghana_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ghana%20Empire',
  ),
  _TimelineFact(
    id: 'chola_maritime_expansion',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 998.5,
    displayKey: 'toolbox.life.timeline.general.chola_maritime_expansion.date',
    titleKey: 'toolbox.life.timeline.general.chola_maritime_expansion.title',
    detailKey: 'toolbox.life.timeline.general.chola_maritime_expansion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chola%20dynasty',
  ),
  _TimelineFact(
    id: 'fatimid_cairo_founded',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1057,
    displayKey: 'toolbox.life.timeline.general.fatimid_cairo_founded.date',
    titleKey: 'toolbox.life.timeline.general.fatimid_cairo_founded.title',
    detailKey: 'toolbox.life.timeline.general.fatimid_cairo_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Cairo',
  ),
  _TimelineFact(
    id: 'university_of_bologna',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 938,
    displayKey: 'toolbox.life.timeline.general.university_of_bologna.date',
    titleKey: 'toolbox.life.timeline.general.university_of_bologna.title',
    detailKey: 'toolbox.life.timeline.general.university_of_bologna.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=University%20of%20Bologna',
  ),
  _TimelineFact(
    id: 'seljuk_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 910.5,
    displayKey: 'toolbox.life.timeline.general.seljuk_empire.date',
    titleKey: 'toolbox.life.timeline.general.seljuk_empire.title',
    detailKey: 'toolbox.life.timeline.general.seljuk_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Seljuk%20Empire',
  ),
  _TimelineFact(
    id: 'reconquista_toledo',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 941,
    displayKey: 'toolbox.life.timeline.general.reconquista_toledo.date',
    titleKey: 'toolbox.life.timeline.general.reconquista_toledo.title',
    detailKey: 'toolbox.life.timeline.general.reconquista_toledo.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=conquest%20of%20Toledo',
  ),
  _TimelineFact(
    id: 'cahokia_peak',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 826,
    displayKey: 'toolbox.life.timeline.general.cahokia_peak.date',
    titleKey: 'toolbox.life.timeline.general.cahokia_peak.title',
    detailKey: 'toolbox.life.timeline.general.cahokia_peak.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Cahokia',
  ),
  _TimelineFact(
    id: 'rapanui_settlement',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 826,
    displayKey: 'toolbox.life.timeline.general.rapanui_settlement.date',
    titleKey: 'toolbox.life.timeline.general.rapanui_settlement.title',
    detailKey: 'toolbox.life.timeline.general.rapanui_settlement.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=settlement%20of%20Easter%20Island',
  ),
  _TimelineFact(
    id: 'swahili_city_states',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 776,
    displayKey: 'toolbox.life.timeline.general.swahili_city_states.date',
    titleKey: 'toolbox.life.timeline.general.swahili_city_states.title',
    detailKey: 'toolbox.life.timeline.general.swahili_city_states.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Swahili%20city-states',
  ),
  _TimelineFact(
    id: 'mali_empire_founded',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 791,
    displayKey: 'toolbox.life.timeline.general.mali_empire_founded.date',
    titleKey: 'toolbox.life.timeline.general.mali_empire_founded.title',
    detailKey: 'toolbox.life.timeline.general.mali_empire_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Mali%20Empire',
  ),
  _TimelineFact(
    id: 'kingdom_of_benin',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 487.5,
    displayKey: 'toolbox.life.timeline.general.kingdom_of_benin.date',
    titleKey: 'toolbox.life.timeline.general.kingdom_of_benin.title',
    detailKey: 'toolbox.life.timeline.general.kingdom_of_benin.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Kingdom%20of%20Benin',
  ),
  _TimelineFact(
    id: 'solomonic_dynasty',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 404,
    displayKey: 'toolbox.life.timeline.general.solomonic_dynasty.date',
    titleKey: 'toolbox.life.timeline.general.solomonic_dynasty.title',
    detailKey: 'toolbox.life.timeline.general.solomonic_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Solomonic%20dynasty',
  ),
  _TimelineFact(
    id: 'majapahit_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 616,
    displayKey: 'toolbox.life.timeline.general.majapahit_empire.date',
    titleKey: 'toolbox.life.timeline.general.majapahit_empire.title',
    detailKey: 'toolbox.life.timeline.general.majapahit_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Majapahit',
  ),
  _TimelineFact(
    id: 'vijayanagara_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 535,
    displayKey: 'toolbox.life.timeline.general.vijayanagara_empire.date',
    titleKey: 'toolbox.life.timeline.general.vijayanagara_empire.title',
    detailKey: 'toolbox.life.timeline.general.vijayanagara_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Vijayanagara%20Empire',
  ),
  _TimelineFact(
    id: 'tenochtitlan_founded',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 701,
    displayKey: 'toolbox.life.timeline.general.tenochtitlan_founded.date',
    titleKey: 'toolbox.life.timeline.general.tenochtitlan_founded.title',
    detailKey: 'toolbox.life.timeline.general.tenochtitlan_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Tenochtitlan',
  ),
  _TimelineFact(
    id: 'inca_empire_expansion',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 540.5,
    displayKey: 'toolbox.life.timeline.general.inca_empire_expansion.date',
    titleKey: 'toolbox.life.timeline.general.inca_empire_expansion.title',
    detailKey: 'toolbox.life.timeline.general.inca_empire_expansion.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Inca%20Empire',
  ),
  _TimelineFact(
    id: 'polynesian_new_zealand_settlement',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 751,
    displayKey: 'toolbox.life.timeline.general.polynesian_new_zealand_settlement.date',
    titleKey: 'toolbox.life.timeline.general.polynesian_new_zealand_settlement.title',
    detailKey: 'toolbox.life.timeline.general.polynesian_new_zealand_settlement.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Maori%20settlement%20of%20New%20Zealand',
  ),
  _TimelineFact(
    id: 'timurid_renaissance',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 587.5,
    displayKey: 'toolbox.life.timeline.general.timurid_renaissance.date',
    titleKey: 'toolbox.life.timeline.general.timurid_renaissance.title',
    detailKey: 'toolbox.life.timeline.general.timurid_renaissance.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Timurid%20Renaissance',
  ),
  _TimelineFact(
    id: 'joseon_dynasty',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 381.5,
    displayKey: 'toolbox.life.timeline.general.joseon_dynasty.date',
    titleKey: 'toolbox.life.timeline.general.joseon_dynasty.title',
    detailKey: 'toolbox.life.timeline.general.joseon_dynasty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Joseon',
  ),
  _TimelineFact(
    id: 'songhai_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 498.5,
    displayKey: 'toolbox.life.timeline.general.songhai_empire.date',
    titleKey: 'toolbox.life.timeline.general.songhai_empire.title',
    detailKey: 'toolbox.life.timeline.general.songhai_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Songhai%20Empire',
  ),
  _TimelineFact(
    id: 'safavid_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 407.5,
    displayKey: 'toolbox.life.timeline.general.safavid_empire.date',
    titleKey: 'toolbox.life.timeline.general.safavid_empire.title',
    detailKey: 'toolbox.life.timeline.general.safavid_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Safavid%20Iran',
  ),
  _TimelineFact(
    id: 'sikhism_founded',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 526,
    displayKey: 'toolbox.life.timeline.general.sikhism_founded.date',
    titleKey: 'toolbox.life.timeline.general.sikhism_founded.title',
    detailKey: 'toolbox.life.timeline.general.sikhism_founded.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Sikhism',
  ),
  _TimelineFact(
    id: 'columbian_exchange',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 480,
    displayKey: 'toolbox.life.timeline.general.columbian_exchange.date',
    titleKey: 'toolbox.life.timeline.general.columbian_exchange.title',
    detailKey: 'toolbox.life.timeline.general.columbian_exchange.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Columbian%20exchange',
  ),
  _TimelineFact(
    id: 'manila_galleon',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 336,
    displayKey: 'toolbox.life.timeline.general.manila_galleon.date',
    titleKey: 'toolbox.life.timeline.general.manila_galleon.title',
    detailKey: 'toolbox.life.timeline.general.manila_galleon.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Manila%20galleon',
  ),
  _TimelineFact(
    id: 'transatlantic_slave_trade_expands',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 342,
    displayKey: 'toolbox.life.timeline.general.transatlantic_slave_trade_expands.date',
    titleKey: 'toolbox.life.timeline.general.transatlantic_slave_trade_expands.title',
    detailKey: 'toolbox.life.timeline.general.transatlantic_slave_trade_expands.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Atlantic%20slave%20trade',
  ),
  _TimelineFact(
    id: 'thirty_years_war',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 393,
    displayKey: 'toolbox.life.timeline.general.thirty_years_war.date',
    titleKey: 'toolbox.life.timeline.general.thirty_years_war.title',
    detailKey: 'toolbox.life.timeline.general.thirty_years_war.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Thirty%20Years\'%20War',
  ),
  _TimelineFact(
    id: 'babylonian_mathematics',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 3726,
    displayKey: 'toolbox.life.timeline.general.babylonian_mathematics.date',
    titleKey: 'toolbox.life.timeline.general.babylonian_mathematics.title',
    detailKey: 'toolbox.life.timeline.general.babylonian_mathematics.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Babylonian%20mathematics',
  ),
  _TimelineFact(
    id: 'ebers_papyrus',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 3576,
    displayKey: 'toolbox.life.timeline.general.ebers_papyrus.date',
    titleKey: 'toolbox.life.timeline.general.ebers_papyrus.title',
    detailKey: 'toolbox.life.timeline.general.ebers_papyrus.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ebers%20Papyrus',
  ),
  _TimelineFact(
    id: 'thales_natural_philosophy',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2599,
    displayKey: 'toolbox.life.timeline.general.thales_natural_philosophy.date',
    titleKey: 'toolbox.life.timeline.general.thales_natural_philosophy.title',
    detailKey: 'toolbox.life.timeline.general.thales_natural_philosophy.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Thales%20of%20Miletus',
  ),
  _TimelineFact(
    id: 'pythagorean_school',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2538.5,
    displayKey: 'toolbox.life.timeline.general.pythagorean_school.date',
    titleKey: 'toolbox.life.timeline.general.pythagorean_school.title',
    detailKey: 'toolbox.life.timeline.general.pythagorean_school.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Pythagoreanism',
  ),
  _TimelineFact(
    id: 'hippocratic_corpus',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2426,
    displayKey: 'toolbox.life.timeline.general.hippocratic_corpus.date',
    titleKey: 'toolbox.life.timeline.general.hippocratic_corpus.title',
    detailKey: 'toolbox.life.timeline.general.hippocratic_corpus.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hippocratic%20Corpus',
  ),
  _TimelineFact(
    id: 'democritus_atomism',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2426,
    displayKey: 'toolbox.life.timeline.general.democritus_atomism.date',
    titleKey: 'toolbox.life.timeline.general.democritus_atomism.title',
    detailKey: 'toolbox.life.timeline.general.democritus_atomism.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Democritus',
  ),
  _TimelineFact(
    id: 'aristotle_lyceum',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2361,
    displayKey: 'toolbox.life.timeline.general.aristotle_lyceum.date',
    titleKey: 'toolbox.life.timeline.general.aristotle_lyceum.title',
    detailKey: 'toolbox.life.timeline.general.aristotle_lyceum.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Lyceum%20Aristotle',
  ),
  _TimelineFact(
    id: 'euclid_elements',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2326,
    displayKey: 'toolbox.life.timeline.general.euclid_elements.date',
    titleKey: 'toolbox.life.timeline.general.euclid_elements.title',
    detailKey: 'toolbox.life.timeline.general.euclid_elements.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Euclid\'s%20Elements',
  ),
  _TimelineFact(
    id: 'archimedes_science',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2275.5,
    displayKey: 'toolbox.life.timeline.general.archimedes_science.date',
    titleKey: 'toolbox.life.timeline.general.archimedes_science.title',
    detailKey: 'toolbox.life.timeline.general.archimedes_science.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Archimedes',
  ),
  _TimelineFact(
    id: 'eratosthenes_earth_measurement',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2266,
    displayKey: 'toolbox.life.timeline.general.eratosthenes_earth_measurement.date',
    titleKey: 'toolbox.life.timeline.general.eratosthenes_earth_measurement.title',
    detailKey: 'toolbox.life.timeline.general.eratosthenes_earth_measurement.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Eratosthenes%20measurement%20of%20Earth',
  ),
  _TimelineFact(
    id: 'antikythera_mechanism',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 2151,
    displayKey: 'toolbox.life.timeline.general.antikythera_mechanism.date',
    titleKey: 'toolbox.life.timeline.general.antikythera_mechanism.title',
    detailKey: 'toolbox.life.timeline.general.antikythera_mechanism.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Antikythera%20mechanism',
  ),
  _TimelineFact(
    id: 'ptolemy_almagest',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1876,
    displayKey: 'toolbox.life.timeline.general.ptolemy_almagest.date',
    titleKey: 'toolbox.life.timeline.general.ptolemy_almagest.title',
    detailKey: 'toolbox.life.timeline.general.ptolemy_almagest.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Almagest',
  ),
  _TimelineFact(
    id: 'zhang_heng_seismoscope',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1894,
    displayKey: 'toolbox.life.timeline.general.zhang_heng_seismoscope.date',
    titleKey: 'toolbox.life.timeline.general.zhang_heng_seismoscope.title',
    detailKey: 'toolbox.life.timeline.general.zhang_heng_seismoscope.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zhang%20Heng%20seismoscope',
  ),
  _TimelineFact(
    id: 'indian_zero_decimal',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1398,
    displayKey: 'toolbox.life.timeline.general.indian_zero_decimal.date',
    titleKey: 'toolbox.life.timeline.general.indian_zero_decimal.title',
    detailKey: 'toolbox.life.timeline.general.indian_zero_decimal.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=zero%20in%20Indian%20mathematics',
  ),
  _TimelineFact(
    id: 'aryabhatiya',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1527,
    displayKey: 'toolbox.life.timeline.general.aryabhatiya.date',
    titleKey: 'toolbox.life.timeline.general.aryabhatiya.title',
    detailKey: 'toolbox.life.timeline.general.aryabhatiya.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Aryabhatiya',
  ),
  _TimelineFact(
    id: 'al_khwarizmi_algebra',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1206,
    displayKey: 'toolbox.life.timeline.general.al_khwarizmi_algebra.date',
    titleKey: 'toolbox.life.timeline.general.al_khwarizmi_algebra.title',
    detailKey: 'toolbox.life.timeline.general.al_khwarizmi_algebra.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=The%20Compendious%20Book%20on%20Calculation%20by%20Completion%20and%20Balancing',
  ),
  _TimelineFact(
    id: 'ibn_al_haytham_optics',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1008,
    displayKey: 'toolbox.life.timeline.general.ibn_al_haytham_optics.date',
    titleKey: 'toolbox.life.timeline.general.ibn_al_haytham_optics.title',
    detailKey: 'toolbox.life.timeline.general.ibn_al_haytham_optics.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Book%20of%20Optics',
  ),
  _TimelineFact(
    id: 'avicenna_canon_medicine',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 1001,
    displayKey: 'toolbox.life.timeline.general.avicenna_canon_medicine.date',
    titleKey: 'toolbox.life.timeline.general.avicenna_canon_medicine.title',
    detailKey: 'toolbox.life.timeline.general.avicenna_canon_medicine.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=The%20Canon%20of%20Medicine',
  ),
  _TimelineFact(
    id: 'mariners_compass',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 876,
    displayKey: 'toolbox.life.timeline.general.mariners_compass.date',
    titleKey: 'toolbox.life.timeline.general.mariners_compass.title',
    detailKey: 'toolbox.life.timeline.general.mariners_compass.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=mariner\'s%20compass',
  ),
  _TimelineFact(
    id: 'gunpowder_formula',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 982,
    displayKey: 'toolbox.life.timeline.general.gunpowder_formula.date',
    titleKey: 'toolbox.life.timeline.general.gunpowder_formula.title',
    detailKey: 'toolbox.life.timeline.general.gunpowder_formula.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Wujing%20Zongyao',
  ),
  _TimelineFact(
    id: 'mechanical_clock',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 743,
    displayKey: 'toolbox.life.timeline.general.mechanical_clock.date',
    titleKey: 'toolbox.life.timeline.general.mechanical_clock.title',
    detailKey: 'toolbox.life.timeline.general.mechanical_clock.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=mechanical%20clock',
  ),
  _TimelineFact(
    id: 'bi_sheng_movable_type',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 986,
    displayKey: 'toolbox.life.timeline.general.bi_sheng_movable_type.date',
    titleKey: 'toolbox.life.timeline.general.bi_sheng_movable_type.title',
    detailKey: 'toolbox.life.timeline.general.bi_sheng_movable_type.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Bi%20Sheng',
  ),
  _TimelineFact(
    id: 'fibonacci_liber_abaci',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 824,
    displayKey: 'toolbox.life.timeline.general.fibonacci_liber_abaci.date',
    titleKey: 'toolbox.life.timeline.general.fibonacci_liber_abaci.title',
    detailKey: 'toolbox.life.timeline.general.fibonacci_liber_abaci.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Liber%20Abaci',
  ),
  _TimelineFact(
    id: 'vesalius_anatomy',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 483,
    displayKey: 'toolbox.life.timeline.general.vesalius_anatomy.date',
    titleKey: 'toolbox.life.timeline.general.vesalius_anatomy.title',
    detailKey: 'toolbox.life.timeline.general.vesalius_anatomy.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=De%20humani%20corporis%20fabrica',
  ),
  _TimelineFact(
    id: 'kepler_planetary_laws',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 412,
    displayKey: 'toolbox.life.timeline.general.kepler_planetary_laws.date',
    titleKey: 'toolbox.life.timeline.general.kepler_planetary_laws.title',
    detailKey: 'toolbox.life.timeline.general.kepler_planetary_laws.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Kepler\'s%20laws%20of%20planetary%20motion',
  ),
  _TimelineFact(
    id: 'harvey_blood_circulation',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 398,
    displayKey: 'toolbox.life.timeline.general.harvey_blood_circulation.date',
    titleKey: 'toolbox.life.timeline.general.harvey_blood_circulation.title',
    detailKey: 'toolbox.life.timeline.general.harvey_blood_circulation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=William%20Harvey%20blood%20circulation',
  ),
  _TimelineFact(
    id: 'torricelli_barometer',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 383,
    displayKey: 'toolbox.life.timeline.general.torricelli_barometer.date',
    titleKey: 'toolbox.life.timeline.general.torricelli_barometer.title',
    detailKey: 'toolbox.life.timeline.general.torricelli_barometer.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=barometer',
  ),
  _TimelineFact(
    id: 'boyle_law',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 364,
    displayKey: 'toolbox.life.timeline.general.boyle_law.date',
    titleKey: 'toolbox.life.timeline.general.boyle_law.title',
    detailKey: 'toolbox.life.timeline.general.boyle_law.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Boyle\'s%20law',
  ),
  _TimelineFact(
    id: 'hooke_cells',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 361,
    displayKey: 'toolbox.life.timeline.general.hooke_cells.date',
    titleKey: 'toolbox.life.timeline.general.hooke_cells.title',
    detailKey: 'toolbox.life.timeline.general.hooke_cells.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Micrographia',
  ),
  _TimelineFact(
    id: 'leeuwenhoek_microorganisms',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 350,
    displayKey: 'toolbox.life.timeline.general.leeuwenhoek_microorganisms.date',
    titleKey: 'toolbox.life.timeline.general.leeuwenhoek_microorganisms.title',
    detailKey: 'toolbox.life.timeline.general.leeuwenhoek_microorganisms.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Antonie%20van%20Leeuwenhoek%20microorganisms',
  ),
  _TimelineFact(
    id: 'halley_comet_prediction',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 321,
    displayKey: 'toolbox.life.timeline.general.halley_comet_prediction.date',
    titleKey: 'toolbox.life.timeline.general.halley_comet_prediction.title',
    detailKey: 'toolbox.life.timeline.general.halley_comet_prediction.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Halley\'s%20Comet%20prediction',
  ),
  _TimelineFact(
    id: 'linnaeus_taxonomy',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 291,
    displayKey: 'toolbox.life.timeline.general.linnaeus_taxonomy.date',
    titleKey: 'toolbox.life.timeline.general.linnaeus_taxonomy.title',
    detailKey: 'toolbox.life.timeline.general.linnaeus_taxonomy.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Systema%20Naturae',
  ),
  _TimelineFact(
    id: 'lavoisier_chemical_revolution',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 237,
    displayKey: 'toolbox.life.timeline.general.lavoisier_chemical_revolution.date',
    titleKey: 'toolbox.life.timeline.general.lavoisier_chemical_revolution.title',
    detailKey: 'toolbox.life.timeline.general.lavoisier_chemical_revolution.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Traite%20Elementaire%20de%20Chimie',
  ),
  _TimelineFact(
    id: 'jenner_smallpox_vaccine',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 230,
    displayKey: 'toolbox.life.timeline.general.jenner_smallpox_vaccine.date',
    titleKey: 'toolbox.life.timeline.general.jenner_smallpox_vaccine.title',
    detailKey: 'toolbox.life.timeline.general.jenner_smallpox_vaccine.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Edward%20Jenner%20smallpox%20vaccine',
  ),
  _TimelineFact(
    id: 'voltaic_pile',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 226,
    displayKey: 'toolbox.life.timeline.general.voltaic_pile.date',
    titleKey: 'toolbox.life.timeline.general.voltaic_pile.title',
    detailKey: 'toolbox.life.timeline.general.voltaic_pile.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=voltaic%20pile',
  ),
  _TimelineFact(
    id: 'oersted_electromagnetism',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 206,
    displayKey: 'toolbox.life.timeline.general.oersted_electromagnetism.date',
    titleKey: 'toolbox.life.timeline.general.oersted_electromagnetism.title',
    detailKey: 'toolbox.life.timeline.general.oersted_electromagnetism.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Oersted%20electromagnetism',
  ),
  _TimelineFact(
    id: 'faraday_induction',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 195,
    displayKey: 'toolbox.life.timeline.general.faraday_induction.date',
    titleKey: 'toolbox.life.timeline.general.faraday_induction.title',
    detailKey: 'toolbox.life.timeline.general.faraday_induction.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Faraday\'s%20law%20of%20induction',
  ),
  _TimelineFact(
    id: 'daguerreotype',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 187,
    displayKey: 'toolbox.life.timeline.general.daguerreotype.date',
    titleKey: 'toolbox.life.timeline.general.daguerreotype.title',
    detailKey: 'toolbox.life.timeline.general.daguerreotype.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=daguerreotype',
  ),
  _TimelineFact(
    id: 'ether_anesthesia',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 180,
    displayKey: 'toolbox.life.timeline.general.ether_anesthesia.date',
    titleKey: 'toolbox.life.timeline.general.ether_anesthesia.title',
    detailKey: 'toolbox.life.timeline.general.ether_anesthesia.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=ether%20anesthesia',
  ),
];
