part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _legacyTimelineFacts03 = <_TimelineFact>[
  _TimelineFact(
    id: 'heian_period',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1232,
    displayKey: 'inline.plan295.life.794_ce.ea9c5495f60d',
    titleKey: 'inline.plan295.life.heian_period_begins.2d2576e3c1eb',
    detailKey: 'inline.plan295.life.after_the_capital_moved_to_heian_kyo.6a8bbf43089b',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Heian-period',
  ),
  _TimelineFact(
    id: 'classic_maya',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1776,
    displayKey: 'inline.plan295.life.from_c_250_ce.309462126556',
    titleKey: 'inline.plan295.life.classic_maya_cities_develop.cf7b79c2838e',
    detailKey: 'inline.plan295.life.maya_lowland_city_states_developed_i.a6711194b762',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Maya-people',
  ),
  _TimelineFact(
    id: 'viking_expansion',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1233,
    displayKey: 'inline.plan295.life.from_c_793_ce.dcb1db887d80',
    titleKey: 'inline.plan295.life.viking_expansion_begins.174d8fb47001',
    detailKey: 'inline.plan295.life.scandinavian_seafarers_traded_settle.40b58febb0cb',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Viking-people',
  ),
  _TimelineFact(
    id: 'angkor_rise',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1224,
    displayKey: 'inline.plan295.life.802_ce.eed78f6882dc',
    titleKey: 'inline.plan295.life.angkorian_kingship_rises.617c0a7a2ce5',
    detailKey: 'inline.plan295.life.angkorian_centers_developed_through.bd9cef6c5b51',
    sourceNameKey: 'toolbox.life.timeline.source.unesco',
    sourceUrl: 'https://whc.unesco.org/en/list/668/',
  ),
  _TimelineFact(
    id: 'treaty_of_verdun',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 1183,
    displayKey: 'inline.plan295.life.843_ce.a26ed15176a6',
    titleKey: 'inline.plan295.life.treaty_of_verdun.7c33dc99fc55',
    detailKey: 'inline.plan295.life.the_carolingian_empire_was_divided_s.20d76c39a8b3',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Treaty-of-Verdun',
  ),
  _TimelineFact(
    id: 'east_west_schism',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 972,
    displayKey: 'inline.plan295.life.1054_ce.1c4b7fb25add',
    titleKey: 'inline.plan295.life.east_west_schism.d86348eab6dd',
    detailKey: 'inline.plan295.life.the_split_between_roman_catholic_and.3c0222e4a168',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/East-West-Schism-1054',
  ),
  _TimelineFact(
    id: 'norman_conquest',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 960,
    displayKey: 'inline.plan295.life.1066_ce.03ff911e7c10',
    titleKey: 'inline.plan295.life.norman_conquest_of_england.056399910375',
    detailKey: 'inline.plan295.life.the_norman_conquest_reshaped_english.9cb7d6fd2333',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Norman-Conquest',
  ),
  _TimelineFact(
    id: 'great_zimbabwe',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 926,
    displayKey: 'inline.plan295.life.from_c_1100_ce.baf3049b97ec',
    titleKey: 'inline.plan295.life.great_zimbabwe_rises.2913cbca5d84',
    detailKey: 'inline.plan295.life.stone_enclosures_and_trade_networks.8de15dfaa055',
    sourceNameKey: 'toolbox.life.timeline.source.unesco',
    sourceUrl: 'https://whc.unesco.org/en/list/364/',
  ),
  _TimelineFact(
    id: 'kamakura_shogunate',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 841,
    displayKey: 'inline.plan295.life.1185_ce.a1f16099b064',
    titleKey: 'inline.plan295.life.kamakura_shogunate_begins.e5352c135eff',
    detailKey: 'inline.plan295.life.warrior_government_became_institutio.cff9eb296b9e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Kamakura-period',
  ),
  _TimelineFact(
    id: 'magna_carta',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 811,
    displayKey: 'inline.plan295.life.1215_ce.80caee8601e4',
    titleKey: 'inline.plan295.life.magna_carta_sealed.3c18bb573b86',
    detailKey: 'inline.plan295.life.magna_carta_constrained_royal_power.1a16daa62975',
    sourceNameKey: 'toolbox.life.timeline.source.archives',
    sourceUrl: 'https://www.nationalarchives.gov.uk/education/resources/magna-carta/',
  ),
  _TimelineFact(
    id: 'baghdad_1258',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 768,
    displayKey: 'inline.plan295.life.1258_ce.50d1db2c969b',
    titleKey: 'inline.plan295.life.fall_of_baghdad.2d62bad1f920',
    detailKey: 'inline.plan295.life.mongol_forces_captured_baghdad_endin.83e5a7fa2d73',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Siege-of-Baghdad-1258',
  ),
  _TimelineFact(
    id: 'yuan_dynasty',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 755,
    displayKey: 'inline.plan295.life.1271_ce.87434fddb572',
    titleKey: 'inline.plan295.life.yuan_dynasty_founded.0c2675d2514b',
    detailKey: 'inline.plan295.life.kublai_khan_founded_the_yuan_transfo.471237044a9d',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Yuan-dynasty',
  ),
  _TimelineFact(
    id: 'ottoman_rise',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 727,
    displayKey: 'inline.plan295.life.c_1299_ce.f3fd42a1192e',
    titleKey: 'inline.plan295.life.ottoman_state_rises.b589faf275e9',
    detailKey: 'inline.plan295.life.a_frontier_polity_in_anatolia_gradua.1fd8339acdc2',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Ottoman-Empire',
  ),
  _TimelineFact(
    id: 'hundred_years_war',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 689,
    displayKey: 'inline.plan295.life.1337_1453_ce.faebc96c052f',
    titleKey: 'inline.plan295.life.hundred_years_war.e64069e13204',
    detailKey: 'inline.plan295.life.the_long_anglo_french_war_transforme.3e1a0d1b414b',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Hundred-Years-War',
  ),
  _TimelineFact(
    id: 'renaissance',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 626,
    displayKey: 'inline.plan295.life.from_c_1400_ce.31b199876bbb',
    titleKey: 'inline.plan295.life.european_renaissance_expands.a355651c97a6',
    detailKey: 'inline.plan295.life.humanism_classical_texts_patronage_a.111a5f97600c',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Renaissance',
  ),
  _TimelineFact(
    id: 'treaty_tordesillas',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 532,
    displayKey: 'inline.plan295.life.1494_ce.75ce5b514b0d',
    titleKey: 'inline.plan295.life.treaty_of_tordesillas.5ae598b4329b',
    detailKey: 'inline.plan295.life.spain_and_portugal_divided_overseas.03a3a74ccd59',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Treaty-of-Tordesillas',
  ),
  _TimelineFact(
    id: 'mughal_empire',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 500,
    displayKey: 'inline.plan295.life.1526_ce.a4a1a276b6af',
    titleKey: 'inline.plan295.life.mughal_empire_begins.9aa6a7a2f9de',
    detailKey: 'inline.plan295.life.babur_founded_the_mughal_empire_in_n.506c85f67844',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/Mughal-dynasty',
  ),
  _TimelineFact(
    id: 'east_india_company',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 426,
    displayKey: 'inline.plan295.life.1600_ce.3d5741445b62',
    titleKey: 'inline.plan295.life.english_east_india_company_founded.200838cb757f',
    detailKey: 'inline.plan295.life.a_chartered_trading_company_became_a.10af892fdaf9',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/East-India-Company',
  ),
  _TimelineFact(
    id: 'tokugawa_shogunate',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 423,
    displayKey: 'inline.plan295.life.1603_ce.4b24cc0c1341',
    titleKey: 'inline.plan295.life.tokugawa_shogunate_begins.a91f3f8d1555',
    detailKey: 'inline.plan295.life.the_edo_period_began_combining_long.57890236162c',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Tokugawa-period',
  ),
  _TimelineFact(
    id: 'english_civil_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 384,
    displayKey: 'inline.plan295.life.1642_1651_ce.a4d466f1192c',
    titleKey: 'inline.plan295.life.english_civil_wars.2a1d5bf6a935',
    detailKey: 'inline.plan295.life.conflict_among_crown_parliament_reli.db553103e743',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/English-Civil-Wars',
  ),
  _TimelineFact(
    id: 'glorious_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 338,
    displayKey: 'inline.plan295.life.1688_ce.57f9a07e0bc3',
    titleKey: 'inline.plan295.life.glorious_revolution.d943517d21ba',
    detailKey: 'inline.plan295.life.relations_between_crown_and_parliame.ba00afe1580f',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Glorious-Revolution',
  ),
  _TimelineFact(
    id: 'seven_years_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 270,
    displayKey: 'inline.plan295.life.1756_1763_ce.b9a15b30a2d3',
    titleKey: 'inline.plan295.life.seven_years_war.8eaef219a735',
    detailKey: 'inline.plan295.life.connected_theaters_in_europe_north_a.e1f9bef971b1',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Seven-Years-War',
  ),
  _TimelineFact(
    id: 'american_declaration',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 250,
    displayKey: 'inline.plan295.life.1776_ce.53447fc50c04',
    titleKey: 'inline.plan295.life.u_s_declaration_of_independence.09a90aa5770e',
    detailKey: 'inline.plan295.life.the_thirteen_colonies_declared_separ.f9e05f733d1b',
    sourceNameKey: 'toolbox.life.timeline.source.archives',
    sourceUrl: 'https://www.archives.gov/founding-docs/declaration',
  ),
  _TimelineFact(
    id: 'french_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 237,
    displayKey: 'inline.plan295.life.1789_ce.bcecaa3dacc9',
    titleKey: 'inline.plan295.life.french_revolution_begins.ada873c1e5d3',
    detailKey: 'inline.plan295.life.the_revolution_challenged_old_regime.4480285b2f80',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/French-Revolution',
  ),
  _TimelineFact(
    id: 'napoleonic_wars',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 223,
    displayKey: 'inline.plan295.life.1803_1815_ce.955c83abb254',
    titleKey: 'inline.plan295.life.napoleonic_wars.5ba4e30ab714',
    detailKey: 'inline.plan295.life.the_wars_reorganized_european_power.4543081a98f1',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Napoleonic-Wars',
  ),
  _TimelineFact(
    id: 'congress_vienna',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 211,
    displayKey: 'inline.plan295.life.1815_ce.89162f724416',
    titleKey: 'inline.plan295.life.congress_of_vienna.16f82c5971fb',
    detailKey: 'inline.plan295.life.european_powers_rebuilt_a_balance_of.4c5af6e15f83',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Congress-of-Vienna',
  ),
  _TimelineFact(
    id: 'revolutions_1848',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 178,
    displayKey: 'inline.plan295.life.1848_ce.3550fe2bfb89',
    titleKey: 'inline.plan295.life.revolutions_of_1848.6a07a8b166dd',
    detailKey: 'inline.plan295.life.nationalist_liberal_and_social_deman.7feb40f4372f',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Revolutions-of-1848',
  ),
  _TimelineFact(
    id: 'communist_manifesto',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 178,
    displayKey: 'inline.plan295.life.1848_ce.3550fe2bfb89',
    titleKey: 'inline.plan295.life.the_communist_manifesto_published.b2dc40d4ba1f',
    detailKey: 'inline.plan295.life.the_pamphlet_by_marx_and_engels_beca.4de1e7b37d5f',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/The-Communist-Manifesto',
  ),
  _TimelineFact(
    id: 'indian_rebellion',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 169,
    displayKey: 'inline.plan295.life.1857_ce.a1f076bec86f',
    titleKey: 'inline.plan295.life.indian_rebellion_of_1857.5bc73db973aa',
    detailKey: 'inline.plan295.life.after_the_anti_british_rebellion_com.4f144739688a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Indian-Mutiny',
  ),
  _TimelineFact(
    id: 'american_civil_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 165,
    displayKey: 'inline.plan295.life.1861_1865_ce.b06c732b217e',
    titleKey: 'inline.plan295.life.american_civil_war.796a4c36d7a3',
    detailKey: 'inline.plan295.life.the_war_over_union_slavery_and_natio.b04b2d2dd860',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/American-Civil-War',
  ),
  _TimelineFact(
    id: 'suez_canal',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 157,
    displayKey: 'inline.plan295.life.1869_ce.b016e2a075e3',
    titleKey: 'inline.plan295.life.suez_canal_opens.278bfee85de2',
    detailKey: 'inline.plan295.life.the_canal_linked_the_mediterranean_a.09b6bba11809',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Suez-Canal',
  ),
  _TimelineFact(
    id: 'german_unification',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 155,
    displayKey: 'inline.plan295.life.1871_ce.2f0bd6fd1558',
    titleKey: 'inline.plan295.life.german_unification.0735e285dca5',
    detailKey: 'inline.plan295.life.prussia_led_unification_changed_euro.976f64a65007',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/German-Empire',
  ),
  _TimelineFact(
    id: 'wright_brothers',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 123,
    displayKey: 'inline.plan295.life.1903_ce.c010c50f49ca',
    titleKey: 'inline.plan295.life.wright_brothers_powered_flight.0f90114b22da',
    detailKey: 'inline.plan295.life.controlled_powered_flight_opened_the.04f2b6a7fa3e',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/biography/Wright-brothers',
  ),
  _TimelineFact(
    id: 'world_war_i',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 112,
    displayKey: 'inline.plan295.life.1914_1918_ce.efbf08ca1a40',
    titleKey: 'inline.plan295.life.world_war_i.234ebf764dfc',
    detailKey: 'inline.plan295.life.industrial_total_war_destroyed_empir.2f7836308494',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/World-War-I',
  ),
  _TimelineFact(
    id: 'influenza_1918',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 108,
    displayKey: 'inline.plan295.life.1918_1919_ce.9e436e47680e',
    titleKey: 'inline.plan295.life.1918_influenza_pandemic.9dfd8bf12fcd',
    detailKey: 'inline.plan295.life.the_global_influenza_pandemic_caused.eb6f8059de7a',
    sourceNameKey: 'toolbox.life.timeline.source.cdc',
    sourceUrl: 'https://www.cdc.gov/flu/pandemic-resources/1918-pandemic-h1n1.html',
  ),
  _TimelineFact(
    id: 'treaty_versailles',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 107,
    displayKey: 'inline.plan295.life.1919_ce.7ee26cba0746',
    titleKey: 'inline.plan295.life.treaty_of_versailles.6ffaabbe3d27',
    detailKey: 'inline.plan295.life.the_postwar_treaty_redrew_europe_and.d047ab3d4674',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Treaty-of-Versailles-1919',
  ),
  _TimelineFact(
    id: 'great_depression',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 97,
    displayKey: 'inline.plan295.life.from_1929_ce.9fb7b5d1fae3',
    titleKey: 'inline.plan295.life.great_depression.2eb58226fb4f',
    detailKey: 'inline.plan295.life.the_global_economic_crisis_disrupted.a727cfe5e9c1',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Great-Depression',
  ),
  _TimelineFact(
    id: 'nazi_power',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 93,
    displayKey: 'inline.plan295.life.1933_ce.5dce133d3dc5',
    titleKey: 'inline.plan295.life.nazi_party_takes_power.5c009f87fed6',
    detailKey: 'inline.plan295.life.after_hitler_became_german_chancello.c90f59a02850',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/topic/Nazi-Party',
  ),
  _TimelineFact(
    id: 'world_war_ii',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 87,
    displayKey: 'inline.plan295.life.1939_1945_ce.d54a3adafdee',
    titleKey: 'inline.plan295.life.world_war_ii.17c7842046af',
    detailKey: 'inline.plan295.life.the_global_war_caused_immense_casual.8f3ea179d057',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/World-War-II',
  ),
  _TimelineFact(
    id: 'holocaust',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 85,
    displayKey: 'inline.plan295.life.1941_1945_ce.a6a5433bb5d7',
    titleKey: 'inline.plan295.life.the_holocaust.1e7cfb0ca4c6',
    detailKey: 'inline.plan295.life.nazi_germany_and_collaborators_syste.3401aa5ba3cb',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Holocaust',
  ),
  _TimelineFact(
    id: 'bretton_woods',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 82,
    displayKey: 'inline.plan295.life.1944_ce.8d8913c36c1e',
    titleKey: 'inline.plan295.life.bretton_woods_conference.f17df37a59a8',
    detailKey: 'inline.plan295.life.the_conference_laid_foundations_for.2bc6510c8cc2',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Bretton-Woods-Conference',
  ),
  _TimelineFact(
    id: 'atomic_bombings',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 81,
    displayKey: 'inline.plan295.life.1945_ce.80eac4768b6b',
    titleKey: 'inline.plan295.life.atomic_bombings_of_hiroshima_and_nag.9cb08d056287',
    detailKey: 'inline.plan295.life.nuclear_weapons_were_used_in_war_for.403c41f0a2ea',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/atomic-bombings-of-Hiroshima-and-Nagasaki',
  ),
  _TimelineFact(
    id: 'universal_declaration_human_rights',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 78,
    displayKey: 'inline.plan295.life.1948_ce.edb3fb0f6af8',
    titleKey: 'inline.plan295.life.universal_declaration_of_human_right.fbfdf078d611',
    detailKey: 'inline.plan295.life.the_un_general_assembly_adopted_the.8447613f9030',
    sourceNameKey: 'toolbox.life.timeline.source.un',
    sourceUrl: 'https://www.un.org/en/about-us/universal-declaration-of-human-rights',
  ),
  _TimelineFact(
    id: 'nato_founded',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 77,
    displayKey: 'inline.plan295.life.1949_ce.e2e1d51bd106',
    titleKey: 'inline.plan295.life.nato_founded.504d4127a0c6',
    detailKey: 'inline.plan295.life.nato_became_the_core_western_collect.088e2817c635',
    sourceNameKey: 'toolbox.life.timeline.source.nato',
    sourceUrl: 'https://www.nato.int/cps/en/natohq/topics_52044.htm',
  ),
  _TimelineFact(
    id: 'korean_war',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 76,
    displayKey: 'inline.plan295.life.1950_1953_ce.67bbcf517541',
    titleKey: 'inline.plan295.life.korean_war.7b90a9063ad5',
    detailKey: 'inline.plan295.life.the_war_became_a_major_cold_war_node.f2d81dee948a',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Korean-War',
  ),
  _TimelineFact(
    id: 'bandung_conference',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 71,
    displayKey: 'inline.plan295.life.1955_ce.5af41a16bba8',
    titleKey: 'inline.plan295.life.bandung_conference.7830281a5f26',
    detailKey: 'inline.plan295.life.the_asian_african_conference_advance.8e570940d933',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Bandung-Conference',
  ),
  _TimelineFact(
    id: 'sputnik',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 69,
    displayKey: 'inline.plan295.life.1957_ce.88f3349331f3',
    titleKey: 'inline.plan295.life.sputnik_1_launched.af418159fad8',
    detailKey: 'inline.plan295.life.the_first_artificial_satellite_opene.dcee53248062',
    sourceNameKey: 'toolbox.life.timeline.source.nasa',
    sourceUrl: 'https://www.nasa.gov/history/sputnik/',
  ),
  _TimelineFact(
    id: 'year_of_africa',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 66,
    displayKey: 'inline.plan295.life.1960_ce.d184aa6f1c7b',
    titleKey: 'inline.plan295.life.year_of_africa.c8279a34d164',
    detailKey: 'inline.plan295.life.many_african_states_became_independe.809172c5785a',
    sourceNameKey: 'toolbox.life.timeline.source.un',
    sourceUrl: 'https://www.un.org/dppa/decolonization/en/history',
  ),
  _TimelineFact(
    id: 'cuban_missile_crisis',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 64,
    displayKey: 'inline.plan295.life.1962_ce.4172ac59c652',
    titleKey: 'inline.plan295.life.cuban_missile_crisis.c323d1c5606a',
    detailKey: 'inline.plan295.life.u_s_soviet_nuclear_confrontation_pea.835e461c4f34',
    sourceNameKey: 'toolbox.life.timeline.source.archives',
    sourceUrl: 'https://history.state.gov/milestones/1961-1968/cuban-missile-crisis',
  ),
  _TimelineFact(
    id: 'arpanet',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 57,
    displayKey: 'inline.plan295.life.1969_ce.dfd9cfe6d128',
    titleKey: 'inline.plan295.life.arpanet_first_connection.00f8d1826b45',
    detailKey: 'inline.plan295.life.the_early_packet_switching_network_c.3b9fd6c2dfa7',
    sourceNameKey: 'toolbox.life.timeline.source.darpa',
    sourceUrl: 'https://www.darpa.mil/about-us/timeline/arpanet',
  ),
  _TimelineFact(
    id: 'un_resolution_2758',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 55,
    displayKey: 'inline.plan295.life.1971_ce.6ef40c26e13f',
    titleKey: 'inline.plan295.life.un_general_assembly_resolution_2758.232cbe2a7e64',
    detailKey: 'inline.plan295.life.the_resolution_changed_china_represe.3e5eb788ff46',
    sourceNameKey: 'toolbox.life.timeline.source.un',
    sourceUrl: 'https://digitallibrary.un.org/record/192054',
  ),
  _TimelineFact(
    id: 'oil_crisis_1973',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 53,
    displayKey: 'inline.plan295.life.1973_ce.668b039a8574',
    titleKey: 'inline.plan295.life.1973_oil_crisis.9a699daa7780',
    detailKey: 'inline.plan295.life.the_oil_shock_changed_energy_securit.a9c9dde7039d',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/oil-crisis',
  ),
  _TimelineFact(
    id: 'china_reform_opening',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 48,
    displayKey: 'inline.plan295.life.from_1978_ce.f63f85bb97c1',
    titleKey: 'inline.plan295.life.china_reform_and_opening_begins.90d356eec1d1',
    detailKey: 'inline.plan295.life.policy_shifted_toward_markets_openin.6d0844c88f06',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/place/China/Economic-policy-changes',
  ),
  _TimelineFact(
    id: 'iranian_revolution',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 47,
    displayKey: 'inline.plan295.life.1979_ce.7456b00b731f',
    titleKey: 'inline.plan295.life.iranian_revolution.f08b3806c5bd',
    detailKey: 'inline.plan295.life.the_pahlavi_monarchy_ended_and_the_i.1f58f08bc586',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Iranian-Revolution',
  ),
  _TimelineFact(
    id: 'chernobyl',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 40,
    displayKey: 'inline.plan295.life.1986_ce.256becfb3a68',
    titleKey: 'inline.plan295.life.chernobyl_nuclear_accident.b3b846169d90',
    detailKey: 'inline.plan295.life.the_accident_caused_long_term_enviro.91f868fcd6f0',
    sourceNameKey: 'toolbox.life.timeline.source.iaea',
    sourceUrl: 'https://www.iaea.org/topics/chornobyl',
  ),
  _TimelineFact(
    id: 'apartheid_ends',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 32,
    displayKey: 'inline.plan295.life.1994_ce.d240300ac720',
    titleKey: 'inline.plan295.life.apartheid_ends_in_south_africa.4378f585b2d0',
    detailKey: 'inline.plan295.life.south_africa_held_its_first_multirac.347d5e353c98',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/apartheid',
  ),
  _TimelineFact(
    id: 'september_11_attacks',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 25,
    displayKey: 'inline.plan295.life.2001_ce.1d003d792b02',
    titleKey: 'inline.plan295.life.september_11_attacks.9fb9d245b020',
    detailKey: 'inline.plan295.life.the_attacks_changed_u_s_and_global_s.a67f88c17c12',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/September-11-attacks',
  ),
  _TimelineFact(
    id: 'china_wto_accession',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 25,
    displayKey: 'inline.plan295.life.2001_ce.1d003d792b02',
    titleKey: 'inline.plan295.life.china_joins_the_wto.a5afddba5a1c',
    detailKey: 'inline.plan295.life.china_wto_accession_deepened_integra.bf78762e1860',
    sourceNameKey: 'toolbox.life.timeline.source.wto',
    sourceUrl: 'https://www.wto.org/english/thewto_e/countries_e/china_e.htm',
  ),
  _TimelineFact(
    id: 'global_financial_crisis_2008',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 18,
    displayKey: 'inline.plan295.life.2008_ce.7c257e27ee22',
    titleKey: 'inline.plan295.life.global_financial_crisis.e37e295ae45a',
    detailKey: 'inline.plan295.life.the_u_s_subprime_crisis_spread_globa.af5b3b7e2c69',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/financial-crisis-of-2007-2008',
  ),
  _TimelineFact(
    id: 'arab_spring',
    collection: 'general',
    category: 'modern',
    yearsBeforePresent: 16,
    displayKey: 'inline.plan295.life.2010_2011_ce.054ab58ed00b',
    titleKey: 'inline.plan295.life.arab_spring.4ea0ba78650b',
    detailKey: 'inline.plan295.life.protests_and_regime_crises_across_me.e1e8519b88a5',
    sourceNameKey: 'toolbox.life.timeline.source.britannica',
    sourceUrl: 'https://www.britannica.com/event/Arab-Spring',
  ),
  _TimelineFact(
    id: 'higgs_boson',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 14,
    displayKey: 'inline.plan295.life.2012_ce.70e3b2b7be75',
    titleKey: 'inline.plan295.life.higgs_boson_discovered.632ed2c6e4b2',
    detailKey: 'inline.plan295.life.cern_experiments_confirmed_the_higgs.ca573a946c9d',
    sourceNameKey: 'toolbox.life.timeline.source.cern',
    sourceUrl: 'https://home.cern/science/physics/higgs-boson',
  ),
  _TimelineFact(
    id: 'jwst_first_images',
    collection: 'general',
    category: 'science',
    yearsBeforePresent: 4,
    displayKey: 'inline.plan295.life.2022_ce.193dc8b9181f',
    titleKey: 'inline.plan295.life.jwst_first_images.3934c356e0ca',
    detailKey: 'inline.plan295.life.jwst_first_science_images_showed_dee.636e959acfc0',
    sourceNameKey: 'toolbox.life.timeline.source.nasa',
    sourceUrl: 'https://www.nasa.gov/image-article/nasas-webb-delivers-deepest-infrared-image-of-universe-yet/',
  ),
];
