part of '../toolbox_life_tools.dart';

const List<_TimelineFact> _generalTimelineFacts01 = <_TimelineFact>[
  _TimelineFact(
    id: 'cosmic_microwave_background',
    collection: 'general',
    category: 'cosmic',
    yearsBeforePresent: 13799620000,
    displayKey: 'toolbox.life.timeline.general.cosmic_microwave_background.date',
    titleKey: 'toolbox.life.timeline.general.cosmic_microwave_background.title',
    detailKey: 'toolbox.life.timeline.general.cosmic_microwave_background.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=cosmic%20microwave%20background',
  ),
  _TimelineFact(
    id: 'first_stars',
    collection: 'general',
    category: 'cosmic',
    yearsBeforePresent: 13600000000,
    displayKey: 'toolbox.life.timeline.general.first_stars.date',
    titleKey: 'toolbox.life.timeline.general.first_stars.title',
    detailKey: 'toolbox.life.timeline.general.first_stars.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=first%20stars',
  ),
  _TimelineFact(
    id: 'milky_way_formation',
    collection: 'general',
    category: 'cosmic',
    yearsBeforePresent: 13500000000,
    displayKey: 'toolbox.life.timeline.general.milky_way_formation.date',
    titleKey: 'toolbox.life.timeline.general.milky_way_formation.title',
    detailKey: 'toolbox.life.timeline.general.milky_way_formation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Milky%20Way%20formation',
  ),
  _TimelineFact(
    id: 'solar_system_formation',
    collection: 'general',
    category: 'cosmic',
    yearsBeforePresent: 4567000000,
    displayKey: 'toolbox.life.timeline.general.solar_system_formation.date',
    titleKey: 'toolbox.life.timeline.general.solar_system_formation.title',
    detailKey: 'toolbox.life.timeline.general.solar_system_formation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=formation%20and%20evolution%20of%20the%20Solar%20System',
  ),
  _TimelineFact(
    id: 'moon_formation',
    collection: 'general',
    category: 'cosmic',
    yearsBeforePresent: 4510000000,
    displayKey: 'toolbox.life.timeline.general.moon_formation.date',
    titleKey: 'toolbox.life.timeline.general.moon_formation.title',
    detailKey: 'toolbox.life.timeline.general.moon_formation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=origin%20of%20the%20Moon',
  ),
  _TimelineFact(
    id: 'oldest_known_zircons',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 4404000000,
    displayKey: 'toolbox.life.timeline.general.oldest_known_zircons.date',
    titleKey: 'toolbox.life.timeline.general.oldest_known_zircons.title',
    detailKey: 'toolbox.life.timeline.general.oldest_known_zircons.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Jack%20Hills%20zircon',
  ),
  _TimelineFact(
    id: 'early_earth_oceans',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 4400000000,
    displayKey: 'toolbox.life.timeline.general.early_earth_oceans.date',
    titleKey: 'toolbox.life.timeline.general.early_earth_oceans.title',
    detailKey: 'toolbox.life.timeline.general.early_earth_oceans.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=origin%20of%20water%20on%20Earth',
  ),
  _TimelineFact(
    id: 'oxygenic_photosynthesis',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 2700000000,
    displayKey: 'toolbox.life.timeline.general.oxygenic_photosynthesis.date',
    titleKey: 'toolbox.life.timeline.general.oxygenic_photosynthesis.title',
    detailKey: 'toolbox.life.timeline.general.oxygenic_photosynthesis.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=oxygenic%20photosynthesis',
  ),
  _TimelineFact(
    id: 'huronian_glaciation',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 2400000000,
    displayKey: 'toolbox.life.timeline.general.huronian_glaciation.date',
    titleKey: 'toolbox.life.timeline.general.huronian_glaciation.title',
    detailKey: 'toolbox.life.timeline.general.huronian_glaciation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Huronian%20glaciation',
  ),
  _TimelineFact(
    id: 'first_multicellular_life',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 1600000000,
    displayKey: 'toolbox.life.timeline.general.first_multicellular_life.date',
    titleKey: 'toolbox.life.timeline.general.first_multicellular_life.title',
    detailKey: 'toolbox.life.timeline.general.first_multicellular_life.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=multicellular%20organism',
  ),
  _TimelineFact(
    id: 'cryogenian_snowball_earth',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 720000000,
    displayKey: 'toolbox.life.timeline.general.cryogenian_snowball_earth.date',
    titleKey: 'toolbox.life.timeline.general.cryogenian_snowball_earth.title',
    detailKey: 'toolbox.life.timeline.general.cryogenian_snowball_earth.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Snowball%20Earth',
  ),
  _TimelineFact(
    id: 'ediacaran_biota',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 575000000,
    displayKey: 'toolbox.life.timeline.general.ediacaran_biota.date',
    titleKey: 'toolbox.life.timeline.general.ediacaran_biota.title',
    detailKey: 'toolbox.life.timeline.general.ediacaran_biota.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ediacaran%20biota',
  ),
  _TimelineFact(
    id: 'ordovician_radiation',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 485000000,
    displayKey: 'toolbox.life.timeline.general.ordovician_radiation.date',
    titleKey: 'toolbox.life.timeline.general.ordovician_radiation.title',
    detailKey: 'toolbox.life.timeline.general.ordovician_radiation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Great%20Ordovician%20Biodiversification%20Event',
  ),
  _TimelineFact(
    id: 'first_land_arthropods',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 450000000,
    displayKey: 'toolbox.life.timeline.general.first_land_arthropods.date',
    titleKey: 'toolbox.life.timeline.general.first_land_arthropods.title',
    detailKey: 'toolbox.life.timeline.general.first_land_arthropods.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=colonization%20of%20land',
  ),
  _TimelineFact(
    id: 'first_forests',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 385000000,
    displayKey: 'toolbox.life.timeline.general.first_forests.date',
    titleKey: 'toolbox.life.timeline.general.first_forests.title',
    detailKey: 'toolbox.life.timeline.general.first_forests.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=first%20forest',
  ),
  _TimelineFact(
    id: 'permian_triassic_extinction',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 251900000,
    displayKey: 'toolbox.life.timeline.general.permian_triassic_extinction.date',
    titleKey: 'toolbox.life.timeline.general.permian_triassic_extinction.title',
    detailKey: 'toolbox.life.timeline.general.permian_triassic_extinction.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Permian-Triassic%20extinction%20event',
  ),
  _TimelineFact(
    id: 'first_mammals',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 225000000,
    displayKey: 'toolbox.life.timeline.general.first_mammals.date',
    titleKey: 'toolbox.life.timeline.general.first_mammals.title',
    detailKey: 'toolbox.life.timeline.general.first_mammals.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=evolution%20of%20mammals',
  ),
  _TimelineFact(
    id: 'first_birds',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 150000000,
    displayKey: 'toolbox.life.timeline.general.first_birds.date',
    titleKey: 'toolbox.life.timeline.general.first_birds.title',
    detailKey: 'toolbox.life.timeline.general.first_birds.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=origin%20of%20birds',
  ),
  _TimelineFact(
    id: 'flowering_plants_emerge',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 140000000,
    displayKey: 'toolbox.life.timeline.general.flowering_plants_emerge.date',
    titleKey: 'toolbox.life.timeline.general.flowering_plants_emerge.title',
    detailKey: 'toolbox.life.timeline.general.flowering_plants_emerge.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=evolutionary%20history%20of%20plants',
  ),
  _TimelineFact(
    id: 'paleocene_eocene_thermal_maximum',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 56000000,
    displayKey: 'toolbox.life.timeline.general.paleocene_eocene_thermal_maximum.date',
    titleKey: 'toolbox.life.timeline.general.paleocene_eocene_thermal_maximum.title',
    detailKey: 'toolbox.life.timeline.general.paleocene_eocene_thermal_maximum.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Paleocene-Eocene%20Thermal%20Maximum',
  ),
  _TimelineFact(
    id: 'first_primates',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 55000000,
    displayKey: 'toolbox.life.timeline.general.first_primates.date',
    titleKey: 'toolbox.life.timeline.general.first_primates.title',
    detailKey: 'toolbox.life.timeline.general.first_primates.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=evolution%20of%20primates',
  ),
  _TimelineFact(
    id: 'great_american_interchange',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 3000000,
    displayKey: 'toolbox.life.timeline.general.great_american_interchange.date',
    titleKey: 'toolbox.life.timeline.general.great_american_interchange.title',
    detailKey: 'toolbox.life.timeline.general.great_american_interchange.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Great%20American%20Interchange',
  ),
  _TimelineFact(
    id: 'quaternary_glaciation',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 2580000,
    displayKey: 'toolbox.life.timeline.general.quaternary_glaciation.date',
    titleKey: 'toolbox.life.timeline.general.quaternary_glaciation.title',
    detailKey: 'toolbox.life.timeline.general.quaternary_glaciation.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Quaternary%20glaciation',
  ),
  _TimelineFact(
    id: 'younger_dryas',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 12900,
    displayKey: 'toolbox.life.timeline.general.younger_dryas.date',
    titleKey: 'toolbox.life.timeline.general.younger_dryas.title',
    detailKey: 'toolbox.life.timeline.general.younger_dryas.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Younger%20Dryas',
  ),
  _TimelineFact(
    id: 'holocene_begins',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 11726,
    displayKey: 'toolbox.life.timeline.general.holocene_begins.date',
    titleKey: 'toolbox.life.timeline.general.holocene_begins.title',
    detailKey: 'toolbox.life.timeline.general.holocene_begins.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Holocene',
  ),
  _TimelineFact(
    id: 'african_humid_period',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 8026,
    displayKey: 'toolbox.life.timeline.general.african_humid_period.date',
    titleKey: 'toolbox.life.timeline.general.african_humid_period.title',
    detailKey: 'toolbox.life.timeline.general.african_humid_period.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=African%20humid%20period',
  ),
  _TimelineFact(
    id: 'eight_two_kiloyear_event',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 8226,
    displayKey: 'toolbox.life.timeline.general.eight_two_kiloyear_event.date',
    titleKey: 'toolbox.life.timeline.general.eight_two_kiloyear_event.title',
    detailKey: 'toolbox.life.timeline.general.eight_two_kiloyear_event.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=8.2-kiloyear%20event',
  ),
  _TimelineFact(
    id: 'minoan_eruption',
    collection: 'general',
    category: 'earth',
    yearsBeforePresent: 3626,
    displayKey: 'toolbox.life.timeline.general.minoan_eruption.date',
    titleKey: 'toolbox.life.timeline.general.minoan_eruption.title',
    detailKey: 'toolbox.life.timeline.general.minoan_eruption.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Minoan%20eruption',
  ),
  _TimelineFact(
    id: 'sahelanthropus',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 7000000,
    displayKey: 'toolbox.life.timeline.general.sahelanthropus.date',
    titleKey: 'toolbox.life.timeline.general.sahelanthropus.title',
    detailKey: 'toolbox.life.timeline.general.sahelanthropus.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Sahelanthropus',
  ),
  _TimelineFact(
    id: 'ardipithecus_ramidus',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 4400000,
    displayKey: 'toolbox.life.timeline.general.ardipithecus_ramidus.date',
    titleKey: 'toolbox.life.timeline.general.ardipithecus_ramidus.title',
    detailKey: 'toolbox.life.timeline.general.ardipithecus_ramidus.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ardipithecus%20ramidus',
  ),
  _TimelineFact(
    id: 'australopithecus_lucy',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 3200000,
    displayKey: 'toolbox.life.timeline.general.australopithecus_lucy.date',
    titleKey: 'toolbox.life.timeline.general.australopithecus_lucy.title',
    detailKey: 'toolbox.life.timeline.general.australopithecus_lucy.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Lucy%20Australopithecus',
  ),
  _TimelineFact(
    id: 'lomekwi_tools',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 3300000,
    displayKey: 'toolbox.life.timeline.general.lomekwi_tools.date',
    titleKey: 'toolbox.life.timeline.general.lomekwi_tools.title',
    detailKey: 'toolbox.life.timeline.general.lomekwi_tools.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Lomekwi',
  ),
  _TimelineFact(
    id: 'homo_habilis',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 2400000,
    displayKey: 'toolbox.life.timeline.general.homo_habilis.date',
    titleKey: 'toolbox.life.timeline.general.homo_habilis.title',
    detailKey: 'toolbox.life.timeline.general.homo_habilis.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Homo%20habilis',
  ),
  _TimelineFact(
    id: 'middle_stone_age',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 300000,
    displayKey: 'toolbox.life.timeline.general.middle_stone_age.date',
    titleKey: 'toolbox.life.timeline.general.middle_stone_age.title',
    detailKey: 'toolbox.life.timeline.general.middle_stone_age.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Middle%20Stone%20Age',
  ),
  _TimelineFact(
    id: 'levallois_technique',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 300000,
    displayKey: 'toolbox.life.timeline.general.levallois_technique.date',
    titleKey: 'toolbox.life.timeline.general.levallois_technique.title',
    detailKey: 'toolbox.life.timeline.general.levallois_technique.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Levallois%20technique',
  ),
  _TimelineFact(
    id: 'denisovans',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 300000,
    displayKey: 'toolbox.life.timeline.general.denisovans.date',
    titleKey: 'toolbox.life.timeline.general.denisovans.title',
    detailKey: 'toolbox.life.timeline.general.denisovans.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Denisovan',
  ),
  _TimelineFact(
    id: 'early_human_burials',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 100000,
    displayKey: 'toolbox.life.timeline.general.early_human_burials.date',
    titleKey: 'toolbox.life.timeline.general.early_human_burials.title',
    detailKey: 'toolbox.life.timeline.general.early_human_burials.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=human%20burial',
  ),
  _TimelineFact(
    id: 'prehistoric_ochre_use',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 100000,
    displayKey: 'toolbox.life.timeline.general.prehistoric_ochre_use.date',
    titleKey: 'toolbox.life.timeline.general.prehistoric_ochre_use.title',
    detailKey: 'toolbox.life.timeline.general.prehistoric_ochre_use.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=ochre%20use%20by%20humans',
  ),
  _TimelineFact(
    id: 'bow_and_arrow',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 64000,
    displayKey: 'toolbox.life.timeline.general.bow_and_arrow.date',
    titleKey: 'toolbox.life.timeline.general.bow_and_arrow.title',
    detailKey: 'toolbox.life.timeline.general.bow_and_arrow.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=bow%20and%20arrow',
  ),
  _TimelineFact(
    id: 'neanderthal_sapiens_interbreeding',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 55000,
    displayKey: 'toolbox.life.timeline.general.neanderthal_sapiens_interbreeding.date',
    titleKey: 'toolbox.life.timeline.general.neanderthal_sapiens_interbreeding.title',
    detailKey: 'toolbox.life.timeline.general.neanderthal_sapiens_interbreeding.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=interbreeding%20between%20archaic%20and%20modern%20humans',
  ),
  _TimelineFact(
    id: 'first_bone_flutes',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 40000,
    displayKey: 'toolbox.life.timeline.general.first_bone_flutes.date',
    titleKey: 'toolbox.life.timeline.general.first_bone_flutes.title',
    detailKey: 'toolbox.life.timeline.general.first_bone_flutes.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Paleolithic%20flutes',
  ),
  _TimelineFact(
    id: 'chauvet_cave_art',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 36000,
    displayKey: 'toolbox.life.timeline.general.chauvet_cave_art.date',
    titleKey: 'toolbox.life.timeline.general.chauvet_cave_art.title',
    detailKey: 'toolbox.life.timeline.general.chauvet_cave_art.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chauvet%20Cave',
  ),
  _TimelineFact(
    id: 'venus_figurines',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 35000,
    displayKey: 'toolbox.life.timeline.general.venus_figurines.date',
    titleKey: 'toolbox.life.timeline.general.venus_figurines.title',
    detailKey: 'toolbox.life.timeline.general.venus_figurines.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Venus%20figurine',
  ),
  _TimelineFact(
    id: 'sewing_needles',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 30000,
    displayKey: 'toolbox.life.timeline.general.sewing_needles.date',
    titleKey: 'toolbox.life.timeline.general.sewing_needles.title',
    detailKey: 'toolbox.life.timeline.general.sewing_needles.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=sewing%20needle',
  ),
  _TimelineFact(
    id: 'peopling_of_americas',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 16000,
    displayKey: 'toolbox.life.timeline.general.peopling_of_americas.date',
    titleKey: 'toolbox.life.timeline.general.peopling_of_americas.title',
    detailKey: 'toolbox.life.timeline.general.peopling_of_americas.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=peopling%20of%20the%20Americas',
  ),
  _TimelineFact(
    id: 'jomon_pottery',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 16000,
    displayKey: 'toolbox.life.timeline.general.jomon_pottery.date',
    titleKey: 'toolbox.life.timeline.general.jomon_pottery.title',
    detailKey: 'toolbox.life.timeline.general.jomon_pottery.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Jomon%20pottery',
  ),
  _TimelineFact(
    id: 'earliest_known_bread',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 14400,
    displayKey: 'toolbox.life.timeline.general.earliest_known_bread.date',
    titleKey: 'toolbox.life.timeline.general.earliest_known_bread.title',
    detailKey: 'toolbox.life.timeline.general.earliest_known_bread.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Shubayqa%201',
  ),
  _TimelineFact(
    id: 'jericho_settlement',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 11000,
    displayKey: 'toolbox.life.timeline.general.jericho_settlement.date',
    titleKey: 'toolbox.life.timeline.general.jericho_settlement.title',
    detailKey: 'toolbox.life.timeline.general.jericho_settlement.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Tell%20es-Sultan',
  ),
  _TimelineFact(
    id: 'sheep_domestication',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 11000,
    displayKey: 'toolbox.life.timeline.general.sheep_domestication.date',
    titleKey: 'toolbox.life.timeline.general.sheep_domestication.title',
    detailKey: 'toolbox.life.timeline.general.sheep_domestication.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=domestic%20sheep',
  ),
  _TimelineFact(
    id: 'cattle_domestication',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 10500,
    displayKey: 'toolbox.life.timeline.general.cattle_domestication.date',
    titleKey: 'toolbox.life.timeline.general.cattle_domestication.title',
    detailKey: 'toolbox.life.timeline.general.cattle_domestication.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=domestication%20of%20cattle',
  ),
  _TimelineFact(
    id: 'maize_domestication',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 9000,
    displayKey: 'toolbox.life.timeline.general.maize_domestication.date',
    titleKey: 'toolbox.life.timeline.general.maize_domestication.title',
    detailKey: 'toolbox.life.timeline.general.maize_domestication.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=domestication%20of%20maize',
  ),
  _TimelineFact(
    id: 'copper_metallurgy',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 8500,
    displayKey: 'toolbox.life.timeline.general.copper_metallurgy.date',
    titleKey: 'toolbox.life.timeline.general.copper_metallurgy.title',
    detailKey: 'toolbox.life.timeline.general.copper_metallurgy.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=copper%20metallurgy',
  ),
  _TimelineFact(
    id: 'irrigation_agriculture',
    collection: 'general',
    category: 'human',
    yearsBeforePresent: 8000,
    displayKey: 'toolbox.life.timeline.general.irrigation_agriculture.date',
    titleKey: 'toolbox.life.timeline.general.irrigation_agriculture.title',
    detailKey: 'toolbox.life.timeline.general.irrigation_agriculture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=irrigation',
  ),
  _TimelineFact(
    id: 'uruk_period',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5576,
    displayKey: 'toolbox.life.timeline.general.uruk_period.date',
    titleKey: 'toolbox.life.timeline.general.uruk_period.title',
    detailKey: 'toolbox.life.timeline.general.uruk_period.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Uruk%20period',
  ),
  _TimelineFact(
    id: 'earliest_cuneiform',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 5326,
    displayKey: 'toolbox.life.timeline.general.earliest_cuneiform.date',
    titleKey: 'toolbox.life.timeline.general.earliest_cuneiform.title',
    detailKey: 'toolbox.life.timeline.general.earliest_cuneiform.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=cuneiform',
  ),
  _TimelineFact(
    id: 'stonehenge_construction',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4526,
    displayKey: 'toolbox.life.timeline.general.stonehenge_construction.date',
    titleKey: 'toolbox.life.timeline.general.stonehenge_construction.title',
    detailKey: 'toolbox.life.timeline.general.stonehenge_construction.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Stonehenge',
  ),
  _TimelineFact(
    id: 'mesopotamian_city_ur',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4476,
    displayKey: 'toolbox.life.timeline.general.mesopotamian_city_ur.date',
    titleKey: 'toolbox.life.timeline.general.mesopotamian_city_ur.title',
    detailKey: 'toolbox.life.timeline.general.mesopotamian_city_ur.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Ur',
  ),
  _TimelineFact(
    id: 'code_of_ur_nammu',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 4101,
    displayKey: 'toolbox.life.timeline.general.code_of_ur_nammu.date',
    titleKey: 'toolbox.life.timeline.general.code_of_ur_nammu.title',
    detailKey: 'toolbox.life.timeline.general.code_of_ur_nammu.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Code%20of%20Ur-Nammu',
  ),
  _TimelineFact(
    id: 'epic_of_gilgamesh',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3676,
    displayKey: 'toolbox.life.timeline.general.epic_of_gilgamesh.date',
    titleKey: 'toolbox.life.timeline.general.epic_of_gilgamesh.title',
    detailKey: 'toolbox.life.timeline.general.epic_of_gilgamesh.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Epic%20of%20Gilgamesh',
  ),
  _TimelineFact(
    id: 'minoan_linear_a',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3651,
    displayKey: 'toolbox.life.timeline.general.minoan_linear_a.date',
    titleKey: 'toolbox.life.timeline.general.minoan_linear_a.title',
    detailKey: 'toolbox.life.timeline.general.minoan_linear_a.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Linear%20A',
  ),
  _TimelineFact(
    id: 'hittite_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3440,
    displayKey: 'toolbox.life.timeline.general.hittite_empire.date',
    titleKey: 'toolbox.life.timeline.general.hittite_empire.title',
    detailKey: 'toolbox.life.timeline.general.hittite_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Hittite%20Empire',
  ),
  _TimelineFact(
    id: 'vedic_period',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3026,
    displayKey: 'toolbox.life.timeline.general.vedic_period.date',
    titleKey: 'toolbox.life.timeline.general.vedic_period.title',
    detailKey: 'toolbox.life.timeline.general.vedic_period.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Vedic%20period',
  ),
  _TimelineFact(
    id: 'mycenaean_linear_b',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3351,
    displayKey: 'toolbox.life.timeline.general.mycenaean_linear_b.date',
    titleKey: 'toolbox.life.timeline.general.mycenaean_linear_b.title',
    detailKey: 'toolbox.life.timeline.general.mycenaean_linear_b.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Linear%20B',
  ),
  _TimelineFact(
    id: 'battle_of_kadesh',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3300,
    displayKey: 'toolbox.life.timeline.general.battle_of_kadesh.date',
    titleKey: 'toolbox.life.timeline.general.battle_of_kadesh.title',
    detailKey: 'toolbox.life.timeline.general.battle_of_kadesh.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Battle%20of%20Kadesh',
  ),
  _TimelineFact(
    id: 'egyptian_hittite_peace_treaty',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 3285,
    displayKey: 'toolbox.life.timeline.general.egyptian_hittite_peace_treaty.date',
    titleKey: 'toolbox.life.timeline.general.egyptian_hittite_peace_treaty.title',
    detailKey: 'toolbox.life.timeline.general.egyptian_hittite_peace_treaty.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Egyptian-Hittite%20peace%20treaty',
  ),
  _TimelineFact(
    id: 'olmec_colossal_heads',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2826,
    displayKey: 'toolbox.life.timeline.general.olmec_colossal_heads.date',
    titleKey: 'toolbox.life.timeline.general.olmec_colossal_heads.title',
    detailKey: 'toolbox.life.timeline.general.olmec_colossal_heads.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Olmec%20colossal%20heads',
  ),
  _TimelineFact(
    id: 'nok_culture',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2376,
    displayKey: 'toolbox.life.timeline.general.nok_culture.date',
    titleKey: 'toolbox.life.timeline.general.nok_culture.title',
    detailKey: 'toolbox.life.timeline.general.nok_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Nok%20culture',
  ),
  _TimelineFact(
    id: 'chavin_culture',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2576,
    displayKey: 'toolbox.life.timeline.general.chavin_culture.date',
    titleKey: 'toolbox.life.timeline.general.chavin_culture.title',
    detailKey: 'toolbox.life.timeline.general.chavin_culture.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Chavin%20culture',
  ),
  _TimelineFact(
    id: 'neo_assyrian_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2786,
    displayKey: 'toolbox.life.timeline.general.neo_assyrian_empire.date',
    titleKey: 'toolbox.life.timeline.general.neo_assyrian_empire.title',
    detailKey: 'toolbox.life.timeline.general.neo_assyrian_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Neo-Assyrian%20Empire',
  ),
  _TimelineFact(
    id: 'babylonian_astronomy',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2476,
    displayKey: 'toolbox.life.timeline.general.babylonian_astronomy.date',
    titleKey: 'toolbox.life.timeline.general.babylonian_astronomy.title',
    detailKey: 'toolbox.life.timeline.general.babylonian_astronomy.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Babylonian%20astronomy',
  ),
  _TimelineFact(
    id: 'achaemenid_royal_road',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2526,
    displayKey: 'toolbox.life.timeline.general.achaemenid_royal_road.date',
    titleKey: 'toolbox.life.timeline.general.achaemenid_royal_road.title',
    detailKey: 'toolbox.life.timeline.general.achaemenid_royal_road.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Royal%20Road',
  ),
  _TimelineFact(
    id: 'zoroastrianism_spreads',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2576,
    displayKey: 'toolbox.life.timeline.general.zoroastrianism_spreads.date',
    titleKey: 'toolbox.life.timeline.general.zoroastrianism_spreads.title',
    detailKey: 'toolbox.life.timeline.general.zoroastrianism_spreads.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Zoroastrianism',
  ),
  _TimelineFact(
    id: 'mahavira_and_jainism',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2589,
    displayKey: 'toolbox.life.timeline.general.mahavira_and_jainism.date',
    titleKey: 'toolbox.life.timeline.general.mahavira_and_jainism.title',
    detailKey: 'toolbox.life.timeline.general.mahavira_and_jainism.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Mahavira',
  ),
  _TimelineFact(
    id: 'axial_age',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2526,
    displayKey: 'toolbox.life.timeline.general.axial_age.date',
    titleKey: 'toolbox.life.timeline.general.axial_age.title',
    detailKey: 'toolbox.life.timeline.general.axial_age.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Axial%20Age',
  ),
  _TimelineFact(
    id: 'library_of_alexandria',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2309,
    displayKey: 'toolbox.life.timeline.general.library_of_alexandria.date',
    titleKey: 'toolbox.life.timeline.general.library_of_alexandria.title',
    detailKey: 'toolbox.life.timeline.general.library_of_alexandria.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Library%20of%20Alexandria',
  ),
  _TimelineFact(
    id: 'seleucid_empire',
    collection: 'general',
    category: 'civilization',
    yearsBeforePresent: 2213.5,
    displayKey: 'toolbox.life.timeline.general.seleucid_empire.date',
    titleKey: 'toolbox.life.timeline.general.seleucid_empire.title',
    detailKey: 'toolbox.life.timeline.general.seleucid_empire.detail',
    sourceNameKey: 'toolbox.life.timeline.source.wikidata',
    sourceUrl: 'https://www.wikidata.org/w/index.php?search=Seleucid%20Empire',
  ),
];
