part of '../toolbox_life_tools.dart';

class _TimelineFact {
  const _TimelineFact({
    required this.id,
    required this.category,
    required this.yearsBeforePresent,
    required this.displayKey,
    required this.titleKey,
    required this.detailKey,
    required this.sourceName,
    required this.sourceUrl,
  });
  final String id;
  final String category;
  final double yearsBeforePresent;
  final String displayKey;
  final String titleKey;
  final String detailKey;
  final String sourceName;
  final String sourceUrl;
}

class _ElementFact {
  const _ElementFact({
    required this.atomicNumber,
    required this.symbol,
    required this.nameEn,
    required this.atomicMass,
    required this.groupBlock,
    required this.standardState,
    required this.yearDiscovered,
    required this.electronConfiguration,
    required this.electronegativity,
    required this.period,
    required this.group,
    required this.displayRow,
    required this.displayColumn,
  });
  final int atomicNumber;
  final String symbol;
  final String nameEn;
  final String atomicMass;
  final String groupBlock;
  final String standardState;
  final String yearDiscovered;
  final String electronConfiguration;
  final String electronegativity;
  final int period;
  final int group;
  final int displayRow;
  final int displayColumn;
}

class _TimelineBackdropAsset {
  const _TimelineBackdropAsset({
    required this.id,
    required this.category,
    required this.imageUrl,
    required this.sourceName,
    required this.sourceUrl,
    required this.credit,
  });

  final String id;
  final String category;
  final String imageUrl;
  final String sourceName;
  final String sourceUrl;
  final String credit;
}

const List<_TimelineBackdropAsset>
_timelineBackdropAssets = <_TimelineBackdropAsset>[
  _TimelineBackdropAsset(
    id: 'cosmic_cliffs',
    category: 'cosmic',
    imageUrl:
        'https://images-assets.nasa.gov/image/carina_nebula/carina_nebula~large.jpg',
    sourceName: 'NASA Image Library: Cosmic Cliffs',
    sourceUrl: 'https://images.nasa.gov/details/carina_nebula',
    credit: 'NASA/ESA/CSA/STScI',
  ),
  _TimelineBackdropAsset(
    id: 'basalt_rock',
    category: 'earth',
    imageUrl:
        'https://commons.wikimedia.org/wiki/Special:FilePath/BasaltUSGOV.jpg?width=1400',
    sourceName: 'USGS basalt rock photograph',
    sourceUrl: 'https://www.usgs.gov/media/images/basalt-rock-photograph',
    credit: 'U.S. Geological Survey, public domain',
  ),
  _TimelineBackdropAsset(
    id: 'rosetta_stone',
    category: 'civilization',
    imageUrl:
        'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Rosetta%20Stone.jpg?width=1400',
    sourceName: 'Wikimedia Commons: Rosetta Stone',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Rosetta_Stone.jpg',
    credit: 'Wikimedia Commons public-domain media',
  ),
  _TimelineBackdropAsset(
    id: 'apollo_earth',
    category: 'science',
    imageUrl:
        'https://images-assets.nasa.gov/image/as17-148-22727/as17-148-22727~large.jpg',
    sourceName: 'NASA Image Library: Apollo 17 Earth',
    sourceUrl: 'https://images.nasa.gov/details/as17-148-22727',
    credit: 'NASA/JSC',
  ),
  _TimelineBackdropAsset(
    id: 'world_wide_web',
    category: 'modern',
    imageUrl:
        'https://images-assets.nasa.gov/image/as17-148-22727/as17-148-22727~large.jpg',
    sourceName: 'NASA Image Library: Apollo 17 Earth',
    sourceUrl: 'https://images.nasa.gov/details/as17-148-22727',
    credit: 'NASA/JSC',
  ),
  _TimelineBackdropAsset(
    id: 'human_artifact',
    category: 'human',
    imageUrl:
        'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Rosetta%20Stone.jpg?width=1400',
    sourceName: 'Wikimedia Commons: Rosetta Stone',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Rosetta_Stone.jpg',
    credit: 'Wikimedia Commons public-domain media',
  ),
];

const List<_TimelineFact> _coreTimelineFacts = <_TimelineFact>[
  _TimelineFact(
    id: 'big_bang',
    category: 'cosmic',
    yearsBeforePresent: 13800000000.0,
    displayKey: 'inline.plan297.life.c_13_8_billion_years_ago.7be0c38b2237',
    titleKey:
        'inline.plan297.life.hot_big_bang_era_of_the_observable_universe.c44c3e48fccd',
    detailKey:
        'inline.plan297.life.modern_cosmology_places_the_hot_dense_early_stat.27acefcef07b',
    sourceName: 'NASA Universe overview',
    sourceUrl: 'https://science.nasa.gov/universe/',
  ),
  _TimelineFact(
    id: 'earth_forms',
    category: 'earth',
    yearsBeforePresent: 4540000000.0,
    displayKey: 'inline.plan297.life.c_4_54_billion_years_ago.3e92a42c6c11',
    titleKey: 'inline.plan297.life.earth_forms.3a01ebc4fbb3',
    detailKey:
        'inline.plan297.life.radiometric_dating_and_meteorite_evidence_suppor.93da1e1fd6c3',
    sourceName: 'USGS: How old is Earth?',
    sourceUrl: 'https://www.usgs.gov/faqs/how-old-earth',
  ),
  _TimelineFact(
    id: 'first_life',
    category: 'earth',
    yearsBeforePresent: 3500000000.0,
    displayKey: 'inline.plan297.life.c_3_5_billion_years_ago.99b0f19ad58c',
    titleKey: 'inline.plan297.life.early_evidence_of_life.16b7d9543020',
    detailKey:
        'inline.plan297.life.common_summaries_place_early_microbial_life_evid.cacd8f02b050',
    sourceName: 'Smithsonian Human Origins Program',
    sourceUrl: 'https://humanorigins.si.edu/',
  ),
  _TimelineFact(
    id: 'great_oxidation',
    category: 'earth',
    yearsBeforePresent: 2400000000.0,
    displayKey: 'inline.plan297.life.c_2_4_billion_years_ago.8c4881d27f07',
    titleKey: 'inline.plan297.life.great_oxidation_event.226b180bfb05',
    detailKey:
        'inline.plan297.life.atmospheric_and_ocean_oxygen_rose_substantially_.226ae67d384d',
    sourceName: 'NASA Astrobiology',
    sourceUrl: 'https://astrobiology.nasa.gov/',
  ),
  _TimelineFact(
    id: 'eukaryotes',
    category: 'earth',
    yearsBeforePresent: 1800000000.0,
    displayKey: 'inline.plan297.life.c_1_8_billion_years_ago.48c555bca08a',
    titleKey: 'inline.plan297.life.eukaryotes_appear.70f3a67d47ce',
    detailKey:
        'inline.plan297.life.nucleated_eukaryotic_cells_appeared_in_the_paleo.9d348e50d788',
    sourceName: 'Encyclopaedia Britannica: eukaryote',
    sourceUrl: 'https://www.britannica.com/science/eukaryote',
  ),
  _TimelineFact(
    id: 'cambrian',
    category: 'earth',
    yearsBeforePresent: 538800000.0,
    displayKey: 'inline.plan297.life.c_538_8_million_years_ago.ee736a11101d',
    titleKey: 'inline.plan297.life.cambrian_period_begins.cd7c9d487e70',
    detailKey:
        'inline.plan297.life.the_ics_2024_12_chart_places_the_start_of_the_ca.a537b96554d9',
    sourceName: 'International Commission on Stratigraphy',
    sourceUrl: 'https://stratigraphy.org/chart',
  ),
  _TimelineFact(
    id: 'land_plants',
    category: 'earth',
    yearsBeforePresent: 470000000.0,
    displayKey: 'inline.plan297.life.c_470_million_years_ago.789ef2fe6dcb',
    titleKey: 'inline.plan297.life.land_plants_spread.fbda3524b4fe',
    detailKey:
        'inline.plan297.life.plant_expansion_onto_land_laid_the_foundation_fo.f7c4870dc8df',
    sourceName: 'Encyclopaedia Britannica: plant evolution',
    sourceUrl:
        'https://www.britannica.com/science/plant/Evolution-and-paleobotany',
  ),
  _TimelineFact(
    id: 'dinosaurs',
    category: 'earth',
    yearsBeforePresent: 230000000.0,
    displayKey: 'inline.plan297.life.c_230_million_years_ago.6cc6127f81da',
    titleKey: 'inline.plan297.life.dinosaurs_appear.3b05c1158769',
    detailKey:
        'inline.plan297.life.dinosaurs_appeared_in_the_late_triassic_and_late.44b2ee700575',
    sourceName: 'Natural History Museum',
    sourceUrl: 'https://www.nhm.ac.uk/discover/when-did-dinosaurs-live.html',
  ),
  _TimelineFact(
    id: 'kpg_extinction',
    category: 'earth',
    yearsBeforePresent: 66000000.0,
    displayKey: 'inline.plan297.life.c_66_million_years_ago.8c21bacf1731',
    titleKey:
        'inline.plan297.life.cretaceous_paleogene_extinction.465c9ac92be9',
    detailKey:
        'inline.plan297.life.a_mass_extinction_ended_non_avian_dinosaurs_and_.41c5389d3c3d',
    sourceName: 'USGS: Geologic time',
    sourceUrl:
        'https://www.usgs.gov/programs/national-geologic-map-database/geologic-time',
  ),
  _TimelineFact(
    id: 'homo_genus',
    category: 'human',
    yearsBeforePresent: 2800000.0,
    displayKey: 'inline.plan297.life.c_2_8_million_years_ago.2cc73ff3a938',
    titleKey: 'inline.plan297.life.early_homo_fossil_record.9b85ece8428d',
    detailKey:
        'inline.plan297.life.early_homo_fossil_evidence_is_commonly_placed_ar.71989fcb7cc2',
    sourceName: 'Smithsonian Human Origins Program',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-habilis',
  ),
  _TimelineFact(
    id: 'stone_tools',
    category: 'human',
    yearsBeforePresent: 2600000.0,
    displayKey: 'inline.plan297.life.c_2_6_million_years_ago.63eb23887f49',
    titleKey: 'inline.plan297.life.oldowan_stone_tools.1bd3ae4fc95e',
    detailKey:
        'inline.plan297.life.oldowan_tools_are_a_classic_evidence_line_for_ea.5b34c867e6a8',
    sourceName: 'Smithsonian: Stone tools',
    sourceUrl: 'https://humanorigins.si.edu/evidence/behavior/stone-tools',
  ),
  _TimelineFact(
    id: 'homo_sapiens',
    category: 'human',
    yearsBeforePresent: 300000.0,
    displayKey: 'inline.plan297.life.c_300_000_years_ago.de7abada8a32',
    titleKey: 'inline.plan297.life.homo_sapiens_appear.f5c862da7196',
    detailKey:
        'inline.plan297.life.current_fossil_and_genetic_evidence_commonly_pla.aa3c8989f502',
    sourceName: 'Smithsonian: Homo sapiens',
    sourceUrl:
        'https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens',
  ),
  _TimelineFact(
    id: 'last_glacial_maximum',
    category: 'human',
    yearsBeforePresent: 26500.0,
    displayKey: 'inline.plan297.life.c_26_500_years_ago.fe13320c5b27',
    titleKey: 'inline.plan297.life.last_glacial_maximum.2e32264076e5',
    detailKey:
        'inline.plan297.life.ice_sheets_reached_near_maximum_extent_during_th.9a3e9b4a19da',
    sourceName: 'NOAA Paleoclimatology',
    sourceUrl: 'https://www.ncei.noaa.gov/products/paleoclimatology',
  ),
  _TimelineFact(
    id: 'agriculture',
    category: 'civilization',
    yearsBeforePresent: 12000.0,
    displayKey: 'inline.plan297.life.c_10_000_bce.1d96609e49ed',
    titleKey:
        'inline.plan297.life.agriculture_and_neolithic_transition.fbd60f7f2490',
    detailKey:
        'inline.plan297.life.plant_and_animal_domestication_developed_in_mult.c1f342554684',
    sourceName: 'Britannica: Neolithic Revolution',
    sourceUrl: 'https://www.britannica.com/event/Neolithic-Revolution',
  ),
  _TimelineFact(
    id: 'bronze_age',
    category: 'civilization',
    yearsBeforePresent: 5300.0,
    displayKey: 'inline.plan297.life.c_3300_bce.69daaba38d63',
    titleKey: 'inline.plan297.life.early_bronze_age.e86493ece9bf',
    detailKey:
        'inline.plan297.life.bronze_metallurgy_and_complex_urban_societies_de.a861cffe8c17',
    sourceName: 'Britannica: Bronze Age',
    sourceUrl: 'https://www.britannica.com/event/Bronze-Age',
  ),
  _TimelineFact(
    id: 'writing',
    category: 'civilization',
    yearsBeforePresent: 5200.0,
    displayKey: 'inline.plan297.life.c_3200_bce.af82a17e41bb',
    titleKey: 'inline.plan297.life.early_writing_systems.40796a41a1e7',
    detailKey:
        'inline.plan297.life.early_writing_systems_such_as_mesopotamian_cunei.10b8e3125af5',
    sourceName: 'Britannica: writing',
    sourceUrl: 'https://www.britannica.com/topic/writing',
  ),
  _TimelineFact(
    id: 'iron_age',
    category: 'civilization',
    yearsBeforePresent: 3200.0,
    displayKey: 'inline.plan297.life.c_1200_bce.c46f7582314a',
    titleKey: 'inline.plan297.life.iron_age_expansion.4644a1346fc2',
    detailKey:
        'inline.plan297.life.widespread_iron_tools_and_weapons_changed_agricu.a8893e4b247c',
    sourceName: 'Britannica: Iron Age',
    sourceUrl: 'https://www.britannica.com/event/Iron-Age',
  ),
  _TimelineFact(
    id: 'qin_unification',
    category: 'civilization',
    yearsBeforePresent: 2247.0,
    displayKey: 'inline.plan297.life.221_bce.0c1cb92a4a80',
    titleKey: 'inline.plan297.life.qin_unifies_china.96f98eadf559',
    detailKey:
        'inline.plan297.life.the_qin_dynasty_completed_a_major_political_unif.e579146f199d',
    sourceName: 'Britannica: Qin dynasty',
    sourceUrl: 'https://www.britannica.com/topic/Qin-dynasty',
  ),
  _TimelineFact(
    id: 'paper',
    category: 'civilization',
    yearsBeforePresent: 1921.0,
    displayKey: 'inline.plan297.life.c_105_ce.d579b9eca006',
    titleKey: 'inline.plan297.life.papermaking_refined.1ba392c0ad4b',
    detailKey:
        'inline.plan297.life.traditional_accounts_place_cai_lun_s_papermaking.a710a304813e',
    sourceName: 'Britannica: papermaking',
    sourceUrl: 'https://www.britannica.com/technology/papermaking',
  ),
  _TimelineFact(
    id: 'black_death',
    category: 'civilization',
    yearsBeforePresent: 679.0,
    displayKey: 'inline.plan297.life.1347_1351_ce.1f5d640e460e',
    titleKey:
        'inline.plan297.life.black_death_across_eurasia_and_north_africa.a70556cb8a72',
    detailKey:
        'inline.plan297.life.the_mid_14th_century_plague_pandemic_caused_enor.1e12db430d36',
    sourceName: 'Britannica: Black Death',
    sourceUrl: 'https://www.britannica.com/event/Black-Death',
  ),
  _TimelineFact(
    id: 'gutenberg',
    category: 'civilization',
    yearsBeforePresent: 576.0,
    displayKey: 'inline.plan297.life.c_1450_ce.6b23789e9ca4',
    titleKey:
        'inline.plan297.life.movable_type_printing_spreads_in_europe.51aa534eb9c2',
    detailKey:
        'inline.plan297.life.gutenberg_era_printing_lowered_book_reproduction.e444d4345c3b',
    sourceName: 'Britannica: printing press',
    sourceUrl: 'https://www.britannica.com/technology/printing-press',
  ),
  _TimelineFact(
    id: 'newton',
    category: 'science',
    yearsBeforePresent: 339.0,
    displayKey: 'inline.plan297.life.1687_ce.dc8be3138fef',
    titleKey: 'inline.plan297.life.newton_s_principia_published.13319f61403b',
    detailKey:
        'inline.plan297.life.newton_systematized_laws_of_motion_and_universal.430748982a46',
    sourceName: 'Britannica: Principia',
    sourceUrl:
        'https://www.britannica.com/topic/Philosophiae-Naturalis-Principia-Mathematica',
  ),
  _TimelineFact(
    id: 'industrial_revolution',
    category: 'modern',
    yearsBeforePresent: 266.0,
    displayKey: 'inline.plan297.life.from_c_1760_ce.060213656827',
    titleKey: 'inline.plan297.life.industrial_revolution_begins.968024e1ca7d',
    detailKey:
        'inline.plan297.life.mechanized_production_fossil_energy_and_factory_.dbff79d41a9a',
    sourceName: 'Britannica: Industrial Revolution',
    sourceUrl: 'https://www.britannica.com/event/Industrial-Revolution',
  ),
  _TimelineFact(
    id: 'darwin',
    category: 'science',
    yearsBeforePresent: 167.0,
    displayKey: 'inline.plan297.life.1859_ce.1f611a91fd8b',
    titleKey:
        'inline.plan297.life.on_the_origin_of_species_published.01f6749ee8fc',
    detailKey:
        'inline.plan297.life.darwin_s_theory_of_natural_selection_became_one_.2415b0a8a0ed',
    sourceName: 'Britannica: On the Origin of Species',
    sourceUrl:
        'https://www.britannica.com/topic/On-the-Origin-of-Species-by-Means-of-Natural-Selection',
  ),
  _TimelineFact(
    id: 'periodic_table',
    category: 'science',
    yearsBeforePresent: 157.0,
    displayKey: 'inline.plan297.life.1869_ce.37a5348fc0d5',
    titleKey: 'inline.plan297.life.mendeleev_periodic_table.21cba26a5695',
    detailKey:
        'inline.plan297.life.mendeleev_arranged_elements_by_atomic_weight_and.1634dfb74a4a',
    sourceName: 'IUPAC Periodic Table',
    sourceUrl: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
  ),
  _TimelineFact(
    id: 'un_founded',
    category: 'modern',
    yearsBeforePresent: 81.0,
    displayKey: 'inline.plan297.life.1945_ce.c29d4b3651a1',
    titleKey: 'inline.plan297.life.united_nations_founded.fb41992a5d60',
    detailKey:
        'inline.plan297.life.after_world_war_ii_the_united_nations_was_formal.5c5b7a6ba72c',
    sourceName: 'United Nations: History',
    sourceUrl: 'https://www.un.org/en/about-us/history-of-the-un',
  ),
  _TimelineFact(
    id: 'dna_double_helix',
    category: 'science',
    yearsBeforePresent: 73.0,
    displayKey: 'inline.plan297.life.1953_ce.8daabed68cf1',
    titleKey: 'inline.plan297.life.dna_double_helix_proposed.a206edea1a73',
    detailKey:
        'inline.plan297.life.watson_and_crick_proposed_the_dna_double_helix_m.dcf58f76cefe',
    sourceName: 'Nobel Prize: DNA structure',
    sourceUrl: 'https://www.nobelprize.org/prizes/medicine/1962/summary/',
  ),
  _TimelineFact(
    id: 'moon_landing',
    category: 'science',
    yearsBeforePresent: 57.0,
    displayKey: 'inline.plan297.life.1969_ce.58209d5f0570',
    titleKey: 'inline.plan297.life.apollo_11_moon_landing.e4c951f9a1a1',
    detailKey:
        'inline.plan297.life.humans_walked_on_the_moon_for_the_first_time.4ffc3353fc40',
    sourceName: 'NASA Apollo 11',
    sourceUrl: 'https://www.nasa.gov/history/apollo-11/',
  ),
  _TimelineFact(
    id: 'web',
    category: 'modern',
    yearsBeforePresent: 35.0,
    displayKey: 'inline.plan297.life.1991_ce.8057f820b589',
    titleKey:
        'inline.plan297.life.world_wide_web_becomes_publicly_available.a34308c282d7',
    detailKey:
        'inline.plan297.life.the_web_combined_hypertext_urls_and_the_internet.1ba6c98ba3c5',
    sourceName: 'CERN: Birth of the Web',
    sourceUrl: 'https://home.cern/science/computing/birth-web',
  ),
  _TimelineFact(
    id: 'human_genome',
    category: 'science',
    yearsBeforePresent: 23.0,
    displayKey: 'inline.plan297.life.2003_ce.ce0b724ff07b',
    titleKey: 'inline.plan297.life.human_genome_project_completed.6d8232a172d1',
    detailKey:
        'inline.plan297.life.the_human_genome_project_completed_a_major_phase.94e05340cb6e',
    sourceName: 'NIH: Human Genome Project',
    sourceUrl: 'https://www.genome.gov/human-genome-project',
  ),
  _TimelineFact(
    id: 'gravitational_waves',
    category: 'science',
    yearsBeforePresent: 11.0,
    displayKey: 'inline.plan297.life.2015_ce.4c5143e3995a',
    titleKey:
        'inline.plan297.life.first_direct_detection_of_gravitational_waves.9ac99d71a47d',
    detailKey:
        'inline.plan297.life.ligo_directly_detected_gravitational_waves_from_.b4ab5a4c856d',
    sourceName: 'LIGO discovery',
    sourceUrl: 'https://www.ligo.caltech.edu/page/detection-companion-papers',
  ),
];

const List<_ElementFact> _elementFacts = <_ElementFact>[
  _ElementFact(
    atomicNumber: 1,
    symbol: 'H',
    nameEn: 'Hydrogen',
    atomicMass: '1.0080',
    groupBlock: 'Nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1766',
    electronConfiguration: '1s1',
    electronegativity: '2.2',
    period: 1,
    group: 1,
    displayRow: 1,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 2,
    symbol: 'He',
    nameEn: 'Helium',
    atomicMass: '4.00260',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1868',
    electronConfiguration: '1s2',
    electronegativity: '',
    period: 1,
    group: 18,
    displayRow: 1,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 3,
    symbol: 'Li',
    nameEn: 'Lithium',
    atomicMass: '7.0',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[He]2s1',
    electronegativity: '0.98',
    period: 2,
    group: 1,
    displayRow: 2,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 4,
    symbol: 'Be',
    nameEn: 'Beryllium',
    atomicMass: '9.012183',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1798',
    electronConfiguration: '[He]2s2',
    electronegativity: '1.57',
    period: 2,
    group: 2,
    displayRow: 2,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 5,
    symbol: 'B',
    nameEn: 'Boron',
    atomicMass: '10.81',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[He]2s2 2p1',
    electronegativity: '2.04',
    period: 2,
    group: 13,
    displayRow: 2,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 6,
    symbol: 'C',
    nameEn: 'Carbon',
    atomicMass: '12.011',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[He]2s2 2p2',
    electronegativity: '2.55',
    period: 2,
    group: 14,
    displayRow: 2,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 7,
    symbol: 'N',
    nameEn: 'Nitrogen',
    atomicMass: '14.007',
    groupBlock: 'Nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1772',
    electronConfiguration: '[He] 2s2 2p3',
    electronegativity: '3.04',
    period: 2,
    group: 15,
    displayRow: 2,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 8,
    symbol: 'O',
    nameEn: 'Oxygen',
    atomicMass: '15.999',
    groupBlock: 'Nonmetal',
    standardState: 'Gas',
    yearDiscovered: '1774',
    electronConfiguration: '[He]2s2 2p4',
    electronegativity: '3.44',
    period: 2,
    group: 16,
    displayRow: 2,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 9,
    symbol: 'F',
    nameEn: 'Fluorine',
    atomicMass: '18.99840316',
    groupBlock: 'Halogen',
    standardState: 'Gas',
    yearDiscovered: '1670',
    electronConfiguration: '[He]2s2 2p5',
    electronegativity: '3.98',
    period: 2,
    group: 17,
    displayRow: 2,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 10,
    symbol: 'Ne',
    nameEn: 'Neon',
    atomicMass: '20.180',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[He]2s2 2p6',
    electronegativity: '',
    period: 2,
    group: 18,
    displayRow: 2,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 11,
    symbol: 'Na',
    nameEn: 'Sodium',
    atomicMass: '22.9897693',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1807',
    electronConfiguration: '[Ne]3s1',
    electronegativity: '0.93',
    period: 3,
    group: 1,
    displayRow: 3,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 12,
    symbol: 'Mg',
    nameEn: 'Magnesium',
    atomicMass: '24.305',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[Ne]3s2',
    electronegativity: '1.31',
    period: 3,
    group: 2,
    displayRow: 3,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 13,
    symbol: 'Al',
    nameEn: 'Aluminum',
    atomicMass: '26.981538',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ne]3s2 3p1',
    electronegativity: '1.61',
    period: 3,
    group: 13,
    displayRow: 3,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 14,
    symbol: 'Si',
    nameEn: 'Silicon',
    atomicMass: '28.085',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1854',
    electronConfiguration: '[Ne]3s2 3p2',
    electronegativity: '1.9',
    period: 3,
    group: 14,
    displayRow: 3,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 15,
    symbol: 'P',
    nameEn: 'Phosphorus',
    atomicMass: '30.97376200',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: '1669',
    electronConfiguration: '[Ne]3s2 3p3',
    electronegativity: '2.19',
    period: 3,
    group: 15,
    displayRow: 3,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 16,
    symbol: 'S',
    nameEn: 'Sulfur',
    atomicMass: '32.07',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ne]3s2 3p4',
    electronegativity: '2.58',
    period: 3,
    group: 16,
    displayRow: 3,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 17,
    symbol: 'Cl',
    nameEn: 'Chlorine',
    atomicMass: '35.45',
    groupBlock: 'Halogen',
    standardState: 'Gas',
    yearDiscovered: '1774',
    electronConfiguration: '[Ne]3s2 3p5',
    electronegativity: '3.16',
    period: 3,
    group: 17,
    displayRow: 3,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 18,
    symbol: 'Ar',
    nameEn: 'Argon',
    atomicMass: '39.9',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1894',
    electronConfiguration: '[Ne]3s2 3p6',
    electronegativity: '',
    period: 3,
    group: 18,
    displayRow: 3,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 19,
    symbol: 'K',
    nameEn: 'Potassium',
    atomicMass: '39.0983',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1807',
    electronConfiguration: '[Ar]4s1',
    electronegativity: '0.82',
    period: 4,
    group: 1,
    displayRow: 4,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 20,
    symbol: 'Ca',
    nameEn: 'Calcium',
    atomicMass: '40.08',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2',
    electronegativity: '1',
    period: 4,
    group: 2,
    displayRow: 4,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 21,
    symbol: 'Sc',
    nameEn: 'Scandium',
    atomicMass: '44.95591',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Ar]4s2 3d1',
    electronegativity: '1.36',
    period: 4,
    group: 3,
    displayRow: 4,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 22,
    symbol: 'Ti',
    nameEn: 'Titanium',
    atomicMass: '47.867',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1791',
    electronConfiguration: '[Ar]4s2 3d2',
    electronegativity: '1.54',
    period: 4,
    group: 4,
    displayRow: 4,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 23,
    symbol: 'V',
    nameEn: 'Vanadium',
    atomicMass: '50.9415',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1801',
    electronConfiguration: '[Ar]4s2 3d3',
    electronegativity: '1.63',
    period: 4,
    group: 5,
    displayRow: 4,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 24,
    symbol: 'Cr',
    nameEn: 'Chromium',
    atomicMass: '51.996',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1797',
    electronConfiguration: '[Ar]3d5 4s1',
    electronegativity: '1.66',
    period: 4,
    group: 6,
    displayRow: 4,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 25,
    symbol: 'Mn',
    nameEn: 'Manganese',
    atomicMass: '54.93804',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1774',
    electronConfiguration: '[Ar]4s2 3d5',
    electronegativity: '1.55',
    period: 4,
    group: 7,
    displayRow: 4,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 26,
    symbol: 'Fe',
    nameEn: 'Iron',
    atomicMass: '55.84',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2 3d6',
    electronegativity: '1.83',
    period: 4,
    group: 8,
    displayRow: 4,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 27,
    symbol: 'Co',
    nameEn: 'Cobalt',
    atomicMass: '58.93319',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1735',
    electronConfiguration: '[Ar]4s2 3d7',
    electronegativity: '1.88',
    period: 4,
    group: 9,
    displayRow: 4,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 28,
    symbol: 'Ni',
    nameEn: 'Nickel',
    atomicMass: '58.693',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1751',
    electronConfiguration: '[Ar]4s2 3d8',
    electronegativity: '1.91',
    period: 4,
    group: 10,
    displayRow: 4,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 29,
    symbol: 'Cu',
    nameEn: 'Copper',
    atomicMass: '63.55',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s1 3d10',
    electronegativity: '1.9',
    period: 4,
    group: 11,
    displayRow: 4,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 30,
    symbol: 'Zn',
    nameEn: 'Zinc',
    atomicMass: '65.4',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1746',
    electronConfiguration: '[Ar]4s2 3d10',
    electronegativity: '1.65',
    period: 4,
    group: 12,
    displayRow: 4,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 31,
    symbol: 'Ga',
    nameEn: 'Gallium',
    atomicMass: '69.723',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1875',
    electronConfiguration: '[Ar]4s2 3d10 4p1',
    electronegativity: '1.81',
    period: 4,
    group: 13,
    displayRow: 4,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 32,
    symbol: 'Ge',
    nameEn: 'Germanium',
    atomicMass: '72.63',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1886',
    electronConfiguration: '[Ar]4s2 3d10 4p2',
    electronegativity: '2.01',
    period: 4,
    group: 14,
    displayRow: 4,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 33,
    symbol: 'As',
    nameEn: 'Arsenic',
    atomicMass: '74.92159',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Ar]4s2 3d10 4p3',
    electronegativity: '2.18',
    period: 4,
    group: 15,
    displayRow: 4,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 34,
    symbol: 'Se',
    nameEn: 'Selenium',
    atomicMass: '78.97',
    groupBlock: 'Nonmetal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[Ar]4s2 3d10 4p4',
    electronegativity: '2.55',
    period: 4,
    group: 16,
    displayRow: 4,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 35,
    symbol: 'Br',
    nameEn: 'Bromine',
    atomicMass: '79.90',
    groupBlock: 'Halogen',
    standardState: 'Liquid',
    yearDiscovered: '1826',
    electronConfiguration: '[Ar]4s2 3d10 4p5',
    electronegativity: '2.96',
    period: 4,
    group: 17,
    displayRow: 4,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 36,
    symbol: 'Kr',
    nameEn: 'Krypton',
    atomicMass: '83.80',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[Ar]4s2 3d10 4p6',
    electronegativity: '3',
    period: 4,
    group: 18,
    displayRow: 4,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 37,
    symbol: 'Rb',
    nameEn: 'Rubidium',
    atomicMass: '85.468',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1861',
    electronConfiguration: '[Kr]5s1',
    electronegativity: '0.82',
    period: 5,
    group: 1,
    displayRow: 5,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 38,
    symbol: 'Sr',
    nameEn: 'Strontium',
    atomicMass: '87.62',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1790',
    electronConfiguration: '[Kr]5s2',
    electronegativity: '0.95',
    period: 5,
    group: 2,
    displayRow: 5,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 39,
    symbol: 'Y',
    nameEn: 'Yttrium',
    atomicMass: '88.90584',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1794',
    electronConfiguration: '[Kr]5s2 4d1',
    electronegativity: '1.22',
    period: 5,
    group: 3,
    displayRow: 5,
    displayColumn: 3,
  ),
  _ElementFact(
    atomicNumber: 40,
    symbol: 'Zr',
    nameEn: 'Zirconium',
    atomicMass: '91.22',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1789',
    electronConfiguration: '[Kr]5s2 4d2',
    electronegativity: '1.33',
    period: 5,
    group: 4,
    displayRow: 5,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 41,
    symbol: 'Nb',
    nameEn: 'Niobium',
    atomicMass: '92.90637',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1801',
    electronConfiguration: '[Kr]5s1 4d4',
    electronegativity: '1.6',
    period: 5,
    group: 5,
    displayRow: 5,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 42,
    symbol: 'Mo',
    nameEn: 'Molybdenum',
    atomicMass: '95.95',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1778',
    electronConfiguration: '[Kr]5s1 4d5',
    electronegativity: '2.16',
    period: 5,
    group: 6,
    displayRow: 5,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 43,
    symbol: 'Tc',
    nameEn: 'Technetium',
    atomicMass: '96.90636',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1937',
    electronConfiguration: '[Kr]5s2 4d5',
    electronegativity: '1.9',
    period: 5,
    group: 7,
    displayRow: 5,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 44,
    symbol: 'Ru',
    nameEn: 'Ruthenium',
    atomicMass: '101.1',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1827',
    electronConfiguration: '[Kr]5s1 4d7',
    electronegativity: '2.2',
    period: 5,
    group: 8,
    displayRow: 5,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 45,
    symbol: 'Rh',
    nameEn: 'Rhodium',
    atomicMass: '102.9055',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Kr]5s1 4d8',
    electronegativity: '2.28',
    period: 5,
    group: 9,
    displayRow: 5,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 46,
    symbol: 'Pd',
    nameEn: 'Palladium',
    atomicMass: '106.42',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Kr]4d10',
    electronegativity: '2.2',
    period: 5,
    group: 10,
    displayRow: 5,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 47,
    symbol: 'Ag',
    nameEn: 'Silver',
    atomicMass: '107.868',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s1 4d10',
    electronegativity: '1.93',
    period: 5,
    group: 11,
    displayRow: 5,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 48,
    symbol: 'Cd',
    nameEn: 'Cadmium',
    atomicMass: '112.41',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1817',
    electronConfiguration: '[Kr]5s2 4d10',
    electronegativity: '1.69',
    period: 5,
    group: 12,
    displayRow: 5,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 49,
    symbol: 'In',
    nameEn: 'Indium',
    atomicMass: '114.818',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1863',
    electronConfiguration: '[Kr]5s2 4d10 5p1',
    electronegativity: '1.78',
    period: 5,
    group: 13,
    displayRow: 5,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 50,
    symbol: 'Sn',
    nameEn: 'Tin',
    atomicMass: '118.71',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s2 4d10 5p2',
    electronegativity: '1.96',
    period: 5,
    group: 14,
    displayRow: 5,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 51,
    symbol: 'Sb',
    nameEn: 'Antimony',
    atomicMass: '121.760',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Kr]5s2 4d10 5p3',
    electronegativity: '2.05',
    period: 5,
    group: 15,
    displayRow: 5,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 52,
    symbol: 'Te',
    nameEn: 'Tellurium',
    atomicMass: '127.6',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1782',
    electronConfiguration: '[Kr]5s2 4d10 5p4',
    electronegativity: '2.1',
    period: 5,
    group: 16,
    displayRow: 5,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 53,
    symbol: 'I',
    nameEn: 'Iodine',
    atomicMass: '126.9045',
    groupBlock: 'Halogen',
    standardState: 'Solid',
    yearDiscovered: '1811',
    electronConfiguration: '[Kr]5s2 4d10 5p5',
    electronegativity: '2.66',
    period: 5,
    group: 17,
    displayRow: 5,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 54,
    symbol: 'Xe',
    nameEn: 'Xenon',
    atomicMass: '131.29',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1898',
    electronConfiguration: '[Kr]5s2 4d10 5p6',
    electronegativity: '2.6',
    period: 5,
    group: 18,
    displayRow: 5,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 55,
    symbol: 'Cs',
    nameEn: 'Cesium',
    atomicMass: '132.9054520',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1860',
    electronConfiguration: '[Xe]6s1',
    electronegativity: '0.79',
    period: 6,
    group: 1,
    displayRow: 6,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 56,
    symbol: 'Ba',
    nameEn: 'Barium',
    atomicMass: '137.33',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1808',
    electronConfiguration: '[Xe]6s2',
    electronegativity: '0.89',
    period: 6,
    group: 2,
    displayRow: 6,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 57,
    symbol: 'La',
    nameEn: 'Lanthanum',
    atomicMass: '138.9055',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1839',
    electronConfiguration: '[Xe]6s2 5d1',
    electronegativity: '1.1',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 58,
    symbol: 'Ce',
    nameEn: 'Cerium',
    atomicMass: '140.116',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f1 5d1',
    electronegativity: '1.12',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 59,
    symbol: 'Pr',
    nameEn: 'Praseodymium',
    atomicMass: '140.90766',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1885',
    electronConfiguration: '[Xe]6s2 4f3',
    electronegativity: '1.13',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 60,
    symbol: 'Nd',
    nameEn: 'Neodymium',
    atomicMass: '144.24',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1885',
    electronConfiguration: '[Xe]6s2 4f4',
    electronegativity: '1.14',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 61,
    symbol: 'Pm',
    nameEn: 'Promethium',
    atomicMass: '144.91276',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1945',
    electronConfiguration: '[Xe]6s2 4f5',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 62,
    symbol: 'Sm',
    nameEn: 'Samarium',
    atomicMass: '150.4',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Xe]6s2 4f6',
    electronegativity: '1.17',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 63,
    symbol: 'Eu',
    nameEn: 'Europium',
    atomicMass: '151.964',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1901',
    electronConfiguration: '[Xe]6s2 4f7',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 64,
    symbol: 'Gd',
    nameEn: 'Gadolinium',
    atomicMass: '157.25',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1880',
    electronConfiguration: '[Xe]6s2 4f7 5d1',
    electronegativity: '1.2',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 65,
    symbol: 'Tb',
    nameEn: 'Terbium',
    atomicMass: '158.92535',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1843',
    electronConfiguration: '[Xe]6s2 4f9',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 66,
    symbol: 'Dy',
    nameEn: 'Dysprosium',
    atomicMass: '162.500',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1886',
    electronConfiguration: '[Xe]6s2 4f10',
    electronegativity: '1.22',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 67,
    symbol: 'Ho',
    nameEn: 'Holmium',
    atomicMass: '164.93033',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1878',
    electronConfiguration: '[Xe]6s2 4f11',
    electronegativity: '1.23',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 68,
    symbol: 'Er',
    nameEn: 'Erbium',
    atomicMass: '167.26',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1843',
    electronConfiguration: '[Xe]6s2 4f12',
    electronegativity: '1.24',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 69,
    symbol: 'Tm',
    nameEn: 'Thulium',
    atomicMass: '168.93422',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1879',
    electronConfiguration: '[Xe]6s2 4f13',
    electronegativity: '1.25',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 70,
    symbol: 'Yb',
    nameEn: 'Ytterbium',
    atomicMass: '173.05',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1878',
    electronConfiguration: '[Xe]6s2 4f14',
    electronegativity: '',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 71,
    symbol: 'Lu',
    nameEn: 'Lutetium',
    atomicMass: '174.9667',
    groupBlock: 'Lanthanide',
    standardState: 'Solid',
    yearDiscovered: '1907',
    electronConfiguration: '[Xe]6s2 4f14 5d1',
    electronegativity: '1.27',
    period: 6,
    group: 3,
    displayRow: 8,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 72,
    symbol: 'Hf',
    nameEn: 'Hafnium',
    atomicMass: '178.49',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1923',
    electronConfiguration: '[Xe]6s2 4f14 5d2',
    electronegativity: '1.3',
    period: 6,
    group: 4,
    displayRow: 6,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 73,
    symbol: 'Ta',
    nameEn: 'Tantalum',
    atomicMass: '180.9479',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1802',
    electronConfiguration: '[Xe]6s2 4f14 5d3',
    electronegativity: '1.5',
    period: 6,
    group: 5,
    displayRow: 6,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 74,
    symbol: 'W',
    nameEn: 'Tungsten',
    atomicMass: '183.84',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1783',
    electronConfiguration: '[Xe]6s2 4f14 5d4',
    electronegativity: '2.36',
    period: 6,
    group: 6,
    displayRow: 6,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 75,
    symbol: 'Re',
    nameEn: 'Rhenium',
    atomicMass: '186.207',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1925',
    electronConfiguration: '[Xe]6s2 4f14 5d5',
    electronegativity: '1.9',
    period: 6,
    group: 7,
    displayRow: 6,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 76,
    symbol: 'Os',
    nameEn: 'Osmium',
    atomicMass: '190.2',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f14 5d6',
    electronegativity: '2.2',
    period: 6,
    group: 8,
    displayRow: 6,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 77,
    symbol: 'Ir',
    nameEn: 'Iridium',
    atomicMass: '192.22',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1803',
    electronConfiguration: '[Xe]6s2 4f14 5d7',
    electronegativity: '2.2',
    period: 6,
    group: 9,
    displayRow: 6,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 78,
    symbol: 'Pt',
    nameEn: 'Platinum',
    atomicMass: '195.08',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1735',
    electronConfiguration: '[Xe]6s1 4f14 5d9',
    electronegativity: '2.28',
    period: 6,
    group: 10,
    displayRow: 6,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 79,
    symbol: 'Au',
    nameEn: 'Gold',
    atomicMass: '196.96657',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s1 4f14 5d10',
    electronegativity: '2.54',
    period: 6,
    group: 11,
    displayRow: 6,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 80,
    symbol: 'Hg',
    nameEn: 'Mercury',
    atomicMass: '200.59',
    groupBlock: 'Transition metal',
    standardState: 'Liquid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s2 4f14 5d10',
    electronegativity: '2',
    period: 6,
    group: 12,
    displayRow: 6,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 81,
    symbol: 'Tl',
    nameEn: 'Thallium',
    atomicMass: '204.383',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1861',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p1',
    electronegativity: '1.62',
    period: 6,
    group: 13,
    displayRow: 6,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 82,
    symbol: 'Pb',
    nameEn: 'Lead',
    atomicMass: '207',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: 'Ancient',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p2',
    electronegativity: '2.33',
    period: 6,
    group: 14,
    displayRow: 6,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 83,
    symbol: 'Bi',
    nameEn: 'Bismuth',
    atomicMass: '208.98040',
    groupBlock: 'Post-transition metal',
    standardState: 'Solid',
    yearDiscovered: '1753',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p3',
    electronegativity: '2.02',
    period: 6,
    group: 15,
    displayRow: 6,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 84,
    symbol: 'Po',
    nameEn: 'Polonium',
    atomicMass: '208.98243',
    groupBlock: 'Metalloid',
    standardState: 'Solid',
    yearDiscovered: '1898',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p4',
    electronegativity: '2',
    period: 6,
    group: 16,
    displayRow: 6,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 85,
    symbol: 'At',
    nameEn: 'Astatine',
    atomicMass: '209.98715',
    groupBlock: 'Halogen',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p5',
    electronegativity: '2.2',
    period: 6,
    group: 17,
    displayRow: 6,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 86,
    symbol: 'Rn',
    nameEn: 'Radon',
    atomicMass: '222.01758',
    groupBlock: 'Noble gas',
    standardState: 'Gas',
    yearDiscovered: '1900',
    electronConfiguration: '[Xe]6s2 4f14 5d10 6p6',
    electronegativity: '',
    period: 6,
    group: 18,
    displayRow: 6,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 87,
    symbol: 'Fr',
    nameEn: 'Francium',
    atomicMass: '223.01973',
    groupBlock: 'Alkali metal',
    standardState: 'Solid',
    yearDiscovered: '1939',
    electronConfiguration: '[Rn]7s1',
    electronegativity: '0.7',
    period: 7,
    group: 1,
    displayRow: 7,
    displayColumn: 1,
  ),
  _ElementFact(
    atomicNumber: 88,
    symbol: 'Ra',
    nameEn: 'Radium',
    atomicMass: '226.02541',
    groupBlock: 'Alkaline earth metal',
    standardState: 'Solid',
    yearDiscovered: '1898',
    electronConfiguration: '[Rn]7s2',
    electronegativity: '0.9',
    period: 7,
    group: 2,
    displayRow: 7,
    displayColumn: 2,
  ),
  _ElementFact(
    atomicNumber: 89,
    symbol: 'Ac',
    nameEn: 'Actinium',
    atomicMass: '227.02775',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1899',
    electronConfiguration: '[Rn]7s2 6d1',
    electronegativity: '1.1',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 90,
    symbol: 'Th',
    nameEn: 'Thorium',
    atomicMass: '232.038',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1828',
    electronConfiguration: '[Rn]7s2 6d2',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 91,
    symbol: 'Pa',
    nameEn: 'Protactinium',
    atomicMass: '231.03588',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1913',
    electronConfiguration: '[Rn]7s2 5f2 6d1',
    electronegativity: '1.5',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 92,
    symbol: 'U',
    nameEn: 'Uranium',
    atomicMass: '238.0289',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1789',
    electronConfiguration: '[Rn]7s2 5f3 6d1',
    electronegativity: '1.38',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 93,
    symbol: 'Np',
    nameEn: 'Neptunium',
    atomicMass: '237.048172',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Rn]7s2 5f4 6d1',
    electronegativity: '1.36',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 94,
    symbol: 'Pu',
    nameEn: 'Plutonium',
    atomicMass: '244.06420',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1940',
    electronConfiguration: '[Rn]7s2 5f6',
    electronegativity: '1.28',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 95,
    symbol: 'Am',
    nameEn: 'Americium',
    atomicMass: '243.061380',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1944',
    electronConfiguration: '[Rn]7s2 5f7',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 96,
    symbol: 'Cm',
    nameEn: 'Curium',
    atomicMass: '247.07035',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1944',
    electronConfiguration: '[Rn]7s2 5f7 6d1',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 97,
    symbol: 'Bk',
    nameEn: 'Berkelium',
    atomicMass: '247.07031',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1949',
    electronConfiguration: '[Rn]7s2 5f9',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 98,
    symbol: 'Cf',
    nameEn: 'Californium',
    atomicMass: '251.07959',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1950',
    electronConfiguration: '[Rn]7s2 5f10',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 99,
    symbol: 'Es',
    nameEn: 'Einsteinium',
    atomicMass: '252.0830',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1952',
    electronConfiguration: '[Rn]7s2 5f11',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 100,
    symbol: 'Fm',
    nameEn: 'Fermium',
    atomicMass: '257.09511',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1952',
    electronConfiguration: '[Rn] 5f12 7s2',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 101,
    symbol: 'Md',
    nameEn: 'Mendelevium',
    atomicMass: '258.09843',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1955',
    electronConfiguration: '[Rn]7s2 5f13',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 102,
    symbol: 'No',
    nameEn: 'Nobelium',
    atomicMass: '259.10100',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1957',
    electronConfiguration: '[Rn]7s2 5f14',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 103,
    symbol: 'Lr',
    nameEn: 'Lawrencium',
    atomicMass: '266.120',
    groupBlock: 'Actinide',
    standardState: 'Solid',
    yearDiscovered: '1961',
    electronConfiguration: '[Rn]7s2 5f14 6d1',
    electronegativity: '1.3',
    period: 7,
    group: 3,
    displayRow: 9,
    displayColumn: 18,
  ),
  _ElementFact(
    atomicNumber: 104,
    symbol: 'Rf',
    nameEn: 'Rutherfordium',
    atomicMass: '267.122',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1964',
    electronConfiguration: '[Rn]7s2 5f14 6d2',
    electronegativity: '',
    period: 7,
    group: 4,
    displayRow: 7,
    displayColumn: 4,
  ),
  _ElementFact(
    atomicNumber: 105,
    symbol: 'Db',
    nameEn: 'Dubnium',
    atomicMass: '268.126',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1967',
    electronConfiguration: '[Rn]7s2 5f14 6d3',
    electronegativity: '',
    period: 7,
    group: 5,
    displayRow: 7,
    displayColumn: 5,
  ),
  _ElementFact(
    atomicNumber: 106,
    symbol: 'Sg',
    nameEn: 'Seaborgium',
    atomicMass: '269.128',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1974',
    electronConfiguration: '[Rn]7s2 5f14 6d4',
    electronegativity: '',
    period: 7,
    group: 6,
    displayRow: 7,
    displayColumn: 6,
  ),
  _ElementFact(
    atomicNumber: 107,
    symbol: 'Bh',
    nameEn: 'Bohrium',
    atomicMass: '270.133',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1976',
    electronConfiguration: '[Rn]7s2 5f14 6d5',
    electronegativity: '',
    period: 7,
    group: 7,
    displayRow: 7,
    displayColumn: 7,
  ),
  _ElementFact(
    atomicNumber: 108,
    symbol: 'Hs',
    nameEn: 'Hassium',
    atomicMass: '269.1336',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1984',
    electronConfiguration: '[Rn]7s2 5f14 6d6',
    electronegativity: '',
    period: 7,
    group: 8,
    displayRow: 7,
    displayColumn: 8,
  ),
  _ElementFact(
    atomicNumber: 109,
    symbol: 'Mt',
    nameEn: 'Meitnerium',
    atomicMass: '277.154',
    groupBlock: 'Transition metal',
    standardState: 'Solid',
    yearDiscovered: '1982',
    electronConfiguration: '[Rn]7s2 5f14 6d7 (calculated)',
    electronegativity: '',
    period: 7,
    group: 9,
    displayRow: 7,
    displayColumn: 9,
  ),
  _ElementFact(
    atomicNumber: 110,
    symbol: 'Ds',
    nameEn: 'Darmstadtium',
    atomicMass: '282.166',
    groupBlock: 'Transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1994',
    electronConfiguration: '[Rn]7s2 5f14 6d8 (predicted)',
    electronegativity: '',
    period: 7,
    group: 10,
    displayRow: 7,
    displayColumn: 10,
  ),
  _ElementFact(
    atomicNumber: 111,
    symbol: 'Rg',
    nameEn: 'Roentgenium',
    atomicMass: '282.169',
    groupBlock: 'Transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1994',
    electronConfiguration: '[Rn]7s2 5f14 6d9 (predicted)',
    electronegativity: '',
    period: 7,
    group: 11,
    displayRow: 7,
    displayColumn: 11,
  ),
  _ElementFact(
    atomicNumber: 112,
    symbol: 'Cn',
    nameEn: 'Copernicium',
    atomicMass: '286.179',
    groupBlock: 'Transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1996',
    electronConfiguration: '[Rn]7s2 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 12,
    displayRow: 7,
    displayColumn: 12,
  ),
  _ElementFact(
    atomicNumber: 113,
    symbol: 'Nh',
    nameEn: 'Nihonium',
    atomicMass: '286.182',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2004',
    electronConfiguration: '[Rn]5f14 6d10 7s2 7p1 (predicted)',
    electronegativity: '',
    period: 7,
    group: 13,
    displayRow: 7,
    displayColumn: 13,
  ),
  _ElementFact(
    atomicNumber: 114,
    symbol: 'Fl',
    nameEn: 'Flerovium',
    atomicMass: '290.192',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '1998',
    electronConfiguration: '[Rn]7s2 7p2 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 14,
    displayRow: 7,
    displayColumn: 14,
  ),
  _ElementFact(
    atomicNumber: 115,
    symbol: 'Mc',
    nameEn: 'Moscovium',
    atomicMass: '290.196',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2003',
    electronConfiguration: '[Rn]7s2 7p3 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 15,
    displayRow: 7,
    displayColumn: 15,
  ),
  _ElementFact(
    atomicNumber: 116,
    symbol: 'Lv',
    nameEn: 'Livermorium',
    atomicMass: '293.205',
    groupBlock: 'Post-transition metal',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2000',
    electronConfiguration: '[Rn]7s2 7p4 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 16,
    displayRow: 7,
    displayColumn: 16,
  ),
  _ElementFact(
    atomicNumber: 117,
    symbol: 'Ts',
    nameEn: 'Tennessine',
    atomicMass: '294.211',
    groupBlock: 'Halogen',
    standardState: 'Expected to be a Solid',
    yearDiscovered: '2010',
    electronConfiguration: '[Rn]7s2 7p5 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 17,
    displayRow: 7,
    displayColumn: 17,
  ),
  _ElementFact(
    atomicNumber: 118,
    symbol: 'Og',
    nameEn: 'Oganesson',
    atomicMass: '295.216',
    groupBlock: 'Noble gas',
    standardState: 'Expected to be a Gas',
    yearDiscovered: '2006',
    electronConfiguration: '[Rn]7s2 7p6 5f14 6d10 (predicted)',
    electronegativity: '',
    period: 7,
    group: 18,
    displayRow: 7,
    displayColumn: 18,
  ),
];

const List<_LifeToolSource> _timelinePeriodicSources = <_LifeToolSource>[
  _LifeToolSource(
    name: 'PubChem PUG REST periodic table',
    url: 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON',
    copyrightNote:
        'Element facts: atomic number, symbol, atomic mass, group block, state, configuration, electronegativity, and discovery year.',
  ),
  _LifeToolSource(
    name: 'IUPAC Periodic Table of Elements',
    url: 'https://iupac.org/what-we-do/periodic-table-of-elements/',
    copyrightNote: 'Authoritative periodic-table naming and element reference.',
  ),
  _LifeToolSource(
    name: 'CIAAW standard atomic weights',
    url: 'https://ciaaw.org/atomic-weights.htm',
    copyrightNote:
        'Reference body for standard atomic-weight intervals and revisions.',
  ),
  _LifeToolSource(
    name: 'International Chronostratigraphic Chart',
    url: 'https://stratigraphy.org/chart',
    copyrightNote: 'Geologic-period anchor dates.',
  ),
  _LifeToolSource(
    name: 'NASA Science',
    url: 'https://science.nasa.gov/',
    copyrightNote: 'Cosmic and space-science anchor dates.',
  ),
  _LifeToolSource(
    name: 'Smithsonian Human Origins Program',
    url: 'https://humanorigins.si.edu/',
    copyrightNote: 'Human-evolution anchor dates.',
  ),
  _LifeToolSource(
    name: 'Encyclopaedia Britannica',
    url: 'https://www.britannica.com/',
    copyrightNote: 'Civilization and science-history cross-checks.',
  ),
  _LifeToolSource(
    name: 'NASA Image Library media',
    url: 'https://images.nasa.gov/',
    copyrightNote:
        'Remote atmosphere images for cosmic and science timeline backdrops.',
  ),
  _LifeToolSource(
    name: 'USGS public-domain geology media',
    url: 'https://www.usgs.gov/media/images/basalt-rock-photograph',
    copyrightNote: 'Rock/geology backdrop reference.',
  ),
  _LifeToolSource(
    name: 'Wikimedia Commons public-domain artifacts',
    url: 'https://commons.wikimedia.org/wiki/File:The_Rosetta_Stone.jpg',
    copyrightNote: 'Artifact backdrop reference.',
  ),
];
