part of 'toolbox_human_tests.dart';

const List<_TypingPassage> _typingPassages = <_TypingPassage>[
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.focus,
    zh: '清醒的注意力来自稳定的呼吸、明确的目标和可持续的节奏。',
    en: 'Focused attention comes from steady breathing, a clear goal, and a sustainable rhythm.',
  ),
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.focus,
    zh: '把复杂任务切成几段，手指会更快找到下一个落点。',
    en: 'Split complex work into smaller steps, and your hands find the next move faster.',
  ),
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.sleep,
    zh: '今晚把单词放慢一点，记忆会在安静的间隔里留下痕迹。',
    en: 'Slow the words down tonight, and memory will leave traces in the quiet gaps.',
  ),
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.tech,
    zh: '专业的输入训练不只看速度，也看错误密度、回退次数和稳定性。',
    en: 'Professional typing practice measures speed, error density, corrections, and stability.',
  ),
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.story,
    zh: '窗外的灯光慢慢亮起，纸上的句子像小船一样靠岸。',
    en: 'Lights rose outside the window, and the sentence on paper drifted gently ashore.',
  ),
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.vocabulary,
    zh: '遇到生词时先读完整句，再把意思、声音和场景一起存进记忆。',
    en: 'Read the whole sentence first, then store meaning, sound, and scene together.',
  ),
  _TypingPassage(
    language: _TypingLanguage.zh,
    topic: _TypingTopic.travel,
    zh: '清晨的车站正在苏醒，背包里的路线图被折成整齐的小方块。',
    en: 'The morning station woke up while the map folded into neat squares.',
  ),
  _TypingPassage(
    language: _TypingLanguage.en,
    topic: _TypingTopic.focus,
    zh: 'A calm mind can move quickly without feeling rushed.',
    en: 'A calm mind can move quickly without feeling rushed.',
  ),
  _TypingPassage(
    language: _TypingLanguage.en,
    topic: _TypingTopic.sleep,
    zh: 'Memory improves when attention has a gentle rhythm.',
    en: 'Memory improves when attention has a gentle rhythm.',
  ),
  _TypingPassage(
    language: _TypingLanguage.en,
    topic: _TypingTopic.tech,
    zh: 'Clean code keeps fast ideas from becoming expensive noise.',
    en: 'Clean code keeps fast ideas from becoming expensive noise.',
  ),
  _TypingPassage(
    language: _TypingLanguage.en,
    topic: _TypingTopic.story,
    zh: 'The quiet station clock counted every suitcase and every goodbye.',
    en: 'The quiet station clock counted every suitcase and every goodbye.',
  ),
  _TypingPassage(
    language: _TypingLanguage.en,
    topic: _TypingTopic.vocabulary,
    zh: 'A useful word becomes stronger each time it appears in a new context.',
    en: 'A useful word becomes stronger each time it appears in a new context.',
  ),
  _TypingPassage(
    language: _TypingLanguage.en,
    topic: _TypingTopic.travel,
    zh: 'The train crossed the river just as the city opened its windows.',
    en: 'The train crossed the river just as the city opened its windows.',
  ),
  _TypingPassage(
    language: _TypingLanguage.mixed,
    topic: _TypingTopic.focus,
    zh: 'Focus 25 minutes, rest 5 minutes, then review one small win.',
    en: 'Focus 25 minutes, rest 5 minutes, then review one small win.',
  ),
  _TypingPassage(
    language: _TypingLanguage.mixed,
    topic: _TypingTopic.tech,
    zh: 'Flutter widget tree: state first, layout second, polish last.',
    en: 'Flutter widget tree: state first, layout second, polish last.',
  ),
  _TypingPassage(
    language: _TypingLanguage.mixed,
    topic: _TypingTopic.sleep,
    zh: 'Sleep mode: dim light, soft voice, zero pressure.',
    en: 'Sleep mode: dim light, soft voice, zero pressure.',
  ),
  _TypingPassage(
    language: _TypingLanguage.mixed,
    topic: _TypingTopic.story,
    zh: 'The note said: 明天见, and the platform became quiet again.',
    en: 'The note said: see you tomorrow, and the platform became quiet again.',
  ),
  _TypingPassage(
    language: _TypingLanguage.mixed,
    topic: _TypingTopic.vocabulary,
    zh: 'Review "steady", 复习「稳定」, then use both in one sentence.',
    en: 'Review "steady", then use both languages in one sentence.',
  ),
  _TypingPassage(
    language: _TypingLanguage.mixed,
    topic: _TypingTopic.travel,
    zh: 'Gate B12 opens at 08:40, 行李放左侧, coffee stays sealed.',
    en: 'Gate B12 opens at 08:40, keep luggage left, coffee sealed.',
  ),
  _TypingPassage(
    language: _TypingLanguage.ja,
    topic: _TypingTopic.focus,
    zh: '静かな集中は、短い休憩と小さな確認から生まれる。',
    en: 'Quiet focus grows from short breaks and small checks.',
    ja: '静かな集中は、短い休憩と小さな確認から生まれる。',
  ),
  _TypingPassage(
    language: _TypingLanguage.ja,
    topic: _TypingTopic.sleep,
    zh: '夜の単語はゆっくり読み、朝にもう一度思い出す。',
    en: 'Read the night words slowly and recall them again in the morning.',
    ja: '夜の単語はゆっくり読み、朝にもう一度思い出す。',
  ),
  _TypingPassage(
    language: _TypingLanguage.ja,
    topic: _TypingTopic.tech,
    zh: '小さな関数は、あとで読む人への親切な案内になる。',
    en: 'Small functions become kind guides for the next reader.',
    ja: '小さな関数は、あとで読む人への親切な案内になる。',
  ),
  _TypingPassage(
    language: _TypingLanguage.ja,
    topic: _TypingTopic.story,
    zh: '雨の駅で、古い切符だけが旅の続きを覚えていた。',
    en: 'At the rainy station, only the old ticket remembered the journey.',
    ja: '雨の駅で、古い切符だけが旅の続きを覚えていた。',
  ),
  _TypingPassage(
    language: _TypingLanguage.ja,
    topic: _TypingTopic.vocabulary,
    zh: '新しい言葉は、例文の中で少しずつ自分の形になる。',
    en: 'New words slowly take shape inside example sentences.',
    ja: '新しい言葉は、例文の中で少しずつ自分の形になる。',
  ),
  _TypingPassage(
    language: _TypingLanguage.ja,
    topic: _TypingTopic.travel,
    zh: '港の朝、白い船が静かにロープをほどいて出発した。',
    en: 'In the harbor morning, a white ship quietly untied and left.',
    ja: '港の朝、白い船が静かにロープをほどいて出発した。',
  ),
  _TypingPassage(
    language: _TypingLanguage.es,
    topic: _TypingTopic.focus,
    zh: 'La mente clara avanza mejor cuando cada tarea tiene un borde visible.',
    en: 'A clear mind moves better when each task has a visible edge.',
    es: 'La mente clara avanza mejor cuando cada tarea tiene un borde visible.',
  ),
  _TypingPassage(
    language: _TypingLanguage.es,
    topic: _TypingTopic.sleep,
    zh: 'Antes de dormir, una frase lenta puede ordenar todo el día.',
    en: 'Before sleep, one slow sentence can put the whole day in order.',
    es: 'Antes de dormir, una frase lenta puede ordenar todo el día.',
  ),
  _TypingPassage(
    language: _TypingLanguage.es,
    topic: _TypingTopic.tech,
    zh: 'Un buen registro explica el fallo sin llenar la pantalla de ruido.',
    en: 'A good log explains the failure without filling the screen with noise.',
    es: 'Un buen registro explica el fallo sin llenar la pantalla de ruido.',
  ),
  _TypingPassage(
    language: _TypingLanguage.es,
    topic: _TypingTopic.story,
    zh: 'La plaza quedó vacía, pero la música siguió doblando la esquina.',
    en: 'The square was empty, but the music kept turning the corner.',
    es: 'La plaza quedó vacía, pero la música siguió doblando la esquina.',
  ),
  _TypingPassage(
    language: _TypingLanguage.es,
    topic: _TypingTopic.vocabulary,
    zh: 'Una palabra nueva necesita sonido, imagen y uso para quedarse.',
    en: 'A new word needs sound, image, and use before it stays.',
    es: 'Una palabra nueva necesita sonido, imagen y uso para quedarse.',
  ),
  _TypingPassage(
    language: _TypingLanguage.es,
    topic: _TypingTopic.travel,
    zh: 'El tren salió temprano y dejó una línea dorada sobre el río.',
    en: 'The train left early and drew a golden line over the river.',
    es: 'El tren salió temprano y dejó una línea dorada sobre el río.',
  ),
];
