part of 'toolbox_human_tests.dart';

const List<_VerbalMemoryDomain> _verbalMemoryDomainOrder =
    <_VerbalMemoryDomain>[
      _VerbalMemoryDomain.fruits,
      _VerbalMemoryDomain.environment,
      _VerbalMemoryDomain.nature,
      _VerbalMemoryDomain.food,
      _VerbalMemoryDomain.travel,
      _VerbalMemoryDomain.technology,
      _VerbalMemoryDomain.home,
      _VerbalMemoryDomain.office,
      _VerbalMemoryDomain.weather,
      _VerbalMemoryDomain.animals,
    ];

const Map<_VerbalMemoryDomain, _VerbalMemoryDomainSpec>
_verbalMemoryDomainSpecs = <_VerbalMemoryDomain, _VerbalMemoryDomainSpec>{
  _VerbalMemoryDomain.fruits: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.fruits,
    zh: '水果',
    en: 'Fruits',
    ja: '果物',
    de: 'Obst',
    fr: 'Fruits',
    es: 'Frutas',
    ru: 'Фрукты',
    accent: Color(0xFFD38A35),
  ),
  _VerbalMemoryDomain.environment: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.environment,
    zh: '环境',
    en: 'Environment',
    ja: '環境',
    de: 'Umgebung',
    fr: 'Environnement',
    es: 'Entorno',
    ru: 'Среда',
    accent: Color(0xFF4D8C7B),
  ),
  _VerbalMemoryDomain.nature: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.nature,
    zh: '自然',
    en: 'Nature',
    ja: '自然',
    de: 'Natur',
    fr: 'Nature',
    es: 'Naturaleza',
    ru: 'Природа',
    accent: Color(0xFF6C8D42),
  ),
  _VerbalMemoryDomain.food: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.food,
    zh: '食物',
    en: 'Food',
    ja: '食べ物',
    de: 'Essen',
    fr: 'Nourriture',
    es: 'Comida',
    ru: 'Еда',
    accent: Color(0xFFC56C45),
  ),
  _VerbalMemoryDomain.travel: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.travel,
    zh: '旅行',
    en: 'Travel',
    ja: '旅行',
    de: 'Reise',
    fr: 'Voyage',
    es: 'Viaje',
    ru: 'Путешествия',
    accent: Color(0xFF4C83B8),
  ),
  _VerbalMemoryDomain.technology: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.technology,
    zh: '科技',
    en: 'Technology',
    ja: 'テクノロジー',
    de: 'Technik',
    fr: 'Technologie',
    es: 'Tecnología',
    ru: 'Технологии',
    accent: Color(0xFF5C68B8),
  ),
  _VerbalMemoryDomain.home: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.home,
    zh: '居家',
    en: 'Home',
    ja: '家',
    de: 'Zuhause',
    fr: 'Maison',
    es: 'Casa',
    ru: 'Дом',
    accent: Color(0xFF8A6849),
  ),
  _VerbalMemoryDomain.office: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.office,
    zh: '办公',
    en: 'Office',
    ja: 'オフィス',
    de: 'Büro',
    fr: 'Bureau',
    es: 'Oficina',
    ru: 'Офис',
    accent: Color(0xFF697282),
  ),
  _VerbalMemoryDomain.weather: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.weather,
    zh: '天气',
    en: 'Weather',
    ja: '天気',
    de: 'Wetter',
    fr: 'Météo',
    es: 'Clima',
    ru: 'Погода',
    accent: Color(0xFF4A9CB4),
  ),
  _VerbalMemoryDomain.animals: _VerbalMemoryDomainSpec(
    domain: _VerbalMemoryDomain.animals,
    zh: '动物',
    en: 'Animals',
    ja: '動物',
    de: 'Tiere',
    fr: 'Animaux',
    es: 'Animales',
    ru: 'Животные',
    accent: Color(0xFFC05B74),
  ),
};

const List<_VerbalMemoryWordSpec> _verbalMemoryWordBank =
    <_VerbalMemoryWordSpec>[
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '苹果',
        en: 'apple',
        ja: 'りんご',
        de: 'Apfel',
        fr: 'pomme',
        es: 'manzana',
        ru: 'яблоко',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '香蕉',
        en: 'banana',
        ja: 'バナナ',
        de: 'Banane',
        fr: 'banane',
        es: 'banana',
        ru: 'банан',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '橙子',
        en: 'orange',
        ja: 'オレンジ',
        de: 'Orange',
        fr: 'orange',
        es: 'naranja',
        ru: 'апельсин',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '梨子',
        en: 'pear',
        ja: '梨',
        de: 'Birne',
        fr: 'poire',
        es: 'pera',
        ru: 'груша',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '葡萄',
        en: 'grape',
        ja: 'ぶどう',
        de: 'Traube',
        fr: 'raisin',
        es: 'uva',
        ru: 'виноград',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '芒果',
        en: 'mango',
        ja: 'マンゴー',
        de: 'Mango',
        fr: 'mangue',
        es: 'mango',
        ru: 'манго',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '桃子',
        en: 'peach',
        ja: '桃',
        de: 'Pfirsich',
        fr: 'pêche',
        es: 'melocotón',
        ru: 'персик',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '柠檬',
        en: 'lemon',
        ja: 'レモン',
        de: 'Zitrone',
        fr: 'citron',
        es: 'limón',
        ru: 'лимон',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '樱桃',
        en: 'cherry',
        ja: 'さくらんぼ',
        de: 'Kirsche',
        fr: 'cerise',
        es: 'cereza',
        ru: 'вишня',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.fruits,
        zh: '李子',
        en: 'plum',
        ja: 'すもも',
        de: 'Pflaume',
        fr: 'prune',
        es: 'ciruela',
        ru: 'слива',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '森林',
        en: 'forest',
        ja: '森',
        de: 'Wald',
        fr: 'forêt',
        es: 'bosque',
        ru: 'лес',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '河流',
        en: 'river',
        ja: '川',
        de: 'Fluss',
        fr: 'rivière',
        es: 'río',
        ru: 'река',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '山脉',
        en: 'mountain',
        ja: '山',
        de: 'Berg',
        fr: 'montagne',
        es: 'montaña',
        ru: 'гора',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '山谷',
        en: 'valley',
        ja: '谷',
        de: 'Tal',
        fr: 'vallée',
        es: 'valle',
        ru: 'долина',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '港湾',
        en: 'harbor',
        ja: '港',
        de: 'Hafen',
        fr: 'port',
        es: 'puerto',
        ru: 'гавань',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '草甸',
        en: 'meadow',
        ja: '草地',
        de: 'Wiese',
        fr: 'prairie',
        es: 'pradera',
        ru: 'луг',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '峡谷',
        en: 'canyon',
        ja: '峡谷',
        de: 'Schlucht',
        fr: 'canyon',
        es: 'cañón',
        ru: 'каньон',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '冰川',
        en: 'glacier',
        ja: '氷河',
        de: 'Gletscher',
        fr: 'glacier',
        es: 'glaciar',
        ru: 'ледник',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '湿地',
        en: 'wetland',
        ja: '湿地',
        de: 'Feuchtgebiet',
        fr: 'zone humide',
        es: 'humedal',
        ru: 'болото',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.environment,
        zh: '极光',
        en: 'aurora',
        ja: 'オーロラ',
        de: 'Polarlicht',
        fr: 'aurore',
        es: 'aurora',
        ru: 'северное сияние',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '叶片',
        en: 'leaf',
        ja: '葉',
        de: 'Blatt',
        fr: 'feuille',
        es: 'hoja',
        ru: 'лист',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '种子',
        en: 'seed',
        ja: '種',
        de: 'Samen',
        fr: 'graine',
        es: 'semilla',
        ru: 'семя',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '苔藓',
        en: 'moss',
        ja: '苔',
        de: 'Moos',
        fr: 'mousse',
        es: 'musgo',
        ru: 'мох',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '石块',
        en: 'stone',
        ja: '石',
        de: 'Stein',
        fr: 'pierre',
        es: 'piedra',
        ru: 'камень',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '云朵',
        en: 'cloud',
        ja: '雲',
        de: 'Wolke',
        fr: 'nuage',
        es: 'nube',
        ru: 'облако',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '黎明',
        en: 'dawn',
        ja: '夜明け',
        de: 'Morgendämmerung',
        fr: 'aube',
        es: 'amanecer',
        ru: 'рассвет',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '黄昏',
        en: 'dusk',
        ja: '夕暮れ',
        de: 'Abenddämmerung',
        fr: 'crépuscule',
        es: 'atardecer',
        ru: 'сумерки',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '潮汐',
        en: 'tide',
        ja: '潮',
        de: 'Gezeiten',
        fr: 'marée',
        es: 'marea',
        ru: 'прилив',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '贝壳',
        en: 'shell',
        ja: '貝殻',
        de: 'Muschel',
        fr: 'coquillage',
        es: 'concha',
        ru: 'ракушка',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.nature,
        zh: '蕨类',
        en: 'fern',
        ja: 'シダ',
        de: 'Farn',
        fr: 'fougère',
        es: 'helecho',
        ru: 'папоротник',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '面条',
        en: 'noodle',
        ja: '麺',
        de: 'Nudel',
        fr: 'nouille',
        es: 'fideo',
        ru: 'лапша',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '饺子',
        en: 'dumpling',
        ja: '餃子',
        de: 'Teigtasche',
        fr: 'ravioli',
        es: 'empanadilla',
        ru: 'пельмень',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '汤品',
        en: 'soup',
        ja: 'スープ',
        de: 'Suppe',
        fr: 'soupe',
        es: 'sopa',
        ru: 'суп',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '面包',
        en: 'bread',
        ja: 'パン',
        de: 'Brot',
        fr: 'pain',
        es: 'pan',
        ru: 'хлеб',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '米饭',
        en: 'rice',
        ja: 'ご飯',
        de: 'Reis',
        fr: 'riz',
        es: 'arroz',
        ru: 'рис',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '奶酪',
        en: 'cheese',
        ja: 'チーズ',
        de: 'Käse',
        fr: 'fromage',
        es: 'queso',
        ru: 'сыр',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '沙拉',
        en: 'salad',
        ja: 'サラダ',
        de: 'Salat',
        fr: 'salade',
        es: 'ensalada',
        ru: 'салат',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '咖喱',
        en: 'curry',
        ja: 'カレー',
        de: 'Curry',
        fr: 'curry',
        es: 'curry',
        ru: 'карри',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '蜂蜜',
        en: 'honey',
        ja: 'はちみつ',
        de: 'Honig',
        fr: 'miel',
        es: 'miel',
        ru: 'мед',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.food,
        zh: '豆腐',
        en: 'tofu',
        ja: '豆腐',
        de: 'Tofu',
        fr: 'tofu',
        es: 'tofu',
        ru: 'тофу',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '车站',
        en: 'station',
        ja: '駅',
        de: 'Bahnhof',
        fr: 'gare',
        es: 'estación',
        ru: 'станция',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '桥梁',
        en: 'bridge',
        ja: '橋',
        de: 'Brücke',
        fr: 'pont',
        es: 'puente',
        ru: 'мост',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '机场',
        en: 'airport',
        ja: '空港',
        de: 'Flughafen',
        fr: 'aéroport',
        es: 'aeropuerto',
        ru: 'аэропорт',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '小径',
        en: 'trail',
        ja: '小道',
        de: 'Pfad',
        fr: 'sentier',
        es: 'sendero',
        ru: 'тропа',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '行李箱',
        en: 'suitcase',
        ja: 'スーツケース',
        de: 'Koffer',
        fr: 'valise',
        es: 'maleta',
        ru: 'чемодан',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '路线',
        en: 'route',
        ja: 'ルート',
        de: 'Route',
        fr: 'itinéraire',
        es: 'ruta',
        ru: 'маршрут',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '指南针',
        en: 'compass',
        ja: 'コンパス',
        de: 'Kompass',
        fr: 'boussole',
        es: 'brújula',
        ru: 'компас',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '小木屋',
        en: 'cabin',
        ja: '小屋',
        de: 'Hütte',
        fr: 'cabane',
        es: 'cabaña',
        ru: 'хижина',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '灯塔',
        en: 'lighthouse',
        ja: '灯台',
        de: 'Leuchtturm',
        fr: 'phare',
        es: 'faro',
        ru: 'маяк',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.travel,
        zh: '渡轮',
        en: 'ferry',
        ja: 'フェリー',
        de: 'Fähre',
        fr: 'ferry',
        es: 'ferry',
        ru: 'паром',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '传感器',
        en: 'sensor',
        ja: 'センサー',
        de: 'Sensor',
        fr: 'capteur',
        es: 'sensor',
        ru: 'датчик',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '服务器',
        en: 'server',
        ja: 'サーバー',
        de: 'Server',
        fr: 'serveur',
        es: 'servidor',
        ru: 'сервер',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '电路',
        en: 'circuit',
        ja: '回路',
        de: 'Schaltkreis',
        fr: 'circuit',
        es: 'circuito',
        ru: 'схема',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '像素',
        en: 'pixel',
        ja: 'ピクセル',
        de: 'Pixel',
        fr: 'pixel',
        es: 'píxel',
        ru: 'пиксель',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '路由器',
        en: 'router',
        ja: 'ルーター',
        de: 'Router',
        fr: 'routeur',
        es: 'rúter',
        ru: 'роутер',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '电池',
        en: 'battery',
        ja: 'バッテリー',
        de: 'Akku',
        fr: 'batterie',
        es: 'batería',
        ru: 'батарея',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '键盘',
        en: 'keyboard',
        ja: 'キーボード',
        de: 'Tastatur',
        fr: 'clavier',
        es: 'teclado',
        ru: 'клавиатура',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '无人机',
        en: 'drone',
        ja: 'ドローン',
        de: 'Drohne',
        fr: 'drone',
        es: 'dron',
        ru: 'дрон',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '信号',
        en: 'signal',
        ja: '信号',
        de: 'Signal',
        fr: 'signal',
        es: 'señal',
        ru: 'сигнал',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.technology,
        zh: '芯片',
        en: 'chip',
        ja: 'チップ',
        de: 'Chip',
        fr: 'puce',
        es: 'chip',
        ru: 'чип',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '枕头',
        en: 'pillow',
        ja: '枕',
        de: 'Kissen',
        fr: 'oreiller',
        es: 'almohada',
        ru: 'подушка',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '窗帘',
        en: 'curtain',
        ja: 'カーテン',
        de: 'Vorhang',
        fr: 'rideau',
        es: 'cortina',
        ru: 'штора',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '台灯',
        en: 'lamp',
        ja: 'ランプ',
        de: 'Lampe',
        fr: 'lampe',
        es: 'lámpara',
        ru: 'лампа',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '窗户',
        en: 'window',
        ja: '窓',
        de: 'Fenster',
        fr: 'fenêtre',
        es: 'ventana',
        ru: 'окно',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '抽屉',
        en: 'drawer',
        ja: '引き出し',
        de: 'Schublade',
        fr: 'tiroir',
        es: 'cajón',
        ru: 'ящик',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '书架',
        en: 'shelf',
        ja: '棚',
        de: 'Regal',
        fr: 'étagère',
        es: 'estante',
        ru: 'полка',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '水壶',
        en: 'kettle',
        ja: 'やかん',
        de: 'Wasserkocher',
        fr: 'bouilloire',
        es: 'hervidor',
        ru: 'чайник',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '毛毯',
        en: 'blanket',
        ja: '毛布',
        de: 'Decke',
        fr: 'couverture',
        es: 'manta',
        ru: 'одеяло',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '地毯',
        en: 'carpet',
        ja: 'じゅうたん',
        de: 'Teppich',
        fr: 'tapis',
        es: 'alfombra',
        ru: 'ковер',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.home,
        zh: '橱柜',
        en: 'cabinet',
        ja: '戸棚',
        de: 'Schrank',
        fr: 'placard',
        es: 'armario',
        ru: 'шкаф',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '笔记本',
        en: 'notebook',
        ja: 'ノート',
        de: 'Notizbuch',
        fr: 'carnet',
        es: 'cuaderno',
        ru: 'блокнот',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '文件夹',
        en: 'folder',
        ja: 'フォルダー',
        de: 'Ordner',
        fr: 'dossier',
        es: 'carpeta',
        ru: 'папка',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '会议',
        en: 'meeting',
        ja: '会議',
        de: 'Besprechung',
        fr: 'réunion',
        es: 'reunión',
        ru: 'встреча',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '打印机',
        en: 'printer',
        ja: 'プリンター',
        de: 'Drucker',
        fr: 'imprimante',
        es: 'impresora',
        ru: 'принтер',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '议程',
        en: 'agenda',
        ja: '議題',
        de: 'Agenda',
        fr: 'ordre du jour',
        es: 'agenda',
        ru: 'повестка',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '图表',
        en: 'chart',
        ja: 'グラフ',
        de: 'Diagramm',
        fr: 'graphique',
        es: 'gráfico',
        ru: 'диаграмма',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '书桌',
        en: 'desk',
        ja: '机',
        de: 'Schreibtisch',
        fr: 'bureau',
        es: 'escritorio',
        ru: 'стол',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '印章',
        en: 'stamp',
        ja: 'スタンプ',
        de: 'Stempel',
        fr: 'tampon',
        es: 'sello',
        ru: 'печать',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '扫描仪',
        en: 'scanner',
        ja: 'スキャナー',
        de: 'Scanner',
        fr: 'scanner',
        es: 'escáner',
        ru: 'сканер',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.office,
        zh: '报告',
        en: 'report',
        ja: 'レポート',
        de: 'Bericht',
        fr: 'rapport',
        es: 'informe',
        ru: 'отчет',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '微风',
        en: 'breeze',
        ja: 'そよ風',
        de: 'Brise',
        fr: 'brise',
        es: 'brisa',
        ru: 'бриз',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '降雨',
        en: 'rainfall',
        ja: '雨',
        de: 'Regenfall',
        fr: 'pluie',
        es: 'lluvia',
        ru: 'дождь',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '阳光',
        en: 'sunshine',
        ja: '日差し',
        de: 'Sonnenschein',
        fr: 'soleil',
        es: 'sol',
        ru: 'солнечный свет',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '雷声',
        en: 'thunder',
        ja: '雷',
        de: 'Donner',
        fr: 'tonnerre',
        es: 'trueno',
        ru: 'гром',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '细雨',
        en: 'drizzle',
        ja: '小雨',
        de: 'Nieselregen',
        fr: 'bruine',
        es: 'llovizna',
        ru: 'морось',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '薄雾',
        en: 'mist',
        ja: '霧',
        de: 'Nebel',
        fr: 'brume',
        es: 'niebla',
        ru: 'туман',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '风暴',
        en: 'storm',
        ja: '嵐',
        de: 'Sturm',
        fr: 'tempête',
        es: 'tormenta',
        ru: 'буря',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '霜冻',
        en: 'frost',
        ja: '霜',
        de: 'Frost',
        fr: 'gel',
        es: 'escarcha',
        ru: 'иней',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '降雪',
        en: 'snow',
        ja: '雪',
        de: 'Schnee',
        fr: 'neige',
        es: 'nieve',
        ru: 'снег',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.weather,
        zh: '湿度',
        en: 'humidity',
        ja: '湿度',
        de: 'Luftfeuchtigkeit',
        fr: 'humidité',
        es: 'humedad',
        ru: 'влажность',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '兔子',
        en: 'rabbit',
        ja: 'うさぎ',
        de: 'Kaninchen',
        fr: 'lapin',
        es: 'conejo',
        ru: 'кролик',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '海豚',
        en: 'dolphin',
        ja: 'イルカ',
        de: 'Delfin',
        fr: 'dauphin',
        es: 'delfín',
        ru: 'дельфин',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '老虎',
        en: 'tiger',
        ja: '虎',
        de: 'Tiger',
        fr: 'tigre',
        es: 'tigre',
        ru: 'тигр',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '水獭',
        en: 'otter',
        ja: 'カワウソ',
        de: 'Otter',
        fr: 'loutre',
        es: 'nutria',
        ru: 'выдра',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '麻雀',
        en: 'sparrow',
        ja: 'すずめ',
        de: 'Spatz',
        fr: 'moineau',
        es: 'gorrión',
        ru: 'воробей',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '熊猫',
        en: 'panda',
        ja: 'パンダ',
        de: 'Panda',
        fr: 'panda',
        es: 'panda',
        ru: 'панда',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '骆驼',
        en: 'camel',
        ja: 'ラクダ',
        de: 'Kamel',
        fr: 'chameau',
        es: 'camello',
        ru: 'верблюд',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '鲸鱼',
        en: 'whale',
        ja: 'クジラ',
        de: 'Wal',
        fr: 'baleine',
        es: 'ballena',
        ru: 'кит',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '狐狸',
        en: 'fox',
        ja: 'きつね',
        de: 'Fuchs',
        fr: 'renard',
        es: 'zorro',
        ru: 'лиса',
      ),
      _VerbalMemoryWordSpec(
        domain: _VerbalMemoryDomain.animals,
        zh: '羊驼',
        en: 'llama',
        ja: 'リャマ',
        de: 'Lama',
        fr: 'lama',
        es: 'llama',
        ru: 'лама',
      ),
    ];

const List<_VerbalMemoryArrowSpec> _verbalMemoryArrowSpecs =
    <_VerbalMemoryArrowSpec>[
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.upLeft,
        icon: Icons.north_west_rounded,
        zh: '左上',
        en: 'Up left',
        ja: '左上',
        de: 'Oben links',
        fr: 'Haut gauche',
        es: 'Arriba izquierda',
        ru: 'Вверх влево',
        symbol: '↖',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.up,
        icon: Icons.arrow_upward_rounded,
        zh: '上',
        en: 'Up',
        ja: '上',
        de: 'Oben',
        fr: 'Haut',
        es: 'Arriba',
        ru: 'Вверх',
        symbol: '↑',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.upRight,
        icon: Icons.north_east_rounded,
        zh: '右上',
        en: 'Up right',
        ja: '右上',
        de: 'Oben rechts',
        fr: 'Haut droite',
        es: 'Arriba derecha',
        ru: 'Вверх вправо',
        symbol: '↗',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.left,
        icon: Icons.arrow_back_rounded,
        zh: '左',
        en: 'Left',
        ja: '左',
        de: 'Links',
        fr: 'Gauche',
        es: 'Izquierda',
        ru: 'Влево',
        symbol: '←',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.right,
        icon: Icons.arrow_forward_rounded,
        zh: '右',
        en: 'Right',
        ja: '右',
        de: 'Rechts',
        fr: 'Droite',
        es: 'Derecha',
        ru: 'Вправо',
        symbol: '→',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.downLeft,
        icon: Icons.south_west_rounded,
        zh: '左下',
        en: 'Down left',
        ja: '左下',
        de: 'Unten links',
        fr: 'Bas gauche',
        es: 'Abajo izquierda',
        ru: 'Вниз влево',
        symbol: '↙',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.down,
        icon: Icons.arrow_downward_rounded,
        zh: '下',
        en: 'Down',
        ja: '下',
        de: 'Unten',
        fr: 'Bas',
        es: 'Abajo',
        ru: 'Вниз',
        symbol: '↓',
      ),
      _VerbalMemoryArrowSpec(
        direction: _VerbalMemoryArrowDirection.downRight,
        icon: Icons.south_east_rounded,
        zh: '右下',
        en: 'Down right',
        ja: '右下',
        de: 'Unten rechts',
        fr: 'Bas droite',
        es: 'Abajo derecha',
        ru: 'Вниз вправо',
        symbol: '↘',
      ),
    ];
