import '../../i18n/app_i18n.dart';

class SoothingMusicCopy {
  const SoothingMusicCopy._();

  static const Map<String, List<String>> trackKeysByMode =
      <String, List<String>>{
        'chill': <String>[
          'track.chill.1',
          'track.chill.2',
          'track.chill.3',
          'track.chill.4',
        ],
        'study': <String>[
          'track.study.1',
          'track.study.2',
          'track.study.3',
          'track.study.4',
        ],
        'sleep': <String>[
          'track.sleep.1',
          'track.sleep.2',
          'track.sleep.3',
          'track.sleep.4',
          'track.sleep.5',
        ],
        'jazz': <String>[
          'track.jazz.1',
          'track.jazz.2',
          'track.jazz.3',
          'track.jazz.4',
          'track.jazz.5',
          'track.jazz.6',
        ],
        'piano': <String>[
          'track.piano.1',
          'track.piano.2',
          'track.piano.3',
          'track.piano.4',
          'track.piano.5',
        ],
        'motion': <String>[
          'track.motion.1',
          'track.motion.2',
          'track.motion.3',
          'track.motion.4',
          'track.motion.5',
          'track.motion.6',
        ],
        'harp': <String>[
          'track.harp.1',
          'track.harp.2',
          'track.harp.3',
          'track.harp.4',
          'track.harp.5',
        ],
        'music_box': <String>[
          'track.music_box.1',
          'track.music_box.2',
          'track.music_box.3',
          'track.music_box.4',
          'track.music_box.5',
          'track.music_box.6',
        ],
        'dreaming': <String>['track.dreaming.1', 'track.dreaming.2'],
      };

  static String text(
    AppI18n i18n,
    String key, {
    Map<String, Object?> params = const <String, Object?>{},
  }) {
    final language = AppI18n.normalizeLanguageCode(i18n.languageCode);
    final localized = _localized[language]?[key];
    final fallback = _localized['en']?[key];
    var value = localized ?? fallback ?? key;
    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }
    return value;
  }

  static String modeTitle(AppI18n i18n, String modeId) =>
      text(i18n, 'mode.$modeId.title');

  static String modeSubtitle(AppI18n i18n, String modeId) =>
      text(i18n, 'mode.$modeId.subtitle');

  static String modeDescription(AppI18n i18n, String modeId) =>
      text(i18n, 'mode.$modeId.description');

  static String modeFooter(AppI18n i18n, String modeId) =>
      text(i18n, 'mode.$modeId.footer');

  static String trackLabel(AppI18n i18n, String labelKey) =>
      text(i18n, labelKey);
}

const Map<String, Map<String, String>>
_localized = <String, Map<String, String>>{
  'en': <String, String>{
    'page.title': 'Soothing music',
    'page.subtitle':
        'Curated calming loops with breathing light effects, local tracks, and a mobile-first immersive layout.',
    'mode.browser.title': 'Browse modes',
    'mode.browser.subtitle':
        'Selecting a mode closes the menu and keeps the current mode clearly highlighted.',
    'mode.button': 'Modes',
    'mode.filter.all': 'All',
    'mode.filter.favorites': 'Favorites',
    'mode.filter.recent': 'Recent',
    'mode.empty.favorites.title': 'No favorite modes yet',
    'mode.empty.favorites.subtitle':
        'Mark modes you use often and they will appear here for quick switching.',
    'mode.empty.recent.title': 'No recent modes yet',
    'mode.empty.recent.subtitle':
        'Once you switch or play a few modes, your recent history will appear here.',
    'mode.show_all': 'Show all',
    'mode.active': 'Active',
    'mode.favorite_toggle': 'Toggle favorite',
    'track.selector': 'Tracks',
    'track.show': 'Show tracks',
    'track.hide': 'Hide tracks',
    'track.count': '{count} tracks',
    'track.previous': 'Previous track',
    'track.next': 'Next track',
    'track.audio_error': 'Unable to load {label}',
    'timer.button': 'Sleep timer',
    'timer.off': 'Off',
    'timer.minutes': '{count} min',
    'timer.active': 'Sleep timer {duration}',
    'audio.toggle_mute': 'Toggle mute',
    'setting.keep_playing': 'Keep playing after leaving',
    'mode.chill.title': 'Relax',
    'mode.chill.subtitle': 'Lofi Chill',
    'mode.chill.description':
        'Soft pulses and warm chords for drifting, recovery, and light reading.',
    'mode.chill.footer': 'A soft sway for easing out of tension.',
    'mode.study.title': 'Study',
    'mode.study.subtitle': 'Lofi Study',
    'mode.study.description':
        'Steady pacing and clearer mids for long reading, writing, and desk sessions.',
    'mode.study.footer': 'Clear mids and steady pacing for sustained focus.',
    'mode.sleep.title': 'Sleep',
    'mode.sleep.subtitle': 'Lofi Sleep',
    'mode.sleep.description':
        'Slower pads and sparse accents for low-stimulation night wind-down.',
    'mode.sleep.footer': 'Less stimulation and slower breath for night use.',
    'mode.jazz.title': 'Jazz',
    'mode.jazz.subtitle': 'Lofi Jazz',
    'mode.jazz.description':
        'Walking bass and brushed motion for evening work and low-pressure flow.',
    'mode.jazz.footer': 'Lazy bounce and warm texture for evening focus.',
    'mode.piano.title': 'Piano',
    'mode.piano.subtitle': 'Lofi Piano',
    'mode.piano.description':
        'Piano-forward melody with gentle rhythm for quiet reading and solitude.',
    'mode.piano.footer': 'A more forward melody line for immersion.',
    'mode.motion.title': 'Motion',
    'mode.motion.subtitle': 'Motion Flow',
    'mode.motion.description':
        'A stronger forward push for walking, tidying up, and light movement.',
    'mode.motion.footer': 'Forward momentum for lifting your state.',
    'mode.harp.title': 'Harp',
    'mode.harp.subtitle': 'Harp Loop',
    'mode.harp.description':
        'More tactile plucks for quiet recovery, soft meditation, and calm resets.',
    'mode.harp.footer': 'Fine plucks for restoring calm.',
    'mode.music_box.title': 'Music Box',
    'mode.music_box.subtitle': 'Music Box',
    'mode.music_box.description':
        'Brighter chimes and shorter tails for gentle evening companionship.',
    'mode.music_box.footer': 'A bright little glow for evening company.',
    'mode.dreaming.title': 'Dreaming',
    'mode.dreaming.subtitle': 'Dreaming',
    'mode.dreaming.description':
        'A floating dream-walk texture for imagination, night reading, and drift.',
    'mode.dreaming.footer': 'More floating and dreamlike for imagination.',
    'track.chill.1': 'Afternoon Hush',
    'track.chill.2': 'Window Pulse',
    'track.chill.3': 'Soft Drift',
    'track.chill.4': 'Lamp Afterglow',
    'track.study.1': 'Focus Base',
    'track.study.2': 'Deep Reading',
    'track.study.3': 'Desk Flow',
    'track.study.4': 'Clear Stretch',
    'track.sleep.1': 'Slow Nightfall',
    'track.sleep.2': 'Midnight Haze',
    'track.sleep.3': 'Gentle Company',
    'track.sleep.4': 'Soft Descent',
    'track.sleep.5': 'Sleep Prelude',
    'track.jazz.1': 'Warm Walk',
    'track.jazz.2': 'Evening Bar',
    'track.jazz.3': 'Lazy Swing',
    'track.jazz.4': 'Low-Key Typing',
    'track.jazz.5': 'Brush Beat',
    'track.jazz.6': 'Jazz Glow',
    'track.piano.1': 'Paper Keys',
    'track.piano.2': 'After-Rain Solo',
    'track.piano.3': 'Night Reading',
    'track.piano.4': 'Soft Touch',
    'track.piano.5': 'Solo Echo',
    'track.motion.1': 'Walking Push',
    'track.motion.2': 'Easy Jog',
    'track.motion.3': 'State Lift',
    'track.motion.4': 'Morning Drive',
    'track.motion.5': 'Beat Forward',
    'track.motion.6': 'Switch Pace',
    'track.harp.1': 'String Glow I',
    'track.harp.2': 'Moon Pluck',
    'track.harp.3': 'Clear Echo',
    'track.harp.4': 'Pine Breeze Harp',
    'track.harp.5': 'Quiet Strings',
    'track.music_box.1': 'Moon in the Box',
    'track.music_box.2': 'Night Chime',
    'track.music_box.3': 'Dream Fragment',
    'track.music_box.4': 'Little Glow',
    'track.music_box.5': 'Bedside Spin',
    'track.music_box.6': 'Sleep Waltz',
    'track.dreaming.1': 'Floating Thought',
    'track.dreaming.2': 'Cloud Drift',
    'track.fallback': 'Default track',
  },
  'zh': <String, String>{
    'page.title': '舒缓轻音',
    'page.subtitle': '精选疗愈系轻音乐与氛围旋律，配合动态呼吸光效与本地曲库，适合手机端沉浸使用。',
    'mode.browser.title': '浏览模式',
    'mode.browser.subtitle': '切换模式后会自动回到播放页，当前模式会高亮显示。',
    'mode.button': '模式',
    'mode.filter.all': '全部',
    'mode.filter.favorites': '收藏',
    'mode.filter.recent': '最近',
    'mode.empty.favorites.title': '还没有收藏模式',
    'mode.empty.favorites.subtitle': '给常用模式点亮爱心，之后就能在这里快速切换。',
    'mode.empty.recent.title': '最近还没有播放记录',
    'mode.empty.recent.subtitle': '切换或播放几个模式后，这里会自动记录最近使用内容。',
    'mode.show_all': '查看全部',
    'mode.active': '当前',
    'mode.favorite_toggle': '收藏模式',
    'track.selector': '曲目',
    'track.show': '展开曲目',
    'track.hide': '收起曲目',
    'track.count': '{count} 首曲目',
    'track.previous': '上一首',
    'track.next': '下一首',
    'track.audio_error': '无法加载 {label}',
    'timer.button': '睡眠定时',
    'timer.off': '关闭',
    'timer.minutes': '{count} 分钟',
    'timer.active': '睡眠定时 {duration}',
    'audio.toggle_mute': '静音切换',
    'setting.keep_playing': '退出界面后继续播放',
    'mode.chill.title': '轻松',
    'mode.chill.subtitle': 'Lofi 轻松',
    'mode.chill.description': '柔和鼓点与暖色和弦，适合放空、恢复和轻阅读。',
    'mode.chill.footer': '轻缓摆动，适合从紧绷切回松弛。',
    'mode.study.title': '学习',
    'mode.study.subtitle': 'Lofi 学习',
    'mode.study.description': '稳定拍点与清晰中频，更适合长时间阅读、写作与专注工作。',
    'mode.study.footer': '清晰拍点与稳定底色，适合持续专注。',
    'mode.sleep.title': '助眠',
    'mode.sleep.subtitle': 'Lofi 助眠',
    'mode.sleep.description': '减弱击打刺激，保留慢速铺底与稀疏点音，更适合夜间放松。',
    'mode.sleep.footer': '更少刺激、更慢呼吸、更适合夜晚。',
    'mode.jazz.title': '爵士',
    'mode.jazz.subtitle': 'Lofi 爵士',
    'mode.jazz.description': '慵懒低音与轻刷节奏，适合傍晚工作、写字和慢节奏输入。',
    'mode.jazz.footer': '懒散弹跳与暖色质感，适合傍晚与低压工作。',
    'mode.piano.title': '钢琴',
    'mode.piano.subtitle': 'Lofi 钢琴',
    'mode.piano.description': '把旋律交给钢琴，保留轻拍与铺底，适合安静阅读与独处。',
    'mode.piano.footer': '旋律更靠前，适合沉浸和独处。',
    'mode.motion.title': '律动',
    'mode.motion.subtitle': '轻动节奏',
    'mode.motion.description': '更明显的推进感，适合走动、整理房间、切换状态与轻运动。',
    'mode.motion.footer': '更明确的推进感，适合把状态提起来。',
    'mode.harp.title': '竖琴',
    'mode.harp.subtitle': '空灵竖琴',
    'mode.harp.description': '拨弦感更明显，适合放空、安静恢复与轻度冥想。',
    'mode.harp.footer': '细碎拨弦，适合放空和安静恢复。',
    'mode.music_box.title': '八音盒',
    'mode.music_box.subtitle': '微光铃音',
    'mode.music_box.description': '铃音更亮、尾音更短，适合作为夜间轻陪伴与低刺激安抚。',
    'mode.music_box.footer': '清亮微光，适合夜间和轻陪伴。',
    'mode.dreaming.title': '遐想',
    'mode.dreaming.subtitle': '漂浮氛围',
    'mode.dreaming.description': '更漂浮、更梦境化，适合夜读、发散思绪与轻想象。',
    'mode.dreaming.footer': '更漂浮、更梦境化，适合夜读与想象。',
    'track.chill.1': '午后暖流',
    'track.chill.2': '窗边慢拍',
    'track.chill.3': '松弛漂流',
    'track.chill.4': '夜灯余温',
    'track.study.1': '专注底色',
    'track.study.2': '长文阅读',
    'track.study.3': '桌面流线',
    'track.study.4': '清醒延展',
    'track.sleep.1': '缓夜铺底',
    'track.sleep.2': '深夜白雾',
    'track.sleep.3': '低刺激陪伴',
    'track.sleep.4': '慢慢坠落',
    'track.sleep.5': '安睡前奏',
    'track.jazz.1': '暖调漫步',
    'track.jazz.2': '傍晚酒馆',
    'track.jazz.3': '懒散摇摆',
    'track.jazz.4': '低压输入',
    'track.jazz.5': '轻刷鼓点',
    'track.jazz.6': '爵士余晖',
    'track.piano.1': '纸页钢琴',
    'track.piano.2': '雨后独奏',
    'track.piano.3': '夜读旋律',
    'track.piano.4': '轻触琴键',
    'track.piano.5': '独处回声',
    'track.motion.1': '步行推进',
    'track.motion.2': '轻跑唤醒',
    'track.motion.3': '状态拉起',
    'track.motion.4': '晨间动能',
    'track.motion.5': '节律前行',
    'track.motion.6': '切换速度',
    'track.harp.1': '弦光一',
    'track.harp.2': '月下拨弦',
    'track.harp.3': '清澈回响',
    'track.harp.4': '松风竖琴',
    'track.harp.5': '静夜细弦',
    'track.music_box.1': '盒中月光',
    'track.music_box.2': '夜色铃音',
    'track.music_box.3': '短梦碎片',
    'track.music_box.4': '微光陪伴',
    'track.music_box.5': '床边回旋',
    'track.music_box.6': '轻眠序曲',
    'track.dreaming.1': '漂浮想象',
    'track.dreaming.2': '梦游云层',
    'track.fallback': '默认曲目',
  },
  'ja': <String, String>{
    'page.title': 'やわらぎミュージック',
    'mode.browser.title': 'モード一覧',
    'mode.browser.subtitle': 'モードを選ぶとメニューが閉じ、現在のモードがはっきり表示されます。',
    'mode.button': 'モード',
    'mode.filter.all': 'すべて',
    'mode.filter.favorites': 'お気に入り',
    'mode.filter.recent': '最近',
    'mode.empty.favorites.title': 'お気に入りのモードはまだありません',
    'mode.empty.favorites.subtitle': 'よく使うモードをお気に入りにすると、ここからすぐ切り替えられます。',
    'mode.empty.recent.title': '最近使ったモードはまだありません',
    'mode.empty.recent.subtitle': 'いくつか再生または切り替えると、ここに履歴が表示されます。',
    'mode.show_all': 'すべて表示',
    'mode.active': '再生中',
    'mode.favorite_toggle': 'お気に入り',
    'track.selector': '曲目',
    'track.show': '曲目を表示',
    'track.hide': '曲目を隠す',
    'track.count': '{count} 曲',
    'track.previous': '前の曲',
    'track.next': '次の曲',
    'timer.button': 'スリープタイマー',
    'timer.off': 'オフ',
    'timer.minutes': '{count}分',
    'timer.active': 'スリープタイマー {duration}',
    'audio.toggle_mute': 'ミュート切替',
    'setting.keep_playing': '画面を閉じても再生を続ける',
  },
  'de': <String, String>{
    'page.title': 'Sanfte Musik',
    'mode.browser.title': 'Modi durchsuchen',
    'mode.browser.subtitle':
        'Beim Wechsel schließt sich das Menü und der aktuelle Modus bleibt klar markiert.',
    'mode.button': 'Modi',
    'mode.filter.all': 'Alle',
    'mode.filter.favorites': 'Favoriten',
    'mode.filter.recent': 'Zuletzt',
    'mode.empty.favorites.title': 'Noch keine Favoriten',
    'mode.empty.favorites.subtitle':
        'Markieren Sie häufig genutzte Modi als Favorit, um sie hier schneller zu öffnen.',
    'mode.empty.recent.title': 'Noch keine zuletzt verwendeten Modi',
    'mode.empty.recent.subtitle':
        'Sobald Sie einige Modi abgespielt haben, erscheinen sie hier.',
    'mode.show_all': 'Alle anzeigen',
    'mode.active': 'Aktiv',
    'mode.favorite_toggle': 'Favorit umschalten',
    'track.selector': 'Titel',
    'track.show': 'Titel anzeigen',
    'track.hide': 'Titel ausblenden',
    'track.count': '{count} Titel',
    'track.previous': 'Vorheriger Titel',
    'track.next': 'Nächster Titel',
    'timer.button': 'Schlaftimer',
    'timer.off': 'Aus',
    'timer.minutes': '{count} Min',
    'timer.active': 'Schlaftimer {duration}',
    'audio.toggle_mute': 'Stumm schalten',
    'setting.keep_playing': 'Nach Verlassen weiter abspielen',
  },
  'fr': <String, String>{
    'page.title': 'Musique apaisante',
    'mode.browser.title': 'Parcourir les modes',
    'mode.browser.subtitle':
        'La sélection ferme le menu et laisse le mode actif bien visible.',
    'mode.button': 'Modes',
    'mode.filter.all': 'Tout',
    'mode.filter.favorites': 'Favoris',
    'mode.filter.recent': 'Récents',
    'mode.empty.favorites.title': 'Aucun favori pour le moment',
    'mode.empty.favorites.subtitle':
        'Ajoutez vos modes fréquents en favori pour les retrouver ici.',
    'mode.empty.recent.title': 'Aucun mode récent pour le moment',
    'mode.empty.recent.subtitle':
        'Après quelques écoutes, votre historique s’affichera ici.',
    'mode.show_all': 'Tout afficher',
    'mode.active': 'Actif',
    'mode.favorite_toggle': 'Mettre en favori',
    'track.selector': 'Pistes',
    'track.show': 'Afficher les pistes',
    'track.hide': 'Masquer les pistes',
    'track.count': '{count} pistes',
    'track.previous': 'Piste précédente',
    'track.next': 'Piste suivante',
    'timer.button': 'Minuteur de veille',
    'timer.off': 'Désactivé',
    'timer.minutes': '{count} min',
    'timer.active': 'Minuteur {duration}',
    'audio.toggle_mute': 'Couper le son',
    'setting.keep_playing': 'Continuer la lecture après avoir quitté',
  },
  'es': <String, String>{
    'page.title': 'Música relajante',
    'mode.browser.title': 'Explorar modos',
    'mode.browser.subtitle':
        'Al elegir un modo el menú se cierra y el modo actual queda claramente resaltado.',
    'mode.button': 'Modos',
    'mode.filter.all': 'Todo',
    'mode.filter.favorites': 'Favoritos',
    'mode.filter.recent': 'Recientes',
    'mode.empty.favorites.title': 'Aún no hay favoritos',
    'mode.empty.favorites.subtitle':
        'Marca tus modos frecuentes como favoritos y aparecerán aquí.',
    'mode.empty.recent.title': 'Aún no hay modos recientes',
    'mode.empty.recent.subtitle':
        'Después de reproducir algunos modos, aquí verás el historial.',
    'mode.show_all': 'Ver todo',
    'mode.active': 'Activo',
    'mode.favorite_toggle': 'Marcar favorito',
    'track.selector': 'Pistas',
    'track.show': 'Mostrar pistas',
    'track.hide': 'Ocultar pistas',
    'track.count': '{count} pistas',
    'track.previous': 'Pista anterior',
    'track.next': 'Siguiente pista',
    'timer.button': 'Temporizador de sueño',
    'timer.off': 'Desactivado',
    'timer.minutes': '{count} min',
    'timer.active': 'Temporizador {duration}',
    'audio.toggle_mute': 'Silenciar',
    'setting.keep_playing': 'Seguir reproduciendo al salir',
  },
  'ru': <String, String>{
    'page.title': 'Спокойная музыка',
    'mode.browser.title': 'Режимы',
    'mode.browser.subtitle':
        'После выбора меню закрывается, а текущий режим остается заметным.',
    'mode.button': 'Режимы',
    'mode.filter.all': 'Все',
    'mode.filter.favorites': 'Избранное',
    'mode.filter.recent': 'Недавние',
    'mode.empty.favorites.title': 'Пока нет избранных режимов',
    'mode.empty.favorites.subtitle':
        'Добавьте часто используемые режимы в избранное, и они появятся здесь.',
    'mode.empty.recent.title': 'Пока нет недавних режимов',
    'mode.empty.recent.subtitle':
        'После нескольких запусков история появится здесь.',
    'mode.show_all': 'Показать все',
    'mode.active': 'Активен',
    'mode.favorite_toggle': 'В избранное',
    'track.selector': 'Треки',
    'track.show': 'Показать треки',
    'track.hide': 'Скрыть треки',
    'track.count': '{count} треков',
    'track.previous': 'Предыдущий трек',
    'track.next': 'Следующий трек',
    'timer.button': 'Таймер сна',
    'timer.off': 'Выкл',
    'timer.minutes': '{count} мин',
    'timer.active': 'Таймер {duration}',
    'audio.toggle_mute': 'Вкл/выкл звук',
    'setting.keep_playing': 'Продолжать воспроизведение после выхода',
  },
};
