// ignore_for_file: unused_element

part of 'toolbox_soothing_music_v2_page.dart';

const List<_SoothingModeTheme> _modes = <_SoothingModeTheme>[
  _SoothingModeTheme(
    id: 'chill',
    zhTitle: '轻松',
    enTitle: 'Relax',
    zhSubtitle: 'Lofi 轻松',
    enSubtitle: 'Lofi Chill',
    zhDescription: '柔和鼓点与暖色和弦，适合放空、恢复和轻阅读。',
    enDescription:
        'Soft pulses and warm chords for drifting, recovery, and light reading.',
    icon: Icons.music_note_rounded,
    accent: Color(0xFF7D8CFF),
    orbitAccent: Color(0xFFFFB15C),
    backgroundA: Color(0xFF0B1326),
    backgroundB: Color(0xFF08111C),
    blobA: Color(0xFF2C3E8F),
    blobB: Color(0xFF5A2B86),
    footerZh: '轻缓摆动，适合从紧绷切回松弛。',
    footerEn: 'A soft sway for easing out of tension.',
  ),
  _SoothingModeTheme(
    id: 'study',
    zhTitle: '学习',
    enTitle: 'Study',
    zhSubtitle: 'Lofi 学习',
    enSubtitle: 'Lofi Study',
    zhDescription: '稳定拍点与清晰中频，更适合长时间阅读、写作与专注工作。',
    enDescription:
        'Steady pacing and clearer mids for long reading, writing, and desk sessions.',
    icon: Icons.radio_button_checked_rounded,
    accent: Color(0xFF62A5FF),
    orbitAccent: Color(0xFFFFAE61),
    backgroundA: Color(0xFF09111D),
    backgroundB: Color(0xFF07121F),
    blobA: Color(0xFF15437D),
    blobB: Color(0xFF274A9B),
    footerZh: '清晰拍点与稳定底色，适合持续专注。',
    footerEn: 'Clear mids and steady pacing for sustained focus.',
  ),
  _SoothingModeTheme(
    id: 'sleep',
    zhTitle: '助眠',
    enTitle: 'Sleep',
    zhSubtitle: 'Lofi 助眠',
    enSubtitle: 'Lofi Sleep',
    zhDescription: '减弱击打刺激，保留慢速铺底与稀疏点音，更适合夜间放松。',
    enDescription:
        'Slower pads and sparse accents for low-stimulation night wind-down.',
    icon: Icons.nightlight_round_rounded,
    accent: Color(0xFFB57CFF),
    orbitAccent: Color(0xFF8E9FFF),
    backgroundA: Color(0xFF090F1A),
    backgroundB: Color(0xFF060A12),
    blobA: Color(0xFF322155),
    blobB: Color(0xFF1D2B5B),
    footerZh: '更少刺激、更慢呼吸、更适合夜晚。',
    footerEn: 'Less stimulation and slower breath for night use.',
  ),
  _SoothingModeTheme(
    id: 'jazz',
    zhTitle: '爵士',
    enTitle: 'Jazz',
    zhSubtitle: 'Lofi 爵士',
    enSubtitle: 'Lofi Jazz',
    zhDescription: '慵懒低音与轻刷节奏，适合傍晚工作、写字和慢节奏输入。',
    enDescription:
        'Walking bass and brushed motion for evening work and low-pressure flow.',
    icon: Icons.mic_external_on_rounded,
    accent: Color(0xFFFF8B7B),
    orbitAccent: Color(0xFFFFC36E),
    backgroundA: Color(0xFF12101A),
    backgroundB: Color(0xFF0C1017),
    blobA: Color(0xFF6A2D35),
    blobB: Color(0xFF5D4428),
    footerZh: '懒散弹跳与暖色质感，适合傍晚与低压工作。',
    footerEn: 'Lazy bounce and warm texture for evening focus.',
  ),
  _SoothingModeTheme(
    id: 'piano',
    zhTitle: '钢琴',
    enTitle: 'Piano',
    zhSubtitle: 'Lofi 钢琴',
    enSubtitle: 'Lofi Piano',
    zhDescription: '把旋律交给钢琴，保留轻拍与铺底，适合安静阅读与独处。',
    enDescription:
        'Piano-forward melody with gentle rhythm for quiet reading and solitude.',
    icon: Icons.piano_rounded,
    accent: Color(0xFFC9D1E2),
    orbitAccent: Color(0xFF8DA8D4),
    backgroundA: Color(0xFF0E1520),
    backgroundB: Color(0xFF0A1018),
    blobA: Color(0xFF3B4557),
    blobB: Color(0xFF26415E),
    footerZh: '旋律更靠前，适合沉浸和独处。',
    footerEn: 'A more forward melody line for immersion.',
  ),
  _SoothingModeTheme(
    id: 'motion',
    zhTitle: '律动',
    enTitle: 'Motion',
    zhSubtitle: '轻动节奏',
    enSubtitle: 'Motion Flow',
    zhDescription: '更明显的推进感，适合走动、整理房间、切换状态与轻运动。',
    enDescription:
        'A stronger forward push for walking, tidying up, and light movement.',
    icon: Icons.directions_run_rounded,
    accent: Color(0xFF32C8A8),
    orbitAccent: Color(0xFF6DE5FF),
    backgroundA: Color(0xFF07161A),
    backgroundB: Color(0xFF07101A),
    blobA: Color(0xFF0E5C56),
    blobB: Color(0xFF15406C),
    footerZh: '更明确的推进感，适合把状态提起来。',
    footerEn: 'Forward momentum for lifting your state.',
  ),
  _SoothingModeTheme(
    id: 'harp',
    zhTitle: '竖琴',
    enTitle: 'Harp',
    zhSubtitle: '空灵竖琴',
    enSubtitle: 'Harp Loop',
    zhDescription: '拨弦感更明显，适合放空、安静恢复与轻度冥想。',
    enDescription:
        'More tactile plucks for quiet recovery, soft meditation, and calm resets.',
    icon: Icons.auto_awesome_rounded,
    accent: Color(0xFF8F93FF),
    orbitAccent: Color(0xFFFFB9AA),
    backgroundA: Color(0xFF101127),
    backgroundB: Color(0xFF0A0E1B),
    blobA: Color(0xFF353C8D),
    blobB: Color(0xFF62367F),
    footerZh: '细碎拨弦，适合放空和安静恢复。',
    footerEn: 'Fine plucks for restoring calm.',
  ),
  _SoothingModeTheme(
    id: 'music_box',
    zhTitle: '八音盒',
    enTitle: 'Music Box',
    zhSubtitle: '微光铃音',
    enSubtitle: 'Music Box',
    zhDescription: '铃音更亮、尾音更短，适合作为夜间轻陪伴与低刺激安抚。',
    enDescription:
        'Brighter chimes and shorter tails for gentle evening companionship.',
    icon: Icons.toys_rounded,
    accent: Color(0xFFFFB061),
    orbitAccent: Color(0xFFFFE0A1),
    backgroundA: Color(0xFF14101A),
    backgroundB: Color(0xFF0F0D16),
    blobA: Color(0xFF7B4E1B),
    blobB: Color(0xFF5B3258),
    footerZh: '清亮微光，适合夜间和轻陪伴。',
    footerEn: 'A bright little glow for evening company.',
  ),
  _SoothingModeTheme(
    id: 'dreaming',
    zhTitle: '遐想',
    enTitle: 'Dreaming',
    zhSubtitle: '漂浮氛围',
    enSubtitle: 'Dreaming',
    zhDescription: '更漂浮、更梦境化，适合夜读、发散思绪与轻想象。',
    enDescription:
        'A floating dream-walk texture for imagination, night reading, and drift.',
    icon: Icons.cloud_outlined,
    accent: Color(0xFF9BB2FF),
    orbitAccent: Color(0xFFE1A8FF),
    backgroundA: Color(0xFF0D1020),
    backgroundB: Color(0xFF090B14),
    blobA: Color(0xFF29417A),
    blobB: Color(0xFF5A2C6F),
    footerZh: '更漂浮、更梦境化，适合夜读与想象。',
    footerEn: 'More floating and dreamlike for imagination.',
  ),
];

const Map<String, List<_TrackLabelPair>> _trackLabelsByMode =
    <String, List<_TrackLabelPair>>{
      'chill': <_TrackLabelPair>[
        _TrackLabelPair(zh: '午后暖流', en: 'Afternoon Hush'),
        _TrackLabelPair(zh: '窗边慢拍', en: 'Window Pulse'),
        _TrackLabelPair(zh: '松弛漂流', en: 'Soft Drift'),
        _TrackLabelPair(zh: '夜灯余温', en: 'Lamp Afterglow'),
      ],
      'study': <_TrackLabelPair>[
        _TrackLabelPair(zh: '专注底色', en: 'Focus Base'),
        _TrackLabelPair(zh: '长文阅读', en: 'Deep Reading'),
        _TrackLabelPair(zh: '桌面流线', en: 'Desk Flow'),
        _TrackLabelPair(zh: '清醒延展', en: 'Clear Stretch'),
      ],
      'sleep': <_TrackLabelPair>[
        _TrackLabelPair(zh: '缓夜铺底', en: 'Slow Nightfall'),
        _TrackLabelPair(zh: '深夜白雾', en: 'Midnight Haze'),
        _TrackLabelPair(zh: '低刺激陪伴', en: 'Gentle Company'),
        _TrackLabelPair(zh: '慢慢坠落', en: 'Soft Descent'),
        _TrackLabelPair(zh: '安睡前奏', en: 'Sleep Prelude'),
      ],
      'jazz': <_TrackLabelPair>[
        _TrackLabelPair(zh: '暖调漫步', en: 'Warm Walk'),
        _TrackLabelPair(zh: '傍晚酒馆', en: 'Evening Bar'),
        _TrackLabelPair(zh: '懒散摇摆', en: 'Lazy Swing'),
        _TrackLabelPair(zh: '低压输入', en: 'Low-Key Typing'),
        _TrackLabelPair(zh: '轻刷鼓点', en: 'Brush Beat'),
        _TrackLabelPair(zh: '爵士余晖', en: 'Jazz Glow'),
      ],
      'piano': <_TrackLabelPair>[
        _TrackLabelPair(zh: '纸页钢琴', en: 'Paper Keys'),
        _TrackLabelPair(zh: '雨后独奏', en: 'After-Rain Solo'),
        _TrackLabelPair(zh: '夜读旋律', en: 'Night Reading'),
        _TrackLabelPair(zh: '轻触琴键', en: 'Soft Touch'),
        _TrackLabelPair(zh: '独处回声', en: 'Solo Echo'),
      ],
      'motion': <_TrackLabelPair>[
        _TrackLabelPair(zh: '步行推进', en: 'Walking Push'),
        _TrackLabelPair(zh: '轻跑唤醒', en: 'Easy Jog'),
        _TrackLabelPair(zh: '状态拉起', en: 'State Lift'),
        _TrackLabelPair(zh: '晨间动能', en: 'Morning Drive'),
        _TrackLabelPair(zh: '节律前行', en: 'Beat Forward'),
        _TrackLabelPair(zh: '切换速度', en: 'Switch Pace'),
      ],
      'harp': <_TrackLabelPair>[
        _TrackLabelPair(zh: '弦光一', en: 'String Glow I'),
        _TrackLabelPair(zh: '月下拨弦', en: 'Moon Pluck'),
        _TrackLabelPair(zh: '清澈回响', en: 'Clear Echo'),
        _TrackLabelPair(zh: '松风竖琴', en: 'Pine Breeze Harp'),
        _TrackLabelPair(zh: '静夜细弦', en: 'Quiet Strings'),
      ],
      'music_box': <_TrackLabelPair>[
        _TrackLabelPair(zh: '盒中月光', en: 'Moon in the Box'),
        _TrackLabelPair(zh: '夜色铃音', en: 'Night Chime'),
        _TrackLabelPair(zh: '短梦碎片', en: 'Dream Fragment'),
        _TrackLabelPair(zh: '微光陪伴', en: 'Little Glow'),
        _TrackLabelPair(zh: '床边回旋', en: 'Bedside Spin'),
        _TrackLabelPair(zh: '轻眠序曲', en: 'Sleep Waltz'),
      ],
      'dreaming': <_TrackLabelPair>[
        _TrackLabelPair(zh: '漂浮想象', en: 'Floating Thought'),
        _TrackLabelPair(zh: '梦游云层', en: 'Cloud Drift'),
      ],
    };
